### ISSUE TITLE
[RN demo app] "Authenticate Anonymously" button is disabled when anonymous user is allowed in web

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1057]
## Background:
- Device / Browser (OS version): iPhone X (13.1.2) / Samsung Galaxy S8
- Build: UAT
- Testing app: https://testlhc.authgear-staging.com

## Description:
"Authenticate Anonymously" is disabled when anonymous user is allowed in RN apps

## Steps to reproduce:
1. Enable anonymous user in web portal
2. Enter Client ID and endpoint in RN demo app
3. Click configure
4. See "Authenticate Anonymously" is disabled

## Expected result:
Should allow user to select "Authenticate Anonymously" when anonymous user is allowed

## Screenshot:
Web admin portal:
![image](https://user-images.githubusercontent.com/69806274/111097937-78431300-857d-11eb-99d8-589e40e480d6.png)

RN demo app:
![image](https://user-images.githubusercontent.com/69806274/111097949-7ed18a80-857d-11eb-94be-a90fcd7daec2.png)

**Comment by stanleylhs** [comment]
Similar issue: (Can open new issue if needed, posting here just to consolidate.)

# [Demo app, Anonymous Users] "Login anonymously" button is enabled when anonymous users is not allowed on portal

## Background:
- Device / Browser (OS version): Chrome on Win10, iPhone X (13.1.2), Pixel 3 
- Build: Version 1.0(1) May 28,2021 at 16:19 / Version 1.0 (1) May 28,2021 at 15:56


## Description:
"Login anonymously" is enabled when anonymous users is not allowed. Error is displayed in Raw code is shown after clicking.

## Steps to reproduce:
1. [Web portal] Disable anonymous user
2. [App] Configure, then Login anonymously
3. See error dialog in raw code


## Expected result:
Should disable "login anonymously" when anonymous users are not allowed

## Screenshot:
![image](https://user-images.githubusercontent.com/4337525/124744524-700a4b80-df51-11eb-9a50-1508c381146c.png)

![image](https://user-images.githubusercontent.com/4337525/124744539-739dd280-df51-11eb-8951-7475c9d496f4.png)

![image](https://user-images.githubusercontent.com/4337525/124745015-ead36680-df51-11eb-9492-61598bd00d8c.png)
