### ISSUE TITLE
[Portal, Settings] Display "More" button when all information is shown

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1061]
## Background:
- Device / Browser (OS version): Chrome on Win10
- Build: UAT

## Description:
After user logged in to an app, he will see 'More' button even if Login info sections is already showing all information

## Steps to reproduce:
1. Login to custom app in desktop browser
2. Click more in "login info"
3. See no new information is shown

## Expected result:
Should not show "more" if all the information is already shown

## Screenshot:
![image](https://user-images.githubusercontent.com/69806274/111102990-57cc8600-8588-11eb-9e52-afdf087f8a45.png)

![image](https://user-images.githubusercontent.com/69806274/111102999-5bf8a380-8588-11eb-9dda-16bff2c79914.png)

**Comment by fungc-io** [comment]
To be changed
- Only show connected social accounts and configured Login ID (phone/email/username) on `/settings`
- User should click "More" to add identities (`/settings/identity`)
- Hide "More" if nothing can be added. i.e. all identities are already shown in `/settings`

**Comment by samchan0221** [comment]
time estimation: 3 hrs

**Comment by fungc-io** [comment]
Testing in the `demo-app` of staging and found the following:
1. Unset Username is still shown in `/settings`, see the same 4 items after clicking `More login methods`. Login IDs (phone/email/username) that are not configured should be in `/settings/identity`, not in `/settings`
2. `More login methods` is still shown even all login ids and identities are set and shown in `/settings`

--
1. 
![1. unset username is still shown](https://user-images.githubusercontent.com/15207470/128654782-e5ebd28f-12ab-4097-9efa-d9ce98659b27.png) ![1. clicking more sees the same 4 items](https://user-images.githubusercontent.com/15207470/128654801-5ca0eee0-39ea-439c-8f35-ab3b5742964f.png)

2. 
![2. "More" is still shown when all info is displayed](https://user-images.githubusercontent.com/15207470/128654818-3fc71f37-e568-496c-a9af-76d3fa9fd74b.png)
