### ISSUE TITLE
[Web portal, Firefox, Dark mode] Browser light / dark mode affects Authgear UI setting

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1064]
## Background:
- Device / Browser (OS version): Firefox on iOS (14.3)
- Build: UAT

## Description:
When the theme mode on Firefox is different from that on the device system, web login portal UI will differ from Admin portal UI setting

## Steps to reproduce:
Pre-condition: Dark mode enabled for the app

Case 1) light mode on device, dark mode on Firefox

1. Turn on light mode in iOS device
2. Open the endpoint of the app on iOS using Firefox
3. See the normal light mode UI
4. Turn on dark mode of Firefox
5. See the colors of the dark mode UI changed

Case 2) dark mode on device, light mode on Firefox
1. Turn on dark mode in iOS device
2. Open the endpoint of the app on iOS using Firefox
3. See the normal dark mode UI
4. Turn on light mode of Firefox
5. See the colors of the light mode UI changed

## Expected result:
Browser dark / light mode should not override UI setting in Authgear admin portal

## Screenshot:
Case 1:

https://user-images.githubusercontent.com/69806274/111105481-06bf9080-858e-11eb-9558-6068ec750205.MP4

Case 2:

https://user-images.githubusercontent.com/69806274/111105509-18a13380-858e-11eb-9754-ad6515c33ea0.MP4

**Comment by louischan-oursky** [comment]
Actually this behavior is correct. The choice of dark mode / light mode is controlled by the browser.

The toggle in the portal is controlling whether the app "supports" dark mode.
But the choice of dark mode / light mode is controlled by the browser.
The rationale is that the browser preferences represent the user preferences.
So if the user wants dark mode AND the app supports dark mode, then dark mode should be shown.
