### ISSUE TITLE
[Portal, UI settings] Display unknown error when file is too large

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1065]
## Background:
- Device / Browser (OS version): Chrome on Win10
- Build: UAT

## Description:
"Unknown Error" is shown when the file is too large but there is no clear instruction what is the max file size allowed

## Steps to reproduce:
1. Login to portal
2. Select an app
3. Go to UI settings
4. Upload a logo with large file size
5. Click save
6. See unknown error

## Expected result:
Suggest to show upper limit for logo file size when user upload image

## Screenshot:
<img width="1280" alt="Screenshot 2021-03-15 at 1 05 54 PM" src="https://user-images.githubusercontent.com/69806274/111105999-2e632880-858f-11eb-98a5-5441329e5cc2.png">

## Testing image:
![2020-10-28 12 07 07](https://user-images.githubusercontent.com/69806274/111105834-c7457400-858e-11eb-95c5-017037992d45.jpg)

**Comment by fungc-io** [comment]
Show Size Limit in the description above image upload components.

Favicon:

![Screenshot 2021-08-02 at 12 06 34](https://user-images.githubusercontent.com/15207470/127803047-ac4d020a-d49b-4627-ad3e-fe2c87432287.png)

App Icon (Under **Light Mode** / **DarkMode**):

![Screenshot 2021-08-02 at 12 02 14](https://user-images.githubusercontent.com/15207470/127803125-2671a46e-c950-42d0-889b-8bc9cc0053cf.png)

**Comment by fungc-io** [comment]
Error message when file is too large:

> The file size is too large. Please upload a [allowed file format] file smaller than [max size].

e.g.
> The file size is too large. Please upload a JPG, PNG or GIF file smaller than 2 MB.

**Comment by samchan0221** [comment]
time estimation: 2 hrs

**Comment by fungc-io** [comment]
Show the resources name in the error message to 
> The [resource] file size is too large. Please upload a [allowed file format] file smaller than [max size].

e.g.

> The favicon file size is too large. Please upload a XXX file smaller than XXX.

> The app logo file size is too large. Please upload a XXX file smaller than [?] MB.
