### ISSUE TITLE
[RN Demo app, Configure] Forever loading when configure without entering Client ID and Endpoint

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1070]
## Background
Device: iPhone X / iOS 14 & Samsung Galaxy S8 / Android 8
Build: UAT

## Description
If user click Configure without entering Client ID and Endpoint, the page will load forever and buttons will become unclickable

## Steps
1. Open RN Demo app
2. Click Configure without filling in Client ID and Endpoint
3. See error message and click OK
4. See forever loading page
5. See buttons become unclickable except 'Third-party app' switch button

## Expected result
Page should not load forever and button should be clickable after user click OK in error

## Video

https://user-images.githubusercontent.com/69806274/111115966-4b542780-85a0-11eb-93d7-d2ede27b0f01.MP4

**Comment by joyzoursky** [comment]
Cannot reproduce now

**Comment by joyzoursky** [comment]
Can reproduce on RN demo app, but changed to trivial as it is only the demo app issue and will not affect real users.

**Comment by chpapa** [comment]
@fungc-io @joyzoursky @haretorii let's open issue that open affect demo app in demo app repo? (Or create one if we don't have..)

**Comment by fungc-io** [comment]
@chpapa @joyzoursky @haretorii it's the repo of the SDK.
- RN demo app -> JS SDK -> https://github.com/authgear/authgear-sdk-js
- Flutter demo app -> https://github.com/authgear/authgear-sdk-flutter
- Android native demo app -> https://github.com/authgear/authgear-sdk-android
- iOS native demo app -> https://github.com/authgear/authgear-sdk-ios
- Xamarin demo app -> https://github.com/authgear/authgear-sdk-xamarin
