### ISSUE TITLE
[iOS Demo app, Login] Show failed to login error when login if 'Is Third-party app' is false

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1073]
## Background
Device: iPhone X / iOS 14
Build: UAT
Testing app: https://testlhc.authgear-staging.com

## Description
If user set 'Is Third-party app' false and login, he will see 'Failed to login' error

## Steps
1. Open the demo app
2. Fill in Client ID and Endpoint
3. Switch 'Is Third-party app' to false
4. Click Configure
5. Click Login
6. See new window pop-ed out and closed automatically
7. See 'Failed to login' error

## Expected result
Should be able to login

## Video

https://user-images.githubusercontent.com/69806274/111122348-e7822c80-85a8-11eb-8607-79db2528706f.MP4

**Comment by joyzoursky** [comment]
"Is Third-party app" toggle is taken away
