### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#11]
Sub-commands:
- `migrate`: handle db/version migration
    - `up`/`down`: apply/revert migrations
    - `verify`: verify the database schema against latest version.
- `init <type> -o <output file>`: setup initial config & generate secrets
    - common use case: `authgear init config; authgear init secret`, output file default to authgear.yaml & authgear.secret.yaml
    - in docker run: `docker run ... authgear init config -o - > authgear.yaml`
    - prompts with default value: app id, redis/database credentials, host
- `start`: start server

@louischan-oursky @chpapa Thoughts on this?

**Comment by chpapa** [comment]
@kiootic looks good at the beginning, some questions:

- `migrate` feel a bit strange if we consider Authgear as a standalone daemon, is it better to just auto do the migration if the DB version is older than the current daemon? 
- Do we need `stop` if there is a `start`? Or just let people kill it?
- Speaking of which, do we need to implement SIGHUP for reload config? (no need if it is trouble , not useful at this point)

**Comment by louischan-oursky** [comment]
> I assume we will show an error when the daemon to start, and ask users to run something like authgear migrate?

This is better.

> Do we need stop if there is a start? Or just let people kill it?

CTRL-C should work fine.

> do we need to implement SIGHUP for reload config? (no need if it is trouble or not useful at this point

We had an idea of watching configuration file change to reload config in the future.

**Comment by chpapa** [comment]
> We had an idea of watching configuration file change to reload config in the future.

Better do it only in some sort of local mode (so with a specific flag), and listen to SIGHUP / reload in production... avoid surprisingly sysadmin :)

**Comment by kiootic** [comment]
> Better do it only in some sort of local mode (so with a specific flag), and listen to SIGHUP / reload in production... avoid surprisingly sysadmin :)

I suppose we'll need a command to signal reload config (like `nginx -s reload`), and the controller would send a signal to server to reload config when config of any app changed in multi-tenant mode.

**Comment by kiootic** [comment]
> I assume we will show an error when the daemon to start, and ask users to run something like authgear migrate?

One thing to note: most likely we cannot show error on database schema mismatch on startup:
- On multi-tenant mode: each tenant can has different database (for sharding, isolation, etc.), so we cannot determine database schema on startup
- On single-tenant mode: we can do it in this mode, but then it'll be a special case since we'll trigger the check only if it is single-tenant mode.

Otherwise, we can log the database schema error at ERROR level when there is a request to a tenant with mismatched database schema.

**Comment by kiootic** [comment]
After discussion with @louischan-oursky: We prefer not doing any verification at runtime. Instead, developers can verify the database schema using `migrate verify` sub-command.

**Comment by chpapa** [comment]
> After discussion with @louischan-oursky: We prefer not doing any verification at runtime. Instead, developers can verify the database schema using migrate verify sub-command.

May I know why? It seems setting up a trap for users?

**Comment by kiootic** [comment]
- We can't check it in multi-tenant mode, so we can only check it in single-tenant mode
- If we check at startup in single-tenant mode, we cannot start the server when DB is not up, which is not a good practice.
- Checking it every request would be costly, and our experience is that developers would trigger DB related errors easily (therefore notice it) if database schema is not up-to-date.
- If developer desire, they can setup a `initContainer` in k8s deployment to verify database schema/auto migrate.

**Comment by chpapa** [comment]
> We can't check it in multi-tenant mode, so we can only check it in single-tenant mode

Why we cannot check it in multi-tenant mode? How's it more complicated than just loop through the DB of each tenant (if each tenant have a seperate DB?)

I wanna understand it so make sure my understanding Authgear align with the implementation.

> If we check at startup in single-tenant mode, we cannot start the server when DB is not up, which is not a good practice.

This one is a good point.

> Checking it every request would be costly, and our experience is that developers would trigger DB related errors easily (therefore notice it) if database schema is not up-to-date.

Agree we should not check it in every request

> If developer desire, they can setup a initContainer in k8s deployment to verify database schema/auto migrate.

But Authgear is not necessarily run in k8s right?

**Comment by kiootic** [comment]
FYI: The database URL is stored in per-app config. In multitenant mode, the config is resolved from config source at request time.

It may not be practical (in terms of time and resource) to connect to a large amount of tenant databases to check their schema on startup.

Also, tenants may be added/removed during the lifetime of the server. Tenants added after startup cannot be checked effectively.

**Comment by chpapa** [comment]
ic... so am I right that we would assume `authgear migrate` might have to run parallelly with an authgear daemon actively running?

> FYI: The database URL is stored in per-app config. In multitenant mode, the config is resolved from config source at request time.

Just curious, do we do any caching of the config, or we literally resolve config source at request time for every request?

**Comment by kiootic** [comment]
> Just curious, do we do any caching of the config, or we literally resolve config source at request time for every request?

Multi-tenant mode is not yet implemented. Single-tenant mode (i.e. read a single set of config files) read the config at startup and reuse it (in-memory) every request.
