### ISSUE TITLE
Improve copy client id button

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1110]
Show an `Copy` icon button next to the ClientId

Show ~a toast (`Snackbar` in Fluent UI)~ a `Tooltip` with the message "Copied to clipboard" when successfully copied, dismiss after 2 seconds

Design:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=4252%3A22663

Ref:
https://fabricweb.z5.web.core.windows.net/oufr/8.26.1/#/examples/tooltip
Tooltip with a closing delay

**Comment by fungc-io** [comment]
@samchan0221 Updated description and included the design file

**Comment by samchan0221** [comment]
time estimation: 3 hrs

**Comment by fungc-io** [comment]
Updated the design to Tooltip to make use of Fluent UI components

**Comment by fungc-io** [comment]
I've found a bug
- there are more than 2 applications in the project
- clicking the copy button on the second row
- The tooltip is shown above the 1st copy button

<img width="504" alt="Screenshot 2021-08-06 at 11 27 54" src="https://user-images.githubusercontent.com/15207470/128451723-af57fb06-366a-4adb-920c-30d22029c40d.png">
