### ISSUE TITLE
Biometrics Login identities missing in user setting page 

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1112]
On user setting page:
![image](https://user-images.githubusercontent.com/16920209/113264878-10732300-9306-11eb-9f38-1e3515e49019.png)

Same user On portal:
![image](https://user-images.githubusercontent.com/16920209/113264951-2680e380-9306-11eb-80ad-38977f98d335.png)

**Comment by louischan-oursky** [comment]
You have to enable it in portal.
