### ISSUE TITLE
Update default signup rate limit

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1122]
Update from 1 signup per 1min to 10 signup per 1min

**Comment by mr9dollars** [comment]
https://3.basecamp.com/3096882/buckets/11477446/messages/3644061125#__recording_3646172589

@louischan-oursky Is our rate limit per IP? Will it overload the server if it is 10 or20? Considering a case where multiple admins create app accounts for their users with same IP

**Comment by louischan-oursky** [comment]
It is per IP. If the accounts are created via API admin, rate limit does NOT apply.
