### ISSUE TITLE
User search feature on Portal

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1124]
Currently, there is no user search function. Admin is hard to get through pages to locate a user to perform some user actions.

- [ ] Allow to search user through email, username, user id or phone number

![image](https://user-images.githubusercontent.com/16920209/113995331-bbe12200-9888-11eb-959b-728a03859c1e.png)

**Comment by mr9dollars** [comment]
@louischan-oursky 
I wanna search for a user with email kelvinhon@oursky.com. When I type kelvin, it cannot show the result. But it works when I search kelvinhon.

**Comment by mr9dollars** [comment]
Also saw this error when I am searching in demo-app
![image](https://user-images.githubusercontent.com/16920209/118223012-3f5ae800-b4b3-11eb-8531-edc12ff5d8aa.png)

**Comment by stanleylhs** [comment]
Our testers also discovered this issue. As typing e.g. userID/email/phone number on search bar couldn't yield desired search result.

**Comment by fungc-io** [comment]
@stanleylhs can you provide the specimen which the QA team discovered that yield bad results?

**Comment by stanleylhs** [comment]
@fungc-io https://portal.authgear-staging.com/project/QXBwOmJ1Z2J1Z2xvbmc/users/

Will this specific apps, search for `ourskydummy`

List of all users, see all users have `ourskydummy` email address:
![Screenshot 2021-07-13 at 12 18 28 PM](https://user-images.githubusercontent.com/4337525/125390219-12548400-e3d5-11eb-82d7-55708c56c500.png)

Only 1 records is shown after searching for `ourskydummy`
![Screenshot 2021-07-13 at 12 19 38 PM](https://user-images.githubusercontent.com/4337525/125390227-1680a180-e3d5-11eb-88b9-2f550012d45c.png)

**Comment by stanleylhs** [comment]
@fungc-io 

On the specific app, search for `ourskydummy`

List of all users, see all users have `ourskydummy` email address:
![Screenshot 2021-07-13 at 12 18 28 PM](https://user-images.githubusercontent.com/4337525/125391419-12ee1a00-e3d7-11eb-95da-f707402f8efa.png)

Only 1 records is shown after searching for `ourskydummy`
![Screenshot 2021-07-13 at 12 19 38 PM](https://user-images.githubusercontent.com/4337525/125391605-62344a80-e3d7-11eb-99b1-d3cfc61507b0.png)

**Comment by carmenlau** [comment]
Found that in the testing app, the users that cannot be searched should be created through admin portal. The root cause of the problem is due to #1381 that makes the admin api failed to perform some interaction effects (e.g. reindex user to elasticsearch).
