### ISSUE TITLE
How to show IdP session and offline grant

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1128]
> Special case on how to show sessions. When an IdP session is associated with exact one offline grant, we show the offline grant only. Of course, this implies we have to revoke them at the same time. When an IdP session is associated with more than 1 offline grant, we show them separately.

**Comment by chpapa** [comment]
We need to consider the following scenario, and show the session list (or device list) with the following results:

1. Desktop Web
= 1 new Session
= 1 device

2. Mobile App login
= 1 new Session 
= 1 device

3. Mobile Safari Login > Mobile App Login
= 2 new Sessions (or 
= 1 device

4. (Case 1 - Desktop Web) + SPA login with offline grant
= 1 new Session
= 1 device

**Comment by louischan-oursky** [comment]
# Sessions in online services

## Google

On myaccount.google.com, sessions are grouped by devices.

Google has its own way to somehow identify a device.

### Grouping browser sessions into mobile session is likely based on heuristic

At the beginning of the experiment, MacBookPro15,2 (my macbook) and rfc1123 (my iPhone 12 mini) are my identified devices.

I signed in with a private tab in the mobile Safari on rfc1123.
No new device was identified.

I signed out rfc1123.
The remaining device is MacBookPro15,2.

I borrowed my friend's iPhone and then signed in with a private tab in the mobile Safari.
The rfc1123 device was resurrected.
Their iPhone is neither named rfc1123 nor the model is iPhone 12 mini.

So device identification is not precise and is likely based on heuristic.

### HTTP User-Agent header and navigator affects how a device is identified.

I installed User-Agent Switcher on Firefox on my macbook.
I switched the User-Agent to Windows/Edge and I signed in.
A new device Windows was identified.

## Facebook

On facebook.com, sessions are not grouped.

Here is my session list.

> Mac, Hong Kong
> Chrome, Active Now
> 
> Mac, Hong Kong
> Firefox, just now
> 
> iPhone 12 mini, Hong Kong
> Facebook app, about an hour ago
> 
> iPhone 12 mini, Hong Kong
> Messenger for iOS, 2021-03-27

As you can see, sessions are not grouped.

# Insights from online services

Device identification is hard and the goal of Authgear is not about device tracking.
Therefore I suggest we do not group sessions by devices.

If our session list looks like that of Facebook, most user should understand it.

The real challenge for ourselves is to group IdP sessions and offline grants so that they appear logically to the user.

# Session properties that can be used for identification

## IdP Session properties that can be used for identification

- User-Agent

## Offline grant properties that can be used for identification

- User-Agent
- Device Name (e.g. rfc1123)
- Device Model (e.g. iPhone 12 mini)
- Application ID (e.g. com.authgear.exampleapp.ios)
- The ID of the IdP session that involved in the authorization code flow. It may not be present if authorization code flow is not used, for example, biometric login.

# Grouping variant 1

In this grouping variant, Application ID is not used at all.
Offline grants are first grouped by Device Name, Device Model and User-Agent.

## Grouping variant 1 example

Given the following list of sessions.

> Offline Grant A (An offline grant issued to a web SPA)
> User-Agent: Safari on Mac
> IdP Session ID: IdP Session A
>
> Offline Grant B (An offline grant issued to a mobile application via authorization code flow)
> Device Name: rfc1123
> Device Model: iPhone 12 mini
> Application ID: com.authgear.exampleapp.ios
> IdP Session ID: IdP Session B
>
> Offline Grant C (An offline grant issued to a mobile application via biometric login)
> Device Name: rfc1123
> Device Model: iPhone 12 mini
> Application ID: com.authgear.exampleapp.ios
> IdP Session ID: null
>
> IdP Session A (An IdP session created in a web browser)
> User-Agent: Safari on Mac
>
> IdP Session B (An Idp session created in ASWebAuthenticationSession)
> User-Agent: Mobile Safari
>
> IdP Session C (An IdP session created in a web browser)
> User-Agent: Safari on Mac

The user should see the following items in the session list.

> rfc1123 (which is a group of Offline Grant B, Offline Grant C, IdP Session B)
> Last Access At: The latest last access among the group members.
>
> Safari on Mac (which is a group of Offline Grant A, IdP Session A)
> Last Access At: The latest last access among the group members.
>
> Safari on Mac (which is a group of IdP Session C)
> Last Access At: The latest last access among the group members.

## Revocation semantics

Since what the user sees is a group, all member of the groups are revoked all together.
Since Application ID is unused, revocation will sign out ALL applications on the same device.

## Logout semantics

Signing out a session will revoke its group member.
So it is equivalent to revocation.

**Comment by chpapa** [comment]
@louischan-oursky thanks for the update, I try to guess how the grouping works.

I think one case we need to consider more is logout, if I have multiple apps logged in from a single IdP Session, if I logout one of the app, do I expect to logout other apps and the IdP session too?

Another issue I can think of now is, this feature was about "letting users know when its session got hijacked"

Let's say if the user has a mobile phone with IdP Session, the IdP Session token got stolen and used to generate another offline grant in another device, how can we show that? Maybe the answer is we need to be very strict on the grouping (e.g. group only if same IP address, same browser of the IdP Session?)

**Comment by chpapa** [comment]
Another idea, maybe for the "groupped session", we will show some indication like "there is a Safari, an iPhone app called com.authgear.xxx, and another iPhone app called "xxx.yyy.zzz") so users can still see what might be wrong inside?

**Comment by louischan-oursky** [comment]
# Details on grouping rules

Offline grants are first grouped by Device Name and Device model.
And then IdP sessions referenced by an offline grant are grouped together.
Finally IdP sessions without any reference are grouped by User-Agent.

# The list of sessions we use

This is the list of sessions we use in the following examples.

```
Offline Grant A (An offline grant issued to a web SPA)
User-Agent: Safari on Mac
IdP Session ID: IdP Session A

Offline Grant B (An offline grant issued to a mobile application via authorization code flow)
Device Name: rfc1123
Device Model: iPhone 12 mini
Application ID: com.authgear.exampleapp.ios
IdP Session ID: IdP Session B

Offline Grant C (An offline grant issued to a mobile application via biometric login)
Device Name: rfc1123
Device Model: iPhone 12 mini
Application ID: com.authgear.exampleapp.ios
IdP Session ID: null

IdP Session A (An IdP session created in a web browser)
User-Agent: Safari on Mac

IdP Session B (An Idp session created in ASWebAuthenticationSession)
User-Agent: Mobile Safari

IdP Session C (An IdP session created in a web browser)
User-Agent: Safari on Mac
```

# Sessions are grouped and details of group members are shown

The user can see which session is suspicious.

```
rfc1123
|Terminate all sessions of this group|
  Mobile Safari
  Last Activity: an hour ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Application: com.authgear.exampleapp.ios
  Last Activity: just now
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Application: com.authgear.exampleapp.ios
  Last Activity: an hour ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

Safari on Mac
|Terminate all sessions of this group|
  Last Activity: about a month ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Last Activity: about a week ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Last Activity: about a day ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|
```

# IdP session without any offline grants can only be grouped by User-Agent

If the user terminates the two offline grants of the iOS application, the session list becomes:

```
Mobile Safari
|Terminate all sessions of this group|
  Mobile Safari
  Last Activity: an hour ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

Safari on Mac
|Terminate all sessions of this group|
  Last Activity: about a month ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Last Activity: about a week ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Last Activity: about a day ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|
```

It is because the IdP session on Mobile Safari is no longer referenced by any offline grant,
so it can only be recognized by its User-Agent.

**Comment by louischan-oursky** [comment]
# How to group sessions

Offline grants are first grouped by Device Name and Device model.
Offline grants issued to mobile devices can be grouped because Device Name and Device model are available.
Offline grants issued to web browser can NOT be grouped because Device Name and Device model are unavailable.

IdP sessions referenced by an offline grant are grouped together.
IdP sessions referenced by an offline grant may appear in more than 1 group.

Remaining IdP sessions are NOT grouped at all.

# The list of sessions we use

This is the list of sessions we use in the following examples.

```
Offline Grant A (An offline grant issued to a web SPA)
User-Agent: Safari on Mac
IdP Session ID: IdP Session A

Offline Grant B (An offline grant issued to a mobile application via authorization code flow)
Device Name: rfc1123
Device Model: iPhone 12 mini
Application ID: com.authgear.exampleapp.ios
IdP Session ID: IdP Session B

Offline Grant C (An offline grant issued to a mobile application via biometric login)
Device Name: rfc1123
Device Model: iPhone 12 mini
Application ID: com.authgear.exampleapp.ios
IdP Session ID: null

IdP Session A (An IdP session created in a web browser)
User-Agent: Safari on Mac

IdP Session B (An Idp session created in ASWebAuthenticationSession)
User-Agent: Mobile Safari

IdP Session C (An IdP session created in a web browser)
User-Agent: Safari on Mac
```

# Sessions are grouped and details of group members are shown

The user can see which session is suspicious.

```
rfc1123
|Terminate all sessions of this group|
  Mobile Safari
  Last Activity: an hour ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Application: com.authgear.exampleapp.ios
  Last Activity: just now
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Application: com.authgear.exampleapp.ios
  Last Activity: an hour ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

Safari on Mac
|Terminate all sessions of this group|
  Safari on Mac
  Last Activity: about a month ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Safari on Mac
  Last Activity: about a week ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

Safari on Mac
Last Activity: about a day ago
IP address: x.x.x.x
Location: Hong Kong
|Terminate this session|
```

# IdP sessions without any offline grants are NOT grouped

If the user terminates the two offline grants of the iOS application, the session list becomes:

```
Mobile Safari
Last Activity: an hour ago
IP address: x.x.x.x
Location: Hong Kong
|Terminate this session|

Safari on Mac
|Terminate all sessions of this group|
  Safari on Mac
  Last Activity: about a month ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

  Safari on Mac
  Last Activity: about a week ago
  IP address: x.x.x.x
  Location: Hong Kong
  |Terminate this session|

Safari on Mac
Last Activity: about a day ago
IP address: x.x.x.x
Location: Hong Kong
|Terminate this session|
```

# Revocation semantics

Revoke a session affects the session itself only.

# Logout semantics

Logging out a session affects the session itself only.

**Comment by louischan-oursky** [comment]
- Shorten "Terminate sessions of this group" to "Terminate"
- Debug why logging in in a mobile app would result in duplicate IDP session.

**Comment by louischan-oursky** [comment]
@carmenlau I cannot reproduce the duplicate IdP session bug :(
I am going to open a PR to just rename the button label.
