### ISSUE TITLE
User table export

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1158]
#1132

- [ ] columns included: ID, username, email, phone, signed up, last login, is active, number of active sessions
- [ ] Export the filtered and searched users

![image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/109f8315-3c60-44e1-9ded-26c16a07023b/a4e0fcfb-4368-4177-8e5c-eb4eaad3b2cd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8xMDlmODMxNS0zYzYwLTQ0ZTEtOWRlZC0yNmMxNmEwNzAyM2IvYTRlMGZjZmItNDM2OC00MTc3LThlNWMtZWI0ZWFhZDNiMmNkIiwiaWF0IjoxNzE5NDk3Mzg3LCJleHAiOjMzMjkwMDU3Mzg3fQ.ji3ABvncz4ezRNNnlZGKM7O567Rhr809u1pA5ix8Iok)

**Comment by fungc-io** [comment]
replaced by project: [User Search Query & Export​](https://linear.app/authgear/project/user-search-query-and-export-75e490b2f89e)
