### ISSUE TITLE
Update to using POST request when logout with `id_token_hint`

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#1191]
Server should handle both GET and POST request. But in js sdk, should use POST request to do the redirection for security reason. We need to do some experiment and see if the following approach works:

1. In JS SDK, when redirecting to the end_session_endpoint, construct a form with POST method and trigger submit.
2. In the `end_session_endpoint`, always perform `GET` redirect when handling `POST`. If logout is valid, redirect user to post logout uri. If logout is not valid, redirect to the original logout confirmation page
3. Check if the browser back works properly if we always redirect to GET after the POST request.

**Comment by mr9dollars** [comment]
handle with another approach in #1195
