### ISSUE TITLE
Add token_endpoint_auth_methods_supported in OpenID Connect Discovery

### ISSUE THREAD

**Issue by tonyhhyip** [authgear/authgear-server#1228]
`token_endpoint_auth_methods_supported` is not provided in OpenID Connect Discovery endpoint (/.well-known/openid-configuration)

- Authgear Server Date/Version:
- Application Platform:
- [x] Attached logs, screenshots
<img width="702" alt="image" src="https://user-images.githubusercontent.com/9844551/120513631-0c937800-c3ff-11eb-9dc6-04d1547c4b96.png">

#### Expected Results

`token_endpoint_auth_methods_supported` is provided in the JSON document

#### Actual Results

`token_endpoint_auth_methods_supported` is not provided in the JSON document

#### Spec
https://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.3

**Comment by louischan-oursky** [comment]
Thank you for telling us this! We do not support confidential client (i.e. `client_secret`) at the moment, so we do not perform authentication at all at the token endpoint. However, the spec says that if `token_endpoint_auth_methods_supported` is omitted, the default is `["client_secret_basic"]`. So the correct value should be an empty array `[]`.
