### ISSUE TITLE
Option in the portal to remove the checkbox for user to choose to not receive the OTP for the same device

### ISSUE THREAD

**Issue by andrewsuryowidagdo** [authgear/authgear-server#1232]
Option in the portal to remove the checkbox for user to choose to not receive the OTP for the same device

OTP is acting as the second authentication of the account and it is required for user to do the second authentication. Even though the common practice in the industry is that they have checkbox to not ask in this device again, the user still wants to force end-user to always go through 2FA everytime they login

**Comment by mr9dollars** [comment]
- Default to allow user to not receive the OTP for the same device
- Add a config for disabling such option.

**Comment by carmenlau** [comment]
Checked the code, we already have this config in authgear.yaml. So what we need to do is to allow developer configure it in the portal.

The config in authgear.yaml
```
authentication:
  device_token:
    disabled: true
```

**Comment by louischan-oursky** [comment]
I could not recall that we can disable device token already :( Too many features to remember.

**Comment by louischan-oursky** [comment]
I tried to turn `disabled` to true and it is still working.
