### ISSUE TITLE
[Username login] Cannot login using case sensitive usernames after case sensitive username is disabled

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#1236]
## Background:
- Device / Browser (OS version): iPhone 11 Pro IOS 14.5
- Build: Version 1.0 (1622188340) May 28,2021 at 15:56

## Description:
Registered username that contains uppercase and lowercase letters cannot be used to login after case sensitive username is disabled.

## Steps to reproduce:
1. Enable case sensitive username in portal 
2. Sign up using a username that contains uppercase and lowercase letters (e.g. AsTuVaa)
3. Login successfully
4. Logout
5. Disable case sensitive username in portal
6. Login using the original username, username in lowercase letters only  (e.g. astuvaa), username in uppercase letters only (e.g. ASTUVAA) and username having different case letters  (e.g. aStuvaa,AStuva...).
7. The above set of data produce 'Invalid credentials'

## Expected result:
After case sensitive username is disabled, user who registered before should be able to login.

## Screenshot:
![IMG_0089](/uploads/d234bcd8351f4f53e6d57975895827f2/IMG_0089.PNG)![IMG_0089](/uploads/c5deac97edfd13008f2ad5253d7ee728/IMG_0089.PNG)

**Comment by chpapa** [comment]
Same reason at #1237
