### ISSUE TITLE
Fail to search user with some specific strings

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1247]
![image](https://user-images.githubusercontent.com/16920209/121653101-ea6cba80-cace-11eb-934e-c6895eb7da83.png)

#### Expected Results
- Should search successfully
#### Actual Results
- Displayed error
#### Steps to reproduce
1. Go to https://demo-app.authgear-staging.com
2. Go to User list
3. Search "lo"
4. See the error
5. No problem for searching "l" or "lou"

**Comment by louischan-oursky** [comment]
Duplicate of https://github.com/authgear/authgear-server/issues/1222
