### ISSUE TITLE
Client Application initiated Re-authentication

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1251]
- [x] Remove `acr` claim in ID token
- [x] Add `https://authgear.com/user/can_reauthenticate` claim in ID token
- [x] Add authenticated_at in IdP session
- [x] Remove sensitive claims from ID token
- [x] Support custom grant type to refresh custom ID token claims
- [x] Support `auth_time` in ID token
- [x] Support `amr` `x_biometric`
- [x] Support `prompt=none` (done in select screen PR)
- [x] Support `max_age=n` (depends on authenticated_at in IdP session)
- [x] Support `id_token_hint` in interaction
- [x] Support reauthentication by adding a new intent

**Add SDK support**
- [x] JS - web & react-native
- [x] iOS
- [x] Android

**Comment by fungc-io** [comment]
Added task checkboxes to track the development of SDKs support
