### ISSUE TITLE
Better UX for country code selector in phone input 

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1253]
When setting SMS 2FA, phone number is needed
The country code picker is hard to use
It would be great if:
- Country name is shown, and searchable by the end-user
- Sort by country name instead to numeric order (as an option)
- ~allow admin to set which countries have priority for their end-users demographics~
- pre-selected by geoip (as an option)

**Comment by louischan-oursky** [comment]
The third point is possible now. A country calling code can be pinned to stay at the top.
The forth point is also possible given that we have embedded geolite2.

**Comment by chpapa** [comment]
I would suggest we just use something like this? https://github.com/jackocnr/intl-tel-input

It already does:

1. Select country by IP
2. Auto format and if you type phone no directly it automatically select the country
3. Looks good and okay on mobile

**Comment by fungc-io** [comment]
Add the option to pre-selected by IP in the Portal
Default to be checked

![country-code preselect](https://user-images.githubusercontent.com/15207470/125385520-3c09ad00-e3cd-11eb-9fb0-9881aca104df.png)

**Comment by fungc-io** [comment]
depends on #1342

**Comment by fungc-io** [comment]
One minor change, the input field should have `inputmode="tel"` to have the `+` button in the mobile keypad

**Comment by fungc-io** [comment]
Is pre-select by geoip and the option mentioned in https://github.com/authgear/authgear-server/issues/1253#issuecomment-878749213 implemented?

**Comment by louischan-oursky** [comment]
The auto detection is implemented and it is always on. The option is not added.

**Comment by louischan-oursky** [comment]
Let me add the option.
