### ISSUE TITLE
Support x_suppress_idp_session_cookie

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1257]
The SDK should specify x_suppress_idp_session_cookie=true when shareSessionWithDeviceBrowser is false.

When x_suppress_idp_session_cookie is true, IDP session cookie is neither written and read.

**Comment by chpapa** [comment]
Discuss altogether: possible to make IdP Sessions "re-authenticate" on another client? (Say from mobile to web on same device)

**Comment by fungc-io** [comment]
A simpler alternative solution for the problem: #1391

**Comment by fungc-io** [comment]
re-open due to the conclusion in https://github.com/authgear/authgear-server/issues/1391#issuecomment-895821271
renamed and edited the issue to be more specific.
