### ISSUE TITLE
[Portal] Broken link - SSO integration guide in Portal

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1271]
![Screenshot 2021-06-17 at 15 15 48](https://user-images.githubusercontent.com/15207470/122349636-02d14f00-cf7f-11eb-9138-055ed15be25c.png)
The link in the Portal is broken. The url of the page has been changed to https://docs.authgear.com/strategies/how-to-setup-sso-integrations due to restructuring of the doc.

**Comment by joyzoursky** [comment]
Guess this should be a minor issue instead of major
