### ISSUE TITLE
Add a link to get help in Auth UI

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1281]
Users may want to provide support to their end-users when the end-users experience problems such as losing MFA devices.
It'd be great if developer can optionally show a link at the bottom of Auth UI, be it a mailto or webpage.

**Comment by fungc-io** [comment]
**Proposed Design:**

Developers shall be able to add link in **Portal > UI Settings > Link Settings**

In MFA login screen,
change **Enter recovery code instead** into --> 
If no support link configured: **Having Trouble? Use a recovery code.**
If support link is configured: **Having Trouble? Use a recovery code or contact customer support.**

<img width="516" alt="Screenshot 2021-06-21 at 13 02 24" src="https://user-images.githubusercontent.com/15207470/122710216-6f579100-d292-11eb-88a3-08930a6f2afe.png">

**Comment by chpapa** [comment]
The word "contact customer support" could be changed as well as the link right?

**Comment by fungc-io** [comment]
I suggest to let them changed it in the Localization settings
