### ISSUE TITLE
Improve Auth UI button copywriting in Login

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1291]
## Forgot Password Screen

<img width="571" alt="bad-copywriting-forgot-pw" src="https://user-images.githubusercontent.com/387241/123064490-e6cb2300-d440-11eb-86af-9256b6ccb7f8.png">

- [x] Change the default copywriting of "Request to send reset password instruction to the email below" to "Confirm to send reset password code to the email below"
- [x] Font size of email address same as the content text above, but bold? (Have to try see if it is okay)
- [x] **Forgot Password Email Request:** Next -> Send Reset Email

## Login Screen

- [x] When type the wrong email address, it said "Invalid Credentials", we should use "Cannot find the user"

**Comment by chpapa** [comment]
Updated the content for a few more copywriting things to solve in one go.
