### ISSUE TITLE
WebAuthn

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#130]
## Problem/Goal

- Biometric login on browser become feasible as the increased support for WebAuthn standard
- To provide more passwordless option for the users, e.g. Yubikey
- To support the use of passwordless on ios/android devices, and websites via Chromium, Safari, Firefox.

## Solution
- End-users can use WebAuthn to authenticate themselve, for registration and (~)MFA
- If it is used as primary authenticator, user will first input their login ID, i.e. phone/email/username, and then auth via webauthn.

Platforms:
* Windows Desktop (Firefox / Edge / Chrome): Windows Hello / FIDO2 (Yubikey) / U2F (Yubikey)
* Mac Desktop (Firefox / Chrome / Safari): FIDO2 (Yubikey) / U2F (Yubikey) / TouchID
* iOS (Safari): Yubikey 5Ci NFC, Lightening, FaceID/TouchID
* Android (Chrome): Yubikey NFC, USB-C

Figma: https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6752%3A101280

Reference:
- Apple Passkey https://9to5mac.com/2022/06/07/passkeys-passwordless-sign-in-ios-16/
- Chrome https://developer.chrome.com/docs/devtools/webauthn/

## Appetite
4 weeks

**Comment by tonyhhyip** [comment]
Any update on this feature?

**Comment by fungc-io** [comment]
User flow for end-user:
1. Sign up with a login ID and an authenticator, e.g. email + password
2. Prompted to setup WebAuthn on its device/hardware key
3. User can set it up or skip
4. If set up, the end-user can login directly using the device or key, 
without typing their login ID and password.

**Comment by louischan-oursky** [comment]
## Desktop Chrome

if the user choose "This Device", the credential is stored in Chrome. It can be clear with `Settings -> Privacy and security -> Clear browsing data -> Advanced -> Check password and other sign-in data`. Note that there is no way to delete individual credential. The "This Device" option corresponds to "platform" [AuthenticationAttachment](https://www.w3.org/TR/webauthn-2/#enumdef-authenticatorattachment). If we set the attachment to be "cross-platform", the "This Device" option is gone. The user must choose cross-platform authenticator.

**Comment by fungc-io** [comment]
Design needed:
- "Add Passkey"
- "Use Passkey", if autofill is not available
- Passkey management in `/settings`
- Passkey icon that fits into tablericons / fluentui
  - [reference from ios](https://hacknicity.medium.com/sf-symbol-changes-in-ios-15-4-31361f112123#:~:text=Here%E2%80%99s%20a%20closer%20look%20at%20them%3A)
