### ISSUE TITLE
[Demo app, Biometric Login] Device still shown in biometric login list on web portal after disabling

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1305]
## Background:
- Device / Browser (OS version): Chrome on Win10 (Web), iPhone X (iOS 13.1.2) (Demo app), Pixel 3 (An 11) (RN Demo app)
- Build: 
  - Server - Staging (2021 Jun 30)
  - Demo app - Version 1.0 (1622188340)

## Description:
Device still shown in biometric login list on web portal after disabling from app.

## Steps to reproduce:
1. [Web and App] Login
2. [App] Enable Biometric Login 
3. [Web] Open the Biometric Login page.
4. [Web] See one device in the list
5. [App] Disable biometric login
6. [Web] Refresh web page
7. [Web] See device still shown
8. Repeat step 2-7, see the same device kept on duplicating

## Expected result:
Should not show device in the biometric login list after disabling from app.

## Screenshot:
![image](https://user-images.githubusercontent.com/4337525/124303477-168ecf00-db95-11eb-8567-b66e494bca0a.png)
(notice "enable biometric" is clickable instead of "disable biometric")

![image](https://user-images.githubusercontent.com/4337525/125557601-fd99f786-80a3-496b-b540-a31473350338.png)

![image](https://user-images.githubusercontent.com/4337525/125557678-c694076e-b98e-44fc-bdab-ee1ecdc7b331.png)

**Comment by louischan-oursky** [comment]
Disable biometric on the device only removes the credentials on the device only.
