### ISSUE TITLE
[Discussion] [Portal, Users] Improve UX for Country Code dropdown

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1310]
## Background:
- Device / Browser (OS version): Chrome on Macbook Pro(10.14.6)
- Build: Staging on 5 Jul 2021

## Description:
If all country code are chosen as in default setting, the dropdown list will become very long, thus it is difficult to find desired country code. 

This long dropdown appears for both end user and admin portal: 
1. End user: Sign up/Login and Add phone number in portal
1. Admin Portal: Add phone as Identities for Users

(Note: Country code listing in LoginID section is not using dropdown, the listing can be filtered by country name or county code typing search box.)

### Prerequisite:
1. Go to admin portal site of any customised app
2. Go to Login ID, enable phone number, select a large number of country code

### Admin Portal:
3. Go to Users, select a User, click Identities tab, change existing phone number or Add Identity by Phone no.
1. See the long list of country code that is difficult to navigate.

### User:
[Sign up/Login]
1. Sign up/Login using phone number
1. See the long list of country code

[Add phone number]
1. Sign in as user on Authgear app portal
1. Under My Account, click Phone Number, add a phone number
1. See the long list of country code

## Expected result:
UX should be enhanced to help user find their country code. Suggest to reference Google/Facebook by adding country name or filter by typing like in the Login ID section. Open for other solutions.

## Screenshot:
[Admin Portal] Add Identities for user:

![image](https://user-images.githubusercontent.com/4337525/124494744-bba1e580-dde9-11eb-9228-79c29e5fb81f.png)

[User] Sign up / Login:

![image](https://user-images.githubusercontent.com/4337525/124494758-c2305d00-dde9-11eb-8d4b-92b1262ea37e.png)

[User] Add phone number:

![image](https://user-images.githubusercontent.com/4337525/124494773-c8263e00-dde9-11eb-973e-6930b76076c7.png)

## References:
Facebook and Google both list country name first before the country code sorted by alphabetical order to help user to find country code. Google is also displaying the country flag for easier discovery.

Google

![image](https://user-images.githubusercontent.com/4337525/124494786-ce1c1f00-dde9-11eb-8c8f-df33411e4502.png)

Facebook

![image](https://user-images.githubusercontent.com/4337525/124494800-d2e0d300-dde9-11eb-818b-e0d4ed95fbb4.png)

Filter by Typing either Country Name or County Code as in Login ID section

![image](https://user-images.githubusercontent.com/4337525/124494814-d96f4a80-dde9-11eb-9b01-366414a1c61d.png)

**Comment by fungc-io** [comment]
Similar issue: #1253

**Comment by stanleylhs** [comment]
Sorry for the duplication, can close this and let me merge to the comments
of the old thread.
