### ISSUE TITLE
[Demo app, Android 11] Install failed with Native App

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1311]
## Background:
- Device / Browser (OS version): Google Pixel 3 (Android 11)
- Build: 1.0 (1) May 28,2021 at 16:04

## Description:

For Android 11, installation failed for Authgear Test Android.

`adb: failed to install /Users/oursky/Downloads/javasample-release.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.oursky.authgeartest]`

## Steps to reproduce:
1. Download from AppCenter, install the APK
2. See the installation failed / App not installed.

## Expected result:
Install correctly.

## Screenshots:
![image](https://user-images.githubusercontent.com/4337525/124498192-85b33000-ddee-11eb-9e45-6d0e56731849.png)

**Comment by fungc-io** [comment]
ref: https://github.com/authgear/authgear-sdk-js/issues/114
ref: https://github.com/authgear/authgear-sdk-android/issues/81

**Comment by stanleylhs** [comment]
Sorry for the duplication, can close this one.
