### ISSUE TITLE
Experiment Sendgrid for transactional email

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1314]
The delay of emails is very likely due to Google's anti-phishing detection. We may want to try switch to Sendgrid to solve the problem.

reference article:
https://workspaceupdates.googleblog.com/2017/05/early-detection-of-phishing-via-delayed-delivery.html

**Comment by louischan-oursky** [comment]
- Check if Sendgrid has Postmark's domain API

**Comment by fungc-io** [comment]
The 4 minutes delay reappears,
We may need to experiment with changing the sender email address from `no-reply@...` to `support@...`
