### ISSUE TITLE
[Demo app] 'Open setting page' button not responsive after login

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1319]
## Background:
- Device / Browser (OS version): iPhoneXR (14.2), OnePlus 2 An 6.0.1
- Build: Version 1.0(1) Jul 07 2021 14:07
- Reported by: Michael Chin
- Application: ourskyqa

## Description:
'Open settings page' is unresponsive after login

## Steps to reproduce:
1. Enter Client ID and Endpoint in demo app and click Configure
2. Click 'open setting page'
3. See the button is unresponsive

## Expected result:
Should open settings page when button clicked

## Screenshot:

![image](https://user-images.githubusercontent.com/4337525/125560980-35f3ab5e-1dec-495a-91fb-7a49bd6aab77.png)
![image](https://user-images.githubusercontent.com/4337525/124789534-f4be8f00-df7c-11eb-9b9b-0300c294caed.png)

**Comment by fungc-io** [comment]
@stanleylhs
I can't reproduce this bug on my device.
Can you check if this still exist?

**Comment by stanleylhs** [comment]
@fungc-io Yes, can't reproduce yesterday. Sorry for not closing this earlier.
