### ISSUE TITLE
[Web Portal, UI Settings] Custom theme colour should be saved transiently for quick colour comparison

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1320]
ux/minor

## Background:
- Device / Browser (OS version): Chrome (90.0.4430.93) on macbook pro
- Build: Staging, 5 May 2021

## Description:
In UI Settings Light/ Dark mode tab, if any preset theme colour is selected, any custom theme colour which the user have picked will be lost. Therefore, it would be very inconvenient if users want to compare preset theme colour and desired custom theme colour.

## Steps to reproduce:
1. Login Authgear
2. Click any preexisting app (Create one if there is none)
3. Click UI Settings
4. Select a preset colour theme in Light/ Dark Mode
5. Click Custom 
6. Change Background, Text and primary colour 
7. Select a preset colour theme
8. Click Custom
9. See Background, Text and primary colour 

## Expected result:
It would be convenient if custom colour theme can be saved transiently as users might want to compare preset theme colour and custom theme colour.

## Screenshot:

https://user-images.githubusercontent.com/4337525/125577818-9884f0b6-b369-45e1-996c-58c78c929978.mp4

**Comment by samchan0221** [comment]
time estimation: 5hrs
