### ISSUE TITLE
[Portal, localization, Free] Editable SMS localization shown in free plan

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1359]
bug/trival

## Background:
- Device / Browser (OS version): Chrome on macbook
- Build: Staging
- Version Tag: 2021-07-14.0

## Description:
SMS messages are editable yet free plan app cannot use any SMS related features.

## Steps to reproduce:
1. Login
2. Create a free plan app
3. Click Localization on side menu
1. Click Forgot password/ passwordless authenticator
1. Scroll down see SMS message editable

## Expected result:
Should not be able to see any SMS related features.

## Screenshot:

![image](https://user-images.githubusercontent.com/4337525/125918924-68bb007d-6a59-427c-98ff-1940c18dc220.png)

**Comment by stanleylhs** [comment]
Issue validation check: Reproducible

## Description: 
Can still see SMS in Localization

## Background:
Device / Browser (OS version): Chrome 114.0.5735.198 on Mac 13.4.1
Build: staging 2023-07-05.0
Retested on: 10 July 2023

**Comment by joyzoursky** [comment]
free plan also have sms now, will close this
