### ISSUE TITLE
[Portal] All Login ID can be turned off

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1360]
bug/trival

## Background:
- Device / Browser (OS version): Chrome on Mac
- Build: Staging Version Tag: 2021-07-14.0
- App: `demo-enterprise` and `demo-free`

## Steps to reproduce:
1. Login in Admin Portal
2. Select the app
3. Go to Authentication, Login ID
1. Turn off all Login ID, click Save
1. See settings saved successfully
(6. Go to user login portal)
(7. See no way to login)

## Expected result:
Should stay like last version, prompt admin to keep at least one Login ID, prevent admin from clicking Save when all Login ID is off.

## Screenshot:
![image](https://user-images.githubusercontent.com/4337525/125933986-85b1a4e5-5200-4375-9e51-26df42d571f4.png)

![image](https://user-images.githubusercontent.com/4337525/125934002-83f6a959-e7a6-4157-a837-18c7590e5a7e.png)

**Comment by fungc-io** [comment]
User may want to disable all Login ID when only social login is allowed
