### ISSUE TITLE
[Portal, Add user] Inconsistent sign up logic between portal and app

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1361]
bug/major

## Background:
- Device / Browser (OS version): Chrome on macbook
- Build: Staging
- Version Tag: 2021-07-14.0

## Description:

If passwordless via email is toggled and ordered at the top, then the password textfield will be disabled when creating a new user using username. While creating a new user on app will ask for a password.

## Steps to reproduce:
1. Login Portal
1. Go to Authentication > Login ID
1. Switch off email and phone login option
1. Go Authentication > Authenticator
1. Tick passwordless via email and phone and order them at the top
1. Click Users on the side menu
1. Click Add user
1. Click username
1. See password textfield is disabled

## Expected result:
Password textfield should not be disabled.

## Screenshot:
![image](https://user-images.githubusercontent.com/4337525/125934616-f41b3c80-d2f6-4f91-8d08-b5c9379cbbef.png)

![image](https://user-images.githubusercontent.com/4337525/125934656-3611b1ce-fc78-4ec6-b20d-f6d88c946856.png)

**Comment by fungc-io** [comment]
Can reproduce bug:
When only the username is enabled in Login ID and a passwordless authenticator is enabled, the admin portal won't allow password input when adding users. While the AuthUI can handle this correctly.

Another UX improvement:
In the admin portal, when only one login ID is enabled, it should be default checked when adding users.
