### ISSUE TITLE
[Portal, add user, session] Creating new user will trigger a Login record in Session

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1362]
bug/minor

## Background:
- Device / Browser (OS version): Chrome on macbook
- Build: Staging
- Version Tag: 2021-07-14.0

## Description:
Creating new user will trigger login session seen in user profile, while the new user has never been logged in.

## Steps to reproduce:
1. Login
2. Click into an app
3. Go to Authentication > Login ID
4. Tick username
5. Go to Authentication > Authenticator
1. Tick Password and ordered it at the top
1. Go to Users > Add user
1. Create user by username
1. Go to newly created user profile > Session
1. See a login session

## Expected result:
1. Corresponding session should not have the type 'login'
1. Should not have this login session

## Screenshot:

![image](https://user-images.githubusercontent.com/4337525/125934891-6d80c432-4cf0-474e-889c-9319a4e87bbe.png)

**Comment by fungc-io** [comment]
Fixed in a related issues
