### ISSUE TITLE
[Android, React Native, Demo App, Dark mode] Text input is shown in white

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1363]
ui/minor

## Background:
- Device / Browser (OS version): Samsung S8 (AOS 9)
- Build: version 1.0 (1) Jul 13, 2021 at 18:53

## Description:
In dark mode, text input is shown in white.

## Steps to reproduce:
1. Switch on phone's dark mode
2. Open app
3. Input any text into any text field
4. See text input is shown in white

## Expected result:
Text input should be shown in white.

## Screenshot:
![image](https://user-images.githubusercontent.com/4337525/125939714-fd9c0736-3180-458d-98c1-85dd66fb7743.png)

**Comment by joyzoursky** [comment]
related https://github.com/authgear/authgear-server/issues/1075
