### ISSUE TITLE
[Portal] Concurrent edit by 2 admins of the same app on the same setting page will be overwritten

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1364]
bug/minor

## Background:
- Device / Browser (OS version): Chrome on Mac
- Build: Staging Version Tag: 2021-07-14.0

## Description:
When 2 admins of the same app open the same setting page, the last edit will overwrite the first one.

## Steps to reproduce:
1. Log in with 2 different admins of the same app
2. Go to the same setting page (e.g. Login ID)
3. With Admin 1, turn off Phone, Click Save
4. With Admin 2, turn off Username, Click Save
5. Refresh with both admin, see Phone turned on again as edit from Admin 2 overwrote the edit from Admin 1.

## Expected result:
Lock the setting page when editing to prevent concurrent edit.

## Screenshot:

https://user-images.githubusercontent.com/4337525/125940199-6239b6cd-3f21-4c03-bb39-7ac3fa499e46.mov

**Comment by stanleylhs** [comment]
Issue validation check: Reproducible

## Description: 
Two concurrent edits will still overwrite each other.

## Background:
Device / Browser (OS version): Chrome 114.0.5735.198 on Mac 13.4.1
Build: staging 2023-07-05.0
Retested on: 10 July 2023

**Comment by joyzoursky** [comment]
i think this is expected as the save is saving the settings of the whole current page but not only the changes.

**Comment by chpapa** [comment]
Maybe open an issue as pitch, as we probably would consider it a new feature to support concurrent edits in portal?

**Comment by chpapa** [comment]
Turned it into pitch format.

**Comment by fungc-io** [comment]
We've found a similar problem for single editor.
If a single editor open 2 tabs for the portal, and updating the 2 different pages simultaneously, the edits will get over-written.

A real case:
1. they open the "Application" and other tab for Authentication methods.
2. They added 1 redirect URI in the application details, and save
3. Switch to another tab to change the authentication method and save
4. Switch back to the application details and update the redirect uri. The authentication method changes are reverted.

This is due to the same root cause of this issue.

**Comment by fungc-io** [comment]
Hi @Ngkaokis @louischan-oursky ,
Based on our discussion, we will fix this issue by showing an warning message on save if the version on server is different from the editing version.

It is implemented by a simple optimistic lock utilizing an MD5 hash of the config file.

When the config is edited by another user, show a warning message in the portal

>  ## The project configuration was edited elsewhere
> 
> The project was edited in another browser tab or by another user. You can reload this page to use the latest version. Do you want to override the changes?
> 
> [Cancel] [Override Changes]

@chpapa Any concerns for the copywriting?
> [Cancel]

**Comment by chpapa** [comment]
Seems ok @fungc-io 

One minor details, sorry misleads you guys, instead of md5, changes detection algo which is faster like CRC32/64 should be used.

**Comment by louischan-oursky** [comment]
Implementation details

- Add `checksum: String` to AppResource. Must return the checksum of the app resource if the app resource exists.
- Add `checksum: String` to AppResourceUpdate. If `checksum` is provided, then the server must calculate the checksum of the resource. Compare the calculated checksum with the provided checksum. If they are different, then we detect a conflict. If `checksum` is not provided, this checking is NOT done (that is, the original behavior)
- The algorithm to calculate the checksum is illustrated here. https://go.dev/play/p/CooZjiSa_jz Basically it is just CRC32 IEEE, and then turn the uint32 into 4 big-endian bytes, finally encoded in hex.

@Ngkaokis
