### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#137]
- Use `zap` logger
- Review & improve logged messages

**Comment by kiootic** [comment]
Some notes from various attempts to refactor the logging mechanism:
- Most (modern) loggers (e.g. zap, zerolog), does not have good support on redacting a generic `interface{}` value, in name of performance.
- Most loggers does not support `TRACE` log level, except zerolog.

**Comment by louischan-oursky** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/14b5b6a944e390e368dd2e2ef234d220d8287d19/specification/logs/data-model.md

**Comment by louischan-oursky** [comment]
After discussion, we are going to change the logging framework.

Instead, we want to review current error reporting

- Log oauth error but do not expose it to end user.
