### ISSUE TITLE
Some question regarding the UI flow of login/signup

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#140]
When I look at the product demo, a few things I was wondering:

1. If a user sign up, MFA like OTP is required, and the user didn't finish setting it up or the browser suddenly close, would the login ID stuck because the account was created but no OTP is configured? If yes we need to see how to improve the behaviour.. maybe next login force users to continue configure the OTP?
    * I suspect it is too difficult, but if not, the ideal solution is have a configuration to determine if the account is not created if it didn't complete all required action like OTP setup or verify of email; OR to force continuing the process as above.

2. If a user do the following: Sign up by input phone no. => Verify SMS and click to send SMS (0) => Enter code (1) => Wrong, Enter Code (2) => Wrong, Enter Code (3); For user at step 3, if he can back, would it go back to step 2, or 0?

**Comment by kiootic** [comment]
> If a user sign up, MFA like OTP is required, and the user didn't finish setting it up or the browser suddenly close, would the login ID stuck because the account was created but no OTP is configured? If yes we need to see how to improve the behaviour.. maybe next login force users to continue configure the OTP?

The principle is that nothing is ever committed into the database until the end of the flow (e.g. signup flow, login flow) (a.k.a. interaction), so the user account is not yet created.

> If a user do the following: Sign up by input phone no. => Verify SMS and click to send SMS (0) => Enter code (1) => Wrong, Enter Code (2) => Wrong, Enter Code (3); For user at step 3, if he can back, would it go back to step 2, or 0?

It goes back to 2, since the entering code is implemented as a HTML form submission. Unless some JS trick (e.g. `history.replaceState`) is used, I don't think it can be improved to go back to step 0.

**Comment by keithtkl** [comment]
created https://github.com/authgear/authgear-server/issues/143 to follow up on point 2
