### ISSUE TITLE
Add a link to GraphiQL in the Portal Admin API page

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1428]
In the Admin API page in the Portal,
the description below the page title writes:

> Use the admin keys to manage your project with the Admin API. [Learn more](link to doc)
> You can build queries in the [GraphiQL playground](link to GraphiQL).

Can we make the schema panel in GraphiQL default to be open?

**Comment by louischan-oursky** [comment]
> Can we make the schema panel in GraphiQL default to be open?

It seems impossible :(

**Comment by fungc-io** [comment]
> > Can we make the schema panel in GraphiQL default to be open?
> 
> It seems impossible :(

Sad, let's leave a sentence mentioning the panel in the doc then.

**Comment by fungc-io** [comment]
@louischan-oursky 
Reading the hint makes me realize the term "Playground" does give an impression of sandbox environment. Perhaps we should avoid this term.

Let's change it to
> You can build queries in the [GraphiQL tool](link to GraphiQL).
