### ISSUE TITLE
Link between Portal and Account settings for Authgear users

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1434]
- Users should be able to access the account settings page from the Portal to change their own Authgear account auth such as passwords, set up MFA, etc.
- If users accidentally went into the setting page instead of the Portal, they will be stuck unless changing the URL manually. There should be a link from the setting page to go back to the Portal.

**Comment by louischan-oursky** [comment]
We have a "Back to App" button in the auth UI. It requires us to set an existing config to make that visible. So the 2nd point should be done very easily.

**Comment by fungc-io** [comment]
@karinyu Can you help design the setting page button in the PortaI?

**Comment by fungc-io** [comment]
Design: https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=4370%3A53998

**Comment by louischan-oursky** [comment]
Fixed.
