### ISSUE TITLE
[Design] [Portal] Better email template and "Form", "Reply-to", "Subject" customization

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1436]
Update 7th Feb: Still missing From/Reply-To

Ref: #1318 
Design for:
Allow customization for the following:
- Forgot Password Email
- Passwordless Signup
- Passwordless Login
- Email Verification

For the following parameters:
- From
- Reply-To
- Subject
- Content

**Comment by fungc-io** [comment]
Design: https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=4512%3A24804

**Comment by chpapa** [comment]
Duplicated #1318, copied:

> If SMTP server is not customize (pending https://github.com/authgear/authgear-server/issues/919), and using our built-in Postmark sender, it is expected that we need users to verify their sender domain via https://postmarkapp.com/developer/api/domains-api first (need UI/UX Design)
