### ISSUE TITLE
[Portal] Cannot remove all SSO once added at least one

### ISSUE THREAD

**Issue by samchan0221** [authgear/authgear-server#1442]
When I am solving #1061, I enabled some oAuth identities to the project. After I fix it, I found that I cannot disable them. I can disable any one of them but not all of them.

- Authgear Server Date/Version: bugs found at 3445fc982, should be before it
- Application Platform: Web, development environment
- Screenshots
![image](https://user-images.githubusercontent.com/36394128/128658169-ded3e060-30b8-451b-a207-7137f558bf20.png)

#### Expected Results
The changes should be able to saved

#### Actual Results
Unsavable

#### Steps to reproduce
1. Open a fresh new authgear project
2. go to /configuration/single-sign-on on the portal
3. add one or more SSO settings (it can be fake clientID as we are not testing the validity of the app)
4. save it
5. disable them all
6. save and fail

**Comment by louischan-oursky** [comment]
Fixed in https://github.com/authgear/authgear-server/pull/1399 https://github.com/authgear/authgear-server/pull/1405 https://github.com/authgear/authgear-server/pull/1413
