### ISSUE TITLE
Minimal Cloud Deployment

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#146]
Plan for a minimal cloud deployment that supports:
* multi-tenant
* update config / connect admin API from Web Portal 
* single user account for each tenant (Because Authgear doesn't support realm yet, and multiple users for each tenant require realm support)

Doesn't need to:
* Use Kubernetes
* Consider scalability
* Sign up / create a new tenant could be done manually

**Comment by kiootic** [comment]
- Authgear multi-tenant mode
    - load multiple config & secret files per-tenant from file-system
    - watch fs and auto-reload
- Cloud deployment
    - store config & secret in k8s ConfigMap & Secret
    - enforce JWT auth for admin API
- Portal backend
    - update k8s ConfigMap & Secret -> auto-sync to server through k8s?
        - update delay up to ~3 mins
    - side-car pod to sync config explicitly?
    - authentication through authgear OAuth (specify authgear endpoint through env var)
    - tailer-made authorization
    - sign authorized requests with JWT to admin API

**Comment by chpapa** [comment]
Thanks for the planning..

> update delay up to ~3 mins

Have we decided how to shorten the deployment delay? Or it can't be solved easily?

**Comment by kiootic** [comment]
> Have we decided how to shorten the deployment delay? Or it can't be solved easily?

We can have a sidecar container to watch k8s and sync to file-system. This should have nearly instantaneous delay.
