### ISSUE TITLE
Emphasize the GraphiQL tool is for inspection purpose 

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1460]
On **Portal**>**Admin API** page, explain to users:
- the GraphiQL tool is using their Portal login session
- On their backend server, they should use the Admin Key JWT and the admin endpoint `/_api/admin/graphql`

**Comment by fungc-io** [comment]
@louischan-oursky @carmenlau 
What do u think about this?

> # Admin API
> 
> The Admin API allows your server to manage your project and users via a GraphQL endpoint.
> 
> ## API Endpoint
> 
> `https://{TENENT_ENDPOINT}/_api/admin/graphql` [Copy button]
> 
> Accessing the Admin API GraphQL endpoint requires your server to generate a valid JWT and include it as `Authorization` HTTP header. Read [the doc](https://docs.authgear.com/apis/admin-apis) for more details.
> 
> 
> ## GraphiQL Explorer
> 
> Inspect the GraphQL schema and build queries with [GraphiQL](link to the tool). 
> On your server you should always use the Admin API endpoint and the API Keys.
> ! Please beware this is **NOT** a sandbox environment, changes are made to **REAL DATA**.  
> 
> ## List of Admin API Keys
> ...
