### ISSUE TITLE
Handle logout when session type is `device`

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#1467]
Assume there are multiple apps in the same project, when user logout in the mobile app which has sessionType = device, user may expect:
1. Logout should only logout the current app, the other apps should remain logged in. (Current behavior)
2. Logout should logout all the apps, like `Remove from this device` in the Google app.
3. ... Any other expected behaviors?

In the proposed solution in  #1391,
> Open webview to logout and then revoke refresh token

It only logout the current app and logout the idp session, the other apps remain logged in. Is that the behavior we want?

We had some discussion about the possible implementation if we want to do point 2(logout should logout all the apps):

1. Introduce session tag, all sessions (idp session and refresh token) in the same device should have the same tag. We will have a new api / new parameter in the current revocation endpoint, that will remove all sessions with the same tag.
1. How to have the same session tag in the same device?
    - In iOS, user need to setup [app group](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_application-groups). SDK will initialize a random session tag in the [user default](https://developer.apple.com/documentation/foundation/userdefaults/1409957-init), this tag will only be initialized once only and share among the apps. SDK will need to include the tag during the authorization process and tag the sessions.
    - In Android, need further study

Some further problems
1. If the user logged in the different users in the different apps, should we logout them?

**Comment by chpapa** [comment]
I think it should be:

1. remove all apps logged out when I click “remove me from this device”
2. By “all apps” it should meant all refresh tokens generated from the current IdPSession, so it should not affect if there are other users in the same devices logged in.

Implementation-wise, I don’t understand why we need a session tag? I think it should be an internal implementation that does not requires any change on API or client SDK. Whenever we generate a new refresh token, we also store which IdPSession this token was generated from in DB or null if it is not linked with one. That should works already?

**Comment by louischan-oursky** [comment]
This issue is obselete.
