### ISSUE TITLE
Email verification code can't be verified with copy and paste 

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#1474]
Step to reproduce:

1. Use Email as Login ID
2. Use Passwordless via Email as Authenticator
3. Try to sign up / login
4. At the OTP verification page, copy/paste the email's verification code to the field
5. It shows "Invalid Credentials" (which is a bad error message btw)

Alternatively, if type in the numbers manually, it is okay.

**Comment by carmenlau** [comment]
@chpapa We suspected that there may be extra space during copy and paste, but I just tried and I cannot reproduce the problem that you mentioned in both mobile and desktop. Could you help to try again and see what have you copied?

Desktop:

<img width="697" alt="Screenshot 2021-08-25 at 2 44 54 PM" src="https://user-images.githubusercontent.com/388892/130728678-a6586101-7d79-4aa2-8b38-003b502800b8.png">
 

Mobile:

![IMG_1323](https://user-images.githubusercontent.com/388892/130728662-87892698-a244-4ee9-993e-3745c28571df.PNG)

**Comment by fungc-io** [comment]
TODO: improve error message to tell the end-user that the code should consist of digits only.

**Comment by chpapa** [comment]
Oh I just encounter it again, I found that there are space at the beginning of the OTP code!

**Comment by louischan-oursky** [comment]
The email client Superhuman is used in this case. Not sure if it is related.

**Comment by louischan-oursky** [comment]
I opened the HTML email with Safari (macos and iOS), Chrome (macos) and Gmail web client. There is no space at the beginning of the OTP code. Is it a Superhuman specific problem?

**Comment by chpapa** [comment]
Can't reproduce

**Comment by chpapa** [comment]
I just encountered it again, and I'm pretty sure it is becoz of the empty space before the OTP code, maybe add a logic to trim space?

**Comment by fungc-io** [comment]
trim spaces in otp and recovery codes before verification
