### ISSUE TITLE
Re-organize sessions configuration screen

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1476]

**Comment by fungc-io** [comment]
Proposed changes:

1.
> # Applications > Edit Application
>> Client ID: [disabled input]
>> Name\*: [input]
>> Authorized Redirect URIs\*: [input(s)]
> 
>> ## Token Settings
>> For use with **token-based** authentication, usually native mobile or single-page apps
>> Access Token Lifetime (in seconds): [input]
>> Refresh Token Lifetime (in seconds): [input]
>> Invalidate refresh token after idling: [checkbox]
>> Refresh Token Idle Timeout (in seconds): [input]
>> Issue JWT as access token [checkbox]
>
>> ## Cookie-based authentication
>> For use with **cookie-based** authentication, usually websites
>> Post Logout Redirect URIs: [input(s)]
>> Change cookie session lifetime and timeout in the \[Cookie Session Settings\](/configuration/apps#cookie)

The application edit page is separated into 3 panes. Grouping configs that are specific to different authorization methods, and add a description to suggest the use-cases for each, also provide a link to change the cookie session lifetime.
Additionally, change "Redirect URIs" to "Authorized Redirect URIs". I think the config here is a whitelist of redirect URIs that the user can specify when using the SDK? Changing this to be more specific.

2.
> # Applications
>> ## Applications
>> (application list)
>
>> ## Allowed Origins
>> (allowed origin list)
>
>> ## Cookie Session Settings
>> Configure the session settings of the Authgear cookie stored for `{tenant_endpoint | custom_domain}`
>> Persistent Cookie [toggle]
>> Session Lifetime (in seconds): [input]
>> Invalidate session after idling [toggle]
>> Idle Timeout (in seconds): [input]

Move the session settings from "Advanced" to inside "Applications". Change the pane title and description to be more specific.

@louischan-oursky @carmenlau , see what do you think?

**Comment by fungc-io** [comment]
Is the "cookie session" relevant if the users use token-based authentication only? If it's irrelevant, we can tell that in the description of "Cookie Session Settings" too.

**Comment by louischan-oursky** [comment]
> Is the "cookie session" relevant if the users use token-based authentication only?

Cookie session is irrelevant if the users use token-based authentication only. I am going to add the description

> If you only use token-based authentication, you can simply ignore this section.

**Comment by fungc-io** [comment]
looking good :+1:
