### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#149]
* Admin API
* Setting page to display
* Portal to show
* Database design
* Log events (not meant to be a good list):
    * Sign up / Login
    * Session revoke
    * Session activities? (What it meant?)
    * Disable
    * Change password
    * Add/Change/Delete of Authenticators

**Comment by mr9dollars** [comment]
Refined HKL requirement:

The requirement from HKL: A list with the following columns
- userid/username/email
- activity type (login/logout)
- timestamp
- filter by activity type (design required)
- filter by from-to timestamp (design required)

**Comment by chpapa** [comment]
Would recommend to keep the logs in ElasticSearch / PostgreSQL to avoid complicating our deployment requirements.

It could be on another connections / instances, so we can handle scalability of logs (which have a very different requirements to our "app postgresql") better.

Did some quick search on PostgreSQL, there is a timescaleDB extensions, but we may also consider using special index type that perform reasonably well without the trouble of handling extensions (as our logs are users generated and not machine generated)

**Comment by louischan-oursky** [comment]
## TimescaleDB

TimescaleDB is a time series database based on PostgreSQL.
It is available as managed service of self-hosted.
Self-hosting it seems too complicated.
So it is not preferred.

## PostgreSQL 10 native partitioning

Native partitioning is supported from PostgreSQL 10 onwards.

## A blogpost on storing time series data on PostgreSQL

https://aws.amazon.com/blogs/database/designing-high-performance-time-series-data-tables-on-amazon-rds-for-postgresql/

## pg_partman

An extension to manage partition.

[The supported version on Google Cloud SQL is 4.4.0](https://cloud.google.com/sql/docs/postgres/extensions#pg_partman)

[AWS RDS PostgreSQL 12.5 onwards supports pg_partman](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_Partitions.html#PostgreSQL_Partitions.pg_partman) so the supported version of pg_partman is at least 4.2.0

[The supported version on Azure Database is 4.0.0](https://docs.microsoft.com/en-us/azure/postgresql/concepts-extensions). [Azure Database does not support PostgreSQL 12 yet](https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions)

[PostgreSQL has name length limit of 63.](https://github.com/pgpartman/pg_partman/blob/master/doc/pg_partman.md#naming-length-limits) So the name fo the partitioned table must be short.

### Install pg_partman

```sql
CREATE EXTENSION IF NOT EXISTS pg_partman SCHEMA partman_test;
```

### Create the parent table and the template table

```sql
CREATE TABLE partman_test.time_taptest_table 
    (col1 int, 
    col2 text default 'stuff', 
    col3 timestamptz NOT NULL DEFAULT now()) 
PARTITION BY RANGE (col3);
CREATE INDEX ON partman_test.time_taptest_table using BRIN (col3);

CREATE TABLE partman_test.time_taptest_table_template (LIKE partman_test.time_taptest_table);
ALTER TABLE partman_test.time_taptest_table_template ADD PRIMARY KEY (col1);
```

### Setup partition on the parent table

```sql
SELECT partman_test.create_parent(
	'partman_test.time_taptest_table',
	'col3',
	'native',
	'daily',
	p_template_table := 'partman_test.time_taptest_table_template'
);
UPDATE partman_test.part_config
SET retention = '1 year', retention_keep_table = FALSE
WHERE parent_table = 'partman_test.time_taptest_table';
```

### Run maintenance periodically

```sql
CALL partman_test.partition_data_proc('partman_test.time_taptest_table');
CALL partman_test.run_maintenance_proc();
```
