### ISSUE TITLE
Re-organize packages

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#154]
@louischan-oursky please review this re-organization plan and let me know what you think.

- `pkg`
    - `pkg/auth`: Authgear API server logic
        - `pkg/auth/handlers`: HTTP handlers
        - `pkg/auth/webapp`: WebApp service
        - `pkg/auth/routes.go`: Route definitions
        - `pkg/auth/endpoints.go`: Endpoint provider
        - `pkg/auth/wire_*.go`: API server DI config
    - `pkg/admin`: Admin API server logic (content TBD)
    - `pkg/resolver`: Session resolver API server logic
    - `pkg/worker`: Background task worker logic
        - `pkg/worker/tasks`: Task logic
        - `pkg/worker/worker.go`: Worker entry point
        - `pkg/worker/wire_*.go`: Task worker DI config
    - `pkg/lib`: Authgear domain logic & data persistence
        - `pkg/lib/config`: Configurations
        - `pkg/lib/authn`: Core authentication
            - `pkg/lib/authn/interaction`
            - `pkg/lib/authn/authenticator`
            - `pkg/lib/authn/identity`
            - `pkg/lib/authn/challenge`
            - `pkg/lib/authn/sso`
            - `pkg/lib/authn/user`
        - `pkg/lib/oauth`: OAuth
            - `pkg/lib/oauth/oidc`
        - `pkg/lib/session`: Session
        - `pkg/lib/hook`: Web-hook
        - `pkg/lib/api`: API definitions
            - `pkg/lib/api/models`
            - `pkg/lib/api/events`
            - `pkg/lib/api/errors`
        - `pkg/lib/features`: Additional Features
            - `pkg/lib/features/forgotpassword`
            - `pkg/lib/features/verification`
            - `pkg/lib/features/welcomemessage`
        - `pkg/lib/infra`: Supporting infrastructure
            - `pkg/lib/infra/db`
            - `pkg/lib/infra/redis`
            - `pkg/lib/infra/template`
            - `pkg/lib/infra/sms`
            - `pkg/lib/infra/mail`
            - `pkg/lib/infra/middleware`
    - `pkg/util`: Utilities (not specific to Authgear, not depending on config)
        - `pkg/util/log`
        - `pkg/util/httputil`
        - `pkg/util/jwkutil`
        - `pkg/util/image`
        - `pkg/util/httproute`
        - `pkg/util/clock`

**Comment by louischan-oursky** [comment]
My preference is to rename from `pkg/core` to `pkg/lib`; rename from `pkg/utils` to `pkg/x`

**Comment by kiootic** [comment]
Is `x` a convention of Go? @@

**Comment by louischan-oursky** [comment]
Maybe, for example https://godoc.org/golang.org/x/text

**Comment by kiootic** [comment]
I think `golang.org/x` is for out-of-tree packages of Go project?
Other projects uses `util` as package name for utilities, e.g. https://godoc.org/k8s.io/apimachinery/pkg/util, or just list flatly in `pkg`, e.g. https://godoc.org/github.com/coreos/etcd/pkg

Anyways, we can use `x` if we like it.

**Comment by louischan-oursky** [comment]
OK. Follow k8s and use the name `pkg/util` (no s) then.
