### ISSUE TITLE
[Password Policy] Duplicates are not discarded in banned words

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1543]
ux/minor

## Background:
- Device / Browser (OS version): Chrome (Mac 10.15)
- Build: staging-2021-09-21.1
- Tested on 27 Sep 2021

## Description:
Duplicates are not discarded in banned words.

Additional:
When duplicates are mixed in with duplicates containing trailing whitespace, the delete buttons will be wonky, either won't delete or clearing all. #1544

## Steps to reproduce:
1. Log in to admin portal, select an app, Go to Authentication, Password Policy
2. In Keywords to be excluded, copy paste a number of duplicated passwords 

## Expected result:
Duplicates should be discarded.

Screenshot:
![image](https://user-images.githubusercontent.com/4337525/134848769-8ebe1e0a-b624-436c-8e61-67f2ebfaabbe.png)

https://user-images.githubusercontent.com/4337525/134849389-95997add-af6e-4789-8e29-d5fa9de67e40.mov

**Comment by stanleylhs** [comment]
Maybe we can also close this as #1820 is done. Not verified tho.

**Comment by fungc-io** [comment]
fixed in #2053
