### ISSUE TITLE
[Password Policy] Trim spaces for keywords to be excluded to avoid duplicated words

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1544]
ui/minor

## Background:
- Device / Browser (OS version): Chrome (Mac 10.15)
- Build: staging-2021-09-21.1
- Tested on 27 Sep 2021

## Description:
In banned words, Leading and trailing white spaces aren't displayed. e.g. 
```
 1234
1234 
```

Users can't distinguish between them the differences

## Steps to reproduce:
1. Log in to admin portal, select an app, Go to Authentication, Password Policy
2. In Keywords to be excluded, input passwords with leading and trailing white spaces
```
 1234
1234 
```
3. See two `1234` with no spaces instead.

## Expected result:
White spaces should be displayed with `&nbsp;` instead of  ` `

Screenshot:
![image](https://user-images.githubusercontent.com/4337525/134858306-7e9415db-202d-4c4b-9af3-3f81bc53561a.png)

**Comment by joyzoursky** [comment]
Seems this issue is valid but too trivial for actual use case (admin can avoid typing same words themselves), we could close this first.
