### ISSUE TITLE
[Password Policy] No error message for new password is shown when force changing password on next login

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1545]
ux/minor

## Background:
- Device / Browser (OS version): Chrome (Mac 10.15)
- Build: staging-2021-09-21.1
- Tested on 27 Sep 2021

## Description:
When user's current password failed new policy, user is asked to change password on next login. However, if user's new password failed the new policy again, no error message is shown and the page simply refresh.

## Steps to reproduce:
1. Log in to admin portal, select an app, Go to Authentication, Password Policy
2. Enable Force Password change on next login and enable some rules to make the current user password fail the policy
3. Login with user, see the password failed new policy and need to changed password
4. Change to a new password which will fail the new policy, e.g. Reuse old password, password too short, etc.
5. See page refreshed with no error prompt

## Expected result:
Should highlight the policy failure like the normal change password ui.

Screenshot: 

https://user-images.githubusercontent.com/4337525/134865354-730257ba-7e47-48e9-81bd-22039eba0c14.mov

Normal change password ui:
![image](https://user-images.githubusercontent.com/4337525/134872598-79804a03-0503-4e0f-89a9-33e4787a377b.png)

**Comment by louischan-oursky** [comment]
I cannot reproduce this :( Any clues?

**Comment by fungc-io** [comment]
@stanleylhs 
I cant reproduce this issue neither, do you remember the sequence of passwords you used to give this result?

**Comment by stanleylhs** [comment]
I can't reproduce it now too. I think this is actually from #1547.
Closed for now, thank you for the attention and effort.
