### ISSUE TITLE
[Password Policy] Account stuck with force password change on new login even after new password meets policy

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1547]
bug/major

## Background:
- Device / Browser (OS version): Chrome (Mac 10.15)
- Build: staging-2021-09-21.1
- Tested on 27 Sep 2021
- demo-enterprise

## Description:
When user's current password failed new policy, user is asked to change password on next login. However, if user's new password failed the new policy again, no error message is shown and the page simply refresh.

## Steps to reproduce:
1. Log in to admin portal, select an app, Go to Authentication, Password Policy
2. Enable Force Password change on next login and enable some rules to make the current user password fail the policy
3. Login with user, see the password failed new policy and need to changed password
4. Change to a new password which meets the new policy
5. Logout, Login
6. See prompt to force change password again.

## Expected result:
Should not stuck with force password change on new login

Screenshot: 
![image](https://user-images.githubusercontent.com/4337525/134898127-7ab62d87-b984-43be-9266-beb166e3644a.png)

https://user-images.githubusercontent.com/4337525/134895284-44db31bb-b10a-4138-8e4a-45fe85574202.mov

**Comment by louischan-oursky** [comment]
Any specific rule changes that can trigger this bug? In a simple test, the password policy is originally minimum 9 characters. The testing account has a password of length 8. I changed the policy to minimum 9 characters. This scenario did not trigger this bug.
