### ISSUE TITLE
[Password Policy] User can click Back to go to expired force change password page

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1548]
bug/minor

## Background:
- Device / Browser (OS version): Chrome (Mac 10.15)
- Build: staging-2021-09-21.1
- Tested on 27 Sep 2021

## Description:
When user's current password failed new policy, user is asked to change password on next login. However, after user has changed to a new password, user can click Back on browser to go to expired force change password page.

The expired force change password page won't allow any new password change.

## Steps to reproduce:
1. Log in to admin portal, select an app, Go to Authentication, Password Policy
2. Enable Force Password change on next login and enable some rules to make the current user password fail the policy
3. Login with user, see the password failed new policy and need to changed password
4. Change to a new password which meets the new policy
5. Click Back on browser
6. See the expired force change password page again

## Expected result:
Should fully expire the used force change password page when user clicks Back, don't show any password input boxes.

Screenshot: 

https://user-images.githubusercontent.com/4337525/134901656-7aef652c-b754-4553-a8a8-91f749afce3f.mov

**Comment by fungc-io** [comment]
Can we omit the "maybe you have... switched your browser" part in this case. Coz it does not explain this situation.
![Screenshot 2021-09-30 at 2 06 32 PM](https://user-images.githubusercontent.com/15207470/135396679-42669650-3207-4094-b634-c28382bb5745.png)

**Comment by louischan-oursky** [comment]
That's a bit tricky. It is quite hard detect this situation.

The `.. switched your browser` was there to handle the situation that the user could have switched their browser. That could happen back in the time we still included a verification link in the verification email. We no longer do so, and only the verification code is included. Under normal condition the user will not switch their browser. I suggest we remove `... switched your browser` in ALL cases. Thoughts?

**Comment by fungc-io** [comment]
I see, yea i think we can just remove it in all cases.
so it will become

> This page is invalid or has expired.
> 
> Please return and retry your request.
> [Return]

(improved the first sentence too)
