### ISSUE TITLE
Automatically switch to login or sign up page if not specified

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#1557]
Handy new feature:

1. Add an options (TBD) at UI Settings: Toggle - Redirect to signup or login depends if users browser have logged in before or not
2. If 1 is enabled, when redirect to [tenant].authgearapps.com, it will redirect to `/login` or `/signup` depends if a cookies was set, the cookie would be set only if the user have logged in before

Default on

**Comment by louischan-oursky** [comment]
We have this already, though it is not configurable.
