### ISSUE TITLE
[Demo app] Show code like option for Token Storage

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1569]
## Background:
- Device / Browser (OS version): iPhone X (13.1.2), Xperia XZ2 Premium (10)
- Build: Android native Version 1.0 (1631087294) / Android RN Version 1.0 (1) 13 Sep / iOS Native Version 1.0 (1630900093) / iOS RN Version 1.0 (1) 13 Sep
- Reported by: Candy

## Description:
Code like options "TransientTokenStorage" and "PersistentTokenStorage" are shown in native demo app. In RN demo app, a switch option "Use TransientTokenStorage" is shown

## Steps to reproduce:
1. Open demo app
2. See code like option names

## Expected result:
Should show readable option names

## Screenshot:
iOS Native demo app:

![image](https://user-images.githubusercontent.com/69806274/136514868-2380dd72-917d-4fcc-a715-589d60eec8a1.png)

Android Native demo app:

<img width="459" alt="Screenshot 2021-10-08 at 3 22 20 PM" src="https://user-images.githubusercontent.com/69806274/136514957-1b51903a-5f85-47e8-9160-6598bdff08d6.png">

iOS RN demo app:
![image](https://user-images.githubusercontent.com/69806274/136514983-032082f5-0d8e-4941-b26f-e3d2d568654e.png)

**Comment by stanleylhs** [comment]
Issue validation check: Reproducible

## Description: 
Text is the same

## Background:
Device / Browser (OS version): Pixel 6 Android 13, iPhone 11 Pro iOS 16.1
Build: Android Version 1.0 (1688364276), iOS Version 1.0 (1687329002)
Retested on: 10 July 2023

**Comment by joyzoursky** [comment]
expected on demo app (for internal use)
