### ISSUE TITLE
[Native demo app, Android] No error message shown when user attempt to proceed with empty fields

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#1570]
## Background:
- Device / Browser (OS version): Xperia XZ2 Premium (10)
- Build: Android native demo app Version 1.0 (1631087294)
- Reported by: Candy

## Description:
No error message shown when user attempt to proceed with empty fields, No problem for Android RN demo app, iOS native and RN demo apps

## Steps to reproduce:
1. Open Android Native demo app
2. Click Configure without filling in any fields
3. See app load for a short moment without error message

## Expected result:
should show error message asking user to fill in fields

## Screenshot:

https://user-images.githubusercontent.com/69806274/136515239-037d16d8-1564-4743-809a-1933fc1c4fa9.mp4

**Comment by stanleylhs** [comment]
Issue validation check: Reproducible

## Description: 
Still no error when empty

## Background:
Device / Browser (OS version): Pixel 6 Android 13, iPhone 11 Pro iOS 16.1
Build: Android Version 1.0 (1688364276), iOS Version 1.0 (1687329002)
Retested on: 10 July 2023

**Comment by joyzoursky** [comment]
no need to fix for internal demo app, close first
