### ISSUE TITLE
[UI Settings] Network problem message is shown when upload oversized image

### ISSUE THREAD

**Issue by harry5858** [authgear/authgear-server#1574]
Device: Chrome on Mac
Build: staging
Description:
Network problem message is shown when upload oversized image, UX minor

Steps:
1. Login
2. Click into one of the projects
3. Go to UI Settings
4. Upload an oversized image for favicon
5. Click Save
6. See error message 'There is a problem with the network'

Expected behaviour:
Should show error message regarding the oversized file uploaded.

Screenshot:

https://user-images.githubusercontent.com/82640760/136763126-5d9e1310-02b7-458d-8c3d-d1d487b0440a.mov

**Comment by fungc-io** [comment]
fixed
