### ISSUE TITLE
[User management] Unable to clear search input field by clicking the cross on the search bar

### ISSUE THREAD

**Issue by harry5858** [authgear/authgear-server#1577]
Device: Chrome on Mac
Build: staging
Description:
Unable to clear search input field by clicking the cross on the search bar, bug minor

Steps:
1. Login
2. Click into one of the projects
3. Go to user management
4. Search for a user by typing in a keyword
5. Click the cross at the search bar
6. See field is not cleared

Expected behaviour:
Should cleared the search input field when the cross is clicked

Screenshot:

https://user-images.githubusercontent.com/82640760/136765008-66f191cb-abf7-494e-910b-58c8225aaf86.mov

**Comment by stanleylhs** [comment]
the search input field cleared successfully.
