### ISSUE TITLE
[UI Settings] Unknown error is shown when an invalid file is uploaded

### ISSUE THREAD

**Issue by harry5858** [authgear/authgear-server#1578]
Device: Chrome on Mac
Build: staging
Description:
Unknown error is shown when an invalid file is uploaded, UX minor

Steps:
1. Login
2. Click into one of the projects
3. Go to UI Settings
4. Upload a jfif image for app logo
5. Click Save
6. See unknown error ....

Expected behaviour:
Should show error message of invalid file type

Screenshot:

https://user-images.githubusercontent.com/82640760/136765749-5313c34a-9ace-4b73-a875-e1b002780d8d.mov

**Comment by fungc-io** [comment]
Show "Title" and "Message" in the Portal error message too
