### ISSUE TITLE
[Custom email provider] Able to save with empty api key when SendGrid is selected

### ISSUE THREAD

**Issue by harry5858** [authgear/authgear-server#1579]
Device: Chrome on Mac
Build: staging
Description:
Able to save with empty api key when SendGrid is selected, bug major

Steps:
1. Login
2. Click into one of the projects
3. Go to custom email provider
4. Toggle use my own provider on
5. Click SendGrid
6. Click Save
7. See able to save with api key empty

Expected behaviour:
Should not be able to save with empty mandatory field.

Screenshot:

https://user-images.githubusercontent.com/82640760/136769114-64f0727b-96f8-40c0-8403-ed3e1914d88a.mov

**Comment by stanleylhs** [comment]
Cannot reproduce. Button disabled if field is empty.
