### ISSUE TITLE
[Custom email provider] Unknown error message is shown when send test mail with mandatory fields are empty

### ISSUE THREAD

**Issue by harry5858** [authgear/authgear-server#1580]
Device: Chrome on Mac
Build: staging
Description:
Unknown error message is shown when send test mail with mandatory fields are empty, bug/ minor

Steps:
1. Login
2. Click into one of the projects
3. Go to custom email provider
4. toggle use my own provider on
5. Click send test email
6. Click send
7. See unknown error message

Expected behaviour:
Should not be able to send test mail when mandatory fields are empty

Screenshot:

https://user-images.githubusercontent.com/82640760/136769855-f6d5b390-171b-48ee-a2b3-d104d356304a.mov

**Comment by stanleylhs** [comment]
Cannot reproduce. Button disabled if fields are empty.
