### ISSUE TITLE
[User management] Unable to search user by partial user id

### ISSUE THREAD

**Issue by harry5858** [authgear/authgear-server#1581]
Device: Chrome on Mac
Build: staging
Description:
Unable to search user by partial user id, UX minor

Steps:
1. Login
2. Click into one of the projects
3. Click user management
4. Search a user by inputting part of the user id
5. See unable to search the corresponding user

Expected behaviour:
Should be able to search the corresponding user

Screenshot:

https://user-images.githubusercontent.com/82640760/136773023-925e451b-df46-4e0c-b985-9b1f44aa4878.mov

**Comment by fungc-io** [comment]
Not a common use case, won't fix
