### ISSUE TITLE
[Authentication] Empty error message is shown if a decimal number is used for the field Verification code valid duration

### ISSUE THREAD

**Issue by harry5858** [authgear/authgear-server#1583]
Device: Chrome on Mac
Build: staging
Description:
Empty error message is shown if a decimal number is used for the field Verification code valid duration, bug minor

Steps:
1. Login
2. Click into one of the projects
3. Go to authentication > verifications
4. Input a decimal number (e.g. 3600.5) for Verification code valid duration
5. Click Save
6. See empty error message

Expected behaviour:
Should not show empty error message

Screenshot:

![Screenshot 2021-10-11 at 6 25 18 PM](https://user-images.githubusercontent.com/82640760/136775641-ceb10782-7e29-48a8-84eb-43a2676d7e27.png)

**Comment by stanleylhs** [comment]
Can't reproduce as decimal point is not allowed anymore.
