### ISSUE TITLE
Do not show outline for focused element

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1598]
We have done this for `input` and `a`. Let's extend that to other focusable elements like `select` and `textarea`.
All form elements should not have `outline` properties when focused

**Comment by stanleylhs** [comment]
Outline for Webhook signature can still be shown, press `Tab` on keyboard from Per-handler timeout (seconds)

![image](https://user-images.githubusercontent.com/4337525/140723273-4ef9a6a2-8941-4647-95b8-3700a72bdded.png)

**Comment by louischan-oursky** [comment]
Oh, this issue is about the Auth UI, not the portal.

**Comment by stanleylhs** [comment]
Oops sorry 🙇
