### ISSUE TITLE
Retain form values in case of error

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1599]
UX Issue: In End-user signup/login pages, the input values are cleared in the case of error. This makes it not user-friendly for them to modify the input and try again.
Fix: Retain form values in case of error

**Comment by stanleylhs** [comment]
I tried most signup/login combo, all input values are not cleared not. 👍

I would suggest to keep clearing password though, as it is difficult to know where the error is as it's hidden.
