### ISSUE TITLE
Demo apps to be supported on iOS15

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1631]
They are currently not working on iOS 15
it shows 
> "Authgear demo iOS" Needs to Be Updated
> The developer of this app needs to update it to work with this version of iOS.

**Comment by stanleylhs** [comment]
![IMG_E6DED90426CC-1](https://user-images.githubusercontent.com/4337525/141722202-a2643d3b-b3cf-4c3d-9a85-7cc80d8f4706.jpeg)

**Comment by louischan-oursky** [comment]
I have configured to use Xcode 13.1 to build the apps. The latest build of the apps should be installable on devices with iOS 15.
