### ISSUE TITLE
[User Management] No Title Casing for Gender

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1632]
ui/trivial

### Environment
Device: Chrome on Mac
Build: staging

### Description
No Title Casing for Gender, `female` and `male` both in small letter case

### Steps:

1. Login
2. Click into one of the projects
3. Go to User Management, click a user
4. Click on the Gender pulldown select
5. See  `female` and `male` 

### Expected behaviour:
Should use Title Casing `Female` and `Male` 

### Screenshot:
![image](https://user-images.githubusercontent.com/4337525/141722440-a8ae266b-20ca-4f7c-acd6-5e28825beb65.png)

**Comment by fungc-io** [comment]
Thanks for reporting, 
This is intentional in the Portal because the internal value is shown here.
They will be title-case and localized according to locale when shown in the AuthUI end-user settings
