### ISSUE TITLE
[User Portal, User details] Language edit pull down selections only shows en and zh-HK  

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1643]
bug/major

### Environment
Device: Chrome on Mac
Build: staging

### Description
Language edit pull down selections only shows en and zh-HK.

When other language is selected from admin portal, user portal edit page will show it as `Unset`

### Steps:

1. Login to app user portal
2. Click My Profile, More, Language edit icon
4. See pull down selections only shows en and zh-HK

### Expected behaviour:
Show all languages as in admin portal.

### Screenshot:
Dutch is currently set.
![image](https://user-images.githubusercontent.com/4337525/141763918-670a9276-7d50-4af5-af71-a0e821642842.png)

**Comment by fungc-io** [comment]
This is expected, Only the languages enabled by the admin will be shown and selectable by the end-user.
