### ISSUE TITLE
Avoid saving identical translation key

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1682]
1. By default the translation.json in the Portal should be empty
2. Add a link to the latest default translation.json for the user to lookup the most updated keys
3. Only the intended overwrites are applied and shown in the Portal.

**Comment by fungc-io** [comment]
Change the copy in the Portal > Localization > Manage Template Contents > translation.json
from `Translations for the web UI as well as app brandings like app name`
to
> You can override the translation of the text by providing the key-value pairs in the box below.
> The latest list of text can be found here: [link]
> See \[the docs\](https://docs.authgear.com/customize/localization) for more instructions
