### ISSUE TITLE
`Failed to delete admin` when delete the portal admin owner

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#1688]
Currently it is suppose that portal admins all have equal rights? So it is surprised that when we delete the tenant, it will show an error as `Failed to delete admin`

#### Expected Results
Either:
1. The owner is listed as "owner" and can't be removed, OR
2. Portal admins can delete each others including owner (the one who created the tenant)

#### Actual Results
A dialog blog "Error", with `Failed to delete admin`

#### Steps to reproduce

1. Create a new tenant as user `A`
2. Invite another user `B`
3. Login as user `B` and Remove `A` from Portal Admins

**Comment by fungc-io** [comment]
**Quickfix**
shown the owner as 
`email@example.com (Owner)` and disable the "Remove" action button
