### ISSUE TITLE
Better support for Password Manager

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#1689]
On some website such as Zapier.com, which requires users to enter `email` and then `password` in two pages, they can support password manager auto complete (such as with 1Password), by automatically jumping to the password page and pre-filled.

The experience is far better than our current one (where the users need to click twice to fill email / phone and password)

**Comment by louischan-oursky** [comment]
The 1Password extension itself never auto submit the form.

Zapier.com is a SPA. By observation, it seems that it hides the password field visually. When the user triggers the auto fill, the password manager auto fills the username field AND the password field. The javascript of Zapier.com detects that the hidden password field was filled, so most likely it was done by the password manager. So it transitioned to the next UI state, which is the filled password field, waiting for the user to click "Sign in".

Auth UI is a traditional website so even we can add javascript to auto submit form when the password manager auto fills the username, we still cannot ask the password manager to auto fill the password field on the next page.

**Comment by chpapa** [comment]
@fungc-io when we work on the new AuthUI templates, make sure our implementation take care of this :)

**Comment by rickmak** [comment]
Seem not fixable and @fungc-io already have another tracking issue for tracking. May be closing it.
