### ISSUE TITLE
Mark login ID identity as verified if corresponding OAuth identity exists

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#172]

**Comment by chpapa** [comment]
Actually if it is not too much work, would be great to add an option for of which oauth identity would automatically verify the user

Eg it may make a lot of sense to assume google login meant the email address is verified, but for some other less creditable provider in future the assumption may not valid

But if it is complicated maybe open in another feature issue

**Comment by kiootic** [comment]
To make it configurable, we'll also need to consider whether OAuth identity is verifiable. Currently OAuth identity is verifiable and is always treated as verified, so a user with just a OAuth identity is a verified user. If the imagined option is turned off:
- Can the user verify an OAuth identity?
- If there are OAuth identity & login ID identity with same email, would verifying one of them makes all of them verified?
- If user unlinked an OAuth identity, would the login ID identity with same email become unverified?

I think we need further discussion on the intended behavior before adding the option.
