### ISSUE TITLE
Consistent styling at Anonymous Users

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#1743]
![anonymous](https://user-images.githubusercontent.com/387241/149888474-85f9c8d1-6370-4faf-9814-4c407d6cf154.jpg)

For the screen cap above:

1. Better if we can align "Idle Timeout", "Session Lifetime" and "Persistent Cookie:" value vertically, it should be more readable.
2. Session Lifetime help text says "User will be logged out after lifetime" is unclear to me. What about for idle timeout and session lifetime, the help text could be:
    1. `Users will be logged out after Idle Timeout`
    2. `Users will be logged out after Session Lifetime regardless of their activity"
 3. This page have a new style / design language -- you can mouse hover the underline text and see the help text. However in other part of the page, we use a small blue "info" icon (as follows), better if we make it consistent?
![info](https://user-images.githubusercontent.com/387241/149889655-04c4e02a-4310-47a6-b04c-7f76816bcbc4.jpg)

**Comment by fungc-io** [comment]
@chpapa 
A quick mockup I ve just made.
How about arrange the list and show indicate the help text like this?
<img width="753" alt="Anonymous User" src="https://user-images.githubusercontent.com/15207470/149893419-2c3d43b3-8992-494f-bd4d-ea8ae8756a1a.png">

**Comment by chpapa** [comment]
@fungc-io ya I think sth like that :)

**Comment by fungc-io** [comment]
@carmenlau 
paddings and margins for the cookie-based list 🙏 
<img width="777" alt="Screenshot 2022-01-18 at 17 39 10" src="https://user-images.githubusercontent.com/15207470/149911059-9665a1d0-6829-4488-b14e-51ebb6975d74.png">
