### ISSUE TITLE
[AuthUI] Show "Undefined" auth-time for anonymous users

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1771]
## Background:
- Device / Browser (OS version): Chrome on Win 10
- Version Tag: 2022-02-08.0
- Reported by: Jason Chan WK

## Description:
The auth-time is undefined after signing in using anonymous accounts. The correct auth-time will only be shown after re-authenticating/refreshing the webpage.

## Steps to reproduce:
1. Configure using either refresh-token/cookie web-app
2. Sign in anonymously
3. Click show auth_time and see the undefined auth_time
4. Refresh the page and click show auth_time again, see the valid auth_time

## Expected result:
Should show the correct auth-time after authenticating (or is this feature unavailable for the anonymous users? If so, the auth-time should remains undefined after refreshing the page)

## Screenshot:

https://user-images.githubusercontent.com/4337525/153803040-9f895c70-2a6d-4c4c-b7f6-fabfffaba7b8.mov

**Comment by stanleylhs** [comment]
Issue validation check: Reproducible

## Description: 
Still the same as in video, auth time is only shown after reauth

## Background:
Device / Browser (OS version): Chrome 114.0.5735.198 on Mac 13.4.1
Build: staging 2023-07-05.0
Retested on: 10 July 2023

**Comment by joyzoursky** [comment]
Issue still exists.

Testing info:

- Server: Staging
- App: qa-authflow (Phone + Passwordless)
- Tested user agent:
  - Android React native demo app
  - iOS Native demo app
- Device: Samsung Galaxy A71 (Android 13), iPhone SE 2 (iOS 16.7)

![Screenshot_20231025_201317_reactNativeExample](https://github.com/authgear/authgear-server/assets/12539486/d6c2e4a6-c151-4ae4-a139-b494ae99c69a)
