### ISSUE TITLE
[Sign in, Anonymous] Still shows previous anonymous user id after switching from cookie to refresh-token app and signing in anonymously

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1773]
bug/minor

## Background:
- Device / Browser (OS version): Chrome Win 10
- Version Tag: 2022-02-08.0
- Reported by: Jason Chan Wing Kit 

## Description:
After switching the configuration and then signing in anonymously, the anonymous user id of the previous configuration is still shown, even though a new anonymous user record is already created in the new app. This issue is resolved only after refreshing/re-signing in.

## Steps to reproduce:
1. Configure using cookie web-app
1. Sign in anonymously
1. Switch to the refresh-token app
1. Sign out and sign in anonymously again
1. See the previous anonymous user-id is shown

## Expected result:
Should show the current anonymous user id

## Screenshot:

https://user-images.githubusercontent.com/4337525/153814708-44e5e17d-1737-4d3c-b2c3-7713b3650e86.mp4

**Comment by stanleylhs** [comment]
Issue validation check: Can't test

## Description: 
Cookies session not working, see #3197 

## Background:
Device / Browser (OS version): Chrome 114.0.5735.198 on Mac 13.4.1
Build: staging 2023-07-05.0
Retested on: 10 July 2023

**Comment by joyzoursky** [comment]
grouped in #3331
