### ISSUE TITLE
[User profile, Settings] Shows 'Server encountered an internal error' upon double-clicking the 'save' button

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1780]
ux/trival

## Background:
- Device / Browser (OS version): Chrome on win 10
- Version Tag: 2022-02-08.0
- Reported by: Jasonns 

## Description:
Shows 'Server encountered an internal error' upon double-clicking the 'save' button

## Steps to reproduce:
1. Log in to any app portal
2. Go to the 'Settings' page > Edit any field in the profile
3. Double-click the save buttons/click 'Enter' key several times
4. See the 'Server encountered an internal error' message is temporarily shown

## Expected result:
Should save the changes without showing internal server error

## Screenshot:

https://user-images.githubusercontent.com/4337525/153826016-dc315468-2d5f-4d84-8281-008ac121eff0.mp4

**Comment by fungc-io** [comment]
Fixed
