### ISSUE TITLE
[User profile, Settings] '0' is not shown for integer/number custom attribute in profile preview

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1784]
ux/minor

## Background:
- Device / Browser (OS version): Chrome on win 10
- Version Tag: 2022-02-08.0
- Reported by: Jasonns 

## Description:
No values are shown for integer/number fields with 0 as their contents, which may confuse users with those fields that have literally no values.

## Steps to reproduce:
1. Log in to the app portal > Go to the Settings page
2. Edit the integer/number fields in the profile and set it to zero
3. See no values are shown in the profile preview page (though values are retrieved when using UserInfo api)
4. Remove the values of those fields
5. See no values are shown in the profile preview page, while no values are retrieved when using UserInfo api

## Expected result:
Should show the assigned values for those profile fields if '0' value is assigned

## Screenshot:

https://user-images.githubusercontent.com/4337525/153841939-040f6173-7aff-4728-9312-3a232bb660c1.mp4

**Comment by louischan-oursky** [comment]
Problem of zero value. We need to introduce `isNil` to check whether a value is nil explicitly.
