### ISSUE TITLE
[Admin Portal, Audit Log] Suggest to set default sort Activities by latest date

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1787]
ux/minor

## Background:
- Device / Browser (OS version): Chrome Version 97.0.4692.99 (Official Build) (x86_64) on Macbook Pro
- Version Tag: 2022-02-08.0
- Reported by: Anthony

## Description:
The default sorting on Audit Log is by the earliest date for now. Suggest changing it to by latest date as it navigates to the first page every time the user back/refreshes the Audit Log page.

## Steps to reproduce:
1. Log in to admin portal
2. Go to Audit Log
3. See the activities is sort by earliest date

## Expected result:
Suggest to sort by latest date

## Screenshot:

https://user-images.githubusercontent.com/4337525/153854640-b9ae3043-a2d2-4713-9946-535c863c4d25.mov

**Comment by fungc-io** [comment]
dup: #1275
