### ISSUE TITLE
[User Portal, Custom Attributes] Large number will shown as scientific notation for Number/Integer attributes

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1791]
ux/minor

## Background:
- Device / Browser (OS version): Chrome Version 97.0.4692.99 (Official Build) (x86_64) on Macbook Pro
- Version Tag: 2022-02-08.0
- Reported by: Anthony

## Description:
When setting the min/max value to a large number for Number/Integer type custom attributes on admin portal, it will show as scientific notation for the large number in the info message on user portal. And, when the user input a large number for the attributes, it will show as scientific notation in placeholder either.

## Steps to reproduce:
1. Log in to admin portal > go to Custom Attributes
2. Select any number/integer type attribute
3. Set large number (> 1000000) on Min/Max field 
4. Log in to user portal > go to Profile
5. Edit the attribute
6. See the large number on info message convert to scientific notation
7. Input a large number > back to Profile page
8. See text value converted to scientific notation on the attribute
9. Edit the attribute again
10. See the placeholder convert to scientific notation

## Expected result:
Should not show as scientific notation, show full number instead.

## Screenshot:

https://user-images.githubusercontent.com/4337525/153862111-4e7ac0c1-01ca-4c88-b15e-887aa71b44ad.mp4

**Comment by louischan-oursky** [comment]
I suggest we add a function to show the value as in `{{ .Value | show_attribute_value }}`
