### ISSUE TITLE
[Account deletion] Disabled accounts become enabled after canceling scheduled removal

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1813]
bug/minor

## Background:
- Device / Browser (OS version): Chrome on win 10
- Build: Version Tag: 2022-02-08.0
- Reported by: Jasonns

## Description:
Disabled accounts will be enabled again after canceling their scheduled removal, even though the account status was originally disabled before scheduling removal.

## Steps to reproduce:
1. Log in to the Authgear portal and select any project
2. Go to the User Management page and edit any account
3. Disable the account
4. Schedule a removal for the account, and then cancel the removal
5. See the account becomes enabled again

## Expected result:
The disabled status should be independent of the deactivated/pending for deletion status

## Screenshot:

https://user-images.githubusercontent.com/4337525/154917288-93e125b4-12b4-48b7-b44d-3e8fc8d946d9.mp4

**Comment by fungc-io** [comment]
We will not change this behavior at the moment.

Please change the copy in the dialog to:
> Do you really want to cancel scheduled removal on user {user}? If the removal is canceled, they will be re-enabled and can login again.

![Screenshot 2022-02-21 at 17 12 17](https://user-images.githubusercontent.com/15207470/154925482-b095aef0-1ceb-4027-946f-6f1084287e71.png)
