### ISSUE TITLE
[Account Deletion] Show code-like error when click browser Back button after accessing to deleted account

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1815]
bug/minor

## Background:
- Device / Browser (OS version): Chrome on win11
- Build: staging-2022-02-11.0
- Reported by: Anthony

## Description:
Related #1814 

When the user goes to the Login page after accessing to deleted account Setting page, he will see code-like error.

## Steps to reproduce:
1. Go to user portal
2. Proceed to input password page for an account that is scheduled for deletion
3. Go to User Management > Select the account
4. Click "Remove Immediately" for Remove User
5. Back to user portal
6. Click Next button
7. See will redirect to error page
8. Click browser Back button
9. See will redirect to Login page with code-like error

## Expected result:
Should not show code-like error

## Screenshot:

https://user-images.githubusercontent.com/4337525/154925601-14e7f104-ff38-402a-8f67-b716085a89bf.mp4

**Comment by fungc-io** [comment]
fixed in #1830
