### ISSUE TITLE
[Account deletion, Audit log] ID of the deleted users will be removed from the audit log listings

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1817]
bug/major

## Background:
- Device / Browser (OS version): Chrome on win 10
- Build: Version Tag: 2022-02-08.0
- Reported by: Jasonns

## Description:
After deleting users, their ID in the activity records will also be removed from the audit log listings page. Note that the user ID can still be found in the raw event log of some activities.

## Steps to reproduce:
1. Log in to the Authgear portal and select any project
2. Go to the 'Audit Log' page and select any activity record
3. Delete the user of that activity record
4. Return to the listings page and see the ID of that deleted users are removed from all related activity logs

## Expected result:
Deleting a user should have no effects on activity logs

## Screenshot:

https://user-images.githubusercontent.com/4337525/154931824-2bdac6bd-da77-48c7-94b1-767c0b4bd679.mov

**Comment by louischan-oursky** [comment]
- [ ] Show `(deleted)` suffix
