### ISSUE TITLE
[User Profile] Allow upload profile `picture` in AuthUI Settings and Portal

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1824]
Tracking issue: #1510 

## Problem

This is the next stage of the Profile feature. The current implementation of the `picture` attribute do not allow uploading pictures to Authgear. The end-users are not able to change it via AuthUI. The URLs are set by the dev or admin and rely on third-party image storage.

## User Stories

- End-users: to edit my profile picture on `settings` alongside with other attributes of my profile
- App developers: To add profile picture editing features quickly only using the front-end and storage provided by Authgear. So the product can be shipped faster and less to be managed.
- (nice to have) Admins: to upload a profile picture for an end-user in the Portal

## Design Reference

https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=4521%3A26291

## Appetite

2 weeks

## Implementation considerations

- Avoid third-party paid services like Cloudflare Images
- Support common cloud storage Azure, GCP and AWS; Perhaps via MinIO
- Try open-source image proxy server
  - https://github.com/imgproxy/imgproxy: written in Go; based on libvips
  - https://github.com/willnorris/imageproxy: written in Go; based on https://github.com/disintegration/imaging

## Breakdown and Tracking

Breakdown based on https://github.com/authgear/authgear-server/pull/1840

- [x] https://github.com/authgear/authgear-server/issues/1843
- [x] https://github.com/authgear/authgear-server/issues/1844
- [x] https://github.com/authgear/authgear-server/issues/1845
    - [x] https://github.com/authgear/authgear-server/issues/1853
    - [x] https://github.com/authgear/authgear-server/issues/1850
    - [x] https://github.com/authgear/authgear-server/issues/1865
- [x] https://github.com/authgear/authgear-server/issues/1846
    - [x] https://github.com/authgear/authgear-server/issues/1861
    - [x] https://github.com/authgear/authgear-server/issues/1862
    - [x] https://github.com/authgear/authgear-server/issues/1863
    - [x] https://github.com/authgear/authgear-server/issues/1864
- [x] https://github.com/authgear/authgear-server/issues/1848
- [x] Auth UI
    - [x] https://github.com/authgear/authgear-server/issues/1859
    - [x] https://github.com/authgear/authgear-server/issues/1868
    - [x] https://github.com/authgear/authgear-server/issues/1871
- [x] Portal
    - [x] #1877
    - [x] #1878
    - [x] #1879
- [ ] Deployment
    - Update helm-chart to add authgear image development
    - Update parent chart to deploy MinIO with GCS
    - Update ingress to adjust nginx client_max_body_size

**Comment by fungc-io** [comment]
Design can be found here:
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=2%3A175

**Comment by carmenlau** [comment]
Breakdown based on https://github.com/authgear/authgear-server/pull/1840

- [ ] Study the open-source image proxy server for image resizing
- [ ] Initial setup
    - Update docker-compose.yaml to setup MinIO for local development
    - Setup empty images server endpoint
    - Load MinIO config from env
- [ ] Implement serving image endpoint
    - Obtain images from MinIO, the file should be in path /APP_ID/OBJECT_ID
    - Preform image resizing, support serving various resizing options (resizing options, pre-configured profile and original)
- [ ] Implement uploading image endpoint
    - create table migration
    - verify url signature
    - upload file to MinIO and insert record to the db
- [ ] Auth UI
    - request upload url api in the main server
    - auth ui frontend image cropping
    - upload image to the url and send update user profile attribute
- [ ] Portal
    - request upload url api in the admin server
    - [TBC]
- [ ] Deployment
    - Update helm-chart to add authgear image development
    - Update parent chart to deploy MinIO with GCS
    - Update ingress to adjust nginx client_max_body_size

**Comment by fungc-io** [comment]
@louischan-oursky 
My Figma file:
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=2%3A175

**Comment by fungc-io** [comment]
@louischan-oursky 
design for editing profile pic in the Portal
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=33%3A1148

See if it make sense?

**Comment by louischan-oursky** [comment]
> See if it makes sense?

It looks good to me. Thank you.

**Comment by chpapa** [comment]
Deployed but not closed? @fungc-io
