### ISSUE TITLE
Improve SMS deliverability to regions around the world

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1854]
Alphanumeric sender ID is not available worldwide. See https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID

Some phone number bought from Twilio is eligible for sending SMS to the same region. For example, SMS sent with Hong Kong numbers can only deliver to Hong Kong numbers. US numbers seem not to have this limitation.

Twilio has a concept of Messaging Services, which is a group of senders (phone numbers). When sending SMS programmatically, instead of specifying a single sender, we can specify a Messaging Service. Twilio will choose appropriate sender available in the service.

It is possible to use alphanumeric sender ID with Messaging Services.

---

Given these fact
- Hong Kong supports alphanumeric sender ID
- South Africa does NOT support alphanumeric sender ID

The following table summarizes my testing results.

|scenario|outcome|
|---|---|
|Send SMS with alphanumeric sender ID to a Hong Kong number|Delivered|
|Send SMS with alphanumeric sender ID to a South Africa number|Failed|
|Send SMS with Messaging Service (1 US Phone Number) and alphanumeric sender ID to a South Africa number|Failed|
|Send SMS with Messaging Service (1 US Phone Number) to a South Africa number|Delivered|

---

Conclusion

- Build a list of alphanumeric sender ID enabled regions
- When the region supports alphanumeric sender ID, we use it, otherwise we don't
- Create a Messaging Service
- Buy a phone number capable of sending SMS worldwide. A US phone number seems good for this job.
- Add that phone number to the Messaging Service
- Make Authgear support Messaging Service and alphanumeric sender ID.

**Comment by fungc-io** [comment]
error handling:

- Can we show a message in AuthUI for the end-user see the SMS sent failed
- Is it captured in error log and audit log
