### ISSUE TITLE
Review any existing iOS / Android / Web SDKs behaviours that is werid or problematic for 1st party application

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#1860]
One problem is when 1st party web app use tokens, the logout doesn't clear the cookies session.

Should do a full review for all of these behaviour, or any confusing APIs / documentations.

**Comment by chpapa** [comment]
fyi Trello x Altassian logout would redirect to another page to click logout button again, maybe a UX ref

**Comment by carmenlau** [comment]
To fix the UX problem that the web app only logout the app but the "apps.authgearapps.com" remains logged in. Maybe we can suppress the idp session when the `sessionType` is `refresh_token`. That means when user login, we only create refresh token but not the idp session. 

To do:
- Do not create idp session when `sessionType` is `refresh_token`
- Use `app_session_token` to open setting page, so the web app won't rely on the idp session to open the setting page.
