### ISSUE TITLE
Prevent empty app name

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1893]
bug/major

## Background:
- Device / Browser (OS version): Chrome on Mac
- Build: Version Tag: 2022-02-24.0

## Description:
In email verification, App name is missing from the Email Title

## Steps to reproduce:
1. Log in to the User Portal with an unverified email
2. Under Email Address, click 'Send Verification Code'
3. Check email, see app name missing in email title, `[]` vs `[Triple]`

## Expected result:
Should have email title.

## Screenshots:
<img width="837" alt="Screenshot 2022-03-21 at 7 08 05 PM" src="https://user-images.githubusercontent.com/4337525/159250874-ae9970c2-b745-43fa-9518-92d16f37461a.png">

<img width="668" alt="Screenshot 2022-03-21 at 7 07 25 PM" src="https://user-images.githubusercontent.com/4337525/159250859-e78cd271-fedf-4351-94b6-94a9ea083635.png">

Reset Password Email which has the App Name
<img width="810" alt="image" src="https://user-images.githubusercontent.com/4337525/159250919-e83da72a-7674-44d3-9f8b-3e995faa83f6.png">

**Comment by fungc-io** [comment]
I believe that was because the appName was missing. I found the demo app missed the appName for a while in Portal > **UI Settings** earlier.
For Empty appName, we shall put "Authgear" as fallback here, so as the site title of AuthUI.

**Comment by fungc-io** [comment]
We can do two things:
- Add validation and make app name compulsory in "UI Settings"
- Make empty appname falls back to "Authgear"

**Comment by louischan-oursky** [comment]
I have an idea of forbidding empty string in translation.json

Here is the actual usage of empty string in translation.json in production

```
***** templates_2f_en_2f_translation.json email.default.reply-to
***** templates_2f_en_2f_translation.json email.default.subject
******** templates_2f_en_2f_translation.json email.default.reply-to
******** templates_2f_en_2f_translation.json email.default.subject
****************** templates_2f_en_2f_translation.json email.default.reply-to
****************** templates_2f_en_2f_translation.json email.default.subject
*************** templates_2f_en_2f_translation.json app.name
*************** templates_2f_en_2f_translation.json email.default.reply-to
*************** templates_2f_en_2f_translation.json email.default.subject
*************** templates_2f_en_2f_translation.json privacy-policy-link
*************** templates_2f_en_2f_translation.json terms-of-service-link
**************** templates_2f_en_2f_translation.json email.default.reply-to
**************** templates_2f_en_2f_translation.json email.default.subject
************* templates_2f_en_2f_translation.json email.default.reply-to
************* templates_2f_en_2f_translation.json email.default.subject
***** templates_2f_en_2f_translation.json email.default.reply-to
***** templates_2f_en_2f_translation.json email.default.subject
***** templates_2f_en_2f_translation.json use-login-id-key
***** templates_2f_en_2f_translation.json sign-up-to-continue
***** templates_2f_en_2f_translation.json log-in-to-continue
***** templates_2f_zh-TW_2f_translation.json email.default.reply-to
***** templates_2f_zh-TW_2f_translation.json email.default.subject
***** templates_2f_zh-TW_2f_translation.json use-login-id-key
***** templates_2f_zh-TW_2f_translation.json sign-up-to-continue
***** templates_2f_zh-TW_2f_translation.json log-in-to-continue
********************* templates_2f_en_2f_translation.json email.default.reply-to
********************* templates_2f_en_2f_translation.json email.default.subject
****** templates_2f_en_2f_translation.json email.default.reply-to
****** templates_2f_en_2f_translation.json email.default.subject
********** templates_2f_en_2f_translation.json email.default.reply-to
********** templates_2f_en_2f_translation.json email.default.subject
********* templates_2f_en_2f_translation.json email.default.reply-to
********* templates_2f_en_2f_translation.json email.default.subject
***** templates_2f_en_2f_translation.json email.default.reply-to
***** templates_2f_en_2f_translation.json email.default.subject
******* templates_2f_en_2f_translation.json email.default.reply-to
******* templates_2f_en_2f_translation.json email.default.subject
******* templates_2f_en_2f_translation.json sign-up-to-continue
******* templates_2f_en_2f_translation.json log-in-to-continue
******* templates_2f_zh-TW_2f_translation.json email.default.reply-to
******* templates_2f_zh-TW_2f_translation.json email.default.subject
******* templates_2f_zh-TW_2f_translation.json sign-up-to-continue
******* templates_2f_zh-TW_2f_translation.json log-in-to-continue
*************** templates_2f_en_2f_translation.json email.default.reply-to
*************** templates_2f_en_2f_translation.json email.default.subject
```

No idea why there are so many `email.default.reply-to` and `email.default.subject` being empty string.
There are valid usage of empty string though, for example, `privacy-policy-link`, `terms-of-service-link`, `sign-up-to-continue`, `log-in-to-continue`. `use-login-id-key` is special one, as it is used as a button label.

**Comment by fungc-io** [comment]
@louischan-oursky 
is this on staging already?
I think it is still accepting empty appname in the ui-settings

![Uploading Screenshot 2022-04-07 at 18.43.17.png…]()

**Comment by louischan-oursky** [comment]
It still accepts empty string, but when you save an empty string, the default value is used instead. So the app name will never be empty at runtime.

**Comment by fungc-io** [comment]
Got it
