### ISSUE TITLE
Create a Getting Started Page

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1899]
Design: 
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=165%3A2284

**Comment by fungc-io** [comment]
Design: 
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=165%3A2284

**Comment by fungc-io** [comment]
Links - 
Community forum: https://github.com/authgear/authgear-server/discussions
Contact Us: https://www.authgear.com/talk-with-us?utm_source=portal&utm_medium=link&utm_id=getting_started

**Comment by fungc-io** [comment]
Change copy:
- "Try your Login page and Setting Page" -> "Sign up your first user"
- "Customize the UI" -> "Customize the signup & login page"

**Comment by fungc-io** [comment]
Please change the link of "How Authgear Works" in "Create Application" to
https://docs.authgear.com/get-started/authentication-approach

**Comment by chpapa** [comment]
@fungc-io @louischan-oursky The responsiveness of the Getting Started page is broken (as well as other pages of the portal), but it is particularly annoying for the Getting Started page. (See below)

Another thing is I think the heading "Getting Started" (which is h1) doesn't look consistent with other pages' h1 (such as "Analytics") which looks werid too.

![getting started authgear](https://user-images.githubusercontent.com/387241/165217482-2d221424-7b2a-490f-a89f-455f7d4a0635.jpg)

**Comment by fungc-io** [comment]
@louischan-oursky 
Please follow the responsive design here:
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=311%3A2925

![1 4 Getting Started-responsive-720](https://user-images.githubusercontent.com/15207470/165716154-42d67bc5-4a5c-4889-ada8-d685ed11e1c8.png)

It should look good in half macbook screen (720px)

**Comment by fungc-io** [comment]
Env: `staging-2022-05-06.0`
The line "Post on our.... and support" should wrap in narrow screen size:
![get-started-narrow-screen](https://user-images.githubusercontent.com/15207470/167565978-1f0ed87a-3471-40da-aff6-d655629565a5.png)

**Comment by fungc-io** [comment]
<img width="462" alt="Screenshot 2022-05-10 at 17 28 37" src="https://user-images.githubusercontent.com/15207470/167597157-41f0b540-f4d5-430e-b13a-c4a47bc69be4.png">

Line break should not break word

e.g.

> ...help and sup
> port

**Comment by louischan-oursky** [comment]
<img width="467" alt="Screen Shot 2022-05-10 at 5 39 50 PM" src="https://user-images.githubusercontent.com/15082564/167599237-b1e8a228-55a7-4e39-a519-93a6e3338738.png">
 Is this OK?

**Comment by fungc-io** [comment]
@louischan-oursky yes!
