### ISSUE TITLE
Connect with Social Media account with existing connection show no error but not connected

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#190]
Using Rees, When I try to connect my account with an Apple ID that's already signed up as another account, it doesn't show any error but just silently ignore my actions.

- Authgear Server Date/Version: (Rees's deployment at 25 Aug 2020)
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results
It should either show me an error tell me another account already exists, or let me merge two accounts (probably need to think carefully how this works)

#### Actual Results
It didn't show any error

#### Steps to reproduce

1. Sign up Rees with my Apple ID
2. Delete the app, and reinstall a new version
3. Sign up Rees with a new phone no.
4. After signup, go to Setting Page, link with Apple ID
5. After the Apple ID verification, it show nothing -- the button next to Apple ID still shows "connect"

**Comment by louischan-oursky** [comment]
Verified that this bug has been fixed some time ago

**Comment by chpapa** [comment]
@louischan-oursky so it is just Rees not using latest version?

**Comment by louischan-oursky** [comment]
Yes.
