### ISSUE TITLE
Update the colors of Dark Mode of the Default theme

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1902]
(Details to be provided)

Background:
Pane Card Background:
Text Color:

Screenshot:

**Comment by karinyu** [comment]
Background color > #212121

**Log in/ Sign up Card**
Background > #353535
Border > #3E3E3E
Elevation > x=0, y=4, b=8, s=0 #000000, 10%

**Text Color**
Primary > #E5E5E5
Secondary/ Placeholder > #A6A6A6
Tertiary > #828282

Divider > #595653

https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=5954%3A110466
<img width="354" alt="Screenshot 2022-04-04 at 3 27 44 PM" src="https://user-images.githubusercontent.com/83946723/161494409-aef0afa1-dd76-489b-a3af-5f7f8ac661d2.png">

**Comment by karinyu** [comment]
**User account settings**
Items' background on card > #F8F8F8, 20%
<img width="678" alt="Screenshot 2022-04-08 at 3 15 34 PM" src="https://user-images.githubusercontent.com/83946723/162384263-9f5f0fa0-4200-45a5-acad-060f9b778366.png">

https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6008%3A110821

**Comment by fungc-io** [comment]
The background color for all the preset themes ("Default", "Tropical",...) should be `#212121`

![Screenshot 2022-05-17 at 15 27 40](https://user-images.githubusercontent.com/15207470/168755215-a3c79ad3-8f08-4fd0-a7ea-89218fd08581.png)

For the existing project, if they are using the preset theme, can we migrate their current color into "Custom"?
