### ISSUE TITLE
Prevent user from uploading ICO file for favicon

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#1907]
- [ ] Remove ICO in the copy in the portal
- [ ] Check the file header of file uploaded to verify the type, so it doesn't crash when the user uploaded a corrupted file

**Comment by louischan-oursky** [comment]
Could we just correct the copywriting to state that we do not intend to supoort .ico?

**Comment by fungc-io** [comment]
Agree, updated the issue content
