### ISSUE TITLE
View port of Setting page could be zoomed in on iOS

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#191]
I can double tap on the setting page to zoom in to the view port under iOS WebView, ideally it should not be possible

- Authgear Server Date/Version:
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Steps to reproduce

1.
2.
3.

**Comment by louischan-oursky** [comment]
Any particular reason why we should disallow the user to zoom in?

**Comment by chpapa** [comment]
> Any particular reason why we should disallow the user to zoom in?

For better UX? Our mobile UI should be responsive to the screen size, so users no need to zoom in for particular part of the UI -- which when they do it is kind of tough to navigate

**Comment by louischan-oursky** [comment]
[This benchmark](https://web.dev/meta-viewport/) says the opposite. https://developers.google.com/web/tools/lighthouse

**Comment by chpapa** [comment]
Good point, but I think that’s for website in general, like we should have zoom when the pages are open on web browser

The in-app one should instead simulate the behavior on mobile app, and the size of layout should be crafted for mobile screen (actually could we make our layout font size follow system default size?)

I am not 100% sure but just seems counter intuitive to usual best practices on mobile

**Comment by louischan-oursky** [comment]
I see your point. Native mobile app, if written with accessibility in mind like Whatsapp, make their font scale along with system accessibility settings. But website cannot take advantage of the user's accessibility settings yet. Allow zooming should be more accessible.

**Comment by louischan-oursky** [comment]
[Given that most of the viewport settings are ignored by Safari](https://webkit.org/blog/7367/new-interaction-behaviors-in-ios-10/), we cannot disable pinch to zoom. However, we want to disable double tap to zoom.

It is possible to intercept double tap globally to disable zoom with the following javascript

```typescript
document.addEventListener("dblclick", function(e) {
  e.preventDefault();
  e.stopPropagation();
});
```
