### ISSUE TITLE
[Profile pic] Can still edit profile picture via direct URL access even access-right is not set to"Editable"

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#1917]
bug/major

## Background:
- Device / Browser (OS version): Chrome 99.0.4844.82/Firefox 98.0.1/Edge 99.0.1150.46 on Win 10
- Build: Staging, demo-enterprise-25032022, demo-webapp-cookie-25032022, demo-webapp-refresh-token-250322
- Version Tag: staging-2022-03-01.1
- Reported by: Jasonns

## Description:
After setting the admin access right on the profile picture to be 'Read-only'/ 'Hidden', admins can still edit user profile pictures by directly accessing the URL `.../details/edit-picture`.

## Steps to reproduce:
1. Log in to the admin portal
2. Select any application (e.g. demo-enterprise)
3. Go to the User Profile > Standard attributes tab
4. Change the admin access right on the profile picture to be 'Read-only' / Hidden'
5. Go to the User Management page > select any user
6. On the user details page, change the URL suffix from `/details#...` to `/details/edit-picture`
7. See the edit picture screen can still be accessed and the admins can still edit the user profile pictures

## Expected result:
Should not allow users to edit the profile pictures if the access right is not set to 'Editable'

## Screenshot:

https://user-images.githubusercontent.com/93981572/160359207-f1c940a6-0a3b-4968-8065-d6df6a9aafc3.mp4

**Comment by fungc-io** [comment]
Change: Show permission denied error and redirect to `/details#user-profile`
