### ISSUE TITLE
[Profile pic] No error dialogs upon uploading files of incorrect extensions

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#1919]
ux/major

## Background:
- Device / Browser (OS version): Chrome 99.0.4844.82/Firefox 98.0.1/Edge 99.0.1150.46 on Win 10
- Build: Staging, demo-enterprise-25032022, demo-webapp-cookie-25032022, demo-webapp-refresh-token-250322
- Version Tag: staging-2022-03-01.1
- Reported by: Jasonns

## Description:
No error dialogs will be shown upon uploading files of incorrect extensions. Users will see a broken avatar preview and unresponsive "save" button, but no error dialogs.

## Steps to reproduce:
Case 1: No error dialogs upon uploading files of incorrect extensions as avatar on User Portal
1. Log in to the demo-enterprise app
2. Edit personal profile > Edit profile picture
3. Upload a non-image file as profile picture
4. See no error dialog

Case 2: No error dialogs upon uploading files of incorrect extensions as avatar on Admin Portal
1. Log in to admin portal
2. Go to the User management page > select any user
3. Edit profile picture
4. Upload a non-image file as profile picture
5. See no error dialog

## Expected result:
Should show error dialogs for invalid file types

## Screenshot:

(on user portal)

https://user-images.githubusercontent.com/93981572/160370171-b63ea50f-6edf-4615-9fb4-37e51c418273.mp4

(on admin portal)

https://user-images.githubusercontent.com/93981572/160369976-9044db46-f231-40f2-bc5d-4b64de57a156.mp4

**Comment by fungc-io** [comment]
Add image file type validation,
and show error message for invalid type:
> Please upload an image file.
