### ISSUE TITLE
[Profile pic] Uploaded picture cropped after switching back and forth from mobile to desktop view

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#1922]
bug/minor

## Background:
- Device / Browser (OS version): Chrome 99.0.4844.82/Firefox 98.0.1/Edge 99.0.1150.46 on Win 10
- Build: Staging, demo-enterprise-25032022, demo-webapp-cookie-25032022, demo-webapp-refresh-token-250322
- Version Tag: staging-2022-03-01.1
- Reported by: Jasonns

## Description:
After uploading a photo as the profile picture and before saving it, the uploaded picture will be cropped if the user switches back and forth from mobile to desktop view, or landscape to portrait mode.

## Steps to reproduce:
1. Log in to the demo-enterprise app
2. Edit the personal profile > Edit profile picture
3. Upload a photo as the profile picture
4. Before saving, switch back and forth from mobile to desktop view, or landscape to portrait mode
5. See the image is cropped

## Expected result:
The ratio of the uploaded image should persist in different view modes.

## Screenshot:

https://user-images.githubusercontent.com/93981572/160401850-c8d9705e-87cd-4f50-93df-10dcf1d1c109.mp4

**Comment by fungc-io** [comment]
very little users will be affected by this problem, and it is not causing significant inconvenience. I decide not to fix.
