### ISSUE TITLE
[Profile pic] Shows blank container on edit-picture screen when the user has no profile icon

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#1925]
ui/major

## Background:
- Device / Browser (OS version): Chrome 99.0.4844.82/Firefox 98.0.1/Edge 99.0.1150.46 on Win 10
- Build: Staging, demo-enterprise-25032022, demo-webapp-cookie-25032022, demo-webapp-refresh-token-250322
- Version Tag: staging-2022-03-01.1
- Reported by: Jasonns

## Description:
A blank container is shown on the edit-picture screen for users without profile pictures. Suggest showing a profile picture placeholder instead.

## Steps to reproduce:
1. Log in to the admin portal
2. Select any application (e.g demo-enterprise) > User management
3. Select any user without profile pictures, and edit their profile picture
4. See the blank container

## Expected result:
Should show the default avatar placeholder

## Screenshot:

![image](https://user-images.githubusercontent.com/93981572/160542782-3c40f429-dce3-4a2a-a873-c762d5d19b8b.png)

**Comment by fungc-io** [comment]
Add a placeholder for empty state like this:
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=202%3A2388
