### ISSUE TITLE
[Profile] Breadcrumb trails for 'Edit picture'/'Add identity' page does not match with design

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#1926]
ui/trivial

## Background:
- Device / Browser (OS version): Chrome 99.0.4844.82/Firefox 98.0.1/Edge 99.0.1150.46 on Win 10
- Build: Staging, demo-enterprise-25032022, demo-webapp-cookie-25032022, demo-webapp-refresh-token-250322
- Version Tag: staging-2022-03-01.1
- Reported by: Jasonns

## Description:
The breadcrumb trails for the 'Edit picture'/'Add identity' page are different in the design and in the implementation. In design, the trails is "User details > Edit profile picture", while in the implementation is "Users > User details > Edit profile picture". Not sure if it is designed to only show the last 2 trails. 

## Steps to reproduce:
1. Log in to the admin portal
2. Select any application (e.g. demo-enterprise) > User management
3. Select any user > Edit profile picture
4. See there are 3 items in the breadcrumb trails, which is inconsistent with that in the design

## Expected result:
Should only show the last 2 trails or the design should be updated

## Screenshot:

![image](https://user-images.githubusercontent.com/93981572/160545398-cc76510f-4ba0-43ac-96cc-6ecabc52aa83.png)

(design)

![image](https://user-images.githubusercontent.com/93981572/160545316-c302fed1-8647-4a60-b2e0-da3cc4191c7a.png)

**Comment by stanleylhs** [comment]
@joyzoursky Issue validation check: Not Reproducible

## Description: 
Please confirm that we can't change picture from admin portal?

## Background:
Device / Browser (OS version): Chrome 114.0.5735.198 on Mac 13.4.1
Build: staging 2023-07-05.0
Retested on: 10 July 2023
