### ISSUE TITLE
[Profile pic] Shows 404 page not found error upon uploading profile pictures

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#1927]
bug/major

## Background:
- Device / Browser (OS version): Chrome 99.0.4844.82/Firefox 98.0.1/Edge 99.0.1150.46 on Win 10
- Build: Staging, demo-enterprise-25032022, demo-webapp-cookie-25032022, demo-webapp-refresh-token-250322
- Version Tag: staging-2022-03-01.1
- Reported by: Jasonns

## Description:
For the demo-webapp-cookie, 404 page not found error is shown if the end-user attempts to save an uploaded image. This is suspected to be related to the incorrect URL domain of the upload endpoint, where the correct domain should be `demo-webapp-cookie.authgear...` but on the end-user side the domain becomes `accounts.demo-webapp-cookie.authgear...`. This issue also happens to all image-retrieval request on the end-user side.

## Steps to reproduce:
1. Log in to the demo-webapp-cookie app
2. Edit the personal profile > Edit profile picture
3. Upload and save a photo as the profile picture
4. See unable to save and the 404 error in the console log

## Expected result:
Should be able to upload photos for the profile picture

## Screenshot:

https://user-images.githubusercontent.com/93981572/160547806-310206f4-adda-4dcc-a427-b54e563ef6fd.mp4

**Comment by louischan-oursky** [comment]
This is due to a configuration problem of the ingress of this particular app. This app is using custom domain. Thank you for discovering this.
