### ISSUE TITLE
Connect to redis over TLS

### ISSUE THREAD

**Issue by hidden-dimensions** [authgear/authgear-server#193]
To improve security we shall support optionally connecting redis over tls. One use case is connecting to aws ElasticCache, which they supports TLS out of the box.

redis supported tls since version 6: https://redis.io/topics/encryption

Not sure do this require any work on authgear as the driver handled it automatically (except maybe we need set `tls-auth-clients no`).

Other optional nice to have features:
- configuration for custom CA
- mTLS (i.e. `tls-auth-clients yes`)

**Comment by rickmak** [comment]
If the redis hosted within isolated network, I think no TLS is fine.

And for kubernetes deploy, sidecar mTLS porxy should be easier to maintain as for the cert rotation and monitor.

**Comment by kiootic** [comment]
- Use URL instead (support `rediss://` protocol)
- Remove sentinel support
