### ISSUE TITLE
Support Login with GitHub

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1930]
Add a login provider "GitHub" and support this in the "portal" app

ref:
https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps

**Comment by fungc-io** [comment]
@louischan-oursky 
please use #171515 to represent GitHub in the Portal
https://www.figma.com/file/swXJYkdXuPsLyA5q0aHu1r/Authgear-UI---Fung?node-id=14%3A1006

**Comment by fungc-io** [comment]
In the GitHub config pane
Add the toggle: `Require the email attribute`

If this is enabled and the end-user do not have a email claim
Show error message:
> Please add a "Public Email" into your GitHub profile. Manage your profile here: \[https://github.com/settings/profile](https://github.com/settings/profile)

**Comment by louischan-oursky** [comment]
- [ ] Use github username to populate name and given_name
