### ISSUE TITLE
Research Android Keystore and iOS Keychain biometric validity interval

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1973]
## Android
The doc of [setUserAuthenticationParameters](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationParameters(int,%20int)) says that the first argument can be used to extend the duration for which the private key is authorized to be used for the user is authenticated. However, when the argument is non-zero, Signature.initSign will throw [UserNotAuthenticatedException](https://developer.android.com/reference/android/security/keystore/UserNotAuthenticatedException). 

Switching the first argument to zero works. After switching back to non-zero, the behavior is the same as the zero case. That is the first argument has no effect.

## iOS

It is possible to specify a LAContext to be used when accessing biometric-protected item. Once authentication is passed, reusing the same LAContext does NOT require further biometric authentication.

**Comment by fungc-io** [comment]
On Android, users must authenticate again if they try to access a different keystore item. 
Therefore the idea of using a timeout in Account Selector and then Login to avoid repeated biometric scanning is not possible.

@chpapa ,
Maybe we should suggest the UX to be select account then biometric.
