### ISSUE TITLE
Remove Elastic Search dependency

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1978]
To reduce the deployment requirement, 
consider removing elastic search as a dependency in Authgear.

Currently Elastic Search is used in the search function in the Admin API, 
See if PostgreSQL can implement the same features.

**Comment by chpapa** [comment]
Or a better idea is to make it fallback to PostgreSQL Full-Text Search when ElasticSearch is not present; And has a more reliable way to sync the PostgreSQL database to ES
