### ISSUE TITLE
Allow setting locale and theme when opening settings page in SDKs

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1988]
In `authgear.open(Page.Settings)`, the theme and language in the settings page opened are depending on the user browser.

However some apps allow changing light/dark theme and locale regardless of the system settings.
Developer should be able to force the setting page to show a locale and theme when calling this page from the SDK.

Update SDK
- [x] RN
- [x] Web
- [x] iOS
- [ ] Android
- [x] Flutter
- [x] Xamarin

**Comment by louischan-oursky** [comment]
@carmenlau @fungc-io 

https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

Our current implementation of dark theme does not support explicit theme selection. If we change the implementation to follow the approach mentioned in the above blogpost, we will break the apps with custom dark themes :(

**Comment by louischan-oursky** [comment]
- https://github.com/authgear/authgear-sdk-flutter/issues/1
- https://github.com/authgear/authgear-sdk-js/issues/181
- https://github.com/authgear/authgear-sdk-ios/issues/80
- https://github.com/authgear/authgear-sdk-android/issues/97
- https://github.com/authgear/authgear-sdk-xamarin/issues/27
