### ISSUE TITLE
shareSessionWithSystemBrowser is not working on Android devices

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2001]
I was testing the Xamarin app and found that the "shareSessionWithSystemBrowser" option doesn't do anything.
The session is always shared with the browser. 
i.e. After authenticated in the app, then access the endpoint in Chrome, I see myself logged in, no matter on or off the option

@louischan-oursky told me offline that the option is not working with Android, it's iOS only. 

What was the reason why the option doest work with Android? Is it technically impossible?
I can't find the related discussion in the original issue https://github.com/authgear/authgear-server/issues/1391

If this is technically impossible, the docs should reflect that the option is not supported:
- https://docs.authgear.com/integrate/single-sign-on implies the option should works with Android
- The SDK docs didn't mention that it only works with iOS
  - RN: https://authgear.github.io/authgear-sdk-js/docs/react-native/classes/ReactNativeContainer/#sharesessionwithsystembrowser 
  - Kotlin: https://authgear.github.io/authgear-sdk-android/sdk/sdk/com.oursky.authgear/-authgear/index.html
  - Flutter: https://authgear.github.io/authgear-sdk-flutter/authgear/Authgear/shareSessionWithSystemBrowser.html

**Comment by louischan-oursky** [comment]
I tested once again and it works on Android. When "shareSessionWithSystemBrowser" is false (the default), signing in will NOT leave a session in the system browser. This can be verified by visit the endpoint in the system browser after signing in.
When "shareSessionWithSystemBrowser" is true, the opposite is true.

**Comment by fungc-io** [comment]
Let me clear all cookies and cache and try again..

**Comment by fungc-io** [comment]
Thanks, 
I've tested again and the option works. :+1:
