### ISSUE TITLE
Handle UserNotAuthenticatedException

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2009]
On some Samsung devices with Android 12, there is a very rare case that UserNotAuthenticatedException will be thrown.

- The device just restarted
- The user unlocks the screen with password, NOT with the biometric
- Create a Signature with a PrivateKey with `setUserAuthenticationParameters`
- Call `Signature.initSign`, UserNotAuthenticatedException will be thrown eagerly

We cannot delay `Signature.initSign` because `CryptoObject` requires an initialized `Signature` to construct.

~~It seems that the only way to work around this situation is to recognize UserNotAuthenticatedException and tell the developer this situation. The developer should handle this error by telling the end-user to lock their phone AND unlock it with biometric ONLY. After that everything turns normal.~~

A further search on the web finds [someone in the same situation with us](https://issuetracker.google.com/issues/227074784#comment2). `setUnlockedDeviceRequired(true)` is the cause. It seems that when `setUnlockedDeviceRequired(true)`, the device MUST be locked with the same level of authentication requirement with the key. Given that we are using BiometricPrompt, which is obviously visible only in an unlocked device, `setUnlockedDeviceRequired(true)` only brings trouble.

- [x] Flutter
- [x] RN
- [x] Android
- [x] Xamarin

**Comment by roxk** [comment]
I will take android + xamarin

**Comment by fungc-io** [comment]
All sdks confirmed working on Android 12 with demo apps
