### ISSUE TITLE
For the "Authgear Branding", open in new window on Desktop and do not link if open in Mobile

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#2027]
Not sure if it is feasible.

UX-wise, if users accidentally touch the Authgear logo on the Setting page on mobile, they will be redirected to Authgear.com in the ASAuthenticationSession.

That's very weird and out of context.

So proposed fixes are:

1. If feasible, make the logo always open in new windows on Desktop, and DO NOT redirect to Authgear.com in mobile (disable the link in mobile)
2. If 1 is not feasible or too complicated, maybe we make Authgear logo not clickable at all

**Comment by fungc-io** [comment]
@andychow326 please help fix this issue too

<img width="487" alt="Screenshot 2022-05-30 at 16 11 09" src="https://user-images.githubusercontent.com/15207470/170947892-e0204543-2987-46c5-8069-8fb0e97d7244.png">

This logo should:

- Desktop: open authgear.com in new tab
- Mobile: no link, do nothing when clicked
