### ISSUE TITLE
[Whatsapp OTP] No instruction for how to continue if user picked "Yes, open in Whatsapp"

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#2061]
ux/minor

## Background:
- Device / Browser (OS version): Chrome on Mac
- Build: Version tag 2022-05-11.0

## Description:
If user is only using one single device i.e. a mobile phone, no instruction is provided for how to continue if user picked "Yes, open in Whatsapp". User may not know that they need to click "Send" in Whatsapp  and they don't know that they need to manually switch back to the app afterwards.

Only if the user is using two devices then they can see the automatic redirect from Authgear, i.e. Login in with computer and  send 2FA via phone, then they can see automatic redirect on the computer.

## Steps to reproduce:
1. Trigger a scenario which Whatsapp 2FA is used, either Sign up with Phone number or in Login with Phone number
2. In Whatsapp 2FA dialog, click "Yes, open in Whatsapp"
3. Redirected to Whatspp but with no instruction on how to to carry on
4. Click "Send"
5. Received no instruction on how to to carry on

## Expected result:
As this is general laymen users facing, instructions should be explicitly stated in details. 

1. In the WA dialog, should hint to user that they need to click "Send" before they clicked "Yes, open in Whatsapp"
2. After user has clicked "Send", further instruction should be sent to the users, as WA is conversational, user will expect response promptly inside WA. A redirect (deep) link should be sent as a reply to the redirect user back to the app to continue.

## Screenshot:
No clear instructions for how to carry on
<img width="1326" alt="Screenshot 2022-06-06 at 11 39 23 AM" src="https://user-images.githubusercontent.com/4337525/172092082-3627a741-9cb2-44c2-a35d-ccb7c6a1690b.png">

**Comment by fungc-io** [comment]
Thanks @stanleylhs , this indeed add a lot of friction to the auth process.

@carmenlau @louischan-oursky , 
I want to experiment with including more instructions in the pre-filled message

en:
```
Verify +852 12345678 with OTP #244328#

Press send on Whatsapp then return to the App
```

zh-hk:
```
以一次性密碼 #244328# 驗證 +852 12345678

請在WhatsApp按傳送，然後返回App
```

The end-user should be authenticated if the message included the OTP, regardless of the other info in the text.
i.e. `244328` and `以一次性密碼 #244328# 驗證...` should all work

**Comment by louischan-oursky** [comment]
Any specific reason we use pound sign `#` to delimit the OTP? We currently prefix the OTP with `#` because we follow [Apple's convention](https://developer.apple.com/news/?id=z0i801mg) e.g. https://github.com/authgear/authgear-server/blob/master/resources/authgear/templates/en/messages/verification_sms.txt

**Comment by fungc-io** [comment]
No technical reason, just aesthetic
