### ISSUE TITLE
Update login / signup page button label

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2068]
Change the label "Next" to "Log in" or "Sign up"

**Comment by louischan-oursky** [comment]
![Screenshot 2022-06-07 at 6 32 13 PM](https://user-images.githubusercontent.com/15082564/172359176-a2ad0121-b9c4-40ca-8804-1e2d1e2365cd.png)
![Screenshot 2022-06-07 at 6 31 59 PM](https://user-images.githubusercontent.com/15082564/172359187-bd6e62e8-42f4-449a-920e-05a215fd333a.png)

Would it look weird if we have buttons "Sign up" and "Log in with ..." on the same page? @fungc-io

**Comment by fungc-io** [comment]
@louischan-oursky i think it's fine, the tab button and the social login button don't match anyway
