### ISSUE TITLE
[Bug] User search returns the wrong users in Portal

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2071]
Reported by customer:
In the User management list in the portal, 
an unrelated user is returned alongside with the actual user when searching with a email address.

**Comment by jimcky** [comment]
@fungc-io do we still plan to fix it by this week @_@?

You mentioned the week of 4th July, just checking in :D

**Comment by fungc-io** [comment]
@jimcky 
Thanks for reminding, 
the dev is looking into the issue.
