### ISSUE TITLE
Update the Copywriting of Portal

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#2087]
On navigation bar:
1. Authentication > `Login ID`: `Login IDs`
2. `Localization` > `Email / Message Templates`

Under `Authenticators`:
- [x] Change `Configure how you want users to authenticate themselves (such as Password), and any MFA requirements` to `Configure how your users can authenticate themselves (such as Password), and any MFA requirements; The order will affect when both options are available, which one will show up first.`
- [x] Change `Secondary Authenticator` > `2nd Factor Authentication (2FA)`
- [x] Change `Require Secondary Authenticator` > `2FA Requirements`
- [x] Change `Required if users have Secondary Authenticator` > `Optional, users can set up 2FA (Recommended)`
- [x] Change `Always Required` > `Mandatory, all users required to setup 2FA`
- [x] Change `Recovery code` to `2FA Recovery code`
- [x] Change `Authenticator Apps / Devices` to `OTP Code via Google Authenticator/Authy (TOTP)` 
- [x] Change `Verify via Phone` and Email to `OTP Code via Phone` and `OTP Code via Email`
- [x] Change `Disable "Do not ask again on this device" for the Secondary Authenticator` to `Show "Do not ask again on this device" for 2FA`, and make the toggle default on
- [x] #2209 

Under `User Verification`
- [x] Change `Verified user criteria` to `isVerified` is true when... (and add a help bubble link to related doc)
- [x] Change `Required` to `Email verification is required to complete sign up` (Phone is same)

Under `Email/Message Templates`:
- [x] `Manage languages and template contents` > `Update template contents and localizations`
- [x] Change the tabs as this orders: `Reset Password`, `Passwordless via Email`, `Passwordless via SMS`, `Other Translations`
- [x] Change `First Time Setup` > `Sign up`, `Subsequent Logins` > `Login`
- [x] If enough time, show the fields only if relevant authenticators / login IDs are enabled
- [ ] If enough time, fix #1318

**Comment by andychow326** [comment]
To-do
- [ ] Authentication > Login ID: Login IDs
- [ ] Localization > Email / Message Templates
- [ ] Authenticators
- [ ] User Verification
- [ ] Email/Message Templates

**Comment by andychow326** [comment]
@fungc-io Currently there is no docs related to `Verified user criteria` under `User Verification`. How about we add a doc about it in the future and what is the url you prefer for this doc?

**Comment by fungc-io** [comment]
@andychow326 
It's referring to "isVerified" of UserInfo, please link to this section: https://docs.authgear.com/integrate/user-profile#userinfo-endpoint
