### ISSUE TITLE
Fetch product details from Stripe

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2106]
- Use GET /v1/products?active=true&limit=100 to fetch active products
- Keep only products that `plan_name` reference to an existing plan
- Use GET /v1/prices?active=true&limit=100 to fetch prices
- Keep only prices that `price_type` is specified and associated with a product
- Expose this information as a GraphQL field

**Comment by carmenlau** [comment]
Todo:

Update fetch subscription plans api with the new product models in stripe, see https://github.com/authgear/authgear-server/issues/2104.
