### ISSUE TITLE
New billing screen

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2123]
- For custom plan, hide the stripe links, Show `-` for most numbers, Hide cards.

**Comment by fungc-io** [comment]
@louischan-oursky 
i've add the button for cancelling the plan:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=6304%3A97848

only show when plan !== 'free'

**Comment by louischan-oursky** [comment]
- Show `Free | - - -` for Free plan
- Show `... or ...` for the customer portal link

**Comment by fungc-io** [comment]
@louischan-oursky ,
display metered pricing for additional MAU in the pricing table
