### ISSUE TITLE
~ Let users to switch between plans

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2163]
Upgrade/Downgrade

Change paid plans:
- Pro rata 

Move "cancel subscription" to #2172

**Comment by louischan-oursky** [comment]
- https://stripe.com/docs/billing/subscriptions/prorations#preview-proration

**Comment by fungc-io** [comment]
@louischan-oursky 

- Before #2178 is fixed, add a warning when downgrade/cancel.
- Add the projected cost for switching plans

> (Only show this line when downgrade/cancel) 
**Warning**: Your apps may stop working if you downgrade to less features. To avoid this, make sure your project configuration fit the plan you are downgrading to.
> 
> When you change your plan, the prorated charges will be reflected in the next invoice. _$xxx (estimated)_ excluding SMS and additional MAU will be charged on 1/8/2022. 
> Do you want to change your plan?

**Comment by fungc-io** [comment]
@louischan-oursky regarding the ambigious copy mentioned yesterday,
> When you change your plan, the prorated charges will be reflected in the next invoice. $xxx (estimated) and any further additional SMS and MAU will be charged on 1/8/2022.
