### ISSUE TITLE
~ Send notification to admin when user subscribe

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2164]
Possible to set a webhook so we can automate it on Zapier?

**Comment by louischan-oursky** [comment]
I tried https://slack.com/apps/A0F81FNVC-stripe but the integration requires a OAuth 2 linkage between Stripe and Slack. When Stripe performs OAuth, it requires the account to be activated / verified first. Stripe Account activation requires us filling business details, bank details and tax information, etc, which is very cumbersome.

**Comment by louischan-oursky** [comment]
The Zapier integration with Stripe is also based OAuth 2. So the same restriction applies.

**Comment by louischan-oursky** [comment]
@fungc-io If we post to Slack in our server using Incoming Webhook, what should the message contain and how should it be formatted?

**Comment by fungc-io** [comment]
> app_id: `app-lorem-ipsum` (email: xxx@email.com) has subscribed to `startups` plan.

> The subscription status of app_id: `app-lorem-ipsum` (email: xxx@email.com) plan: `startups` has changed to past_due
