### ISSUE TITLE
~ add MAU metered billing

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2166]

**Comment by louischan-oursky** [comment]
@fungc-io Should we round down or round up when calculating the cost of additional MAU?

For example, an app subscribing to a plan with 30000 MAU included has MAU of 34000, the additional MAU is 4000. The price is USD50/mo per 5000 additional MAU. In this case, should the quantity be `floor(4000 / 5000) = 0 (round down) => USD 0 additional cost` or `ceil(4000 / 5000) = 1 (round up) => USD50 additional cost`?

**Comment by louischan-oursky** [comment]
BTW, the price created in the Stripe dashboard is always round up. I cannot find a way in the dashboard to make it round down.
