### ISSUE TITLE
Server performance enhancement

### ISSUE THREAD

**Issue by andychow326** [authgear/authgear-server#2170]
## Problem

The AuthUI is too slow and the signup/login page sometimes takes more than 30 seconds to load up even under 1000Mbps network. 
This is problematic to the UX and conversions as longer the load time, poorer the bounce rate. [See research.](https://www.thinkwithgoogle.com/marketing-strategies/app-and-mobile/mobile-page-speed-new-industry-benchmarks/)

## Goal

On a reasonably fast computer/mobile phone, at 50Mbps (typical cellular/home internet speed), the end-users should be able to interact with the signup/login page in under *3 seconds* after starting.

## Todo

Use `pprof` to profile the requests and find the area we can optimize so that Authgear is more reliable and faster.

- [ ] Reduce the memory usage of each request
- [ ] Reduce the latency of AuthUI

**Comment by fungc-io** [comment]
@andychow326 
The issue description is updated

cc: @louischan-oursky @carmenlau
