### ISSUE TITLE
[Admin Portal, Analytics] No response when clicking on "Weekly" tab for Activity

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#2182]
bug/major

**Describe the bug**
When the user clicks on "Weekly" tab for Activity, the "Weekly" tab does not switch to active state and the dashboards do not update.

**Authgear Version**
 - Version: staging-2022-06-27.0
 
**To Reproduce**
1. Log in to admin portal
2. Select a project
3. Go to Analytics
4. Click "Weekly" on Activity section
5. See the tab and dashboard not update

**Expected behavior**
Dashboard should change the displayed data accordingly

**Screenshots**

https://user-images.githubusercontent.com/93981572/176606019-75cc5f8d-a0ea-4bc0-b636-dcc7447bab62.mp4

**Client Env:**
 - Device: Chrome on win11

**Comment by JasonNS1425** [comment]
Can still reproduce this issue on Chrome win 11.
