### ISSUE TITLE
[Sign Up, Whatsapp] Authentication code is accepting characters starting with # instead of simply digits

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#2194]
## Background:
- Device / Browser (OS version): Safari on MacBook Pro(11.5.5)
- Build: staging

## Description:
When using Whatsapp during for sign up process, typing any characters after the authentication code started with # will result in successful authentication.

## Steps to reproduce:
1. In Authgear portal, choose a project with paid plans
2. Enable Phone number under Authentication > Login IDs 
3. Go to  Authentication > Verifications
4. Choose Whatsapp/ Whatsapp or SMS for Phone number verification
5. Go to the Authgear site
6. Sign up for a new account using phone number
7. Use Whatsapp for account verification, 6-digit code will be given, e.g. 123456
8. Send a whatsapp message to the given number
9. Type the verification started with # (indicating the verification code) and some other characters after the code, e.g. #123456789/ #123456sfds
10. See that authentication is successful

## Expected result:
Should block numbers after the code to prevent from guessing the 6-digit verification code.

## Screenshot:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/12539486/177303099-37583f3e-9c96-4cf9-80c2-600ebaaf159c.png">

![IMG_8244D85DBC52-1](https://user-images.githubusercontent.com/12539486/177303105-e940a828-2678-4b42-b681-2889937bffe8.jpeg)

<img width="1552" alt="image (1)" src="https://user-images.githubusercontent.com/12539486/177303170-4f970f1f-4351-4d47-b0b2-5de461c2d9a5.png">

**Comment by carmenlau** [comment]
In the current implementation, we accept 2 formats
- A message with the code only
- A message that has other text, and the code will be the 6 digit number after the `#` symbol

The latter one is for better ux, authgear will provide a default message that guide the user to go back to the app.
e.g.
> Verify +852912**** with OTP #123456
> Press send on WhatsApp then return to the App

In both 2 formats, we only accept 1 code per message so there is no extra benefit for the user to use `#` to guess the code.

**Comment by carmenlau** [comment]
Maybe we could make the matching more distinct to avoid confusion? Don't allow other characters after the 6 digit code. Only allow space or new line after `#123456`. What do you think? :)
