### ISSUE TITLE
Add support for TLS for Redis

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2291]
Reference: https://redis.uptrace.dev/guide/go-redis.html#using-tls

**Comment by carmenlau** [comment]
Checked the `redis-go` lib, seems TLS is supported already via `redis.ParseURL`. We can change the URI scheme to `rediss` to use TLS.

How we construct the redis options:
https://github.com/authgear/authgear-server/blob/001ccc601663ebd82bdddef1ef1c8c50643d020e/pkg/lib/infra/redis/pool.go#L76

How `go-redis` parse the URL: 
https://github.com/go-redis/redis/blob/cae67723092cac2cb441bc87044ab9edacb2484d/options.go#L269

I tried starting a Redis cache in azure with SSL port only and using my local authgear to connect it, using `rediss://..` works for me.

**Comment by louischan-oursky** [comment]
What if the TLS certificate is self-signed?
