### ISSUE TITLE
More robust passkey error handling

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2320]
## Scenario 1

- Create an account with passkey on another device
- Sign in the account on Chrome desktop
- Choose "This device"
- Chrome shows an error message in the modal dialog with "Your identity couldn't be verified"
- The end user has no choice but to click cancel to close the modal dialog

### Cause

Chrome does not have the passkey. And it is not smart enough to hide the "This device" option.

### Suggested solution

In /use_password page, offer some **static** help text to explain **possible** errors

## Scenario 2 (Fixed in https://github.com/authgear/authgear-server/pull/2322)

- Create an account with passkey on another device
- Sign in the account on Firefox desktop
- Firefox only supports security key so use security key
- navigator.credentials.get will be rejected with `DOMException(name="InvalidStateError", message="An attempt was made to use an object that is not, or is no longer, usable")`.

### Cause

This message could mean 2 things. The security key indeed contained the passkey in the past but it has been removed. The security key never contains the passkey, the user switches device.

### Suggested solution

Literally tell the user the 2 possible situation.

## Scenario 3 (Fixed in https://github.com/authgear/authgear-server/pull/2321)

- Sign up a new account on Chrome desktop
- Choose "Add a new Android phone" or a named device in the list
- Go through the process as instructed by the phone
- See failed message on phone, and Chrome shows an error message in the modal dialog with "Your identity couldn't be verified"
- The end user has no choice but to click cancel to close the modal dialog

### Cause

We require resident key but Android does not support it yet.

### Suggested solution

Relax [ResidentKeyRequirement](https://www.w3.org/TR/webauthn-2/#enumdef-residentkeyrequirement) to preferred

## Scenario 4

- Sign up a new account on iOS 16 with passkey
- Sign in the account
- Choose use security key instead
- See passkey not found message in the modal dialog. The system asks the user to retry
- We do not need to do anything

## Scenario 5 (Fixed in https://github.com/authgear/authgear-server/pull/2324)

- Sign up a new account on iOS 16 with passkey
- Sign in the account
- Choose use Android phone instead
- Safari throws `DOMException(name="NotAllowedError", message="Operation failed.")`

### Suggested solution

The exception is distinguishable if we also take message into account.

**Comment by louischan-oursky** [comment]
@carmenlau @fungc-io Any thoughts on addressing Scenario 1?

**Comment by carmenlau** [comment]
For scenario 1, since we cannot identify it is canceled by the user or the passkey is missing. Static help text should be the best that we can do.

**Comment by fungc-io** [comment]
Other known issues I've found, these are cases that can't be fixed by us, 
just to document it for future reference:

OS: macOS 12.5 Monterey

Browser: Chrome 104.0.5112.101
When passkey in not on device, a nearby iOS device cannot share its credential. Only Android is supported.
The iOS device will keep searching after scanning the QR code.

Browser: Safari 15.6
No option to use nearby device. Only allow store in browser or physical key

Browser: Firefox 103.0.2
No option to use nearby device nor store in browser. Only allow physical key
