### ISSUE TITLE
Redesign Admin API to avoid "identities" and "authenticators" ambiguity

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2328]
The admin API is counterintuitive that the users find it hard to manage the credentials. 

For example passkeys, biometric, login ids, third-party login, are all represented by identities, in the perception of a developers, they hardly belong to same category.

Redesign the API for easier CRUD of "identities" and "authenticators".

**Comment by louischan-oursky** [comment]
I am going to list out the potential problems of the existing API. To give more context, a simplified version of the schema is inlined here.

```graphql
type User {
  id: ID!
  isAnonymous: Boolean!
  identities(after: String, before: String, first: Int, last: Int): IdentityConnection
  authenticators(after: String, before: String, first: Int, last: Int): AuthenticatorConnection
}

type Identity {
  id: ID!
  type: IdentityType!
  claims(names: [String!]): IdentityClaims!
}

type Authenticator {
  id: ID!
  type: AuthenticatorType!
  kind: AuthenticatorKind!
  claims(names: [String!]): AuthenticatorClaims!
}
```

## The arguments of identities and authenticators do not support filtering

It is a pain point to find out all passkeys of a given user. The caller have to paginate through all the pages.

## Most primary authenticators depend on identities. They cannot be deleted individually

Password is standalone. But passkeys, OOB OTP authenticators depend on identities. Currently they can be listed and deleted individually, which will result in undefined behavior. The dependent relationship is unclear.

---

Suggestion

TODO
