### ISSUE TITLE
Custom style of command bar primary button cause collapse to miscalculate

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2348]
<img width="461" alt="186105242-9f7e4e4b-5d68-48d5-ac87-07326120262b" src="https://user-images.githubusercontent.com/15082564/186115624-355ebef7-cb99-491c-926b-a2979c067cc9.png">

**Comment by louischan-oursky** [comment]
It seems that if we specify `styles` in CommandBarPrimaryButton, the collapse does not always work.

**Comment by carmenlau** [comment]
Seems any customization via `onRender` will cause the problems.

- Remove primary button customization
<img width="837" alt="Screenshot 2022-08-23 at 11 16 47 am" src="https://user-images.githubusercontent.com/388892/186134033-06a2b523-7dff-4cdd-94a6-fa5cd092d639.png">

- Remove all customization
<img width="837" alt="Screenshot 2022-08-23 at 11 16 58 am" src="https://user-images.githubusercontent.com/388892/186134155-7a8caabf-2aee-43a5-9592-c44fa762aff7.png">

Let me check how to fix it.

**Comment by carmenlau** [comment]
Referring to the styles applied to the default command bar button, applying `whitespace: 'nowrap'` to the label help solve the miscalculation problem.

ref: https://github.com/microsoft/fluentui/blob/76ec1f86ae20b24c103d6fcdf1ddd47f43289e49/packages/react/src/components/CommandBar/CommandBar.styles.ts#L43
