### ISSUE TITLE
Investigate how to add CDN for auth UI

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2352]
- [x] Convert authgear.css to tailwind.css. authgear.css is currently an app-specific resource.
- [x] Turn avatar_placeholder into a generated assets.
- [x] Always serve the base resource. Serve app-specific resource only if it is defined. For example, authgear-light-theme.css is turned into a generated resource and thus always served. If the theme of the app has been changed, then the app-specific authgear-light-theme.css is referenced by an extra HTMLLinkElement and served.
- [x] Serve generated assets with another wildcard endpoint that does not depend on the app. This endpoint echos CORS origin. This endpoint DOES NOT check validate the HTTP host header so it is compatible with CDN.
- [x] Support `WEB_APP_CDN_HOST` environment variable.

**Comment by carmenlau** [comment]
@louischan-oursky Just noticed that we may need to return `*` for the`Access-Control-Allow-Origin` header when we serve the generated assets with CDN? Echo the request origin should not work as the requests may come from different apps.


https://github.com/authgear/authgear-server/blob/001ccc601663ebd82bdddef1ef1c8c50643d020e/pkg/lib/infra/middleware/cors_echo.go#L14

**Comment by louischan-oursky** [comment]
You're right. The cached response should be a response with `Access-Control-Allow-Origin: *` so that every app can use it.
