### ISSUE TITLE
[UI Setting] End-user app "Log in" and "Sign up" buttons do not follow primary color in dark mode

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#2366]
## Environment
- Browser: Safari, Chrom on Macbook Pro
- Server: Staging

## Description
In dark mode, the Log in / Sign up button color does not follow the Primary color in UI Settings as in light mode.

## Steps to reproduce
1. Go to UI Settings in portal
2. Select Custom color and set the primary color for both dark and light mode
3. Go to the web endpoint of the app
4. Change the device theme to dark mode
5. See the Log in / Sign up page, but the buttons color are not the primary color as in light mode

## Expected result
The  Log in / Sign up buttons should use primary color in both light and dark mode as shown in the portal preview.

## Screenshot

<img width="1440" alt="Screenshot 2022-08-24 at 8 55 56 PM" src="https://user-images.githubusercontent.com/12539486/186425070-c71c162a-7e27-4c70-8813-c8be97a6d2aa.png">

<img width="1440" alt="Screenshot 2022-08-24 at 8 56 10 PM" src="https://user-images.githubusercontent.com/12539486/186425146-728ab3cd-cf37-4618-86ea-560ff98cb286.png">

**Comment by andychow326** [comment]
@fungc-io Should the color of Log in / Sign up buttons be changed to primary?

**Comment by fungc-io** [comment]
@karinyu 
For dark mode, I think the Login/Signup buttons in white looks better than in the theme color. i.e. the real page looks better than the preview. What do you think?

**Comment by karinyu** [comment]
@fungc-io Agree.

I checked with the old design, it's using white instead of the theme color. Let's follow.

<img width="234" alt="Screenshot 2022-08-26 at 6 36 08 PM" src="https://user-images.githubusercontent.com/83946723/186886600-69ec9717-5324-40ee-a526-46edf3411ea0.png">

**Comment by joyzoursky** [comment]
@andychow326 In this case please update the "Preview Mode" on the portal instead, thanks.

@fungc-io @karinyu And the light mode should keep using primary color for the buttons in active state right?

Also notice that in light mode, the "Sign up" text looks too light now on the web site, in the preview mode it is black color, seems the preview side is correct?

**Comment by fungc-io** [comment]
@andychow326 the color of "Sign up" is correct in `demo-enterprise`. Can you check what's making it too light on `refuse-anchor-618`?

<img width="1466" alt="Screenshot 2022-08-29 at 10 47 44" src="https://user-images.githubusercontent.com/15207470/187174886-e8dd3f1d-2ce9-4002-abe9-d80654d01a4a.png">

<img width="1433" alt="Screenshot 2022-08-29 at 10 50 09" src="https://user-images.githubusercontent.com/15207470/187174909-045b1588-f15f-4f7a-84be-e2242235aaed.png">

**Comment by andychow326** [comment]
@fungc-io Currently we are using fluentui to generate theme color for us. The color of `secondary-txt` we use is `--color-text-shaded-1`. With the text color using `#212121` in `refuse-anchor-618`, the `--color-text-shaded-1` will become `#e4e4e4`. But with the text color using `#000000`, the `--color-text-shaded-1` will become `#898989`.

**Comment by fungc-io** [comment]
I see, so it's not the default colors. Let's fixed that in https://github.com/authgear/authgear-server/issues/1706
