### ISSUE TITLE
[Add User] "Unknown error" shown when add user if the app is login with passkey and no other authenticator set

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#2375]
bug/major

**Describe the bug**
After the user enable passkey but not select any authenticator, he will see "Unknown error: Parse error for Registration" when creating user.

**Authgear Version**
 - Version: staging-2022-08-24.0

**To Reproduce**
1. Log in to Admin Portal
2. Create a new project / Select a project
3. Go to Authentication > Authenticators
4. Enable passkey but not select any authenticator
5. Go to User Management > Add user
6. See "Unknown error: Parse error for Registration" shown

**Expected behavior**
1. if not allow user to use passkey without authenticator, should show error message when not selecting any authenticator, or
2. show a proper error message when adding user

**Screenshots**

https://user-images.githubusercontent.com/93981572/186871729-f7f83ca0-a535-48e1-b58f-daffb309d118.mp4

**Client Env:**
 - Device: Macbook Air
 - Browser: Chrome

**Comment by fungc-io** [comment]
Show only the info message bar under the breadcrumbs in "Add User" 

> User must be created using their own devices when passkey is the only way to login.
