### ISSUE TITLE
[Applications, Traditional Web Application] Blank page shown when clicking "Cookie Session Settings"

### ISSUE THREAD

**Issue by anthonyfhj** [authgear/authgear-server#2413]
bug/trivial

**Describe the bug**
When the user setup a traditional web application and clicks "Cookie Session Settings" on Cookie-based authentication section, he will be navigated to a blank page

**Authgear Version**
 - Version: staging-2022-09-02.0

**To Reproduce**
1. Log in to Admin Portal
2. Select a project
3. Go to Applications > Select a "Traditional Web Application" type application / Add one
4. Scroll down to Cookie-based authentication section > Click "Cookie Session Settings"
5. See blank page

**Expected behavior**
Should navigate to Cookie page

**Screenshots**

https://user-images.githubusercontent.com/93981572/189070827-be6f91e4-d8fe-42d9-9fb2-4f0bd76965b0.mov

**Client Env:**
 - Device: Chrome on MacBook Air

**Comment by fungc-io** [comment]
it is linked to `configuration/apps/advanced/session` instead of `advanced/session`
