### ISSUE TITLE
Do not auto prompt passkey dialog in signup

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2415]
Very few users know what a passkey is and they are unfamiliar with the platform passkey dialog.
To give more context to the users, the registration should be invoked by a user.

When login, keep the auto prompt because the users should be familiar with the dialog already.

**Comment by louischan-oursky** [comment]
- [ ] Improve copywriting in the prompt create passkey page
- [ ] Optimize the spacing in prompt create passkey page
