### ISSUE TITLE
Revise Widget to support extend and collapse

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2417]
- [x] Support extend and collapse in Widget
- [x] Support transition in extend/collapse
- [x] Replace existing usage of ExtendableWidget with Widget
- [x] Remove ExtendableWidget

**Comment by carmenlau** [comment]
<img width="1460" alt="screenshot_2022-09-14_at_15 28 13" src="https://user-images.githubusercontent.com/388892/190171714-abc9b23e-a296-46ca-a9f5-76559de63e9c.png">

**Comment by carmenlau** [comment]
@louischan-oursky Please take a look at PR #2439 when free.
