### ISSUE TITLE
Front-end Design for OIDC Client

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2428]
Auth UI
- Authorized apps in `/settings`
- Consent screen

Portal
- Application details
- Authorized apps in user details

**Comment by carmenlau** [comment]
The basic one should be enough. No matter whether the user click cancel or authorize, they will be redirected back to the third-party app. The error should be handled by the third-party app.

Content can reference here: https://github.com/authgear/authgear-server/blob/b8caa603967c270efc6099e4cb9989f2d510d3de/docs/specs/oidc.md#consent-screen

**Comment by fungc-io** [comment]
@carmenlau 
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=7904%3A94105

I've updated the page design in settings, frame "Authgear - signed in devices and apps" and "Authgear - signed in devices and no apps"
