### ISSUE TITLE
Update design of the create passkey screen

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2429]
- More explanation of passkey
- Better margins and alignments

**Comment by joyzoursky** [comment]
How about change to use terms like "set password" / "set passkey" instead of create?

**Comment by fungc-io** [comment]
@joyzoursky good idea!

@louischan-oursky updated design: https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=7562%3A113912
The copy is also changed from "create" to "set up"
