### ISSUE TITLE
[Login, Passkey] Users with existing passkeys can still log in with passkey though the method has been disabled

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2459]
Bug critical, reported by qa

## Background
Build: Staging
Device: Chrome, Firefox on win 11, S21 FE (Android 12), iPhone 12 mini (iOS 16), Samsung note 9 (Android 12)

## Steps
1. Log in to the admin portal and enable the passkey feature for the application
2. Return to the application and sign up for an account with passkey
3. Return to the admin portal and disable the passkey feature
4. Log out of the application, and log in with an account with added passkeys
5. See the "use passkey instead" option is shown on the "Enter Password" page and can be used to log in

## Expected behavior
Should forbid users from logging in with Passkey if that feature is disabled

## Screenshots
![image](https://user-images.githubusercontent.com/67095825/190606290-58501fe0-fe2e-46e4-8394-102df7a28056.png)

**Comment by louischan-oursky** [comment]
Actually it follows the existing behavior. For example, if a project originally has password enabled, a user signed up with password. Later on the project has changed to passwordless, the user can still sign in with password. The rationale is to prevent the user from locked account.

**Comment by JasonNS1425** [comment]
Understood, will close this issue.
