### ISSUE TITLE
Portal Authentication Configuration Screen

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#246]
- [x] Study the shape of authentication configuration
- [x] Study the UI design of authentication configuration
- [x] Review the mapping between the configuration file and the UI
- [x] Review existing designed screens and list out some potential reusable components
- [x] Implement the authentication configuration screen with all editable fields.

**Comment by axolotl0212** [comment]
Fluent UI component:

- tab -> pivot (https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot)
- toggle button / switch (https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle)
- checkbox (https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox)
- tooltip (https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip)
- text field (https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield)

Reusable component:

- consider making wrapper for components available in fluent UI to add custom style
- Widget with toggle and extend button (custom)

**Comment by louischan-oursky** [comment]
One thing about component receiving another component from props.

The best way to do this is to receive a component directly, instead of receiving a renderXXX function. The rationale behind this design is that the caller can supply a function component or a class component. The supplied function component can use hooks.

Here is an example

```typescript
interface HeaderProps {}

interface ListProps {
  // The caller can pass anything component, be it function or class.
  HeaderComponent: React.Component<HeaderProps>;
}

function List(props: ListProps) {
  const { HeaderComponent } = props;
  const headerProps = ... ;
  return (
    <>
      <HeaderComponent {...headerProps} />
      <p>Some content here </p>
    </>
  );
}
```

**Comment by axolotl0212** [comment]
Mapping between configuration file and the UI:

LoginID tab:
- {yaml file root} -> identity -> login_id
- toggle enable => login_id -> keys -> verification -> enabled
- detailed setting for each type => login_id -> types -> {TYPE_KEY}
