### ISSUE TITLE
[Android Chrome, Login] No response upon clicking "Sign in with Passkey" 

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2461]
bug major, reported by qa

## Background
Build: Staging
Device: Chrome, Firefox on win 11, S21 FE (Android 12), iPhone 12 mini (iOS 16), Samsung note 9 (Android 12)

## Steps
1. Log in to the admin portal and enable the passkey feature of the application
2. Go to the login page of that application using Android Chrome browsers
3. Click the "Sign in with Passkey" option and see no response
4. Input the account email address to proceed to the password input screen
5. Click "Use Passkey instead" and see the passkey dialog can be triggered successfully

## Expected behavior
Should trigger the passkey dialog, or show proper error messages if the current device is not supported

## Screenshots

https://user-images.githubusercontent.com/67095825/190607758-2e5ff5a2-43b5-4098-b894-3fc16f9889cc.mp4

**Comment by louischan-oursky** [comment]
Any error in console or network tab?

**Comment by JasonNS1425** [comment]
@louischan-oursky Yes, I see ``passkey.ts:173 DOMException: Use of an empty `allowCredentials` list is not supported on this device.``

**Comment by fungc-io** [comment]
Show an error message if empty `allowCredentials` list is not supported on the browser
> Sign in with passkey is not fully supported on this device. Please sign in with another method.
