### ISSUE TITLE
[Admin portal, Application] Redirect URIs input field loses focus after typing a character

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2466]
bug major, reported by qa

## Background
Build: Staging
Device: Chrome, Firefox on win 11, S21 FE (Android 12), iPhone 12 mini (iOS 16), Samsung note 9 (Android 12)

## Steps
1. Log in to the admin portal and select a project
2. Go to its application page and select any application to edit
3. Tap on the Redirect URI input field, and type any character
4. See the input field loses focus once a character has been typed

## Expected behavior
Should continue to focus on the input field

## Screenshots

https://user-images.githubusercontent.com/67095825/190618681-6d6d1c3e-10cd-4cc6-9d44-564bf63d4c11.mp4

**Comment by fungc-io** [comment]
also happens on "Post Logout Redirect URIs"

**Comment by fungc-io** [comment]
and on production too
