### ISSUE TITLE
[Admin portal, Authentication] Case Sensitive settings only applies to local part of email login IDs

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2467]
ux minor, reported by qa

## Background
Build: Staging
Device: Chrome, Firefox on win 11, S21 FE (Android 12), iPhone 12 mini (iOS 16), Samsung note 9 (Android 12)

## Steps
1. Log in to the admin portal and select a project
2. Go to the Authentication > Login IDs page and enable the Case Sensitive option for the email address 
3. Go to the application login page
4. Sign in using email addresses with different case sensitivities
5. See the email addresses with local/domain part in different case sensitivities are rejected/accepted

e.g. given address a@b.com, A@b.com is rejected but a@B.COM is accepted

## Expected behavior
The case sensitivity option should be applied to the full email address (to be clarified, or does the email address login ID require case sensitivity constraint?)

## Screenshots

https://user-images.githubusercontent.com/67095825/190621479-eaf6b146-99ef-4681-be83-789259d1360f.mp4

**Comment by louischan-oursky** [comment]
Email address is `local-part "@" domain` (https://www.rfc-editor.org/rfc/rfc5322#section-3.4.1)
Domain is always case insensitive, as defined by this RFC (https://datatracker.ietf.org/doc/html/rfc4343#section-2)
