### ISSUE TITLE
[Login, Passkey] Passkey dialog is triggered automatically though the "use passkey instead" option is not clicked

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2468]
ux minor, reported by qa

## Background
Build: Staging
Device: Chrome, Firefox on win 11, S21 FE (Android 12), iPhone 12 mini (iOS 16), Samsung note 9 (Android 12)

## Steps
1. Go to the login page of an application that has enabled the passkey feature
2. Sign in with an email address/username that has added passkeys
3. See the Passkey dialog is triggered when entering the password input screen, though the "Use passkey instead" option has not been clicked

## Expected behavior
Should not trigger the passkey dialog unless the user has clicked the "use passkey instead" option (to be clarified)

## Screenshots

https://user-images.githubusercontent.com/67095825/190622482-8d31ee2f-9eb6-4a6c-b7dd-5020ed820b53.mp4

**Comment by fungc-io** [comment]
It is auto-prompted in login if the user have created passkeys before. 
So the user can login immediately, saving some clicks

**Comment by JasonNS1425** [comment]
I just find the behavior confusing as there is already a "use passkey instead" option at the bottom... let me close this issue first as it is confirmed to be expected

**Comment by fungc-io** [comment]
agree it's a bit weird on desktop indeed. on mobile the dialog should be blocking the screen behind already, so they will only see the button after they dismiss the dialog.
