### ISSUE TITLE
[Admin portal, Single Sign-On] Some WeChat config fields are pushed out of the visible area when both client ID and account ID are in error state

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2476]
ui must, reported by qa

## Background
Build: Staging
Device: Chrome, Firefox on win 11, S21 FE (Android 12), iPhone 12 mini (iOS 16), Samsung note 9 (Android 12)

## Steps
1. Log in to the admin portal and select any project
2. Go to the Single Sign-On page and Enable the WeChat sign-on option
3. Without filling in the client ID and account ID, click save
4. See part of the WeChat config fields are pushed out of the visible area

## Expected behavior
Should show all the fields fully

## Screenshots
![image](https://user-images.githubusercontent.com/67095825/190635330-9c85de64-9f99-49e2-a5d0-ee2d0311e959.png)

**Comment by andychow326** [comment]
Mentioned in https://github.com/authgear/authgear-server/issues/2417#issuecomment-1246792203 and fixed
