### ISSUE TITLE
Guide the user where to change the wallet account

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2490]
After clicking the "MetaMask" button,
It shows my active current account in MetaMask
<img width="522" alt="image" src="https://user-images.githubusercontent.com/15207470/191784292-bf7c07c8-7379-445d-a621-2c50684a3ace.png">

To use another account, I must open the metamask window manually to change it there,
~Can we add a button for changing the account and the corresponding metamask UI would show up?~

~Ideally:~
<img width="444" alt="image" src="https://user-images.githubusercontent.com/15207470/191790337-915a2940-1ef2-410f-9c02-dd00df2121eb.png">

---

After discussion off the thread, we decided to follow the convention which account is changed in the MetaMask Extension. 
Instead of adding the button, we will add a text to tell the user how to change account.

**Comment by hochiw** [comment]
We thought that the convention would be to change it manually in the metamask extension, as adding the change account button would disconnect the current account and prompt to reconnect, which is a workaround to begin with. But yes, we can add it

**Comment by louischan-oursky** [comment]
So it is possible to open the MetaMask extension programmatically?

**Comment by hochiw** [comment]
https://github.com/authgear/authgear-server/blob/16cc924922962f933efe4ba89f1e4c9b643da3f0/authui/src/web3.ts#L244-L268

the way we do it is to request permission from no account, and that would essentially 'disconnect' the wallet as it overwrites the list of accounts we have requested before. Then we can prompt the user to connect to their wallet as if they were never connected before

**Comment by andychow326** [comment]
@fungc-io As per our discussion, it might be better to show in hint text (to show the user to change their account through MetaMask) instead of using button, how is the design of the hint should be?

**Comment by fungc-io** [comment]
@andychow326 
Thank you!
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=7385%3A113252
