### ISSUE TITLE
[ETH auth] MISC UI updates needed in AuthUI and Admin Portal

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#2499]
## Background:
- Device / Browser (OS version): Chrome on Mac
- Build: Version tag 2022-09-20.0

## Description:
AuthUI:
In AuthUI settings, it says “There are the methods to sign in your account” but as ETH auth will disable other traditional auth method, this line is confusing.

Admin Portal:
In Admin Portal, User Management, Identities, "Add Identities" (disabled) button is still present, whereas it doesn't exist in the Figma design.

## Steps to reproduce:
AuthUI:
0. Use an app with ETH enabled.
1. Go to AuthUI, Sign in with a user that has ETH setup
2. Go to Settings.
3. Under Login info, See “There are the methods to sign in your account”.

Admin Portal:
0. Use an app with ETH enabled.
1. Go to Admin Portal, User Management, 
2. Select a user
3. Go to Identities tab
4. See "Add Identities" button still exist.

## Expected result:
In AuthUI settings, update the string for “There are the methods to sign in your account” when ETH is enabled.

In Admin Portal, Identities tab, remove "Add Identities" button as in Figma design when ETH is enabled.

## Screenshot:
AuthUI:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/4337525/192245214-226a7c38-9266-4437-9223-cb97dc9a3865.png">

Admin Portal:
Current:
![image](https://user-images.githubusercontent.com/4337525/192259560-e7c3cfbb-5199-44aa-ac23-e913ad6bd23d.png)

Figma design:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/4337525/192244654-ba366d0f-9f4e-49e6-8b71-136997cfcf60.png">

**Comment by fungc-io** [comment]
Todo: 

- remove the H2 "Login info"
- Do not pluralize if # of method = 1 (`This is the method to sign in to your account`)
p.s. Please fix grammar for the plural version too, it should be `sign in to your account`, "to" is missing

https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=8104%3A92844

<img width="810" alt="image" src="https://user-images.githubusercontent.com/15207470/195055642-162c11a6-1683-4563-bb2e-3fae2f647f1f.png">


@carmenlau can you help fix this issue? 🙏

**Comment by carmenlau** [comment]
To make it consistent with the other components, I adjust the padding a bit and keep the word **account** in lower case.

<img width="703" alt="Screenshot 2022-10-11 at 11 45 47 am" src="https://user-images.githubusercontent.com/388892/195070319-355a7e06-d459-441c-9596-6c2a5c6f9c45.png">

**Comment by fungc-io** [comment]
@hochiw
can you help remove the "Add Identity" button in "User Management > User Details > Identities" when SIWE is on?
