### ISSUE TITLE
Cannot set empty "Terms" and "Privacy Policy" links

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2500]
The "Terms" and "Privacy Policy" links are default set to be those of Authgear
It is very hard to remove them from the signup/login page.

For end-users, it should be as easy as setting the input empty in the "UI Settings" in the Portal.

Changes:

1. Fix the bug where "Terms" and "Privacy Policy" links cannot be set to have only one.
> - By registering, you agree to our Terms of Service and Privacy Policy.
> - By registering, you agree to our Terms of Service.
> - By registering, you agree to our Privacy Policy.
> - (none)

2. In the UI Settings in Portal, the default values of the links for new projects should be `https://www.authgear.com/terms` and `https://www.authgear.com/data-privacy` respectively.
For older projects, **migrate** the unset values to `https://www.authgear.com/terms` and `https://www.authgear.com/data-privacy`

3. The default localization.json should have these values set as empty. So when the user leave the input empty in UI Settings, the links would not be shown.

**Comment by louischan-oursky** [comment]
- [ ] When creating a new app, set
  - `"privacy-policy-link": "https://www.authgear.com/data-privacy"`
  - `"terms-of-service-link": "https://www.authgear.com/terms"`
- [ ] Update all builtin translation.json to set `"privacy-policy-link"` and `"terms-of-service-link"` to an empty string
- [ ] Update `toc-pp-footer` to use `select` to render 4 variants. You may need to introduce `__toc_pp_footer.html` to reduce boilderplate
- [ ] Write migration
