### ISSUE TITLE
[Ethereum & NFT, Login IDs] Confusing error message is shown upon enabling login IDs when the Ethereum login method is activated

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2510]
ux major, reported by qa

Build: Staging-29Sep2022
Device: Chrome, Firefox, Edge on win 11

Steps:
1. Log in to the admin portal and select any project space
2. Go to Authentication > Ethereum & NFT and toggle on the ETH login method
3. Go to the Login ID tab and toggle on any login ID
4. Save the changes and see the "you must enable at least 1 login ID to use passkey" error is shown

Expected behavior:
Should disable the ETH login and re-enable the selected login ID method, or show a clearer error message like "you must disable the ETH login method before re-enabling login ID" etc.

Screenshots:

https://user-images.githubusercontent.com/67095825/193020237-6fada2e5-938e-4439-aa1b-8c17b9403d17.mp4

**Comment by hochiw** [comment]
@fungc-io Shall we disable the settings on login id, biometric and anonymous user pages and add a reminder to ask the user to disable SIWE before they can change the settings? cc @louischan-oursky

**Comment by fungc-io** [comment]
@hochiw 

Agree, they should be reminded to manually disable the SIWE first.

**Comment by louischan-oursky** [comment]
Since I am working on the authentication settings, let me do this.
