### ISSUE TITLE
[Ethereum & NFT] Cannot recognize some ERC-721 standard contract addresses of Goerli chain

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2512]
bug major, reported by qa

Build: Staging-29Sep2022
Device: Chrome, Firefox, Edge on win 11

Steps:
1. Log in to the admin portal and select any ETH login-enabled project space
2. Go to Authentication > Ethereum & NFT
3. Add the below testing ERC-721 standard NFT contract address to the NFT collection
4. See the "this NFT type is not yet supported" error

Expected behavior:
ERC-721 standard contract addresses should be supported

Screenshots:

https://user-images.githubusercontent.com/67095825/193021649-a2233185-6313-4afb-b4df-91206836b787.mp4

testing ERC-721 standard NFT:
- https://testnets.opensea.io/assets/goerli/0xcdb683b4aa11e1981c4ad2d7a8a6d9b42ba973ae/0
- https://testnets.opensea.io/assets/goerli/0x3ca08ce6217863fd936465cae7dc98ed2ccbc27c/7
- https://testnets.opensea.io/assets/goerli/0xed6e212b65a5e04315a20d16c0177d3a665d8ab1/1

**Comment by hochiw** [comment]
The first two I will need to follow up with Alchemy API, the third one is because the contract is not enumerable, i.e. no total supply, @fungc-io see how we want to handle contracts without total supply?

**Comment by hochiw** [comment]
Seems all of the sample contracts provided above can be recognized now
