### ISSUE TITLE
[Ethereum & NFT, Login] Incorrect alignment of the MetaMask icon on the "Install Wallet" screen

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2513]
ui must, reported by qa

Build: Staging-29Sep2022
Device: Chrome, Firefox, Edge on win 11

Steps:
1. Uninstall the MetaMask extension of the using browser (if any)
2. Go to any ETH login-enabled sign-in portal
3. Continue with MetaMask to proceed to the Install Wallet screen
4. See the Install MetaMask icon of the continue button is not left-aligned as shown in the design

Expected behavior:
Should follow the design and left-align the MetaMask icon

Screenshots:
![image](https://user-images.githubusercontent.com/67095825/193023336-344964ae-ebf0-493d-aa77-8bfcf5596d04.png)
![image](https://user-images.githubusercontent.com/67095825/193023383-f6dccb5e-ea05-44c9-9390-d3dd190d8c1c.png)

**Comment by hochiw** [comment]
Handled via https://github.com/authgear/authgear-server/pull/2525
