### ISSUE TITLE
[Login, 2FA, Passkey] Users can skip the mandatory 2FA setup process if they log in by passkey

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2515]
bug major, reported by qa

Build: Staging-29Sep2022
Device: Chrome, Firefox, Edge on win 11

Steps:
1. Visit the sign-in portal of any project that has enabled both passkey and mandatory 2FA login
2. Log in to an account that has added passkey but has not set 2FA yet
3. Sign in with the passkey and see no 2FA setup process is shown
4. Sign in with the password and see the 2FA setup process is shown

Expected behavior:
Should require all users without 2FA to enter the setup process upon login

Screenshots:

https://user-images.githubusercontent.com/67095825/193025993-c187178a-92a5-4263-942c-70717ad05364.mp4

**Comment by chpapa** [comment]
@joyzoursky @JasonNS1425 It was a decision to skip 2FA when login with Passkey, we could revisit it when Passkeys getting more popular and use cases.
