### ISSUE TITLE
Manage authorized app list in settings

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#2526]

**Comment by fungc-io** [comment]
@carmenlau 
The button in the `/settings` home page will read
```
## Signed in Devices and Apps

Manage your authenticated devices and apps
```

**Comment by fungc-io** [comment]
@carmenlau 
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=7904%3A94357
design is updated to avoid the ambiguous "Terminate all other sessions"
