### ISSUE TITLE
Add a link to explorer to show the latest blocks

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2528]
When we click on the details of a collection, we show the synced block height. But the progress is not trivial to the user. I suggest we add a link to the explorer which shows the latest blocks. Then the user can get a sense of the progress.

```
Block Height
30575782 / [Latest Block Height](https://polygonscan.com/blocks)
(i) Syncing chain. It will take few minutes.
```

@fungc-io Thoughts?

**Comment by fungc-io** [comment]
ok, good idea
