### ISSUE TITLE
Handle authgear support for ERC-1155 collections

### ISSUE THREAD

**Issue by hochiw** [authgear/authgear-server#2530]
- [ ] Handle large collection error 
- [ ] Update api call param to support passing token id to watch collection api
- [ ] Update UI to handle tokenId field

**Comment by fungc-io** [comment]
@hochiw @louischan-oursky 
Please check the updated design here: https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=8021%3A96689

**Comment by hochiw** [comment]
@fungc-io oh sorry I didn't clarify enough, one 1155 token can be divided into multiple pieces. For example if a 1155 contract has 10 tokens and each of them is divided into 10000 pieces we would have 100000 records on db if we track all 10 of them. So we might want to lower the number of tokens we can add for now

**Comment by hochiw** [comment]
yeah I think so
