### ISSUE TITLE
Test passkey implementation on Android and Chrome

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2573]
https://android-developers.googleblog.com/2022/10/bringing-passkeys-to-android-and-chrome.html
Passkey is now available on Google Play Services Beta and Chrome Canary.

We should check if Authgear works as expected or any changes are needed.

**Comment by louischan-oursky** [comment]
Given the following conditions

- Chrome Canary as of the time of this writing (2022-10-24)
- Turned on Google Sync with at least passwords checked. (other items can be unchecked)

---

The "Sign in with Passkey" at `/login` works seamlessly.

---

`DOMException(code=11, name="InvalidStateError", message="The user attempted to register an authenticator that contains one of the credentials already registered with the relying party.")` is not handled when adding a new passkey on a device that already has an associated passkey.

**Comment by louischan-oursky** [comment]
Autofill seems not working on iOS 16.1.
