### ISSUE TITLE
Support embed Typescript instead of Webhook

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#2581]
**Problem**
Webhook create a lot more frictions for developers when they need to customize some simple behaviour of Authgear

(e.g. Embed custom claims in Access Tokens)

**Appetite**
6 weeks

**Solution**
Embed a builtin Deno (or a like), and have the Portal to support writing Javascript to customize those behaviour

- [x] https://github.com/authgear/authgear-server/issues/2644
- [x] #2646 
- [x] https://github.com/authgear/authgear-server/issues/2665
- [x] https://github.com/authgear/authgear-server/issues/2670
- [x] https://github.com/authgear/authgear-server/issues/2677
- [x] authgear/authgear-server#2630
- [x] https://github.com/authgear/authgear-server/issues/2710
- [x] authgear/docs#125

**Rabbit holes**
For first version, we should try to make it stateless and an extension to webhook -- we provide everything we could as input to the function like webhook, and take a return values.

Later on we can add more libraries supported which have practical use case (e.g. calling external APIs for permissions etc)

**No-goes**
Functionality or use cases we intentionally aren’t covering to fit the appetite

**Comment by fungc-io** [comment]
Design Required for adding TS hook handler using the Portal

**Current Webhook page:**
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/15207470/207635811-ac16cafe-1750-422b-985f-efb93bb4a6bc.png">

**Event Handlers:**

<img width="775" alt="image" src="https://user-images.githubusercontent.com/15207470/207636022-a76934da-b69b-4fb9-a496-a90f28e80472.png">

- For a event, user can choose to handle with "Webhook" or "TypeScript/JavaScript"
- If "Webhook", user should enter a URL endpoint
- If TypeScript/JavaScript, user can use a script editor to write the script

There are currently 4 types of blocking events,
- User Pre-create
- User Profile Pre-update
- User Deletion Pre-Schedule
- JWT Session Pre-create

All non-blocking events will be handled by the webhook or TS/JS runner,
Therefore no need to select the specific event in the portal.
However a design is still needed to let the user config TS/JS runner.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/15207470/207638147-4b1dd6b1-97d9-4965-8cfb-e98d9fe37ed3.png">


**Learn more from the draft doc:**
 https://docs.authgear.com/~/revisions/Zg7AaLL0U3HXYWc0H2F9/integrate/events-hooks

**Temporary design implemented for reference:**

![SCR-20221214-owi](https://user-images.githubusercontent.com/15207470/207638467-0823c84e-3819-427e-9469-96f16f342083.png)

**Comment by fungc-io** [comment]
@louischan-oursky 
Design update in Figma:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=8593%3A94796&t=VrK3FtMjslf1xEzd-3

**Comment by louischan-oursky** [comment]
- Add a dialog to confirm changing blocking event, as the script will be overwritten on change.
