### ISSUE TITLE
[NFT] "Unknown error: BadRequest" is shown when adding NFT collection that might be unsupported

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#2584]
## App Config
- Testing app: pipe-flash-309 - https://pipe-flash-309.authgear-staging.com
- Login method: Login with Etherum
- Network: Etherum Goerli
- Testing collection contract address: 0xf4910c763ed4e47a585e2d34baa9a4b611ae448c
- Contract address retrieved from: https://testnets.opensea.io/assets/goerli/0xf4910c763ed4e47a585e2d34baa9a4b611ae448c/77619005451484494259801483225203211997713331154527329161892606647731232964609

## Description
When trying to add this NFT collection contract address and click save, "Unknown error: BadRequest" is shown. It is expected to show clear error message if the address is invalid or if the collection is unsupported.

## Screenshot
<img width="1515" alt="Screenshot 2022-10-16 at 10 44 37 PM" src="https://user-images.githubusercontent.com/12539486/196042072-2099a4bf-90b6-4ff2-b59d-a191537509d4.png">

**Comment by hochiw** [comment]
Seems alchemy api key is expired on staging, will update

**Comment by hochiw** [comment]
Seems ok now
