### ISSUE TITLE
[Passkey, Android] "Sign in with Passkey" not working without typing identity

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#2589]
## Background:
Device / Browser (OS version): Pixel 5a Android 13, Google Play services 22.41.13 (190408-480714934) beta, Chrome Canary 109.0.5363.0
Build: Version tag 2022-09-20.0

## Description:
Sign in with Passkey not working without typing identity

## Steps to reproduce:
1. Go to AuthUI of an app which has passkey enabled
2. Login and add passkey to a user
3. Logout
4. Go back to AuthUI
5. Click 'Sign in with Passkey'
6. See error prompt Device not supported

## Expected result:
Should be able Sign in with Passkey without typing identity, let user choose from saved passkey.

## Screenshot:
After Clicking Sign in with Passkey
![image](https://user-images.githubusercontent.com/4337525/196125166-5f920c5f-cf0b-407d-ba23-527d490e9d6e.png)

Expected from Google:
<img width="306" alt="Screenshot 2022-10-17 at 4 57 24 PM" src="https://user-images.githubusercontent.com/4337525/196140214-efef792c-54ee-4497-bf44-a3e1b69434c1.png">

<img width="300" alt="Screenshot 2022-10-17 at 4 57 38 PM" src="https://user-images.githubusercontent.com/4337525/196140237-255cbb13-cc55-4d51-8433-ee2701a6195c.png">

**Comment by fungc-io** [comment]
@louischan-oursky I think the error is shown when discoverable keys are not available? 
which means it is because of lacking support in the beta android/canary chrome, and should be automatically supported once their implementation is completed.

**Comment by louischan-oursky** [comment]
Did you turn on Sync in Chrome Canary? Specifically you need to turn on Sync for passwords, since [the implementation relies on Google Password Manager](https://android-developers.googleblog.com/2022/10/bringing-passkeys-to-android-and-chrome.html) to sync discoverable passkeys.

**Comment by stanleylhs** [comment]
Opps, sorry, no I didn't have sync on
