### ISSUE TITLE
Generate GraphQL endpoint documentation

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#259]
- [ ] Research how generate schema reference on schemas.
- [ ] Deploy the generated schema reference on every commit.

**Comment by kiootic** [comment]
It seems GraphQL doc generator does not provide much value: GraphQL schema is already quite readable by layman, so there is not much value it doing this. Most documentation generator merely adds links to referenced types.

Currently, the GraphQL schema are exported and committed in repo:
- Admin API: https://github.com/authgear/authgear-server/blob/master/portal/src/graphql/adminapi/schema.graphql
- Portal API: https://github.com/authgear/authgear-server/blob/master/portal/src/graphql/portal/schema.graphql

@chpapa Please let me know if you need any help in reading the schema.

**Comment by chpapa** [comment]
@kiootic thanks, please mention me when there is a PR to make changes to the admin api schema? (Portal one is not public API so I guess i won't look into it)

I guess I need to take some time to learn the graphQL schema @@

**Comment by chpapa** [comment]
However on the longer term, shall we still have some sort of public documentation? Or the norm of GraphQL API is people just show an explorer or something..

**Comment by kiootic** [comment]
As far as I know, providing a playground/explorer is common for GraphQL APIs, since developer can embed documentation of individual types/fields in GraphQL schema. Most documentation are just re-stating the documentation in the schema, with cross-reference links between symbols.

**Comment by chpapa** [comment]
Thanks. I just did a quick read on the AdminAPI GraphQL. Forgive me for never used GraphQL before and only have some brief impression, my only quick question:

There are `AuthenticatorConnection` and `AuthenticatorEdge`, is it common to have the Connection and Edge the same name? My very limited GraphQL understanding was, it is like "User -> FriendsConnection -> UserEdge", it reads a bit werid...

Should it be called at least in plural form `AuthenticatorsConnection` instead? Or even better `UserAuthenticatorsConnection`? What is the best practices here?

(Similar applies to `IdentityConnection` vs `IdentitiesConnection` or `UserIdentitiesConnection`)

What is the "standard practices" here? Or at least how Facebook does it on their own GraphQL endpoint?

**Comment by louischan-oursky** [comment]
> There are AuthenticatorConnection and AuthenticatorEdge, is it common to have the Connection and Edge the same name? My very limited GraphQL understanding was, it is like "User -> FriendsConnection -> UserEdge", it reads a bit werid...

The Connection and Edge convention is following [Relay convention](https://relay.dev/graphql/connections.htm), which is also adopted by [Github GraphQL API](https://docs.github.com/en/graphql/reference/objects#marketplacelistingconnection). That convention sets a standard for exposing a paginated API.

> Should it be called at least in plural form AuthenticatorsConnection instead? Or even better UserAuthenticatorsConnection? What is the best practices here?

It seems that the common practice is to use singular form, e.g. [Github GraphQL API](https://docs.github.com/en/graphql/reference/objects#marketplacelistingconnection)

Since we do not have a strong reason to prefix `Identity` with `User` to make it `UserIdentity`, the connection type and edge type of it does not start with the prefix `User`.

> What is the "standard practices" here? Or at least how Facebook does it on their own GraphQL endpoint?

Though GraphQL was created and popularized by Facebook, they do not expose their GraphQL endpoint to the public. They do have a Graph API (not to be confused with GraphQL API) which is a REST API.

In addition to [the core GraphQL spec](https://spec.graphql.org/June2018/), they also published [Relay convention](https://relay.dev/graphql/connections.htm). We follow the two when inventing our own GraphQL schema.
