### ISSUE TITLE
[Passkey] 'Something went wrong' shown when user choose authenticate with USB and idle browser for long time

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#2591]
## Background
Device: Google Chrome on Mac
Build: Staging
Testing project: https://qaenterprise.authgear-staging.com/

## Description
If user try to authenticate with USB, and idle the browser for a while, he will see 'Something went wrong - The request timed out' error

## Steps
1. Sign up in the testing project by passkey on device
2. Login with the passkey
3. In user setting, Add passkey with USB device
4. Idle the browser for some time
5. See 'Something went wrong - The request timed out' error

## Expected result
Suggest to show clearer error message like 'The request timed out - Please try connect USB again'

## Screenshot

<img width="1440" alt="Screenshot 2022-10-18 at 4 19 53 PM" src="https://user-images.githubusercontent.com/69806274/196376171-9d001936-fd02-4482-ac86-ee2d36a309bb.png">

**Comment by louischan-oursky** [comment]
That error message is not controllable :(

**Comment by joyzoursky** [comment]
This error should be come from Chrome
