### ISSUE TITLE
[Question, Passkey] User is still asked to verify identity after passkey is disabled 

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#2592]
## Background
Device: Google Chrome on Mac
Build: Staging
Testing project: https://qaenterprise.authgear-staging.com/
Testing username: coffee

## Description
If an user signed up with passkey then the project's admin disabled it, the user is still asked to verify identity even he sign in to the project and created password

## Steps
1. Set project's login method to 'Username with passkey enabled'
2. Sign up with username and passkey in project endpoint
3. Project admin disable passkey
4. User open endpoint again and sign in with username
5. User set up password for login
6. User re-open endpoint and login with username
7. User is asked to verify identity before entering password

## Expected result
Should not ask user to verify identity if passkey is disabled?

## Screenshot

https://user-images.githubusercontent.com/69806274/196384650-6ea71edf-4e0c-4b76-aacd-d49dc9139aa1.mov

**Comment by fungc-io** [comment]
same issue as:
https://github.com/authgear/authgear-server/issues/2459

We will not remove end-users login methods when it is disabled. Because that may lock the users out because they cannot use the existing method to login next time.
