### ISSUE TITLE
Custom Attributes + Claims (Primary)

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#260]
## Metadata Feature Completion

Developer users can add custom attributes as key/value to each user.

We will need the following changes:

- Configuration: Setting the schema of custom attributes (Type, Type-Attribute, Mutatable by User)
- OAuth Endpoints: Return some Standard OIDC Attributes in Claims
- Fill in SSO scope to Standard OIDC Attributes, and sync mode = 'none' vs 'first login' vs 'force'
- Admin API: CRUD of custom attributes of User
- Management Portal: User Details, list out all custom attributes, and edit of custom attributes
- Management Portal: Configuration of the schema of custom attributes

### 2nd Release / Nice to have
- Allow developer user to change, which custom attributes to return in Claims
- Allow developer to configure, which attributes are hidden/read-only/editable in Auth UI Setting page, or via Admin API 
- More type of the custom attributes, for some auto-validation

### Future
- Allow developer to fine tune permission of each custom attributes, which app can access what custom attributes

## Claims
Currently, Authgear doesn't return much information at the claim, main reason is we support multiple identities and there are no way to choose the primary email/phone.

We should allow end user to set it in Auth UI Setting page.

**Comment by kiootic** [comment]
Some notes:
- the term 'labels' is borrowed from Kubernetes.
- they are solely used by the developer, and is not read by Authgear.
- it is planned that authorization mechanism in portal would be implemented using labels.

**Comment by chpapa** [comment]
> they are solely used by the developer, and is not read by Authgear.
> it is planned that authorization mechanism in portal would be implemented using labels.
Actually it smell like we actually shouldn't overload custom attributes feature implemented by labels?

**Comment by kiootic** [comment]
> Actually it smell like we actually shouldn't overload custom attributes feature implemented by labels?

Portal should considered an independent component from the core Authgear (i.e. main server, resolver server, admin APIs). Therefore there're no contradictions between the two points you quoted.

Consider a Role-Based Access Control plugin implemented on top of Authgear: it may read the role labels attached to a particular user in authorization process. This kind of plugin may be developed by us in future, but it would not be considered as a core Authgear component.

**Comment by chpapa** [comment]
But custom attributes will be a core Authgear feature, and I'm worried it would be not flexible enough... say if our next feature is provide end-to-end encrypted custom attributes, or if we someone want to "search" the custom attributes...?

**Comment by kiootic** [comment]
I have some questions about the two use cases you mentioned:
- E2E encrypted custom attributes: As far as I know, E2E encryption means the plaintext data should not leave the device. I don't see how Authgear can assist in this, except storing the ciphertext in custom attributes/deriving part of E2E key.
- Searching custom attributes: I suppose some kind of search engine like ElasticSearch would be needed, which I don't think it is Authgear's responsibility to host this component.

I found myself confused by the purpose of custom attributes. If custom attributes are supposed to be custom claims defined by developers, I think just calling them 'claims' would be suitable. In that case, it seems similar enough that labels can be replaced with claims. Otherwise, do you prefer developers to store all user data directly in custom attributes, using it as an ad-hoc database?

**Comment by chpapa** [comment]
> E2E encrypted custom attributes: As far as I know, E2E encryption means the plaintext data should not leave the device. I don't see how Authgear can assist in this, except storing the ciphertext in custom attributes/deriving part of E2E key.

Yes basically it is to store the ciphertext in custom attributes, and also provide some key management services to make key exchange between user's devices easy.

> Searching custom attributes: I suppose some kind of search engine like ElasticSearch would be needed, which I don't think it is Authgear's responsibility to host this component.

Again, just like the "ask developer users to build their own cache layer" case, I hardly imagine we can ask our developer users to, say: store custom attributes on Authgear, but if you want to query it, build your own elastic search server. They would expect there is an API just for that.

Lack of the feature is acceptable in "short" term... but it really depends on how many users would want that...

> I found myself confused by the purpose of custom attributes. If custom attributes are supposed to be custom claims defined by developers, I think just calling them 'claims' would be suitable. In that case, it seems similar enough that labels can be replaced with claims. Otherwise, do you prefer developers to store all user data directly in custom attributes, using it as an ad-hoc database?

Ideally, we don't want developer users to store anything other than identity claims with Authgear. However the real-world experience was everyone expects they could at least store the user profile with Auth Server, aka -- user profile might or might not appear in auth claims (could be just accessible via AdminAPI some time); So I think we could imagine people abuse it to a certain extend, maybe think of it like an adhoc key/value DB store is easier...

(Hence I wrote this as bonus above: "- Allow developer user to change, which custom attributes to return in Claims, which attributes are hidden/read-only/editable in Auth UI Setting page via Admin API and/or configurations")

Plus given the previous experience, I actually thought maybe there is an opportunity -- if we can just let developer user to store all Personal Information of the user as custom attributes (they would anyway), we can provide features like E2EE encryption / time deletion to enable developer build securer apps / easier to comply with things like GDPR.

**Comment by chpapa** [comment]
We sort of have basic support.
