### ISSUE TITLE
[Billing, Social / Enterprise Login] Missing Upgrade Prompt for Enterprise Login

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#2689]
## Background:
Device / Browser (OS version): Chrome on Mac
Build: Version tag 2022-11-14.0

## Description:
Enterprise Login is greyed out, but there is no upgrade prompt to let use know how to unlock them.

## Steps:

1. Login to app go to projects with free or Developer or Starup plan.
2. Navigate to Authentication, Social / Enterprise Login
3. See AD related option greyed out but no prompt for upgrade.

## Expected:
Should have a little tool tip telling user to upgrade like other premium features.

## Screenshot:
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/4337525/203039682-126ba7c2-0db3-460d-864b-fcaf1387e951.png">

**Comment by joyzoursky** [comment]
seems they are not grey in free plan now
