### ISSUE TITLE
Allow to set primary email / phone number

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#271]
We want to allow the user to set a email or phone number as primary. The primary email and the primary phone number are then being used as the `email` and `phone_number` claim in the UserInfo.

An identity can have email and phone number at the same time. Therefore the minimal unit of primary assignment is a claim of an identity, not just an identity itself. Therefore, we do not introduce primary identity.

## Proposed database schema change

- Add column `primary_email_reference` to `_auth_user`. It is a nullable foreign key reference to `_auth_identity`. It should be populated at user creation if possible. Set it to null when the corresponding identity is about to be deleted.
- Add column `primary_phone_reference` to `_auth_user`. it is a nullable foreign key reference to `_auth_identity`. It should be populated at user creation if possible. Set it to null when the corresponding identity is about to be deleted.

## Adjust user info

Adjust user info to include `email`, `email_verified`, `phone_number`, `phone_number_verified` if `primary_email_reference` or `primary_phone_reference` is non-null.

## UI design

The UI should show individual claim (email or phone) of an identity. Add a button to set a specific claim as primary.

**Comment by fungc-io** [comment]
Completed in User Profile #1510
