### ISSUE TITLE
[Email verification] "Click to resend" in error message no response during cool down time

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#2729]
## Background
- Environment: Staging
- Testing app: qa-app
- Testing account: new sign up

## Description
When user enters an invalid code on email verification screen, an error message will be shown on top bar with "Click to resend" button. The button will be no response during cool down time.

## Steps to reproduce
1. Go to an app endpoint
2. Sign up
3. Fill in email, click Next to email verification screen
4. Fill in a wrong code, see error message on top
5. Click "Click to resend" in the error message
6. No response
7. Wait until the Resend button enables (cool down time below Next button)
8. Click "Click to resend" in the error message again
9. Success

## Expected result
Suggest not showing the "Click to resend" button in the error bar to avoid confusion during cool down time, as user can click the lower resend button to resend.

Or hide the button, or disable the button with timer shown until the cool down time ends.

## Screenshot
<img width="1074" alt="Screenshot 2022-12-16 at 2 04 37 PM" src="https://user-images.githubusercontent.com/12539486/208033758-d15d3db4-f6da-45b7-b2ff-66e61de2d63b.png">

**Comment by joyzoursky** [comment]
Retest pass.

During cooldown time, the click to resend button will be disabled now. And after cooldown time it will be enabled automatically.

<img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/b30cbc75-d4b2-4937-b74d-adebcc95487c" /> <img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/4dbd968d-a4a7-4065-a7cf-df1ed3f095f6" />

**Comment by stanleylhs** [comment]
@fungc-io I have ran into a similar issue,

For email magic link, when the cool down time 60s is still in effect, say if I login logout login, 3 actions within 1 min, the second magic link won't be sent with no prompt to user, will require pressing "Resend" manually. Is this expected?

**Comment by fungc-io** [comment]
@stanleylhs 
Yes this is expected, as we don't want the user to send too many emails from our service.
It's ok if you see the countdown number.

**Comment by stanleylhs** [comment]
I didn't see the count down number tho. I think the end user need some kind
of prompt.

**Comment by fungc-io** [comment]
@stanleylhs 🤔 that sounds like a UX issue. Can you help create an issue for that?

**Comment by joyzoursky** [comment]
@fungc-io stanley is part-time helper and not always here, we can either open ourselves or wait for his next timeslot (maybe next monday).

**Comment by stanleylhs** [comment]
@joyzoursky @fungc-io I can open next Monday 🙇🏽‍♀️
