### ISSUE TITLE
[Anonymization] User Anonymization

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#2731]
## Implementations

- Add database migration to add column `is_anonymized` and `anonymized_at` to the `_auth_user` table.
    - ref:
        - https://github.com/authgear/authgear-server#database-setup
        - https://github.com/authgear/authgear-server/tree/master/migrations/authgear
- Audit log and hook
    - blocking event
        - `user.pre_schedule_anonymization`
            - https://github.com/authgear/authgear-server/blob/master/pkg/api/event/blocking/user_pre_schedule_deletion.go
    - non-blocking events
        - `user.anonymized`
            - https://github.com/authgear/authgear-server/blob/master/pkg/api/event/nonblocking/user_deleted.go
        - `user.anonymization_scheduled`
            - https://github.com/authgear/authgear-server/blob/master/pkg/api/event/nonblocking/user_deletion_scheduled.go
        - `user.anonymization_unscheduled`
            - https://github.com/authgear/authgear-server/blob/master/pkg/api/event/nonblocking/user_deletion_unscheduled.go
- Update admin API
    - implement `anonymizeUser` mutation
        - can reference to `deleteUser`, delete all the user's data except the record of `_auth_user` table. Change the `is_anonymized` and `is_disabled` to `true`. Clear standard and custom attributes.
            - https://github.com/authgear/authgear-server/blob/master/pkg/admin/graphql/user_mutation.go
            - https://github.com/authgear/authgear-server/blob/master/pkg/admin/facade/user.go
            - https://github.com/authgear/authgear-server/blob/master/pkg/lib/facade/user.go
            - https://github.com/authgear/authgear-server/blob/master/pkg/lib/facade/coordinator.go
            - https://github.com/authgear/authgear-server/blob/master/pkg/lib/authn/user/commands_raw.go
    - update user query
        - Add `isAnonymized` and `anonymizeAt`
            - https://github.com/authgear/authgear-server/blob/master/pkg/admin/graphql/user.go
        - Check if the user query behaves normally with anonymized users (identities, authenticators ...etc should be empty)
            - query user with id
            - list all users with anonymized user
    - implement `scheduleAccountAnonymization` mutation
        - can reference to `scheduleAccountDeletion`
            - add `account_anonymization` config with `grace_period_days`
    - implement `unscheduleAccountAnonymization`
        - can reference to `unscheduleAccountDeletion`
- Update background command to anonymize scheduled anonymization
    - can reference to the account deletion
        - https://github.com/authgear/authgear-server/blob/master/cmd/authgear/background/main.go
        - https://github.com/authgear/authgear-server/blob/master/cmd/authgear/background/wire.go
        - https://github.com/authgear/authgear-server/tree/master/pkg/lib/feature/accountdeletion
- Update admin portal
    - Add `Anonymize user` button on the user management page
        - Support `Schedule Anonymization` and `Anonymize immediately` like deleting user
    - Add `Cancel Anonymization` button
        - On the user detail page and listing page
    - How to display anonymized users on the user management page (UI design needed)
- (TBC) Support schedule account anonymization by the end user via the settings page 
    - add `scheduled_by_end_user_enabled` to the `account_anonymization` config
    - Show `anonymize your account` link in the `/settings/identity` page
        - The copywriting should be the same as deleting the user (e.g. `Delete your account`)? Anonymization should be the backend implementation only
    - Should also fire audit log and hook event

**Comment by fungc-io** [comment]
@IniZio 

In list page:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/15207470/208896215-dc98e2c6-41fc-4a92-8a70-7e605e863891.png">

In user detail page:

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/15207470/208897261-2dc227b1-c626-4969-9346-04aa4d14bd60.png">

Message bar content:

> This user is anonymized and all data are erased.

**Comment by fungc-io** [comment]
The message bar design is as 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/15207470/208897458-80a82ba1-3aac-4bc9-ac98-8ad40e59c673.png">

**Comment by IniZio** [comment]
Added
