### ISSUE TITLE
[OTP] Create or retrieve OTP via Admin API

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2740]
# Use case

Sometimes OTP code can fail to deliver to the audience. It would be helpful if the admin staff can tell the end-user the OTP code when the end-user asks for support.

# Technical background

Currently OTP code in Authgear is handled by different packages.

When sending OTP code for signing in, the OTP code is bound to an authenticator ID. See https://github.com/authgear/authgear-server/blob/master/pkg/lib/authn/authenticator/oob/provider.go#L87

When sending OTP code for signing up or verification, the OTP is bound to an identity ID and a web session. See https://github.com/authgear/authgear-server/blob/master/pkg/lib/feature/verification/service.go#L190 

We would like to unify OTP code such that the OTP code is bound to the target itself (email address or phone number).

# Implementation details

- Introduce a new struct in `pkg/lib/authn/otp` to generate and verify OTP code.
```golang
// pseudocode!!!

type Code struct {
  // 6 digit code
  Code string
  ExpireAt time.Time
  // Code will be persisted so it does not contain target.
  // Add any other necessary fields...
}

type OTPCodeService interface {
  // GenerateCode generates a new Code or return an existing Code.
  GenerateCode(target string) (*Code, error)
  // VerifyCode verifies if code matches an existing Code.
  // The error it returns should follow existing implementation.
  VerifyCode(target string, code string) error
}
```

- [x] #2760
- [x] #2761
- [x] #2762
-  ~(**Design Required**) (TBC) Find a place in the portal to trigger this mutation. @fungc-io Thoughts?~
- ~Display the generated code in a [Dialog](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog). The title is `OTP code for [email or phone]`. The description is `The end-user can use this code to sign in if they did not receive the code`. The only button is a cancel button which dismisses the dialog. Click outside the dialog should also dismiss the dialog.~
- [x] #2763

**Comment by fungc-io** [comment]
Need to refactor the OTP generation package for signup, verification and 2FA

**Comment by louischan-oursky** [comment]
@Rubikium I have updated the description to reflect the actual changes we want to make. Feel free to ask if you are not sure what to do.

**Comment by Rubikium** [comment]
> Introduce a new struct in pkg/lib/authn/otp to generate and verify OTP code.

> Remove the old implementation in pkg/lib/authn/authenticator/oob and pkg/lib/feature/verification

Is an implementation of `OTPCodeService` needed for this issue?

**Comment by Rubikium** [comment]
Time estimations:
- [ ] Refactor to use new service: 1.5 days
- [ ] Add new mutation: 1 day
- [ ] UI design in portal: 1.5 days

**Comment by fungc-io** [comment]
No need to provide this feature in the portal, so i'm removing the Portal subtasks

**Comment by fungc-io** [comment]
Added a sub task for documentation

**Comment by louischan-oursky** [comment]
- Always generate a new code to send.
