### ISSUE TITLE
Create the customized UI for signup/login

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2751]
A highly customized UI for signup and login is requested by the [client](https://3.basecamp.com/3096882/buckets/11477446/documents/5653990958)

While @louischan-oursky is working on [the refactoring](https://github.com/authgear/authgear-server/issues/2749), the frontend can be developed in parallel.

- Follow the provided UI flow and create the elements and pages. 
- It should also be functional as a mockup to demonstrate the flow.
- Translation file support is needed. `zh-Hant-HK` and `en-US` are required.

**Comment by fungc-io** [comment]
@kiootic 

update: 3 languages are needed `en-US`, `zh-Hant-HK`, `zh-Hans`

**Comment by kiootic** [comment]
@fungc-io Do we use the system language, or specified by app?

**Comment by fungc-io** [comment]
Specified by app -> fallback to system language -> fall back to project default

**Comment by kiootic** [comment]
Also just to confirm, `en-US` or `en-HK`?

**Comment by fungc-io** [comment]
@louischan-oursky which one do we support in Authgear? or no region?

**Comment by louischan-oursky** [comment]
No region. But the English used in Authgear should be American English.
