### ISSUE TITLE
[Key Rotation] Admin API Key Rotation

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2775]
@louischan-oursky has specified how it should be supported
Please refer to: 
https://github.com/authgear/authgear-server/issues/912#issuecomment-885434010

## Designs:

![Image](https://user-images.githubusercontent.com/15207470/210953142-f51164d7-3208-4330-93b3-3ba9e5bfdee6.png)

- Add a button "Generate new key pair"
  - When there is already 2 keys, hide button and show: "Max. 2 keys per project"
- Under "Action" column, add a "Delete" button in Red
  - When there is only 1 key, disable the delete button and show tooltip "At least 1 key per project" when hover
  - When deleting, show warning dialog:

> ## Delete Admin API key
> 
> Are you sure you want to delete this key? This action CANNOT be undone. Any applications using this key will no longer be able to access the Admin API.
> 
> [I understand, delete this key] [Cancel]

### Tooltip design:

![Image](https://user-images.githubusercontent.com/15207470/210953457-ff739030-fc32-4a0f-a2a7-c8bc106d57b6.png)

### Add button design:

![Image](https://user-images.githubusercontent.com/15207470/210953599-9c9122f9-2a37-45f1-bc5f-58a1e73de127.png)

## Tasks:

- [x] #2860
  - Est.: 1 day
- [x] #2861
  - Est.: 0.5 days
- [x] #2862
  - Est.: 1.5 days

**Comment by fungc-io** [comment]
@carmenlau @louischan-oursky 
See if the design make sense?

**Comment by louischan-oursky** [comment]
Looks good to me!

**Comment by Rubikium** [comment]
@fungc-io @louischan-oursky Added planned tasks and time estimations

**Comment by louischan-oursky** [comment]
Please add more detailed steps in each issue. Like what I did in https://github.com/authgear/authgear-server/issues/2781, https://github.com/authgear/authgear-server/issues/2783, and https://github.com/authgear/authgear-server/issues/2784
