### ISSUE TITLE
Support registering custom ui per OAuth client

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#2779]
- Add `x_custom_ui_uri` (format: uri) to OAuthClientConfig
- Update authz endpoint 
    - Support `x_custom_ui_query` parameter
    - Append `x_custom_ui_query` to OAuth client `x_custom_ui_uri`, and redirect to the URI instead of the authgear authui page
- Update SDKs to add `CustomUIQuery` (string) to `AuthenticateOptions` (Developers can also use custom UI ASWebAuthenticationSession, so it should be in `AuthenticateOptions` instead of `WebViewOption`)

**Comment by carmenlau** [comment]
@louischan-oursky When you have time, can you see if the list makes sense to you or any comment? I can help work on this. thanks!

**Comment by louischan-oursky** [comment]
Looks good to me
