### ISSUE TITLE
[OTP] Generate OTP on every resend

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2782]
## Requirement

- Regardless of the OTP valid lifetime, every resend should generate a new OTP. And the old one is immediately invalidated.

## Design

- no design

**Comment by louischan-oursky** [comment]
This was done in https://github.com/authgear/authgear-server/pull/2753/commits/1ca9b9f257687a8dae4582cc405f02e25bd44854

**Comment by Rubikium** [comment]
Relevant PR merged
