### ISSUE TITLE
[Magic Link/SDK] Open mail app

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2785]
## Use case

- It will be a smooth UX if after sending the login link via email, the end-user can go to the email app **inbox** with a click without going back to system home screen.
- After triggering the login link send via email, show a button "Open email app". When clicked, show a list of email apps

## Requirement

- Open email client apps with a link from the WebView inside SDK
- This is only supported with the UIVariant is WebView because this requires JS injection to the in-app browser

### iOS

- Show an Action Sheet with 2 buttons:
  - Mail `message://`
  - Gmail `googlegmail://`

### Android

- Launch an intent chooser with a list of installed email apps
- ref: https://stackoverflow.com/questions/8099017/how-to-open-the-default-mail-inbox-from-android-code/69043615#69043615

**Comment by IniZio** [comment]
Maybe can refer to https://github.com/includable/react-native-email-link

Example:

<table>
<tr>
	<td>iOS
	<td>Android
<tr>
	<td>

![Screen Shot 2023-01-07 at 7 54 41 PM](https://user-images.githubusercontent.com/3119725/211234416-943aa9c3-9f66-4952-850c-d817ef737a1f.png)
	<td>

![Screenshot_20230107_195349](https://user-images.githubusercontent.com/3119725/211234446-9f7ff8dd-89af-4576-bf3b-a183eca2498f.png)
</table>

**Comment by tung2744** [comment]
@fungc-io Are we going to support this in all sdks including react native, flutter and xamarin?

**Comment by louischan-oursky** [comment]
## iOS

- Add an **optional** method to the Authgear delegate
```swift
func onOpenEmailClient(vc: UIViewController) -> Void
```
- Inject a JavaScript snippet into the webview to listen for  the [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) `authgear:onOpenEmailClient`. The event listener notifies the webview in the native side. The webview in turn notifies Authgear instance. Finally Authgear instance notifies the delegate.
- Implement a class function on Authgear to present an action sheet with a list of items. When the item is selected, open the `openURL`.
```swift
public enum EmailClient {
  case gmail
  case mail
  // other cases......

  var englishName: String
  var openURL: String
}

public struct EmailClientItem {
  title: String
  openURL: String
  init(c: EmailClient)
}

public class func makeChooseEmailClientAlertController(items: [EmailClientItem]) -> UIAlertController
```

Example usage

```swift
func onOpenEmailClient(vc: UIViewController) {
  let items = [EmailClientItem(emailClient: .gmail)]
  let alert = Authgear.makeChooseEmailClientAlertController(items)
  vc.present(alert, animated: true)
}
```

## Android

- Add an **optional** method to the Authgear delegate. Interface in Java 8 can have default method.
```java
void onOpenEmailClient(Activity activity)
```
- Inject a JavaScript snippet into the webview to listen for  the [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) `authgear:onOpenEmailClient`. The event listener notifies the webview in the native side. The webview in turn notifies Authgear instance. Finally Authgear instance notifies the delegate.
- (Provisional) Add the following API to simplify intent chooser creation.
```java
public enum EmailClient {
  GMAIL,
  // other cases.
  // Think about what is the best way to make the API ergonomic while adding exotic mail client is easy.
}

public static Intent makeEmailClientIntentChooser(ctx Context)
```

**Comment by fungc-io** [comment]
@tung2744 
yes, but ios and android native is priority
we can add to the other sdks later, but the design should be consistent

**Comment by tung2744** [comment]
@louischan-oursky I think in android we don't need to define `EmailClient` because we can query them by using `mailto:`.
https://github.com/includable/react-native-email-link/blob/master/android/src/main/java/agency/flexible/react/modules/email/EmailModule.java#L32
