### ISSUE TITLE
Make authenticators available in the `user.pre_create` event hook payload

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2804]
Use case:

Check the authenticators used in signup before the user is created.

So that this is possible:

```TypeScript
import { EventUserPreCreate, HookResponse } from "https://deno.land/x/authgear_deno_hook@v0.4.0/mod.ts";

export default async function(e: EventUserPreCreate): Promise<HookResponse> {
  for (const a of e.payload.authenticators) {
    if (a.kind === "secondary" && a.type === "oob_otp_email") {
      // checking
      return {
        is_allowed: true,
        }
      }
    }
  }

  return {
    is_allowed: false,
  };
}
```

**Comment by carmenlau** [comment]
The authenticator payload should be the same as the admin API. 

The only difference is that the keys are in camelcase in the Admin API, but the event payload should be in underscore in the event payload.

ref: https://github.com/authgear/authgear-server/blob/88bc6e8f11a176734d8dc99259cd1e91e6b8db5b/portal/src/graphql/adminapi/schema.graphql#L170

Also, when we do this issue, we should review the returned claims for each of the authentication methods.
