### ISSUE TITLE
Secondary authenticators pre-update event

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2806]
Related to: https://github.com/authgear/authgear-server/issues/2804

Let's say event hook is used to copy a value from 2FA to a user profile attributes,
we need to ensure the attribute and 2FA are always in-sync

**Comment by carmenlau** [comment]
We are planning to add 2nd authenticators related non-blocking events in this spec, ref https://github.com/authgear/authgear-server/pull/2745

The only question is, do we also want to add blocking events? There will be a lot, we will have `pre-add`, `pre-udpate`, and `pre-delete` for each of the 2nd authenticate methods. Then we will ask how about the `pre` methods for identities. We need to consider the use cases and see if it makes sense to add them.

**Comment by fungc-io** [comment]
Abandoned as 2FA should not be updated. User should add a new one and remove the old one
