### ISSUE TITLE
[Portal] Fix inconsistent fonts

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#281]
The rendered font for elements is inconsistent, especially the headers. Some are rendered `Segoe UI`, some are `.SF NS`. I suggest using `Text` component of Fluent UI at all time to ensure consistent styling.

**Comment by axolotl0212** [comment]
For header, instead of writing `h1`, `h2`, we can try `<Text as="h1">Hello world</Text>`

**Comment by louischan-oursky** [comment]
Enable this rule https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-elements.md to ban `h1`, `h2`, ...

**Comment by axolotl0212** [comment]
> Enable this rule https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-elements.md to ban `h1`, `h2`, ...

Handled in PR #279
