### ISSUE TITLE
Trigger email verification from SDK

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2858]
- [x] Update server to support app session action via authz endpoint
- [ ] Update SDKs to support performing actions
    - [ ] iOS native
    - [ ] Android native
    - [ ] JS web and reactnative
    - [ ] Flutter
    - [ ] Xamarin

**Comment by carmenlau** [comment]
We had a discussion on how to perform setting actions (verify email, change password) in SDK. The following flowcharts explain how it works.

We will work on the simplified version first.

## Simplified version

[![](https://mermaid.ink/img/pako:eNpVUcFuhCAQ_RXDeZWkR7Mx2Y23dnuoR20MwqhEBAvYZtf47x2WvTgHAu_Ne0PebIQbASQng2XLmHx8NTrButRs9eMjAS0WI7U_d5YW1ATwjYbTWPmA79h8rRn30ujELcBlL_lRBtmQJbTFJ1jNlKMOvJd6cG2U0V-wsr-3MDOpXpZlzZYl4UypjvHpTDsbbbiZM2RyehC1I9NCgUVxlFfle5oGBwfOhZ95M4FO0-JyhLkxkwTErylWUQY9OZEZLNoKTGULfg3xI8zQkByvAnq2Kt-QU6Qc_Kyg-ZPd4nQER_NXvYjPde7AusB7u0Jo2Ru94xjM0VR3zUkeiBNZF8E8lJLhLmaS95gVoiCkN_YWt_Rc1v4P3QuVuQ?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNpVUcFuhCAQ_RXDeZWkR7Mx2Y23dnuoR20MwqhEBAvYZtf47x2WvTgHAu_Ne0PebIQbASQng2XLmHx8NTrButRs9eMjAS0WI7U_d5YW1ATwjYbTWPmA79h8rRn30ujELcBlL_lRBtmQJbTFJ1jNlKMOvJd6cG2U0V-wsr-3MDOpXpZlzZYl4UypjvHpTDsbbbiZM2RyehC1I9NCgUVxlFfle5oGBwfOhZ95M4FO0-JyhLkxkwTErylWUQY9OZEZLNoKTGULfg3xI8zQkByvAnq2Kt-QU6Qc_Kyg-ZPd4nQER_NXvYjPde7AusB7u0Jo2Ru94xjM0VR3zUkeiBNZF8E8lJLhLmaS95gVoiCkN_YWt_Rc1v4P3QuVuQ)


## Completed version

[![](https://mermaid.ink/img/pako:eNplUstuwyAQ_BXEOQSpRyuKlMS3Pg7N0a4QhnWMYoMLuFES5d-7xKhVWh-QmdmZHXv3SpXTQAt68HLsyMt7bQk-m0pOsbsQsHp0xsZV4_mauwQ-8XQ6by7wMRdvK6micZaEEZRpjXqUwfKwJFzgFbyVfeABYjT2EMQs41_gTXsWMEjTZ8tdZUKYgORSkhukrD_mZMUbn91zMnFXiazK_sJDmPookjjbl5UcR6Jk3zdSHX99lBuWyBT8IZPopNU9eBTP8n35zFhyCBBCyhXdESxj680jrJw7GkB8y9ifL5kz_VbsGDuZ2P2jdSLL1Jgu6AAe82ic1jUFqWnsYICaFviqoZUoqelipgJ8TmDVnb3OsRHs3GmfibdpaMCHxEc_QSq51faGbfBfuv3ZKlokYkGnUcsIpZG4IwMtWpwhoqBNdP513p77Et2-AbYRzW0?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNplUstuwyAQ_BXEOQSpRyuKlMS3Pg7N0a4QhnWMYoMLuFES5d-7xKhVWh-QmdmZHXv3SpXTQAt68HLsyMt7bQk-m0pOsbsQsHp0xsZV4_mauwQ-8XQ6by7wMRdvK6micZaEEZRpjXqUwfKwJFzgFbyVfeABYjT2EMQs41_gTXsWMEjTZ8tdZUKYgORSkhukrD_mZMUbn91zMnFXiazK_sJDmPookjjbl5UcR6Jk3zdSHX99lBuWyBT8IZPopNU9eBTP8n35zFhyCBBCyhXdESxj680jrJw7GkB8y9ifL5kz_VbsGDuZ2P2jdSLL1Jgu6AAe82ic1jUFqWnsYICaFviqoZUoqelipgJ8TmDVnb3OsRHs3GmfibdpaMCHxEc_QSq51faGbfBfuv3ZKlokYkGnUcsIpZG4IwMtWpwhoqBNdP513p77Et2-AbYRzW0)

[![](https://mermaid.ink/img/pako:eNotkE1rwzAMhv-K0TkhsGMYhUJv-zgsx7kEJVYbQ2x3ttwxQv775Lo-mfd5LMnaYA6GoIdrxNui3r-0V3KO32FitF4lYrb-qnBmG7yKlPLKr1PsDl3AzMtLN0oW1juNT3Ws6ljVs_a14nB6a9uaqdKybQ_HwqABR9GhNTLEVlwNvJAjDb1cDV1QnmhoKkr0k8nPD7rVyhIu4Xd4gs_sJoqpcI6ZirJrv0sbGTcMf36GvoAG8s0g08mifN1Bf8E1SUrGcogfdSmP3ez_pIZkfw?type=png)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNotkE1rwzAMhv-K0TkhsGMYhUJv-zgsx7kEJVYbQ2x3ttwxQv775Lo-mfd5LMnaYA6GoIdrxNui3r-0V3KO32FitF4lYrb-qnBmG7yKlPLKr1PsDl3AzMtLN0oW1juNT3Ws6ljVs_a14nB6a9uaqdKybQ_HwqABR9GhNTLEVlwNvJAjDb1cDV1QnmhoKkr0k8nPD7rVyhIu4Xd4gs_sJoqpcI6ZirJrv0sbGTcMf36GvoAG8s0g08mifN1Bf8E1SUrGcogfdSmP3ez_pIZkfw)
