### ISSUE TITLE
Fix outgoing IP for deno for SMS gateway

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2859]
The SMS Gateway may require IP whitelisting in the firewall

**Comment by tung2744** [comment]
https://cloud.google.com/nat/docs/gke-example
It seems static outgoing ip is achievable by using cloud NAT with private cluster, but we need to recreate the whole cluster for that.

@fungc-io @louischan-oursky

**Comment by tung2744** [comment]
@louischan-oursky 
https://cloud.google.com/products/calculator#id=b4c3b7ba-3fbe-4567-ac65-42de6a267dee
Just a very rough estimated cost. The number of vms is the number of node in our cluster, but I have no idea how to find out the current egress traffic of the cluster so I just guess a number. If there is any method to know the exact number please let me know.

**Comment by kiootic** [comment]
I think it would be simpler to setup a HTTP proxy in a fixed IP node, and configure fetch to use the proxy in Deno script?

ref: https://github.com/denoland/deno/pull/10907

**Comment by tung2744** [comment]
But if we setup a new node for it, should we just deploy a custom middleware for it?

**Comment by fungc-io** [comment]
After discussion, for such cases, 
custom middleware with webhook is a simpler option. 
Decide not to go for fixed outbound IP for deno hooks
