### ISSUE TITLE
Clarify integration with custom UI

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#2874]
For integration with custom UI:
- completing OAuth flow should use redirect URI given by the workflow API (WIP)
- cancelling OAuth flow should use redirect URI from query parameter.
- In case no redirect URI is given, should display error.

**Comment by keithtkl** [comment]
all the questions should be resolved. @kiootic let us know if now

**Comment by kiootic** [comment]
I think mainly is for updating docs on how to develop custom UI for Authgear.

**Comment by fungc-io** [comment]
To be replaced with the new workflow api
