### ISSUE TITLE
[Custom UI] Forgot password workflow

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2893]

**Comment by tung2744** [comment]
@louischan-oursky Sorry I am not sure about the details of the forgot password link so want to confirm. Is it actually a link containing the otp used to reset password, so that what the workflow should receive is an otp?

**Comment by louischan-oursky** [comment]
The workflow of this issue is about a workflow to request a reset password message. The message is rendered by a [Go template](https://github.com/authgear/authgear-server/blob/2023C01/resources/authgear/templates/en/messages/forgot_password_email.txt) with [the data](https://github.com/authgear/authgear-server/blob/2023C01/pkg/lib/feature/forgotpassword/provider.go#L184) As you can see, the default template does not actually make use of `Code`, instead, it renders the `Link`. `Link` is a link to the default UI. For our use case here, we want to show a link to the custom UI. The link to the custom UI must have the `Code` embedded in the query. When the link to the custom UI is visited, it performs [reset password workflow](https://github.com/authgear/authgear-server/issues/2892). You do not need to concern about the templates. The templates will handled in another issues.

**Comment by louischan-oursky** [comment]
You can try the forgot password / reset password flow with the default UI to get a sense of what it is doing. That would give you a bigger picture of what is happening here.

**Comment by tung2744** [comment]
ok I think I got it, thanks!
