### ISSUE TITLE
[Custom UI] How to perform authenticated workflow

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2899]
Workflow that required authenticated user

- For each redirect URI used in this kind of workflow, configure them in redirect_uris
- func generateURL(redirectURI: String, completion: (URL,error) -> Void) -> Void
- specific to custom UI (not related to authgear core): The app open a WKWebView with the generated URL. It watches WKNavigation and see if the navigation is navigating to `/_internal/finish`.

**Comment by kiootic** [comment]
For this task, the main work is to add this:

> func generateURL(redirectURI: String, completion: (URL,error) -> Void) -> Void

We can add this function into an experimental namespace in a branch of SDK, refactoring the relevant logic out of existing `openURL` function.
