### ISSUE TITLE
[Custom UI] Disable authentication and settings in auth UI

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2905]
- Keep public_signup_disabled. It is being used.
- Add `ui.authentication_disabled`. By default it is false. When it is true, /login, /signup, and /promote shows a UI similar to public_signup_disabled, saying that authentication is disabled.
- Add `ui.settings_disabled`. By default it is false, When it is true, /settings and /settings/* shows a UI saying that settings is disabled.

**Comment by IniZio** [comment]
Or should we use existing`custom_ui_enabled` instead? Since otherwise this flag will be pretty confusing.
