### ISSUE TITLE
Exceeding `failed_attempt` OTP rate limit would not produce rate limit error

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#2936]
When `failed_attempt` OTP rate limit is exceeded, it always return `InvalidCredentials` error, ad `RateLimited` error is never returned.

**Comment by kiootic** [comment]
The problem is in `handleFailedAttempt` of `otp.Service`. When remaining tokens = 1:
1. `TakeToken` passed, remaining tokens = 0
2. `CheckToken` failed, delete OTP code and return `ErrInvalidCode`

Subsequent attempts would fail early due to missing OTP code and rate limit is not checked anymore. So OTP verification would never return `RateLimited` error due to failed attempt rate limit.

**Comment by louischan-oursky** [comment]
- Rename CanVerifyCode to FailedAttemptRateLimitExceeded
- Call CheckToken in CanVerifyCode and VerifyCode in the beginning
