### ISSUE TITLE
[OTP SMS] Failing to receive SMS OTP

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#2965]
## Background:
Device / Browser (OS version): Chrome on Mac, Safari on Mac, Firefox on Mac
Build: staging-2023-02-17.0

## Description:
Failing to receive SMS OTP for signing up by phone number with 46443593 and personal phone number.

## Steps:

1. Go to AuthUI of a project that allow sign up by phone number and verify by SMS
2. Sign up with 46443593 or other phone number
3. Check phone, see no SMS

## Expected:
Receive SMS

## Screenshot:
<img width="477" alt="Screenshot 2023-02-20 at 4 27 31 PM" src="https://user-images.githubusercontent.com/4337525/220115679-597eed32-7340-4e97-9568-5d6ff38d6727.png">

**Comment by joyzoursky** [comment]
Tried on my own project and my phone number also cannot receive SMS:
- Project: https://idontknow123.authgear-staging.com/

**Comment by joyzoursky** [comment]
cannot reproduce
