### ISSUE TITLE
[OTP Whatsapp] Whatsapp OTP failed to verify

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#2966]
## Background:
Device / Browser (OS version): Chrome on Mac, Safari on Mac, Firefox on Mac
Build: staging-2023-02-17.0

## Description:
Failing to receive SMS OTP for signing up by phone number with 46443593 and personal phone number.

## Steps:

1. Go to AuthUI of a project that allow sign up by phone number and verify by Whatsapp
2. Sign up with 46443593 or other phone number
3. Follow instruction to send code by Whatsapp
4. See no redirect in verification page.

## Expected:
Successful verification.

## Screenshot:
<img width="634" alt="Screenshot 2023-02-20 at 8 07 05 PM" src="https://user-images.githubusercontent.com/4337525/220118011-8adbeec1-b12b-45d9-9d29-b93edca19b91.png">

**Comment by joyzoursky** [comment]
Tried on my project also have no response after sending the WhatsApp message or inputting the 6 digit code manually.

![IMG_D14DE81225B2-1](https://user-images.githubusercontent.com/12539486/220307097-fee8f69c-ca4f-4c59-a93e-42440db94961.jpeg)


Send code page no update after sending the messages.

<img width="867" alt="Screenshot 2023-02-21 at 5 37 55 PM" src="https://user-images.githubusercontent.com/12539486/220307055-70177780-285d-4045-b1e6-0d9aa1d216d0.png">

**Comment by joyzoursky** [comment]
it is updated to use input code instead, cannot reproduce now
