### ISSUE TITLE
[Portal] Should not rotate the hover highlight

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#298]
In Authentication page Login ID tab, when the right arrow toggle button is tapped, the hover highlight also rotates. This should not happen.

**Comment by kiootic** [comment]
Actually that was not the fix I expected, since having a highlight for interactive buttons is desirable. Also, now I can still see a rotated focus rectangle if I trigger the button using keyboard. We should keep the highlight and just rotate the icon, not the whole button.

**Comment by louischan-oursky** [comment]
Pass a `styles` that only target the icon for animation?
