### ISSUE TITLE
Support first party confidential client

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3001]
- [x] Update the condition on whether client secret is required. Client secret is required when ClientConfidentiality is ClientConfidentialityConfidential
- [x] Update the condition on whether full-access scope is allowed. Full-access scope is allowed when `HasFullAccess()` is true
- [x] Update the condition on whether ID token has PII. ID token has PII when `PIIAllowedInIDToken()` is true
- [x] Add `x_application_type=confidential`
- [x] Support `x_application_type=confidential` on portal
- [x] Hide `x_application_type=third_party_app` on portal

**Comment by fungc-io** [comment]
Ready on staging, pending deployment
