### ISSUE TITLE
Consolidate and review rate limits

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#3010]
- Upload profile image: `presign-images-upload`
  - hard-coded: 10 per hour, per user
- Password authentication: `auth-secret`
  - configurable default: 10/min/user/authentication type
- Other authentication (TOTP, passkey, OOB-OTP, etc.): `auth-secret`
  - hard-coded: 10 per minute, per user, per authentication type
- MFA recovery code: `auth-recovery-code`
  - hard-coded: 10 per minute, per user
- MFA device token: `auth-device-token`
  - hard-coded: 10 per minute, per user
- General OTP Failed Attempt (verification OTP, OOB-OTP): `otp-failed-attempt`
  - Invalidate existing OTP if rate limit is exceeded
  - configurable default: 5 per 20 minutes, per email/phone; disabled by default
- Forgot password send message: `reset-password-send-code`
  - hard-coded: 5 per 5 minutes, per login ID
- Forgot password validate code: `reset-password-verify-ip`
  - hard-coded: 10 per minute, per IP
- SWIE authentication: `siwe-nonce`
  - hard-coded: 10 per minute, per IP
- Verification validate code: `verification-verify-code`
  - hard-coded: 10 per minute, per IP
- Send email: `email-message`
  - hard-coded: 10 per minute, per email
- Send SMS (phone): `sms-message`
  - configurable default: 10 per 24 hours, per phone; disabled by default
- Send SMS (IP): `sms-message-per-ip`
  - configurable default: 120 per minute, per IP; disabled by default
- Hard SMS limit: `sms-message-hard`
  - feature config
- Signup user: `signup`
  - hard-coded: 10 per minute, per IP
- Legacy interaction request: `request`
  - hard-coded: 200 per minute, per IP
- Legacy interaction signup anonymous user: `signup-anonymous-user`
  - checked if new user is anonymous, after checking `signup` rate limit
  - hard-coded: 60 per hour, per IP
- Legacy interaction account enumeration: `account-enumeration`
  - checked before verifying input login ID exists
  - hard-coded: 10 per minute, per IP
- Send OTP code cooldown: `otp-code`
  - configurable default: 1 per 60 seconds, per email/phone

**Comment by kiootic** [comment]
Suggestions:
- Consolidate authentication rate limits into one (`auth-secret`, `auth-recovery-code`, `auth-device-token`)
- Exclude OTP from authenticate rate limits to avoid duplication.
- Consolidate forgot password OTP rate limit into general OTP (`reset-password-send-code`, `reset-password-verify-ip`)
- Make authentication/OTP rate limit based on failed attempts (successful attempts would not take token)
- Make OTP rate limits consistent:
  - IP-based rate limit
  - Target-based (email/phone) rate limit
  - Resend cooldown
  - Validation rate limit
  - Failed attempt invalidation
- Remove signup (& anonymous user) rate limits
- Make OOB message (email/SMS) rate limit consistent
  - Global rate limit (configured by server operator)
  - IP-based rate limit
  - Target-based (email/phone) rate limit

**Comment by chpapa** [comment]
Create a table of spec, sth like this?

| Item                          | Global          | per IP | per target |
| ----------------------------- | --------------- | ------ | ---------- |
| **System Level (multi-tenant)** |                 |        |            |
| All SMS                       | 60/s, 50000/day |        |            |
| All Email                     |                 |        |            |
| **Tenant Level**                |                 |        |            |
| All SMS                           |                 |        |            |
| All Email                         |                 |        |            |
| **Application Level**           |                 |        |            |
| Login SMS                     |                 |        |            |
| Verification SMS              |                 |        |            |
