### ISSUE TITLE
Login with WhatsApp OTP is not working

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3024]
Env: both staging and production

This bug is probably introduced after implementing the login link.

In the WATI callback, the server is unable to figure out which app the incoming webhook is for.

**Comment by tung2744** [comment]
@louischan-oursky 

In the original implementation, the whatsapp code was stored in redis without app id:
https://github.com/authgear/authgear-server/blob/4b51cea5cc972705f51402e8680046c8bc359fcc/pkg/lib/authn/authenticator/whatsapp/store_redis.go#L91-L93
Therefore, the wati webhook endpoint can find the code even the app id doesn't match.


In [this pr](https://github.com/authgear/authgear-server/pull/2753/files), we removed the original whatsapp code redis store, and replaced it with the otp store. Now the redis key includes the app id:
https://github.com/Rubikium/authgear-server/blob/716bc0949cd0072702c29086b925157feb40c084/pkg/lib/authn/otp/store_redis.go#L86-L88

So should we fix this by separating otp and whatsapp code and exclude app id in the code key again?

**Comment by louischan-oursky** [comment]
It is just my idea.

- Remove UserInputtedCode from code model
- We store the wati callback in redis, key by the target only, something like`whatsapp-code:{target}`, and the value is the received code.
- When we need to check the received code, we lookup `whatsapp-code:{target}`.

**Comment by fungc-io** [comment]
This issue is obsoleted as the feature will be replaced by: https://github.com/authgear/authgear-server/issues/3027
