### ISSUE TITLE
[Portal] Warn before leaving if the form is dirty

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#306]
- [x] Investigate how we can achieve this with `react-router-dom@6`
- [x] Apply this to every form
- [x] Use [Dialog](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog) for confirmation

**Comment by axolotl0212** [comment]
`useBlocker` in `react-router-dom`? Seems like this is what we need. Haven't studied it in detail though
