### ISSUE TITLE
"At least 1 uppercase or lowercase alphabet" in password policy

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3079]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/15207470/236779199-6aa88ee9-876f-41a2-a257-3ab5cd27ed07.png">

In the password policy configuration, we have uppercase and lowercase alphabet as separated rules.

Would like to introduce 1 more rule so that user can include either lowercase or uppercase alphabet in their password.

In the portal, the config should be:
```
- Requires at least 1 digit (0-9)
- Requires at least 1 alphabetic character (a-z,A-Z) 
- Requires at least 1 lowercase alphabetic character (a-z)
- Requires at least 1 uppercase alphabetic character (A-Z)
- Require at least 1 special character (**List out what the special characters are**)
```

~The separated configs for lowercase/uppercase should be sub-items for the "alphabetic character".
e.g. A user must first enable **Requires at least 1 alphabetic character (a-z,A-Z)** to enable **Requires at least 1 lowercase character (a-z)**~

~@hlh112 Can you help design how the new config should be presented?~

**Comment by fungc-io** [comment]
Sorry @hlh112 , after discussion with @louischan-oursky , we think it should be kept simple in the portal and display them just as separated items.

So a new design is not needed. 

Thanks 🙏

**Comment by tung2744** [comment]
@fungc-io 

> List out what the special characters are

It is any non-digit and alphabetic character, so impossible to list out.

**Comment by tung2744** [comment]
But we still allow any characters in server? i.e. That is for description purpose only?

**Comment by louischan-oursky** [comment]
Yes, for description purpose. Maybe we should say `Require 1 non-alphanumeric character (List the examples here)`. @fungc-io

**Comment by fungc-io** [comment]
Fixed on staging, to be included in the next release
