### ISSUE TITLE
Search Audit Log by User ID

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3093]
Suggest to add the ability to search the audit log by user id,
It will be useful for tracing the changes applied on a specific user.

**Comment by fungc-io** [comment]
@hlh112 Can you help design how adding a User ID filter to the Audit Log page will look?


![Image](https://github.com/authgear/authgear-server/assets/15207470/c8eef347-a752-4aec-ac8c-52a2b005a114)


It should be a text filed for searching the "User ID", only 1 user id can be searched at a time, exact match.

**Comment by hlh112** [comment]
@fungc-io design updated, [entry screen of the flow](https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?type=design&node-id=9000-97380&t=7tgwfZzcp31vQsE3-4)

**Comment by fungc-io** [comment]
Hi @tung2744 ,
Hunt has helped updated the design in Figma to use the outlined search box.
Please help update the implementation in the Portal.
