### ISSUE TITLE
Support whstapp otp flow in auth ui

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3102]
- [x] Update implementations of the following edges so that it send the code with whatsapp
  - [x] EdgeCreateAuthenticatorWhatsappOTPSetup
  - [x] EdgeAuthenticationWhatsappTrigger
  - [x] EdgeVerifyIdentityViaWhatsapp

- [x] Update implementations of the following nodes so it requires a code input to verify
  - [x] NodeCreateAuthenticatorWhatsappOTP
  - [x] NodeAuthenticationWhatsapp
  - [x] NodeVerifyIdentityViaWhatsapp

- [x] Update /flows/whatsapp_otp so that it can accept code input on POST

- [x] Update whatsapp otp screen in authui to support inputting code

- [x] Implement resend

- [x] Skip sending in debug mode

- [x] Clean up unused code
    - [x] Wati webhook handler
    - [x] Mark wati credential deprecated
    - [x] Review GetWhatsappOTP
    - [x] Review GetServerWhatsappPhone

**Comment by fungc-io** [comment]
@tung2744 Let's reuse the SMS screen with the title changed to WhatsApp

![Image](https://github.com/authgear/authgear-server/assets/15207470/92935f54-8c6d-4806-b135-de6f3799e106)

**Comment by fungc-io** [comment]
Please make sure this works when switching SMS/WhatsApp
1. Sent code in Whatsapp
2. Switch to SMS, receive SMS code
3. Switch back to WhatsApp, cool down is still counting, the old code received in whatsapp should still work
