### ISSUE TITLE
Portal become unusable if a sso provider config set without an client id

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3106]
There are two bugs here:

1. Under some conditions, client_id of sso providers can be set to empty string without validation error.
2. When we successfully trigger 1, we cannot update other configs of the app because it always throw validation error saying that client_id is missing.

**Comment by tung2744** [comment]
I found this is a more generic problem of the whole authgear config, let me create a new issue to describe the details.
For this issue, I made a pr to fix the client_id field only.

**Comment by fungc-io** [comment]
Ready on staging, pending deployment
Follow up in #3109
