### ISSUE TITLE
Account Lockout policy for repeated login attempts

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3129]
## Goal

To enhance account security by locking out account after repeated failed login attempts.
This is different from API rate limit, which throttles the requests into a constant average number.

## Design

After certain failed attempts (X) in a duration (Y), end-user must wait for a lockout duration (T1) before next attempt.
For subsequent failed attempts, the end-user must wait for another lockout duration (T2), etc.
Z grows exponentially by a backoff factor (n) until a maximum defined duration.
The lockout is reset after:
- The end-user authenticated successfully with the correct credentials.
- Duration Y is passed after their last failed attempts.

A developer can define the lockout policy by:
- **X** - Max attempts: Maximum attempts to login before the account was locked
- **Y** - Duration: The duration of the max attempts is counted
- **Tmin** - minimum
- **Tmax** - Maximum
- **n** - Backoff Factor

Let's say the security policy is
- X: 10, Y: 1440m, Tmin: 5m, Tmax: 5m, n:1
  - It means within 24 hour, if the end-user input the wrong password 10 times, they will be locked for 5 minutes. For every next failed attempt, they must wait for another 5 minutes until the entered password is correct.

**Comment by fungc-io** [comment]
backend change is done in staging, frontend to be added in #3139

**Comment by fungc-io** [comment]
@tung2744 


![Image](https://github.com/authgear/authgear-server/assets/15207470/f754a7ac-f9fb-4e0c-80ae-d508051a762a)


When showing the account is locked,
The input and button should be disabled. And can we make the error message a count down?

**Comment by louischan-oursky** [comment]
@tung2744 We have a ResendButtonController. Maybe you can reference to it.

**Comment by tung2744** [comment]
@fungc-io 
> The countdown will show a round down number in the message.
When they need to wait 2 minutes, it always show "1 min" in the first minute. I think round up should be a better UX?
Currently, the relative time was formatted using the [intl api](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat). The behavior was controlled by the api. Also round up will has problem when you have 2 minutes counting down, you will see "2 minutes" -> "59 seconds".

**Comment by fungc-io** [comment]
> Also round up will has problem when you have 2 minutes counting down, you will see "2 minutes" -> "59 seconds".

I think that's better than "1 min" for 1st min?

> Currently all error message should be dismissed manually by user. I am not sure if it is a good idea to have a exception here.

But the message becomes irrelevant. Previously the errors were not recovered by time.
How about change the message to -> `Your account is unlocked` and change to Yellow when the lock is lifted?

**Comment by fungc-io** [comment]
I will created another 2 issues for these

**Comment by tung2744** [comment]
What about moving the countdown into the login form (Similar to resend)? It seems making a count down in the error message is incorrect :sosad:

**Comment by fungc-io** [comment]
tested ok on staging
to be followed up in: https://github.com/authgear/authgear-server/issues/3221
