### ISSUE TITLE
[Admin API] Add entity mutations

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#313]
- [x] Add Identity
- [ ] Add Authenticator
- [x] Add User

## Interaction in Admin API

Mutations of Admin API would be performed using interaction mechanism. Therefore, web-hooks are dispatched as usual, and constraints are applied.

However, we'd like Admin API able to bypass some constraints, for example:
- Resetting user password does not require reset code
- Logging in as a user does not require authentication (i.e. impersonation)
- Creating user may disregard required verification settings

To achieve this, we have two ways:
- Augment existing flows: flags is added to interaction graph input to indicated to intended behavior (e.g. `SkipVerification() bool` for skipping verification).
- Adding new flows: Impersonation would likely require a new flow to keep the logic simple.

In additional, interactions should have context to describe environmental information:
- Source: Where is the interaction triggered? Admin API or Auth UI?
- User: Who triggered the interaction? Authgear User or Admin API requestor? For Admin API, the user is inferred from JWT auth token.
- Request metadata: Metadata about the request that triggered the interaction: IP, user agent, time, etc.

These interaction context may be logged in audit logs, or send as part of web-hook events.

## Multi-step Interaction in Admin API

Creating user is a complicated process:
- User may be required to setup multiple ways of authentication (MFA)
- User may want to be authenticated at third-party OAuth provider
- User may be required to verify their email/phone
- User may need to receive MFA recovery code
- etc.

At the same time, it is essentials to allow developer to maintain some invariant in the system through configuration. For example, 'all user must be linked with a OAuth provider' is a useful invariant.

Therefore, we may need to have some way for developer to perform multi-step interaction through Admin API mutations.

**Comment by louischan-oursky** [comment]
> Multi-step Interaction in Admin API

Can the Admin API simply create a minimal user and let the other requirements be fulfilled when the user actually logs in their new account? Our interaction can now add missing required secondary authenticators, verify required claims. The missing piece is that we do not enforce a user must have a certain type of identity.

**Comment by kiootic** [comment]
Sure, we can ask user setup secondary authenticator and perform verification on first login. However, it means the MFA/verification requirement in configuration cannot be treated as an invariant: creating user through Admin API may break this. I suppose that's acceptable for now.

Anyways, we still need to setup first identity and primary authenticator on signup:
- How is admin supposed to setup OAuth identity in Portal?
- I suppose setting up OOB authenticator does not require verification code to be sent/validated.
