### ISSUE TITLE
[SDK] Update SDKs to be compatible with Android API level > 31

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3132]
Add a version check before https://github.com/authgear/authgear-sdk-js/blob/master/packages/authgear-react-native/android/src/main/java/com/authgear/reactnative/AuthgearReactNativeModule.java#L231

- [x] React Native
- [x] Android
- [x] Xamarin
- [x] Flutter

**Comment by fungc-io** [comment]
For RN and Android, the changes is still on 2023C01 branch, waiting to be merged to main
