### ISSUE TITLE
Update portal design for Account Lockout policy

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3139]
UI for #3129 
So the user can configure the account lockout policy on the Authgear Portal

**Comment by fungc-io** [comment]
Hi @crys-tal ,

thanks for your design in https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?type=design&node-id=9212%3A97671&t=4Ot1CNlr3Ktyu7Rn-1

I've left 1 comment in the figma,
And we've added 2 more settings to the feature

Please also add these

- for which types of authenticators will their attempts be tracked, only the enabled authenticators should be available in the config
    - type:
        - Password
        - Passwordless vis Email/Phone
        - Authenticator apps
        - Recovery code
    - If the user can login with OTP than Password, and only password is participating in the lockout policy,
        - They can try OTP by many times and only locked when password failed
 
- Lockout type
    - Per user
        - The user will be lockout from logging in on any devices
    - Per user per IP 
        - The user will be lockout from logging in on the same IP

**Comment by crys-tal** [comment]
@fungc-io (correct me if I'm wrong...) User should be able to set different lockout threshold/ lockout duration for different authenticator types? Or would it be one 'universal' lockout policy for all the selected authenticator types? Thanks!

**Comment by fungc-io** [comment]
It will be one 'universal' lockout policy for all the selected authenticator types

**Comment by crys-tal** [comment]
@fungc-io I've added the 2 new settings to the feature. Please take a look and see if it's okay. Thanks a lot! https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?type=design&node-id=9212%3A97671&t=sZ8d06oiccoh8IUE-1

**Comment by fungc-io** [comment]
Hi @chpapa 
see if you have any comments on the design for this portal config?
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?type=design&node-id=9212%3A97671&t=ogvDhOD5BYceEY5E-1

**Comment by chpapa** [comment]
Left a few minor comments on copywriting. @crys-tal @fungc-io

**Comment by fungc-io** [comment]
Design confirmed! thanks @crys-tal

**Comment by tung2744** [comment]
@fungc-io Some point would like to mention after looking at the design:
1. Passwordless via Phone / Email should be a single config, we didn't support configuring them seperately.
2. `A user account will be locked after 10 failed login attempts within 1440 minutes (i.e. 24 hours).`. This description is not wrong, but inaccurate. The 10 attempts might not be all within 24 hours. Once the user failed an attempt, if the last attempt is within 24 hour, the failed count will be incremented. Therefore, it seems "cooldown period" is a more accurate word, because we actually require the user to stop trying for 24hour to reset the counts.
3. `If a user account has exceeded the lockout threshold, it will be locked for 5 minutes. For every subsequent failed attempt, the user must wait for another 5 minutes until a correct password is entered.` This description only works if the config has backoff factor = 1.

**Comment by chpapa** [comment]
@tung2744 can you give a more layman but accurate description for 2?

For 3, I suppose if backoff factor = N, Is this correct?

```
If a user account has exceeded the lockout threshold, it will be locked for X minutes. For every subsequent failed attempt, the user must wait for another X*N minutes until a correct password is entered
``

**Comment by fungc-io** [comment]
1. Passwordless via Phone / Email should be a single config, we didn't support configuring them seperately.

Ok let's combine them

2. Let's do: 
`The failure attempts will be reset after X minutes (i.e. Y hours).` 

3. How about the copy in this?
<img width="1168" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/5f39108a-c088-4767-97f3-2d7d5dba8d4f">

**Comment by tung2744** [comment]
@fungc-io 
Oh sorry I didn't saw there was a design for backoff factor > 1. I think it works.
However, for X minutes (i.e. Y hours), do we still display Y hours if Y is not an integer?

**Comment by tung2744** [comment]
> can you give a more layman but accurate description for 2?

My suggestion is `Time Limit (minutes)` can be named as cooldown period. And the description can be something like `A user account will be locked after 10 failed login attempts. The failure attempts will be reset after Y minutes of the last failure.`

**Comment by fungc-io** [comment]
@tung2744 
How about 
Label: `Reset failed attempts after`
Desc: `A user account will be locked after 10 failed login attempts. The failure attempts will be reset after Y minutes of the last failure.` (as you suggested)

**Comment by tung2744** [comment]
@fungc-io Thanks I think it works.
There is still a description `The duration of time where failed login attempts are counted.`. Maybe it can be `The interval to reset reset failed attempts after the last failure.`?

**Comment by fungc-io** [comment]
okok
> The interval to reset ~reset~ failed attempts after the last failure.

**Comment by tung2744** [comment]
@fungc-io 
By louis:

> Setting max attempts to 0 to disable account locking is non-trivial to the developer. I suggest we add a toggle to turn this on and off. When turn on, set the max attempts to a sensible value like 10. When the toggle is off, we disable all following fields, or even hide them all.

What do you think?

**Comment by tung2744** [comment]
The ui after adding the toggle.

<img width="661" alt="Screenshot 2023-06-29 at 6 49 04 PM" src="https://github.com/authgear/authgear-server/assets/34942210/46aa4f69-bb89-425d-9adb-653a277306e5">

**Comment by fungc-io** [comment]
ok on staging
