### ISSUE TITLE
[Portal, Getting Started] "Sign up your first user" cannot be checked even when user is already signed up

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3149]
## Background
- Environment: Staging
- Test account: joyz+demo1@oursky.com
- Test project: pipe-flash-309 - https://pipe-flash-309.authgear-staging.com

## Description
When user creates a new project, it will go to the Getting Started page. After signing up the first user, the first box "Sign up your first user" is still not checked and it's still a remaining item on the tutorial.

## Steps to reproduce
1. Login to portal
2. Create a new project
3. Click on step 1 on "Getting Started" to Sign up the first user
4. Go to Getting Started page
5. See "Sign up your first user" is not checked

## Expected result
"Sign up your first user" should be checked after the first user is signed up.

## Screenshot
<img width="1552" alt="Screenshot 2023-06-20 at 1 46 45 PM" src="https://github.com/authgear/authgear-server/assets/12539486/f2f89c79-824a-4b85-a259-6378ad0eb181">

**Comment by joyzoursky** [comment]
Seems it is removed now

<img width="984" alt="Screenshot 2023-08-30 at 6 09 12 PM" src="https://github.com/authgear/authgear-server/assets/12539486/9eaa8d44-1f18-4ef5-b98e-a856b7da9f9d">

**Comment by joyzoursky** [comment]
@fungc-io @louischan-oursky  The button is back, but when I click to sign up a new user, and click "Back to Authgear Portal" button to come back, it goes back to Get Started page and the "Sign up your first user" step does not change to green tick (as the original issue description).

<img width="1513" alt="Screenshot 2023-10-24 at 3 17 55 PM" src="https://github.com/authgear/authgear-server/assets/12539486/35c43096-d5dc-4511-93aa-4b3e1d776914">
<img width="1171" alt="Screenshot 2023-10-24 at 3 19 29 PM" src="https://github.com/authgear/authgear-server/assets/12539486/35081be1-953c-46ac-a58a-c5fb8846a4ab">

**Comment by fungc-io** [comment]
Thanks @joyzoursky 
The tracking for signup is currently not working, will fix in later cycles

**Comment by joyzoursky** [comment]
TODO: Change to green tick if query and found an existing user.

**Comment by fungc-io** [comment]
tested ok
