### ISSUE TITLE
[Portal, Social Login] Cannot edit social login

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3150]
## Background
- Environment: Staging
- Test account: joyz+demo1@oursky.com
- Test project: pipe-flash-309 - https://pipe-flash-309.authgear-staging.com

## Description
When click edit on social login, it directs user to reauthentication page, but when it comes back, it still does not enable user to edit or toggle the social login methods.

## Steps to reproduce
1. Login to portal
2. Go to Authentication > Social / Enterprise Login
3. Click "Edit" button
4. Enter password and pass the reauthentication
5. Come back and see the items are still disabled / not in edit mode

## Expected result
Should be able to edit social login methods

## Video
https://github.com/authgear/authgear-server/assets/12539486/79d74c31-4ca3-47c7-ae82-b5e72168ecba

**Comment by fungc-io** [comment]
fixed on staging, will be deployed in next release
