### ISSUE TITLE
[Portal, Billing] No redirection when click on "Go Enterprise" button

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3152]
## Background
- Environment: Staging
- Test account: joyz+demo1@oursky.com
- Test project: smart-swallow-805 - https://smart-swallow-805.authgear-staging.com

## Description
On Billing page, when clicking on "Enterprise Plan" it will show a dialog, but clicking the "Go Enterprise" button on the dialog it only dismisses it without going to the corresponding page.

## Steps to reproduce
1. Login to portal
2. Go to Billing page
3. Click "Enterprise Plan" text at the bottom of page
4. See a dialog, click "Go Enterprise" button
5. The dialog dismisses and no further redirection

## Expected result
Should open corresponding page when clicking on "Go Enterprise" button.

## Screenshot
<img width="1552" alt="Screenshot 2023-06-20 at 2 16 41 PM" src="https://github.com/authgear/authgear-server/assets/12539486/e5de633e-56fc-42ff-b644-b90ac16c19d2">

**Comment by fungc-io** [comment]
It should open `mailto:hello@authgear.com`

**Comment by fungc-io** [comment]
@tung2744 can we fix this dead link in this cycle? tgt with the pricing page update
