### ISSUE TITLE
Update WhatsApp count display on the Billing page

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3157]
Instead of "Free"
always start from "$0" and 
show the count and calculated price on hover

**Comment by tung2744** [comment]
@fungc-io I saw the new design has contact us button added. What will it do?

**Comment by tung2744** [comment]
Oh I found you mentioned it in another issue
https://github.com/authgear/authgear-deploy-production/issues/33#issuecomment-1601605182

**Comment by fungc-io** [comment]
the link will go to https://www.authgear.com/talk-with-us
Sorry the design is not finalized

**Comment by fungc-io** [comment]
tested ok
