### ISSUE TITLE
Allow different Billing dates and charge price difference immediately on upgrade

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3159]
When a user upgrade their plan,
the pro-rata amount will be charged in their next invoice.
Better to charge it immediately to avoid payment problem

- Modify updateSubscription and previewUpdateSubscription
    - [x] do not update plan name in the mutation
    - [x] Use `payment_behavior=pending_if_incomplete` and `proration_behavior=always_invoice` to update the subscription
- Update webhook handler
    - [x] Update `handleActiveSubscriptionEvent` to allow updating subscription without checkout session
- Allow querying the subscription update status
    - [x] Add a `pending_update_since` column in `_portal_plan`, type is `timestamp | null`
    - [x] In webhook, set `pending_update_since` to null if we get a subscription updated event and the status is active
    - [x] Add a graphql query to query the `pending_update_since` column.
- Update portal
    - [x] In SubscriptionScreen, poll `pending_update_since` from graphql api until it is reset to null.
    - [x] Modify upgrade dialog

**Comment by chpapa** [comment]
I think the main thing is by doing this, we will have different billing day for each users instead of pro-rata at a given day to charge everyone.

**Comment by tung2744** [comment]
After studying stripe documentations, I think

- The billing day can still be at the same day for all users, we charge for the remaining days of the plan only
- We should update our implementation of update plan to use [pending updates](https://stripe.com/docs/billing/subscriptions/pending-updates), which will create a invoice immediately for the updates and only update the subscription if the payment was success.

**Comment by tung2744** [comment]
@louischan-oursky I've written down some plannings in this issue, please see if any thoughts?

**Comment by tung2744** [comment]
@fungc-io I found we supported "Downgrade" of the plans. If we charge the user immediately, we may need to "refund" money to the user. Stripe handles this by adding credits to the [customer's balance](https://stripe.com/docs/billing/customer/balance). The balance can be used in the next invoice of the same customer.
I think we should tell the user about this in the downgrade dialog.
Currently the text inside the downgrade dialog is

```
When you change your plan, the prorated charges will be reflected in the next invoice. $166.38 (estimated) and any further additional SMS and MAU will be charged on 8/1/2023.
```

Suggested change:

```
When you change your plan, the remaining credits ($166.38 estimated) will remain in your balance and will be deducted in your next invoice on 8/1/2023.
```

Or see if you have other ideas?

**Comment by chpapa** [comment]
@tung2744 can we make downgrade happens for next cycle?

So for now, if the users commit to monthly plan, he can only downgrade starting next cycle.

It would be more important in future, if we support annual plan with discount, we don't want users to downgrade during the period before they finish the commitment.

So, let's say a user:

1. On 7th Jul, subscribe to Startups plan: Charge USD 100 immediately
2. On 12nd Jul, upgrade to Business plan: Charge pro-rata USD 500 for rest of the period in 12nd Jul - 6th Aug
3. On 9th Sep, downgrade to Startups plan again: will remain in Business plan til 6th Oct, and charge USD 100 for 7th Oct cycle.

**Comment by fungc-io** [comment]
I think the downgrade should only happen in the next cycle if possible.

Downgrade
> Your plan will be downgraded on the next billing cycle. `{new plan fee}` will be charged on `{date}`.

or 

Cancel
> Your plan will be canceled on the next billing cycle. You can continue to use the {current plan} plan until {cycle end date}.

**Comment by louischan-oursky** [comment]
Agree with Ben and Fung that Downgrade should happen in the next billing cycle.

For cancel, we have been using [cancel at period end](https://stripe.com/docs/billing/subscriptions/cancel#cancel-at-the-end-of-the-current-billing-cycle) already. I think it serves us well.

For downgrade, it looks like we can use [subscription schedules](https://stripe.com/docs/billing/subscriptions/cancel#cancel-at-the-end-of-the-current-billing-cycle).

For upgrade, we should upgrade immediately and prorate on the subscription. [pending updates](https://stripe.com/docs/billing/subscriptions/pending-updates) seems exactly what we want. It allows to charge successfully and immediately before we actually upgrade the plan and let the developer to use more features.

**Comment by tung2744** [comment]
Created another issue to handle downgrade.
https://github.com/authgear/authgear-server/issues/3194

**Comment by tung2744** [comment]
I just found that pending updates cannot delete subscription items on update, but we must delete the previous plan item.
Maybe we should use `payment_behavior=allow_incomplete` to implement it.

**Comment by tung2744** [comment]
Per discussion we will stick to `pending_if_incomplete`.
We will make an assumption that all plans must contain exactly 6 items.
1. Plan Monthly charge
2. SMS North america
3. SMS Other region
4. Whatsapp North america
5. Whatsapp Other region
6. MAU

For existing plans, we should add back all the above items, and set to $0 if it is free.

**Comment by tung2744** [comment]
@fungc-io 

Currently, when payment failed on initial subscription, we have this ui.

![Image](https://github.com/authgear/authgear-server/assets/34942210/d42c188e-5657-4617-aa97-4157e0d136b6)

I think we may want a screen to handle failed payments event it is not the initial payment, I think we can reuse this ui but change the button to "Pay invoice". The button redirects the user to the page of invoice create by stripe. It is something like this:
https://invoice.stripe.com/i/acct_1LBFRwDwzy5EhFXX/test_YWNjdF8xTEJGUndEd3p5NUVoRlhYLF9PRWxVcDRNT0VrTUVHV3lDdnZ2Q0xrY1RESzZNVEVOLDc5NTI4MTUw02005eneVv8D?s=ap

What do you think?

**Comment by tung2744** [comment]
Please check the ui of payment failure section and upgrade dialog here:

![Image](https://github.com/authgear/authgear-server/assets/34942210/3a7cded1-008c-446a-b0b3-b001b4e0db68)
![Image](https://github.com/authgear/authgear-server/assets/34942210/51078831-8b13-4cac-9fd8-e56f13cce3f4)

**Comment by fungc-io** [comment]
@tung2744 lgtm 👍
