### ISSUE TITLE
[Demo App, Flutter iOS] It always opens another app on app launch

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3166]
## Background
- Environment: Staging
- Testing app: iOS TestFlight - Authgear Demo Flutter
- Build: 1.0.0 (1687258327)
- Device: iPhone SE 2 (iOS 16.4.1 (a))

## Description
When launching the iOS Flutter demo app, it always opens the WeChat app on my phone instead, seems to be some app configuration issue on the testing build.

## Steps to reproduce
1. Fresh install the iOS Flutter demo app fromTestFlight
2. Open app
3. See it switches to another app automatically (WeChat on my phone)

## Expected result
It should open the app normally.

## Video

https://github.com/authgear/authgear-server/assets/12539486/c290a24d-7a71-46d2-8c5c-cc1cdffac819

**Comment by fungc-io** [comment]
Cannot reproduce the problem in the latest demo app.
