### ISSUE TITLE
[Portal, Login Methods] Rate limit for OTP is shown when user selects "Enter Password" as authentication

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3168]
## Background
- Environment: Staging
- Testing target: Authgear portal
- Testing browser: Chrome on Mac
- Testing app: smart-swallow-805 - https://smart-swallow-805.authgear-staging.com

### Problem 1 - Email / Mobile:
When user sets the login method (mobile or phone) to use "Enter Password" as authenticator, the tab "Verification and OTP" is enabled with the settings for passwordless shown, which is a bit confusing to user as user didn't choose to use passwordless.

**Steps to reproduce:**
1. Create or select an app
2. Select mobile / email for login method
3. Select "Enter password"
4. See the tab "Verification and OTP" is enabled with settings for OTP are shown, while some of the items might be related to enter password too, e.g. Number of attempts allowed, but cannot be found

### Problem 2 - Username:
When user selects username as login method instead, it will be forced to "Enter Password", in this case, the OTP tab is not shown and therefore the no. of attempts rate limit cannot be set too.

**Steps to reproduce:**
1. Create or select an app
2. Select username for login method
3. See "Enter password" is selected by default
4. See the tab "Verification and OTP" is not shown, and therefore user cannot set the rate limit for some items like no. of attempts allowed

## Expected result
- Settings not related to user selected option should be hidden or disabled to avoid confusion.
- For "Enter password" cases, if the "Number of attempts allowed" (and/or any other) setting is also applicable, it should also be shown to user and let user configure.

## Screenshot

Email / phone - Enter password (rate limit settings for OTP is shown):

<img width="1552" alt="Screenshot 2023-06-27 at 1 54 50 PM" src="https://github.com/authgear/authgear-server/assets/12539486/38967731-a8d8-4563-93db-9b1ac133b96f">

Username - Enter password (no rate limit for passowrd):

<img width="1552" alt="Screenshot 2023-06-27 at 3 05 56 PM" src="https://github.com/authgear/authgear-server/assets/12539486/d334b435-d224-42ae-ac9f-04c8c254156f">

**Comment by fungc-io** [comment]
Thanks @joyzoursky 

**Problem 1 - Email / Mobile with Password**

- The **6-digit OTP** section is for both email/phone verification & passwordless login. In this case, it's controlling the email and phone verification. We can be more explicit about that.
- password attempts settings are set in this issue: https://github.com/authgear/authgear-server/issues/3139 it's not available on the portal yet

**Problem 2 - Username:**
- Verification and OTP relates to the verification and passwordless login only which is unrelated if only Username is enabled.
- password attempts settings are set in this issue: https://github.com/authgear/authgear-server/issues/3139 it's not available on the portal yet

----------


## For Problem 1 How about we:

**Change 1. change the top part**

<img width="700" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/3a0c3ea4-79aa-43d9-a4d4-c5b8c50e8808">


If "Enter Password"

1. Verification
2. Verification Settings
3. Configure how a user should be verified

If "Passwordless" or enabled both

1. Verification and Passwordless
2. Verification and Passwordless Settings
3. Configure how a user should be verified and using OTP to login

**Change 2: Move the 6 digit OTP section to the bottom**
So the user can focus on the "Verification" aspect of it first. The valid duration and limit should be less important.

<img width="500" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/52f80cbe-cb10-4bf0-a0b7-5045599ab8ec">

**Comment by fungc-io** [comment]
![Image](https://github.com/authgear/authgear-server/assets/15207470/e35abcd7-b60a-44d5-a5b7-0140c047a10f)


This value should be changed to "6-digit OTP"

**Comment by fungc-io** [comment]
tested ok on staging
