### ISSUE TITLE
[WhatsApp] Missing translation for wrong OTP error message

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3170]
## Background
- Environment: Staging
- Testing app: iOS TestFlight - Authgear Demo Flutter
- Build: 1.0.0 (1687258327)
- Device: iPhone SE 2 (iOS 16.4.1 (a))
- Testing app: smart-swallow-805 - https://smart-swallow-805.authgear-staging.com/
- Testing user: joyz@oursky.com

## Description
When user logins with WhatsApp, the error message for invalid otp is not translated even though the app is in Chinese. It should be translated as the error messages for SMS login.

## App configuration (test sample)
- Mobile login
- Passwordless login
- User language: Traditional Chinese

## Steps to reproduce
1. Configure on demo app
2. Authenticate and Sign up
3. On enter OTP for WhatsApp screen, enter wrong code
4. See error message "invalid otp code"

## Expected result
Should show translated message as on SMS login.

## Screenshot

Left: WhatsApp error in Chinese | Right: SMS error in Chinese

<img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/8ae5c66f-42cf-4099-90b9-02c7332531d3" /> <img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/7e0025db-9a0e-4da1-aa12-517b6e234d90" />

**Comment by fungc-io** [comment]
confirmed fixed on staging
