### ISSUE TITLE
[Portal, Search] Error when click pagination on search result

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3176]
## Background
- Environment: Staging
- Testing app: demo-enterprise
- Test account: fung+qa@oursky.com

## Description
When search in User Management and click pagination, it shows error `Error: invalid character 'o' looking for beginning of value`, not sure if it also happens on other search result pagination pages.

## Steps to reproduce
1. Go to User Management on portal
2. Search with some text with many result
3. Scroll down and click to the next page
4. See error message

## Expected result
Should be able to show the next page of result normally.

## Video

User info is masked:

https://github.com/authgear/authgear-server/assets/12539486/e46f631b-c5ad-45e0-a9ef-893f4599ef6e

**Comment by tung2744** [comment]
@louischan-oursky This problem occurs because we used [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) of elasticsearch. In other places, we assume the cursor is something like `offset:10`. When using elasticsearch, it is an object returned from the elasticsearch api.
This bug cannot be fixed, because if fact our ui is incompatible with the search_after parameter. We need to obtain the cursor from the `sort` field of the elasticsearch result, meaning that if we want to get a cursor pointing to page 4, we must be on page 3. However, the current ui allow us to jump to page 4 from page 1. In this case, we have no way to obtain the cursor.

By searching `CursorToSearchAfter` in code, it seems only user search is using `search_after`. What do you think if we simply switch to `from` param so that we can pass any offset to it?

**Comment by tung2744** [comment]
@fungc-io After discussed with louis, we think that letting user to select the page when searching user seems not very useful. If there are too many results, the user can just type more to reduce the results. Therefore we suggest to remove the pagination for search result in this screen and only display the top 100 items. Note that If the user didn't type anything in the search bar the pagination can be keep.
We can also display some text like "Search results are limited to 100 rows, please modify your keyword if you didn't find what you want." at the bottom to let user know the search result is not fully displayed.
What do you think?

**Comment by fungc-io** [comment]
I think it's not unlikely that a user want to search more than 100 items..
e.g. What if I want to export all gmail.com users, can it be done using Admin API if not the portal?

**Comment by louischan-oursky** [comment]
> What if I want to export all gmail.com users, can it be done using Admin API if not the portal?

This is a different use case. We do not support export officially yet. Typically export paginates through the result set without the ability to skip a page (i.e. this pagination does not support page number, must iterate from the beginning til the end), and the output is a archive (zip file) containing a file (csv).

The reason for the proposed change is that page-number pagination would cause performance issue if you query the page 99 of gmail.com users and the project has ten of thousands of them.

So with the proposed change, your use case cannot be done. Even if we fix the bug, the result set is still limited to [first 10000 hits](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/paginate-search-results.html), your use case can only be done if the project has not many users.

**Comment by tung2744** [comment]
I think what we cannot support is letting user to skip pages, e.g. user want to view page 3 from page 1.
However for this use case:
> What if I want to export all gmail.com users, can it be done using Admin API if not the portal?

User can visit the users page by page, so as long as we support cursor in the api it will be possible.

**Comment by fungc-io** [comment]
What if the user really don't have a very precise searching keywords but I need to search some users in the middle?

> User can visit the users page by page

How about instead of skip page, when it's viewing search result,
- Show the top 100
- Click "Show more"
- Add the next 100 to the end of list
- Click "Show more", show 100 more.

**Comment by tung2744** [comment]
I think it is possible.

**Comment by fungc-io** [comment]
Hi @crys-tal 
Please help design the new pagination for when searching,
When searching, the pagination buttons on the bottom-right part should disappear,
and became a "Show more" button at the end of list

**Comment by fungc-io** [comment]
As an intermediate fix, 
- limit the search result into 1000 items
- Each page contain 100 items
- Keep the pagination and allow skip (only 10 pages max)
- Show a warning if more the 1000 items are expected
  - `Only showing top 1000 results, please refine the search query if you can't find what you want`

**Comment by fungc-io** [comment]
@tung2744 @louischan-oursky 
Please try add pagination with 100 items per page, and only get the cursors on search.
I tried on staging with a project of 60xx users, searching "@gmail.com" took 35 seconds, wanna see if that help shorten the time needed

**Comment by tung2744** [comment]
I've just tried to query 1XX users with only cursor, and it still took 8secs, which is similar to to original query with the whole user object. I guess the time was spent on making request to elasticsearch. Maybe we can exclude some fields from the source. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#source-filtering

**Comment by fungc-io** [comment]
🤔 can we try that tmr

**Comment by tung2744** [comment]
I've tested to send a request to elasticsearch which result in 110 results inside a pod in cluster, and it is very fast. So it seems not related.

**Comment by tung2744** [comment]
After reviewed some code, I think the performance can be improved by rewriting the user query.
https://github.com/authgear/authgear-server/blob/2023C01/pkg/lib/authn/user/queries.go#L97
The current implementation is creating N+1 queries.

**Comment by tung2744** [comment]
It seems `NewConnectionFromResult` also loaded the user one by one in the query, which seems causing the dataloader to load the data one by one and therefore breaking the purpose of using a data loader.
https://github.com/authgear/authgear-server/blob/main/pkg/util/graphqlutil/connection.go#L24

**Comment by louischan-oursky** [comment]
So even with batching, the performance is still not good enough?

**Comment by tung2744** [comment]
https://github.com/authgear/authgear-server/blob/2023C01/pkg/lib/authn/user/queries.go#L97

I think the problem is here, we are not batching the relation queries.

**Comment by fungc-io** [comment]
This bug is fixed temporarily by removing pagination and show only the top 10 results
Created another issue for the performance issue: https://github.com/authgear/authgear-server/issues/3233
Then we can show more results from the query


![Image](https://github.com/authgear/authgear-server/assets/15207470/a566cee0-cc70-4988-9816-0dc607d14f4d)
