### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3179]
## Problem

In a B2B2B or B2B2C model business, an application usually needs to support multi-tenancy.

This requirements is very common in business SaaS platform, for example, GitHub, Slack, Figma, JIRA, etc.
The applications are used by multiple organizations, and used by their employees

Authgear should support this user model so developers can build these amazing applications easily.

![image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/27472398-a4ab-4571-a001-fb29246ccf8a/3882fe0c-1dc9-4991-ba8b-90ae273a4948?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8yNzQ3MjM5OC1hNGFiLTQ1NzEtYTAwMS1mYjI5MjQ2Y2NmOGEvMzg4MmZlMGMtMWRjOS00OTkxLWJhOGItOTBhZTI3M2E0OTQ4IiwiaWF0IjoxNzIwMDExODg4LCJleHAiOjMzMjkwNTcxODg4fQ.IdniV7CqlHgpXDqv4HhlpLgNWhqTiAWWHgYJAk_5Sg8)

## Appetite

6 weeks

## Solution

* Introduce a new concept called "Organization" to Authgear.
* Users from different organization will see a different login experience (UI)
* Each user can belongs to multiple organization

### Organizations Page

In portal, user can

* create/remove organization
* Set up the branding for the organization (Logo, name, colors of AuthUI)
* Assign users to organizations
* Sent invitation users to organization, manage the invitations
* Each organization is represented by a unique `org_id` generated by Authgear.

### User Management

* In the user listing, perform user search filtered by organization
* In the user details page, view the organization list, assign to or remove from an organization.

### Applications

* In each client application, user can define if this application is used by individuals or organization.
  * If used by individuals, the authentication flow will not include organization related features. The tokens issued will not include org_id.
  * If used by organizations, organization related features will be enabled for this client application.

### Signup

* When triggering sign up from SDK, Include the org_id, so the user will see the signup UI in the organization's branding.
* After signup, the user will be assigned to that organization automatically, and redirected back to the application
* If `org_id` is not included, a user without organization is created. After redirection, the application should handle this case by themselves.

### Invitation

* Admin can send invitation emails to users by Admin API or from the portal
* The invitation email should show the organization name
* The email includes a link for signup
* The link can also be generated alone without Authgear sending the email using the built-in email template
* After signup, the user is assigned to the organization and redirected to the application.
* The invitation can be revoked before the user accepts it.

### Login

* When triggering login from SDK, Include the org_id, so the user will see the login UI in the organization's branding.
* After login, the user is logged in to the organization.
* If `org_id` is not included, the user should select the organization from a list in the AuthUI before redirected back to the application.

### Tokens

After authentication, the application should know which organization did the user logged in to. And the list of organizations they belongs to.
The `/token` endpoint should response

* The ID Token contains `org_ids` that represents all organizations that users belongs to
* The Access token contain the `org_id` that the user logs in to.

### Competitor Analysis

Some analysis on the similar features provided by the competitors:

[https://www.notion.so/oursky/How-Organization-works-on-other-competitors-466eadd1118c4f6ea779eacb9655325f?pvs=4](https://www.notion.so/oursky/How-Organization-works-on-other-competitors-466eadd1118c4f6ea779eacb9655325f?pvs=4)

## Rabbit holes

// WIP

## No-goes

Some nice-to-have features that are NOT covered in this pitch:

* Support "roles" in organization
* Important: **Social/Enterprise connection to Organization.**
  * e.g. End-users login by ACME Inc ADFS connection will be automatically assigned to ACME Inc's organization
* Signup flows are always identical for different organizations, only differs in brandings
  * No different login strategies for different organizations
* Organization-first login flow is not supported.
  * i.e. If org_id is not provided when triggering authentication, the user must log in with their credential first and select the organization later.

**Comment by chpapa** [comment]
I suspect this is too important to miss:

> Social/Enterprise connection to Organization.

As many orgs would need to configure their particular AD/ADFS/LDAP/Google workspace login.

If we don't do it in the first 6 week pitch, we need to ensure the design allows further enhance with this in future

**Comment by fungc-io** [comment]
Agree that's an important feature, but i think it's not essential in the first phase.
We should include it in our design, and develop it in the next phase.

**Comment by fungc-io** [comment]
Converted into project: [Organizations​](https://linear.app/authgear/project/organizations-7a0df81d684f)
