### ISSUE TITLE
[Demo Webapp] Cookies Sessions on Demo Webapp not working

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#3197]
## Background:
Device / Browser (OS version): Chrome 114.0.5735.198 on Mac 13.4.1
Build: staging 2023-07-05.0, Retested on: 10 July 2023

## Description:
The demo web app doesn't work with the old webapp for cookies, Client ID `f330284f5fc624b4`,  which has become legacy. 

A newly created Traditional Web App , Client ID `e079ddbd68468f3c`, with params copied from the legacy app, also doesn't work with the demo web app.

## Steps to reproduce:
1. Go to authgear-demo-webapp
2. Select Cookie in Session Type
3. Use old legacy Client ID `f330284f5fc624b4`
4. See Login failed with both normal sign in or anonymous
5. Go to Admin portal, Create new Traditional Webapp
6. Go back to Demo we app Use the new Client ID `e079ddbd68468f3c`
7. See Login failed with both normal sign in or anonymous

## Expected result:
Cookie session should still work in demo webapp.

## Screenshot:
<img width="1633" alt="image" src="https://github.com/authgear/authgear-server/assets/4337525/61f52646-ff58-42de-b06d-3ade875897a3">

**Comment by joyzoursky** [comment]
grouped in #3331
