### ISSUE TITLE
[WeChat Login] Issues found when Sign in with WeChat on customer app

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3211]
On our client project https://github.com/oursky/te-merchant/issues/1421, we observed the following behaviours through WeChat login: 

**Problem 1:**
If I open app as anonymous, then click "Sign up" button in app (promote user), and proceed with a WeChat user who has already signed up, it will show unexpected error.

**Problem 2:**
If I open app as anonymous, then click "Login" button in app, and kill the WeChat app on my device, then proceed with WeChat login on the app, it shows a TypeError: Network request failed.

**Problem 3:**
The buttons in the web view allows user to click for multiple times, and sometimes it will call the action for multiple times as well and ends with a page is invalid error.

**Problem 4 (seems to be specific account problem):**
Seems my WeChat account is broken in the app, when I login (avoiding the above problematic steps), it always shows that my login is expired after a few seconds.

Problem 1-3 should be Authgear issue but we don't have other test account to test on our demo apps. So please developers to help check on the client project directly. More details and related video can be found in the original project.

**Comment by fungc-io** [comment]
an issue was also created here: https://github.com/authgear/authgear-sdk-js/issues/247
