### ISSUE TITLE
Support app2app configuration in portal

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3231]
![Image](https://github.com/authgear/authgear-server/assets/34942210/c0752ea0-6480-4b6f-8e73-6b48e686193c)

@fungc-io I suggest to update the portal as shown in the image, please see if any thoughts?

**Comment by fungc-io** [comment]
I think App2App login should belong to "Authentication" rather than "Application" when the user finding for it.

<img width="330" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/882d6350-b3da-444d-979a-e33bb798fe3a">

**Comment by tung2744** [comment]
@fungc-io 

1. It is a per application config
2. It requires other settings in application to work, such as redirect uri
3. It seems "Authentication" controls authentication methods, such as otp / password. In developer perspective app2app is not an authentication method but about how applications share session with each other.

**Comment by louischan-oursky** [comment]
> It seems "Authentication" controls authentication methods, such as otp / password. In developer perspective app2app is not an authentication method but about how applications share session with each other.

If we put "App2App" under Authentication, I guess the developer will find it easier. On that page we can briefly explain what it is, and direct the developer to configure app2app in the Applications screen.

I just realize we lack the terms to refer to "App A" and "App B". In the spec, I see Tung used the term "the authenticating client" to refer to "App B", but we do not have a term for "App B".

**Comment by louischan-oursky** [comment]
> I suggest to put this 2 config components into feature flag and treat it as experimental. Only enable if the client request it or later when the feature is mature.

Agree.

**Comment by tung2744** [comment]
One point to note: I think we only display app2app options for native apps. Because app2app is not supported in other platforms.

**Comment by tung2744** [comment]
Some suggested changes in the copy writings:

Description of app2app enable toggle:

`Allow this application to handle App2App requests from other applications.`

Because it actually doesn't affect requests **from** this application, it only allows handling app2app request **to** this application.

Description of migration:

`App2App login requires a refresh token generated after App2App login enabled. Enable Migration mode will allow old refresh tokens to participate in app2app login. This mode is less secure and not recommended.`

It seems device key is implementation detail and user / developer have no idea about it. So I updated the wordings a bit to hide it from the description.

@fungc-io See if they are ok?

**Comment by fungc-io** [comment]
looks good on staging
