### ISSUE TITLE
Cannot receive non-blocking event when one of the handlers return errors

### ISSUE THREAD

**Issue by cychiuae** [authgear/authgear-server#3232]
**Describe the bug**
Let's say I have 4 non-blocking event handlers configured. If the 2nd handler return non-2xx status code, the 3rd and 4th handlers cannot receive the event. 

**Authgear Version**
 - Version: SaaS [20/07/2023]

**Expected Result**
For non-blocking event, all event handlers should receive the event.

If handler return non-2xx status code,
https://github.com/authgear/authgear-server/blob/da05503570ee10582edc677e58282adc15913b07/pkg/lib/hook/hook_web.go#L135-L139

the err propagate up to here
https://github.com/authgear/authgear-server/blob/da05503570ee10582edc677e58282adc15913b07/pkg/lib/hook/sink.go#L157-L160

Then, the chain is stopped.

**Comment by fungc-io** [comment]
Thanks for reporting the bug, we should be able to fix it in the next project cycle.
