### ISSUE TITLE
Improve performance of list user query

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3233]
Re: https://github.com/authgear/authgear-server/issues/3176

Now only the top 10 results are shown
We would like to increase the number with pagination of 100 entries per page

![image](https://github.com/authgear/authgear-server/assets/15207470/0f8efa30-bba3-47fb-a521-d5c3172bbc43)

TODO:

- [ ] Refactor user queries so that it doesn't create N+1 queries on loading users. https://github.com/authgear/authgear-server/blob/2023C01/pkg/lib/authn/user/queries.go#L97 

---

- [x] Rewrite user.Queries
    - Reduce number of queries
        - [x] identity.Service should implement new method for batch querying identities
            - ListByUserIDs(userIDs []string)
        - [x] authenticator.Service should implement new method for batch querying authenticators
            - List(userIDs []string)
        - [x] verification.Service should be re-implemented to batch querying verification statuses
            - Rewrite GetVerificationStatuses(is []*identity.Info) to accept identity from multiple users
        - [x] stdattrs.ServiceNoEvent should be re-implemented to reduce number of queries
            - Rewrite DeriveStandardAttributes to accept multiple userIDs, and issue less queries
    - [x] Rewrite GetMany to use the new methods above
    - [x] Rewrite Get to use GetMany with one item

**Comment by fungc-io** [comment]
@tung2744 please help fill in the technical details of this issue
Thanks! 🙏

**Comment by tung2744** [comment]
This problem has significant impact on performance when the database latency increases. Therefore might need to fix it before supporting multi region database.

**Comment by tung2744** [comment]
Added some technical details, see if you have any opinion? @louischan-oursky

**Comment by louischan-oursky** [comment]
Looks good to me.

**Comment by tung2744** [comment]
Although this improved the performance, the signup flow is still slow if the database latency is high. I think I would like to spend more time to investigate it.
