### ISSUE TITLE
Allow cancelling developer plans

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3237]

**Comment by tung2744** [comment]
@fungc-io If we cancelled developer plan, as developer plan doesn't appear in portal, the user will not be able to reactivate the plan. Do you think it is ok?

**Comment by tung2744** [comment]
For custom plans, the cancel dialog looks this:

![Image](https://github.com/authgear/authgear-server/assets/34942210/5a4d670c-b72d-4ad4-8690-2f0aed790eaa)

**Comment by fungc-io** [comment]
> If we cancelled developer plan, as developer plan doesn't appear in portal, the user will not be able to reactivate the plan. Do you think it is ok?

ok 👍 

> For custom plans, the cancel dialog looks this:

Awesome 👍

**Comment by fungc-io** [comment]
tested ok
