### ISSUE TITLE
Identity duplication checking does not respect userID

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3261]

**Comment by fungc-io** [comment]
I've tested the following cases

- Signed up with Google Login:
  - Login with Google Login successfully in login page
  - Login with Google Login successfully in signup page
  - Signup with the email address: It shows: `This email is associated with an account. Do you want to sign in with Google?`
  - Login with the email address: It shows: `This identity cannot be found. Please ensure it is correct.`
- Signed up with email
  - Proceed Google Login in signup/login page: it says: `This email is associated with an account. You can link it with your Google account via the settings page after signing in.`

**Comment by louischan-oursky** [comment]
Related issue https://github.com/authgear/authgear-server/issues/3260

**Comment by fungc-io** [comment]
@louischan-oursky sorry is this issue completed? I forgot what the symptom is with this issue

**Comment by louischan-oursky** [comment]
The issue to track the bug that caused the rollback of the deployment. The original symptom of the bug is cannot sign in with Google. When we discovered the bug, we rolled back the deployment. I opened this issue to track the fix of the bug. The bug was fixed by https://github.com/authgear/authgear-server/pull/3262. The fix was deployed https://github.com/authgear/authgear-server/commits/2023-08-04.0?before=0e0e0a20c4513c83f9fe161cf5b6f9ec9372b675+35&branch=2023-08-04.0&qualified_name=refs%2Ftags%2F2023-08-04.0

**Comment by fungc-io** [comment]
ok thanks 👍
