### ISSUE TITLE
Support a approved free plan

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3291]

**Comment by fungc-io** [comment]
If a user:
- enabled Mobile passwordless login
- is in limited free plan

show a message in blue

> To avoid spam content, free plans are limited to send 5 SMS and Whatsapp message by default. To apply for an increase of limit in your project, please complete [the application form](https://form.typeform.com/to/pkFftzs5)

<img width="813" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/2b4ee9cb-ee55-45ef-aee3-04166532b26e">

Show the bar here:
<img width="1177" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/0972a57e-094e-4162-aec4-5dbc7a4edd58">

And here:
<img width="1379" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/2d84f960-ef63-4154-8ce1-48f67ae852d9">

**Comment by chpapa** [comment]
To avoid spam SMS, free plans are limited to sending 5 SMS and Whatsapp message by default. To be eligible for 100 free SMS/Whatsapp/mo, please complete [the application form](https://go.authgear.com/portal-support)

Replace the link of Application form to: https://go.authgear.com/portal-support

**Comment by chpapa** [comment]
BTW, what's the error message we should at auth UI for this? Maybe we should add that as well..

**Comment by fungc-io** [comment]
now on AuthUI it's showing:
> [To Developer] Your project has exceeded the usage limit. Please review your subscription.

**Comment by chpapa** [comment]
@fungc-io probably should have another issue, for us to send email notification (and internal notification to us) when a project hit certain limits that needs attention.
