### ISSUE TITLE
Show a message bar if project quota is reached

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3293]
Show a message bar in the projects screen if the project quota is reached.

**Comment by fungc-io** [comment]
Show a blue message bar on the top of `/projects`

> You have reached the maximum number of projects in your account, please apply for an increase by completing [this form](https://form.typeform.com/to/pkFftzs5)

**Comment by fungc-io** [comment]
Replace the link of Application form to: https://go.authgear.com/portal-support
