### ISSUE TITLE
[Demo App, App2App] App 2 will stuck at Loading if App 1 is not authenticated

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#3309]
## Background:
Device / Browser (OS version): Pixel 5a (Android 13)
    * Android (App1): App Center - Authgear demo Android Version 1.0 (1691638367)
    * Android (App2): App Center - Authgear demo Android 2 Version 1.0 (1) Aug 08, 2023 at 18:41

## Description:
App 2 will stuck at Loading if App 1 is not authenticated, with all buttons disabled, user need to kill app to restart

## Steps to reproduce:
1. Open App 1 and App 2
2. Fill in the config 
* Application 1 (App1):
    * Client ID: example1
    * Endpoint: https://app2apptest
    * After filling it, tap Configure
* Application 2 (App2):
    * Client ID: example2
    * Endpoint: https://app2apptest
    * App2App Endpoint: https://authgear-demo-android/app2app/authorize
    * After filling it, tap Configure
3. In App2, tap Authenticate App2App, without Authenticating in App 1 beforehand
4. See error in App 1
5. Go back to App 2, see it stuck at Loading

## Expected result:
App 2 should timeout when App 1 is not Authenticated.

## Screenshot:
App2 stuck at Loading
<img width="410" alt="Screenshot 2023-08-14 at 12 39 26 PM" src="https://github.com/authgear/authgear-server/assets/4337525/a35c0b82-d2ca-4f86-9cee-2d2b0799fde3">

Error from App1
<img width="406" alt="Screenshot 2023-08-14 at 12 38 35 PM" src="https://github.com/authgear/authgear-server/assets/4337525/ab4271a4-89b8-4195-9d2d-6ed270addee6">

Video

https://github.com/authgear/authgear-server/assets/4337525/fc082278-9970-43aa-b8d4-a54f6e1c2bf2

**Comment by tung2744** [comment]
Demo app problem, maybe should reject request instead of throw error.

**Comment by joyzoursky** [comment]
Probably won't fix this one, close first
