### ISSUE TITLE
Handle change tab (Pivot item) discards form state in the tab item

### ISSUE THREAD

**Issue by axolotl0212** [authgear/authgear-server#333]
This is caused by pivot item is dismounted when user changes tab, causing state in the tab discarded

As we warn user when user tries to leave the page with dirty form, we should either warn users when user tries to switch tab with dirty form, or persist the form state

Possible solution includes:
- try to persist the state
  - perhaps move state to parent (component with `<Pivot>`) ?
  - local storage ?
- try to find callback on tab change
  - try to block tab switching and show dialog similar to navigation blocker and warn user

**Comment by louischan-oursky** [comment]
> perhaps move state to parent (component with <Pivot>) ?

Use this solution.

**Comment by louischan-oursky** [comment]
@nicolaslee2775 beware of this bug.

**Comment by nicolaslee2775** [comment]
@axolotl0212 You can set `alwaysRender={true}` to PivotItem if you don't want tab child unmount when changing tab.

**Comment by axolotl0212** [comment]
> @axolotl0212 You can set `alwaysRender={true}` to PivotItem if you don't want tab child unmount when changing tab.

Nice, seems like this is the easiest solution, will follow your approach in password screen such that the behaviour is consistent.

**Comment by nicolaslee2775** [comment]
@axolotl0212 I think warning user before changing tab is better. As user may not know that other tab has unsaved changes.
