### ISSUE TITLE
[Billing] Payment stuck when upgrade if it is the last day of a month

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3332]
## Background
- Environment: Staging
- Browser: Chrome on Mac
- Test project: qa-smoke-001, qa-smoke-002

## Description
If it is the last day of a month, e.g. 31 Aug, if the user tries to upgrade the project a pay the bill, it will stuck at the payment processing screen.

## Steps to reproduce
1. Select a "Free" plan project
2. Go to Billing page
3. Upgrade to "Startup" plan
4. Proceed to payment
5. See green tick at stripe and redirect back to the portal
6. Page stuck at payment processing

## Expected result
Should be able to finish the payment successfully as on other days of the month.

Please check for the 1st day, middle date, and last day of month for subscription.

Please also help recover the testing project `qa-smoke-001` and `qa-smoke-002`.

## Crash log
https://oursky.slack.com/archives/C01P0NCS3F1/p1693479131632079

## Screenshot
<img width="1021" alt="Screenshot 2023-08-31 at 6 57 03 PM" src="https://github.com/authgear/authgear-server/assets/12539486/c3ea0c69-24ea-48bd-9344-2de9b2999f2b">

**Comment by fungc-io** [comment]
@tung2744 please prioritize and check this bug first, i'm moving it to focus on today

**Comment by fungc-io** [comment]
Fixed on staging.
@joyzoursky can you retest it on 31 Oct (The next window that this bug will happen)?

**Comment by joyzoursky** [comment]
Tested on 30 Sep, no stuck on upgrade or downgrade.
Scheduled to retest on 1 Oct and 31 Oct as double check.

**Comment by fungc-io** [comment]
Tested today on 31 Oct. The upgrade is successful
