### ISSUE TITLE
[Social Login] Unexpected error when login with Google if the account has email/phone as primary login

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3334]
## Background
- Environment: staging
- Testing project: qa-app
- Testing device: iPhone SE (iOS 16.4.1 (a)), Samsung Galaxy A71 (Android 13)
- Testing demo app: iOS, Android Native demo apps
- Demo app build: iOS TestFlight 1.0 (1692936706), Android App Center 

## Description
When the user has first signed up with email, then open settings and connect their Google account. Then when the user tries to login with Google, it will show unexpected error.

The user can login normally if social login if the account's primary login method.

Previous issue and fix related to social login https://github.com/authgear/authgear-server/issues/3261 (for ref).

## Steps to reproduce
1. Configure to the testing app (with Social login supported)
2. Sign up an account with email
3. Open Settings
4. Go to Passwordless section
5. Connect a Google account
6. Logout
7. Login again but with the connected Google account
8. See unexpected error when login

## Expected result
Should be able to login successfully.

## Screenshot
<img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/39e52964-e55d-4829-a563-3e496f30ebfe" /> <img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/7531c062-b3ef-485d-bf58-8003a581ca78" />

**Comment by fungc-io** [comment]
Thanks for reporting
i've tested on Production and cannot see such issue. 
Maybe a staging issue or a project specific bug

**Comment by tung2744** [comment]
I am not able reproduce it in staging & local. @joyzoursky Could you provide the exact user id so I can check the data?

**Comment by fungc-io** [comment]
The criteria to produce the bug is found:
1. Primary authenticator is email passwordless
2. Adding another oauth provider and its email matches the primary authenticator

It's fixed in #3340 and will be deployed to staging soon

**Comment by fungc-io** [comment]
Tested ok on staging
