### ISSUE TITLE
Return Client ID in Session Node

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3353]
**Problem**

- In the Session node, it only contains the following info
  - `createdAt`
  - `createdByIP`
  - `displayName`
  - `lastAccessedAt`
  - `lastAccessedByIP`
  - `type`: `IDP` or `OFFLINE_GRANT`
  - `updatedAt`

If there are multiple sessions from the same device, say multiple apps, the developer is unable to identify which sessions correspond to which app. So they cannot see which app are logged in (have valid tokens) and it's hard to revoke the specific token related to the app.

**Appetite**

2 weeks

**Solution**

- Suggest to show the **Client ID** of the session so the dev knows which app it is.
- For `type = "IDP"`, client ID should be `null` because the session is for SSO, i.e. it's a device-wide session, it's not specific to a certain client ID.

**Rabbit holes**
> Details about the solution worth calling out to avoid problems

**No-goes**
> Functionality or use cases we intentionally aren’t covering to fit the appetite

**Comment by louischan-oursky** [comment]
Remember the type of clientID should be `*string`.

**Comment by tung2744** [comment]
@fungc-io Do we need to add client id in portal session list too?

**Comment by tung2744** [comment]
- Currently settings screen grouped sso session together
- Portal lists session from user query as is

- Rewrite the query in portal such that it groups the session in the same way in settings

**Comment by fungc-io** [comment]
@tung2744 yes please

**Comment by fungc-io** [comment]
@tung2744 I found a problem


![Image](https://github.com/authgear/authgear-server/assets/15207470/f6b141d7-c50a-485a-872c-12f0162332e1)

The default length of our random generated client ID is truncated in the table, which is missing the last 3 characters, and it looks weird,
Can we adjust the width so it is showing the full client id?

**Comment by fungc-io** [comment]
checked ok
