### ISSUE TITLE
Whatsapp OTP is prompted twice in login

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3366]
**Describe the bug**
Whatsapp OTP is prompted twice in login

**Authgear Version**
 - Version: SaaS 2023-09-13.0

**To Reproduce**
1. Configure the project to login with phone and Whatsapp OTP
2. Trigger authentication
3. Enter phone number
4. Enter OTP
5. See the OTP page again
6. Enter OTP again
7. See authenticated.

**Expected behavior**
Whatsapp OTP is prompted once.

**Screenshots**

**Client Env (if applicable, please complete the following information):**
 - Device: [e.g. Desktop, Smartphone]
 - OS: [e.g. Windows, iOS]
 - Browser Version [e.g. 22]

**Additional context**

**Comment by tung2744** [comment]
Confirmed reproducible. Only triggered if the phone number identity is not verified. And after login once, the identity will become verified and won't trigger this bug.
