### ISSUE TITLE
Allow all known origins of app to be redirect uri

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3379]
~If the redirect uri is relative, it should be interpreted as `{{currentOrigin}}{{redirect_uri}}`.~

According to [oauth spec](https://datatracker.ietf.org/doc/html/rfc6749#section-3.1.2), it must be an absolute URI.

Maybe we could simply allow all known origins to be redirect uri.

Related to https://github.com/authgear/authgear-sdk-js/issues/248

**Comment by louischan-oursky** [comment]
- Add all known origins of a project to `AppContext`
- Make sure database configsource construct and cache `AppContext` with origins correctly.
- May need to extract the redirect_uri checking logic into reusable code. In the code, respect all known origins. Make every place uses this code.
