### ISSUE TITLE
New AuthUI

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3388]
## Problem

We observed some problems regarding the current AuthUI 
- The customization options were not enough to fit the user's branding
- The design of the current AuthUI is quite stylized and not compatible with many branding
- There is only 3 color settings (Primary, Text, Background) which make it impossible to finetune the colors. And the Text color generated by the algorithm is not usable if the text color is not `#000000`, basically unusable.

## Appetite

6 weeks (For the first stage, this will be a multiple cycle endeavor)

## Solution

In Stage 1, we would offer 2 layout presets with full customization option in the backend.

### Layout

- You can think of the AuthUI as 2 major components, 1) The center widget 2) the Background
  - The Center Widget house the Title, CTA, Input fields, Buttons, etc, that are related to the current signup/login steps
  - The Background is the logo, the static background, website navigation... which are peripheral to the actual Login UX
- We will offer different layouts for the background component
  - Presets
    - Logo at the middle (1st stage)
    - Logo at top left (1st stage)
    - Header navigation with other links (Later stage)
  - Fully Customization by HTML (Later stage)
- Users can choose 1 layout for their AuthUI, each layout preset will provide their own set of customization options, such as
  - Logo size
  - Logo margins
  - Background
  - Links

### Theming

The user can also adjust the following with fine control:
- Copywriting and CTA
- Colors
    - Background, text, buttons (Including different state)
- Font
- Font size
- Shadow
- Border radius
- Text Alignment
- Logo
- Background image
- Layout
- Darkmode
  - colors and shadow in darkmode
  - always light/always dark/sync with system

### Configurations from the user

There will be 2 level of complexity in the theming options
1. Quick Start
    - By starting with the default AuthUI, which has a bland but pleasant look.
    - User can 1) replace the logo, 2) pick a primary color, 3) change the background color, and call it a day.
    - This is designed for lighter use cases.
2. Advanced customization
    - All the configurations above can be adjusted to fit their branding perfectly.

For either mode, the user will see an instant preview in the portal alongside the knobs.

In the 1st stage, we will only provide the quick start mode in the portal.
We will not have the full configuration in the portal yet, the full theme options can only be changed in the backend.

### User Settings Page

The options will also affect the look of the user settings page offered by AuthUI. But the AuthUI only has 1 layout.

## Rabbit holes

> Details about the solution worth calling out to avoid problems

## No-goes 

> Functionality or use cases we intentionally aren’t covering to fit the appetite

- Do not build the full customization UI in the portal, we want to have the new customizable AuthUI for demo first.
- The signup/login flow is not a part of the theming options, they will be controlled by the "Authentication Settings"

**Comment by arvinhoux** [comment]
Figma Link
https://www.figma.com/file/a02CAVhCmsExNXftqfSvfQ/Authgear-(Shared)?type=design&node-id=4%3A35&mode=design&t=3C8NUpaEzt3nIYUo-1

**Comment by fungc-io** [comment]
Hi @arvinhoux 
Thanks for your help.

As mentioned in our meeting, you need some more info on the flows we need to support

---

- An old design for the AuthUI can be found in Figma in this board: https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?type=design&node-id=3467-12394&mode=design
- There are different flows authgear supports, you can think of them as the user flow in AuthUI
    - Signup
        - 2FA Setup
        - OAuth (Social Login)
        - Passkey setup
    - Login
        - Login with 2FA
        - OAuth (Social Login)
        - Use Passkey to login
        - Passkey setup
    - Combined Signup/Login
    - Re-authentication
    - Anonymous users Promotion
    - Forgot & Reset password
- Basic structure of the signup/login flow
    - Login ID is the first step in signup/login, it includes: email, phone, username
    - 1st factor for authentication includes:
        - Email OTP
        - Email link
        - SMS OTP
        - WhatsApp OTP
        - Password
    - 2nd factor includes:
        - Email OTP
        - SMS OTP
        - WhatsApp OTP
        - TOTP (Authenticator apps)
    - User can switch between these methods if they have it set up
- Authflow is the backend engine that controls the different user flows presented in the UI. You are recommended to read and understand the design of the configuration. This will help you understand what pages and interactions are needed:
    - Technical Design: https://github.com/authgear/authgear-server/blob/main/docs/specs/authentication-flow.md#concepts
        - “Concepts”, "Design” and “Use Case examples” are recommended chapters
- 🔮 See them in action‼️
    - You should use a test project in the demo apps to try out the supported flows.
        - I’ve sent you an invitation on Testflight, you should be able to download the demo app.
        - I’ve take a video about how it’s used on Slack

**Comment by fungc-io** [comment]
Updated Figma: https://www.figma.com/file/l08e1BDjom14TaSrpAvMj5/New-Auth-UI?type=design&node-id=647%3A28859&mode=design&t=9w75kn2aOLlDsuVO-1

**Comment by fungc-io** [comment]
Customization options: https://www.notion.so/oursky/New-AuthUI-Spec-bda3c2b5375a4c7d96352741c365d118?pvs=4

**Comment by arvinhoux** [comment]
Yes, I have set up a corresponding color palette in Figma, and it is located in Local variables, but I'm not sure if you can view it.
Let's discuss the method of text replacement together; it requires comprehensive consideration.
Ok, I can create a simple interactive prototype.

**Comment by chpapa** [comment]
> Yes, I have set up a corresponding color palette in Figma, and it is located in Local variables, but I'm not sure if you can view it.

@arvinhoux but I think the color palette doesn't have the formula of how the color are derived (calculated) from primary color? So your answer didn't really reply to @fungc-io question?

Or in another words, he is asking when users use the basic mode, and if user changed the primary color, how it affect the rest of color palette

**Comment by arvinhoux** [comment]
@chpapa ok, I got it I will supplement and modify the logical relationships when updating the colors.

**Comment by arvinhoux** [comment]
@fungc-io @louischan-oursky @tung2744  

This is the new Figma link, please use this one.
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=568%3A28067&mode=design&t=P4J7tKWdbXtInHof-1

**Comment by tung2744** [comment]
2FA can be skipped by a device token
Add a screen cap of the current authui @tung2744

**Comment by louischan-oursky** [comment]
Use this site https://fonts.google.com/icons to search the icons. Example usage in our codebase

```html
<span class="material-symbols">person</span>
```

**Comment by tung2744** [comment]
@fungc-io @arvinhoux 

<img width="370" alt="Screenshot 2024-01-10 at 3 21 23 PM" src="https://github.com/authgear/authgear-server/assets/34942210/b2e28963-09a8-417d-a437-8dc24c45de1d">

Some screens will have a checkbox for skipping the step in the same device (Using device token), please see the above image for the current design.

Supported screens:
- Enter Password
- Enter otp (sms / whatsapp / email)
- Enter totp (Authenticator app)

**Comment by fungc-io** [comment]
> a checkbox for skipping the step 

(this is for skipping 2FA on trusted device)
