### ISSUE TITLE
Password strength in passowrd setup UX issue

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3392]
The UX of password setup page is strange because it's unclear what strength of password is needed.
Please make the following changes:

1. In the requirement section, Instead of showing the bar indicator, only show the strength requirement in text. Only normal or error state, no need for diff colors for diff strength level.

2. Since the policy is also checked in frontend, If the overall requirements are not met, disable the "Next" button and do not allow the user to proceed.

<img width="491" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/2fcfa6f8-9260-40b4-9f11-5d4817b80ff3">

**Comment by fungc-io** [comment]
@tung2744 lol
thanks for pointing it out "You new password must be Very unguessable" sounds very absurd too.

I've just quickly check the UX of common design, usually the strength requirement is not shown in the policy list.
Usually just a note saying "Please use a stronger password" below the password input

Let's do this:
<img width="381" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/2341e406-86f8-4adc-b2d0-bd2e8c8c814d">

**Comment by louischan-oursky** [comment]
I suggest we change the tone of the sentence so that it can always be there. If the tone is like "Please use a strong password", that sounds like an error message, which should only appear when the password is weak. But the strength indicator is real time. When the end-user is typing the password, flickering will occur.



I suggest we change it to something like "Password is strong enough"

https://github.com/authgear/authgear-server/assets/15082564/8366df40-3ce4-4adc-bc65-020eb488b582

**Comment by fungc-io** [comment]
"Please use a strong password" is shown only when the requirement is not meet. And no need to show the message if the pw is strong enough. To avoid flickering, we can keep it in one line, or reserve a margin for the line
- Default don't show text when pw is empty: ` `
- `Strength: Fair - Please use a stronger password` (in red)
- `Strength: Unguessable` (in green)

Reference from the design in Woocommerce for min strength requirement - 

GIF taken from: https://rudrastyh.com/woocommerce/password-strength-meter.html
![password-strength-meter-woocommerce](https://github.com/authgear/authgear-server/assets/15207470/41e574d4-4da1-4fc9-a49a-4e6304b3602f)

**Comment by fungc-io** [comment]
@calumhale can you help create the flow and design in Figma for this change?

**Comment by fungc-io** [comment]
Design:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?type=design&node-id=9933-113961&mode=design&t=M4X5wMJ8VnEtw2Md-4

![image](https://github.com/authgear/authgear-server/assets/15207470/1295cf22-c912-4030-a3c3-039963123d41)
