### ISSUE TITLE
CSP and GTM

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3423]
GTM supports custom HTML tag, which could inject any inline script or external script sources. But our CSP is not configurable. One implication is that a developer may not be able to integrate Mixpanel with GTM.

**Comment by roxk** [comment]
Tested GTM's Custom HTML with
```
<script>console.log("test")</script>
```
It would trigger CSP error.

GTM Custom HTML with
```
<script src="$authgear-script-on-cdn"/>
```
It would _NOT_ triggger CSP error. 

Suggest we also update GTM doc. Add a section for Custom HTML integration and provides links to configure CSP in authgear.

**Comment by louischan-oursky** [comment]
Maybe we can look into this CSP 3.0 feature: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic

**Comment by roxk** [comment]
> For example, a policy such as script-src 'strict-dynamic' 'nonce-R4nd0m' https://allowlisted.example.com/ would allow loading of a root script with <script nonce="R4nd0m" src="https://example.com/loader.js"> and propagate that trust to any script loaded by loader.js, but disallow loading scripts from https://allowlisted.example.com/ unless accompanied by a nonce or loaded from a trusted script.

That would require authgear server to append nonce to _all_ scripts it load @_@ Otherwise existing sentry script etc might break

**Comment by louischan-oursky** [comment]
If `'strict-dynamic'` is present, then sources other than `nonce` or `hash` are IGNORED.

**Comment by louischan-oursky** [comment]
- Specify `script-src 'strict-dynamic' 'nonce-NONCE' <host-sources> ['unsafe-inline'] 'self'`
