### ISSUE TITLE
[CD-8] Cooldown issues for the 8th cooldown

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3431]
**SDK Issues**
- [x] https://github.com/authgear/authgear-server/issues/3427
- [x] https://github.com/authgear/authgear-server/issues/3428

**Auth Flow Followup:**

- [x] https://github.com/authgear/authgear-server/issues/3430

**QA**

- [x] https://github.com/authgear/authgear-sdk-js/issues/250

**Code quality**

- [ ] #3098 
- [x] #3479
- [x] https://github.com/authgear/authgear-server/issues/3338

**Bugs**
- [x] https://github.com/authgear/authgear-server/issues/3379
    - https://github.com/authgear/authgear-server/pull/3440 
- [x] https://github.com/authgear/authgear-sdk-js/issues/248
- [x] https://github.com/authgear/authgear-server/issues/3149
    - https://github.com/authgear/authgear-server/pull/3447

**Lower Priority**
- [ ] https://github.com/authgear/authgear-server/issues/3133
- [ ] https://github.com/authgear/authgear-server/issues/3189
- [ ] https://github.com/authgear/authgear-server/issues/3367
- [ ] https://github.com/authgear/authgear-server/issues/3392

**Comment by fungc-io** [comment]
@louischan-oursky @tung2744 
The cooldown period will be from 1-14 Nov.
Do you want to add other issues to the list above?

**Comment by louischan-oursky** [comment]
These two
- https://github.com/authgear/authgear-server/issues/3427
- https://github.com/authgear/authgear-server/issues/3428
