### ISSUE TITLE
`state` is only available in `user.pre_create` blocking event, but not `user.created` or `user.authenticated`

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3443]
**Describe the bug**
`state`, if provided by the developer, should appear in `user.created` and `user.authenticated` event.

**Authgear Version**
 - Version: SaaS

**To Reproduce**
1. Register a webhook for `user.pre_create`, `user.created` and `user.authenticated`
2. Provide `state`
3. Observe that only `user.pre_created` has `state` propagated.

**Expected behavior**
All three events have `state` if `state` was provided.

**Screenshots**
N/A

**Client Env (if applicable, please complete the following information):**
N/A

**Additional context**
N/A

**Comment by fungc-io** [comment]
We may want to sanitize the state in the auditlog

**Comment by fungc-io** [comment]
checked ok, i can see the state in user.authenticated
