### ISSUE TITLE
[AuthUI] Web view does not anchor to top when error message is displayed

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3445]
## Environment
- Server: Staging
- App: qa-authflow (Phone + Passwordless)
- Tested user agent:
  - iOS Native demo app
- Device: iPhone 15 (iOS 17.0.3)

## Description
When error message is shown on top of the web view, the page scroll position always stays at the current position, and cannot see the error message on top as it is blocked by the web view bar.

Should be an existing issue for a long time but I can't find an opening issue, so created a new one here.

## Steps to reproduce
1. Setup a project
2. Sign up a new user on iOS or Android app
3. Logout
4. Try to sign up with the same phone number or email
5. Looks like no response as there is actually an error message on top hidden behind the web view bar

Same problem occurs on other kinds of errors, e.g. wrong OTP.

## Expected result
If the error message is always on top, it should anchor to top position when there is error displayed, so user can see the error.

## Screenshot

https://github.com/authgear/authgear-server/assets/12539486/b53c079b-c4dc-4484-8055-a1b78ecdfcf2

<img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/b9d5184d-deb4-40cd-958f-1486fc78128a" />

**Comment by tung2744** [comment]
I can fix it in desktop by using sticky position, but seems difficult to be fixed in mobile. The mobile browser such as safari will make the page scrollable, and sticky is not working.

**Comment by tung2744** [comment]
@fungc-io @joyzoursky 

Please see this video for the latest fix:

https://github.com/authgear/authgear-server/assets/34942210/78bf2d52-6ee1-42c3-a042-56cc9a6692f6

**Comment by joyzoursky** [comment]
@tung2744 seems ok. What did you press at 0:07?
And double confirm keyboard will still show and auto-focus when first enter page (no top bar showing) right?

**Comment by tung2744** [comment]
@joyzoursky  I pressed signup again.

And yes, the initial auto focus is still there.

**Comment by joyzoursky** [comment]
I think we can merge first so we could start testing

**Comment by fungc-io** [comment]
@tung2744 
thanks! 🙏  the video looks ok
Please merge it and we can test

**Comment by fungc-io** [comment]
tested ok
