### ISSUE TITLE
[AuthUI] Country code dropdown does not stick to the field when display

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3446]
## Environment
- Server: Staging
- App: qa-authflow (Phone + Passwordless)
- Tested user agent:
  - iOS Native demo app
- Device: iPhone 15 (iOS 17.0.3)

## Description
When there are only a few country options configured for the project, when AuthUI user selects the country code in app, the country code dropdown display is quite far from the field. It is expected to stick closer to the field instead.

## Steps to reproduce
1. Setup a project with phone number, and only enable a few country codes
2. Open mobile app and start authenticate
3. Click on the country code
4. See a country code dropdown menu but it is quite far from the field

## Expected result
Country code dropdown should show sticky to the field.

## Screenshot

<img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/b2c781f7-f414-4726-b542-7eff9864306a" />

## Other edge case UI problems

Chrome responsive - Samsung Galaxy Fold size:

<img width="1000" alt="Screenshot 2023-11-02 at 7 33 52 PM" src="https://github.com/authgear/authgear-server/assets/12539486/3726793a-2bdf-4c08-87c5-7c59ccefcf27">

Chrome browser - window innerwidth 500:

<img width="612" alt="Screenshot 2023-11-02 at 7 34 27 PM" src="https://github.com/authgear/authgear-server/assets/12539486/719f4516-9798-4c81-99ab-03cfa9c9a415">

**Comment by tung2744** [comment]
It seems the expected behavior of  https://github.com/jackocnr/intl-tel-input

There isn't an option to force using desktop / mobile dropdown ui at the moment, but there is an open pr:
https://github.com/jackocnr/intl-tel-input/pull/1463

**Comment by fungc-io** [comment]
when the screen is very narrow, like folded galaxy fold, the tel input selection will bleed outside the view



![Image](https://github.com/authgear/authgear-server/assets/15207470/89ac8eb8-bfbd-4653-9d3f-492f3c5f28b1)

A minor issue tho, closing this issue first
