### ISSUE TITLE
[AuthUI] Slow performance when opening authenticate web view

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3451]
## Environment
- Server: Staging
- App: qa-authflow
- Build: iOS TestFlight Authgear Demo iOS 1.0 (1698821396)
- Device: iPhone 15 (iOS 17.0.3)

## Description
After implementing new authflow, it seems taking a longer time to open the Authenticate web view on demo apps (~6s).

## Video
https://github.com/authgear/authgear-server/assets/12539486/f32399f8-ccd1-4548-a342-d00885826b10

**Comment by joyzoursky** [comment]
@fungc-io @louischan-oursky @tung2744 Retried many times and it has different results each time.
- Often happen: New auth flow project a little bit slower than old project, but both around 5s, and the new project is usually a little bit slower (but sometimes it is the faster one too)
- Sometimes happen: Both load slowly suddenly (> 5s), and the old project shows content first
- Seldom happen: Both load fast suddenly (< 3s)

It seems that the main cause of the slow issue is not related to the new auth flow, as when it is slow, both projects will be slow.

**Comment by fungc-io** [comment]
closing as unrelated to authflow
