### ISSUE TITLE
[AuthUI] Show "flow not found" error if proceed after going to forgot password page

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3452]
## Environment
- Server: Staging
- App: qa-authflow
- Build: iOS TestFlight Authgear Demo iOS 1.0 (1698821396)
- Device: iPhone 15 (iOS 17.0.3)

## Description
If user has navigated to the forgot password page during login, then when click Next to proceed the login it will show error page.

## Steps to reproduce
1. Configure email + phone + password (or others)
2. Click "Authenticate" to start authentication
3. Login by email
4. Fill in email and see Enter Password screen
5. **Click "Forgot password"**
6. Go back
7. Fill in password and click "Next"
8. See "flow not found" error

## Expected result
Should be able to proceed normally after accessing forgot password page

## Video

https://github.com/authgear/authgear-server/assets/12539486/27bf429e-7fd8-4ec8-93a6-cbfe41973032

**Comment by fungc-io** [comment]
@louischan-oursky please add me to qa-authflow so i can test it too,
thanks

**Comment by fungc-io** [comment]
tested ok
