### ISSUE TITLE
Update cookie based app docs nginx config

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3476]
We need the Host header for the resolver to work correctly.

```
proxy_set_header Host accounts.authgear-qa-app.pandawork.com;
proxy_set_header X-Forwarded-Host accounts.authgear-qa-app.pandawork.com;
```

And we need to use `/_resolver/resolve` as resolver path.

**Comment by fungc-io** [comment]
@tung2744 Can you help review these pages and suggest the changes?
- https://docs.authgear.com/deploy-on-your-cloud/auth-nginx
- https://docs.authgear.com/get-started/backend-api/nginx

**Comment by fungc-io** [comment]
https://github.com/authgear/docs

**Comment by tung2744** [comment]
Done.
https://github.com/authgear/docs/commit/d8c9460b920acff4d1729e1a2b30dde08c3f077a

I only updated the backend integration guide. For the deploy on your cloud guide, as the context is using authgear in docker with fs config source, the host is not needed so I didn't add in that guide.
