### ISSUE TITLE
Email link (Websocket) is not working in Authflow

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3496]
the websocket for login link is not working properly
After confirming the link in the email, the page is not redirected when going back to the app with AuthUI
The link is verified after refreshing the page in AuthUI

**Comment by louischan-oursky** [comment]
I tested a few times. Only in the first time, the socket was disconnected due to unknown reason. Websocket is not 100% reliable. Maybe we want to add a button to allow the end-user to refresh the page manually if they believe they have approved the link.

**Comment by fungc-io** [comment]
- We will add polling to this screen

**Comment by fungc-io** [comment]
it's working
