### ISSUE TITLE
Complete the default design for all pages

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3497]
Main Pitch: #3388

Based on the new default theme designed, create the detailed pages for the following interactions.
It should include all the states

- Identity
  - Email
  - Phone number
  - username
- Identity verification
  - Email
  - Phone Number
- Authenticators
  - Password
    - Password policies
  - TOTP
  - OTP via SMS
  - OTP via WhatsApp
  - OTP via Email
  - Email Link
  - Passkey
- Account recovery:
  - Forgot password/Reset Password by email link
- Reauthentication
  - By any authenticator
- Account Lockout (Time-based)
- Disabled account (Can be re-enabled by admin)

----

- Generic Error page
  - With & without back button

**Comment by louischan-oursky** [comment]
Do you mean this screen? https://louischan.authgear.cloud/errors/error

**Comment by fungc-io** [comment]
oh, ok thank you
