### ISSUE TITLE
Support reset password by sms otp - Auth ui

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3502]
From https://github.com/authgear/authgear-server/issues/3500

**Comment by tung2744** [comment]
@fungc-io 

I found a problem at the flow end:



![Image](https://github.com/authgear/authgear-server/assets/34942210/f1ed0448-94ed-4e21-8e95-2297f90456f9)


The original reset password success page has no action button, the user will stuck in this page after resetting the password with otp.

Maybe we add a Sign In button, just like forgot password success page?



![Image](https://github.com/authgear/authgear-server/assets/34942210/92d7322b-9d8a-4a2b-95fe-358ee4b5b64e)

**Comment by fungc-io** [comment]
yes, can we write "Back to sign in" on the button?

**Comment by tung2744** [comment]
I found it could be confusing if the "Back to sign in" button always exist, because if user opened the reset password from link in other device, he shouldn't continue sign in in that device. So I think we should only show the button if we are resetting password in the same browser session.

**Comment by fungc-io** [comment]
> So I think we should only show the button if we are resetting password in the same browser session.

👍

**Comment by tung2744** [comment]
@fungc-io Fixed and deployed to staging. Please try again.
