### ISSUE TITLE
Support reset password by sms otp - Portal

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3503]
From https://github.com/authgear/authgear-server/issues/3500

**Comment by fungc-io** [comment]
Update:

1. Sections 
    - "Reset Password"
    - "Basic" -> "Password Requirements"
    - "Advanced" -> "Advanced Password Requirements"
2. Disable irrelevant settings:
    - Disable “Reset Password with email by” or “… phone by” depends on authenticator setting
    - Disable “Reset [link/OTP] valid duration” also depends on setting
    - "Reset by" go before "Valid durations"
3. Put the "Force password change on next login if it does not meet the policy requirements" into "Password Requirements"
3. Add “WhatsApp or SMS”  to “Reset password with phone by”
4. Change heading "Password Policy" -> "Passwords"

**Comment by fungc-io** [comment]
lgtm

**Comment by fungc-io** [comment]
tested
