### ISSUE TITLE
Detect invalid whatsapp numbers and fallback to SMS

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3528]
## Problem 

When sending OOB-OTP via "Whatsapp or SMS" to passwordless login/verify the numbers
Authgear will first send the OTP using whatsapp, and the user needs to manually select "Send via SMS" if they don't have a whatsapp account.

## Solution

- Fallback to SMS automatically if the number is not registered with a whatsapp account
- In our testing, if the number is a vali number but not registered on whatsapp, the API will return "user is not valid".

**Comment by fungc-io** [comment]
@tung2744 
In this project https://demo-enterprise.authgear-staging.com/ , seems it's always sending SMS even when "WhatsApp or SMS" is enabled and the phone number i'm using is registered on whatsapp. Can you check if any issue?

**Comment by tung2744** [comment]
Reproducible with the same project config in local, investigating.

**Comment by fungc-io** [comment]
checked ok
