### ISSUE TITLE
Roles and Groups

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3537]
## Problem

Role-based access control is a common approach to restrict access to certain functions in an applications to authorized users.

In the same project, the applications may have different defined roles. For example:
- In the company bulletin board (A): `admin`, `writer`, `reader`
- In the roster management app (B): `admin`, `manager`, `senior_staff`, `junior_staff` 
- A store manager is always assigned to `writer` in “A” and `manager` in “B”. 

It will be great if the store managers can be assigned to a `store_manager` group and automatically get the corresponding application roles.

## Appetite

6 weeks

## Solution

Introducing Roles and Groups in Authgear:

- Roles are associated with an application. A user can be assign to roles.
- Roles can be associated to a group. A user assigned to a group will automatically receive the entitlement of the corresponding application roles.
- A user can be assigned to many groups.

### Role Creation and Editing

In the portal, developers can define the roles for the applications. They can also assign the users to the roles.

- Name: Display name in the portal
- Key: the string that will be returned in the user info
- Description: Optional description
- Default?: A boolean, the default role to this application if the user sign up without explicitly defining it in the API request

### Groups creation and Editing

In the portal, developers can define the user groups for the applications. They can also assign users into groups

- Group ID: Unique group ID to be used in API
- Name: Display name
- Description: Optional description
- Roles: The application roles which the group members are automatically assigned to.

### Search users by group

In the portal, developers can filter the users by groups. e.g. See all users in the `Manager` group.

### Using roles in the application

Return roles in the JWT and user info as an Array of String. Only the roles in the application are returned, this is determined by the client ID. The user info will not return the roles for other applications of another client id.

The roles can also be obtained from the resolver

### Group and roles assignment on signup

- When creating the users by API, developers can specify the groups and roles the users belong
- In the user pre-create hook, developers can specify the groups and roles the users belong

## Discussion

- Should a role be specific to an application? App B cannot see role in app A? 
- How should the application-specific role returned in Admin API or when there is no client id
  - Will that lead to different representation in userInfo for specific app and in Admin API?
- How should the access token be revoked/refreshed after the roles of the user is updated

**Comment by louischan-oursky** [comment]
> Default?: A boolean, the default role to this application if the user sign up without explicitly defining it in the API request

If we have "Group and roles assignment on signup", I think this is not necessary.

> Return roles in the JWT and user info as an Array of String. Only the roles in the application are returned, this is determined by the client ID. The user info will not return the roles for other applications of another client id.

Does this mean role is specific to a client application? Or the assignment is specific to a client application? What is the use case of this?

**Comment by fungc-io** [comment]
> Does this mean role is specific to a client application? Or the assignment is specific to a client application? What is the use case of this?

Yes, in this design the role is specific to the application. In the cases stated in the background, a `store_manager` may have different `roles` in different application. So the store manager is added to a user group called `store_manager` where they receives the corresponding roles in app A and app B

**Comment by fungc-io** [comment]
Hi @chpapa We were discussing if the "roles" should be under a specific "application".

The idea was to have different `roles` in different applications for a group of users. Then the user groups can be used to model the job positions in the company.

For Example:
![Image](https://github.com/authgear/authgear-server/assets/15207470/b0847ed5-e0b1-4c71-82cd-26a90b7d4d83)

@louischan-oursky expressed concerns that this may make the design more complicated than needed and suggested the developers can achieve a similar result by using more clever naming in the role keys (id of the role). So admins in App A have different role identifier than admin in App B.

**Roles must belong to an application**

Pros:
- The client application only need to concern the roles defined in their configuration

Cons:
- The user need to define all roles in different apps. e.g. Define an admin once in app A, and once in app B,...

**No role-application association**

Pros:
- It's a simpler design, easier to understand and setup for the users

Cons:
- An app may see many of the roles that are not concerned.


Do you have any thoughts on the design?

**Comment by chpapa** [comment]
@fungc-io @louischan-oursky I've been thinking about it as well. I think we can start with roles not belongs to application, and rely on application developers to do the permission check.

I'm imagining, if someone want a strong guarantee, say, "Only users with Analyst role can access the **Our Analysis** app", they can add a "after login" webhook to check. (And we can add a UI in portal to allow these type of checking and respond in AuthUI to display custom text for error message)

BTW, I think we should reserve the prefix of `authgear_` roles, for future development related with RBAC when we have organization support.

**Comment by fungc-io** [comment]
@louischan-oursky Fat-marker sketches for Portal design FYR
https://www.figma.com/file/CyCGxFFIjlT8DpuAH8GlDL/Roles-and-Groups-Sketches?type=whiteboard&node-id=0%3A1&t=37OrYDrWLwrOTZJH-1

**Comment by fungc-io** [comment]
In today's offline discussion:
- We should keep the roles and applications relationship, i.e. different application will see different roles in the jwt
- “Roles and Applications/ClientID” is a many-to-many relationship
