### ISSUE TITLE
AuthUI V2 Breakdown

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3553]
- Layout
    - [ ] Frame
        - Need to be responsive
        - Should be overridable by app resources
    - [ ] Auth Widget

- Screens
    - [ ] Signup Screen
        - Brand Icon
        - Screen Title
        - Screen Description
        - Text Field
        - Primary Button
        - Divider
        - Secondary Button
        - Phone Input Field
    - [ ] Login Screen
        - Brand Icon
        - Screen Title
        - Screen Description
        - Text Field
        - Primary Button
        - Divider
        - Secondary Button
        - Phone Input Field
    - [ ] Reauth Screen
        - TBC 
    - [ ] Enter OOB OTP Screen
        - Screen Title
        - Screen Description
        - OTP Field
        - Text Button
        - Alert
        - Divider
        - Secondary Button
    - [ ] Create Password Screen
        - Screen Title
        - Screen Description
        - Password Field
        - Divider
        - Secondary Button
    - [ ] Enter Password Screen
        - Screen Title
        - Screen Description
        - Password Field
        - Text Button
        - Divider
        - Secondary Button
    - [ ] Update Password Screen
        - Screen Title
        - Screen Description
        - Password Field
    - [ ] Send OOB OTP Link Screen
        - Screen Icon
        - Screen Title
        - Screen Description
        - Primary Button
        - Divider
        - Secondary Button
    - [ ] Approve OOB OTP Link Screen
        - TBC
    - [ ] Setup 2FA OOB OTP (Email / Phone) Screen
        - Screen Title
        - Screen Description
        - Phone Input Field
        - Text Field
        - Primary Button
        - Divider
        - Secondary Button
    - [ ] Setup TOTP Screen
        - Screen Title
        - Screen Description
        - Code Display Block
        - Tertiary Button
            - Copy Action
        - Primary Button
    - [ ] Enter TOTP Screen
        - Screen Title
        - Screen Description
        - OTP Field
        - Text Button
    - [ ] View Recovery Code Screen
        - Screen Title
        - Screen Description
        - Code Display Block
        - Tertiary Button
            - Copy Action
            - [ ] Download
        - Primary Button
    - [ ] Ask For Create Passkey Screen
        - Screen Icon
        - Screen Title
        - Screen Description
        - Primary Button
        - Text Button
        - Setup Passkey
    - [ ] Use Passkey Screen
        - TBC
        - Use Passkey
    - [ ] Account Unavailable Screen
        - Screen Icon
        - Screen Title
        - Screen Description
        - Primary Button
            - Countdown Text
    - [ ] Generic Error Screen
        - Screen Icon
        - Screen Title
        - Screen Description
    - [ ] Terminate Other Session Screen
        - TBC
    - [ ] Promote Anonymous Screen
        - TBC, should be same ui as signup?
    - [ ] Account Recovery Screen (Forgot Password)
        - Screen Title
        - Screen Description
        - Text Field
        - Phone Input Field
    - [ ] Reset Password Screen (Same as update password)
        - Screen Title
        - Screen Description
        - Password Field
    - [ ] Reset Password OTP Screen
        - Screen Title
        - Screen Description
        - OTP Field
        - Text Button
        - Alert
        - Divider
        - Secondary Button
    - [ ] Reset Password Success Screen
        - TBC
    - [ ] SSO login
    - [ ] Wechat Login

- [ ] Dark Mode Support
    

- Components
    - [ ] Brand Icon https://github.com/authgear/authgear-server/issues/3558
    - [ ] Screen Icon https://github.com/authgear/authgear-server/issues/3558
    - [x] Screen Title https://github.com/authgear/authgear-server/pull/3554
    - [x] Screen Description https://github.com/authgear/authgear-server/issues/3555
    - [ ] Body Text https://github.com/authgear/authgear-server/issues/3558
    - [ ] Text Field https://github.com/authgear/authgear-server/issues/3557
    - [x] Primary Button https://github.com/authgear/authgear-server/pull/3554
    - [x] Tertiary Button https://github.com/authgear/authgear-server/issues/3555
        - [x] Copy Action (Reuse CopyButtonController)
    - [x] Secondary Button https://github.com/authgear/authgear-server/issues/3555
    - [x] Text Button https://github.com/authgear/authgear-server/issues/3555
    - [ ] Divider ("-- OR --") https://github.com/authgear/authgear-server/issues/3558
    - [ ] Phone Input Field https://github.com/authgear/authgear-server/issues/3561
    - [ ] Alert https://github.com/authgear/authgear-server/issues/3559
    - [x] OTP Field https://github.com/authgear/authgear-server/issues/3562
    - [ ] Password Field https://github.com/authgear/authgear-server/issues/3560
    - [ ] Code Display Block https://github.com/authgear/authgear-server/issues/3558
    - [ ] Countdown Button https://github.com/authgear/authgear-server/issues/3565

**Comment by fungc-io** [comment]
Hi @arvinhoux,
Tung spotted 2 screens missing from the design

## Use Passkey

**Scenario**
- Given the account is setup with passkey.
- The user didn't tap "Login with passkey" on the first page
- They enter the email/phone number and tap continue
- The user tap "Use Passkey Instead", they will be brought to a screen to use the passkey

https://github.com/authgear/authgear-server/assets/15207470/cab92fb7-9877-44fc-9570-dcd99ecd447d

## Terminate Other Session

When "Expire when login on another device" is enabled in the application, login from another device will see confirm message at the end of login (After entering pw and stuff)

![Image](https://github.com/authgear/authgear-server/assets/15207470/793da5f1-5899-4287-b828-a903336e7122)

Current design:
![Image](https://github.com/authgear/authgear-server/assets/15207470/e3465d9a-0965-46b9-ac22-dbc685db4f48)

**Comment by tung2744** [comment]
@fungc-io Do we aim supporting siwe in the new auth ui?

**Comment by fungc-io** [comment]
@tung2744 
no 😆

**Comment by fungc-io** [comment]
Can you help check if any user is using that in the production?

**Comment by louischan-oursky** [comment]
Auth flow itself does not support SIWE.

**Comment by fungc-io** [comment]
@arvinhoux @tung2744 i just rmb that this design seems also missing

- When SSO is enabled, after login in App A, the user will see a screen to "Continue as" or "Login as another account" when login in App B


![Image](https://github.com/authgear/authgear-server/assets/15207470/ac40042b-435b-45f7-a5a7-1ba054341951)

**Comment by tung2744** [comment]
Broken down into smaller issues, closing
