### ISSUE TITLE
AuthUI V2 - Implement common components (2)

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3558]
- [x] Brand Icon
    - Respect logo alignment variable

![Image](https://github.com/authgear/authgear-server/assets/34942210/4127ce55-48e5-4b25-8483-1f9dfab186c7)

- [x] Screen Icon

![Image](https://github.com/authgear/authgear-server/assets/34942210/e1a25ca8-36f0-4f3a-b1ab-d2cd9e52d762)

- [x] Divider
    - Create a html template for it. Expected usage:
    ```html
    {{ template "authflowv2/__divider.html" }}
    ```

![Image](https://github.com/authgear/authgear-server/assets/34942210/e0b4e733-6996-4952-b74e-94c15b2de287)

- [x] Code Display Block
    - Styles only. Excluding the buttons. Including styles of text.

![Image](https://github.com/authgear/authgear-server/assets/34942210/93e94fa9-7293-47e0-b6b7-3c306a622b6b)

- [x] Body Text
    - Styles only.
    - Style the inline links.

![Image](https://github.com/authgear/authgear-server/assets/34942210/2ea3339d-6f26-41be-bf41-195fa1f3bb77)

**Comment by louischan-oursky** [comment]
For the divider, we may want to support specifying additional classnames, like `{{ template "authflowv2/__divider.html" "mb-10" }}`. Thoughts? @tung2744 @Ngkaokis

**Comment by tung2744** [comment]
Or we can simply do
```html
<div class="mb-10">
  {{ template "authflowv2/__divider.html" }}
</div>
```

**Comment by louischan-oursky** [comment]
I prefer avoiding elements without semantics. Let's start with something like

`{{ template "authflowv2/__divider.html" (dict "Classname" "mb-10") }}`

Use a distinct translation label for this new divider.

**Comment by Ngkaokis** [comment]
per offline discussion, seems `template` not supporting passing dynamic variable so hardcoding `or` label first.
May need implement function similar to helm `include` if there is actual usage other than `or`

https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions

**Comment by tung2744** [comment]
We can define something like `page-content` in `resources/authgear/templates/en/web/__page_frame.html`.
