### ISSUE TITLE
AuthUI V2 - Implement Password Field

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3560]
Based on:
- https://github.com/authgear/authgear-server/issues/3557

![Image](https://github.com/authgear/authgear-server/assets/34942210/1a8c1b59-168a-4768-9290-10ff5458701a)

- Error state should be supported
- Password strength meter should be implemented, with on / off config
- Can toggle visibility using the "eye" button

**Comment by Ngkaokis** [comment]
Any detail requirement on the Password strength meter ? @tung2744

**Comment by tung2744** [comment]
@Ngkaokis The design is here:
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=1109-21880&mode=design&t=BCEU1x8kYuE0BIdk-4

But I found it only have 4 level
- Strong
- Medium
- Weak
- Very Weak
where our existing meter (See __password_strength_meter.html) has 5 level.

I think the missing level is "Very Strong" and the color can be the same as Strong.

@arvinhoux @fungc-io See if any opinion?

**Comment by Ngkaokis** [comment]
Do you expect to reuse `password-policy.ts` / `passwordVisibility.ts`? No need to have a v2 version right?

**Comment by tung2744** [comment]
@Ngkaokis 
- `password-policy.ts`: It seems we don't need it in v2, because I didn't see we any password policy checklist in figma.
- `passwordVisibility.ts`: You can reuse it in password field if you find it useful.

**Comment by Ngkaokis** [comment]
> password-policy.ts: It seems we don't need it in v2, because I didn't see we any password policy checklist in figma.

Oh right, it check the password point by point. But what I want to ask is that is there a reference on determining the strength of password? Like the password doesn't have symbol so it's a weak password etc.

@tung2744
