### ISSUE TITLE
AuthUI V2 - Implement Phone Input Field

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3561]
![Image](https://github.com/authgear/authgear-server/assets/34942210/7f6de684-17a0-45f2-a24a-dca5f20920de)

- Responsive
    - Mobile: Full screen modal opened on click
    - Desktop: Dropdown opened on click
- Search (Frontend search only)
- Error state should be supportted.

**Comment by fungc-io** [comment]
Design: https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=890-8744&mode=design&t=87GCqRocri2Fd5th-4

**Comment by fungc-io** [comment]
Reference for flags:
- https://github.com/jackocnr/intl-tel-input?tab=readme-ov-file
- https://github.com/fonttools/region-flags

**Comment by fungc-io** [comment]
- Other emoji font for reference: https://fonts.google.com/noto/specimen/Noto+Color+Emoji

**Comment by IniZio** [comment]
Don't think Noto Color Emoji has variant that provides flag without wave.

Found Twitter emoji compiled as font https://github.com/13rac1/twemoji-color-font, tried the font and pretty close to current design

Preview provided on their repo:
![Image](https://github.com/authgear/authgear-server/assets/3119725/07ec8be4-e622-453b-93c6-e1c9bd6de2a3)
