### ISSUE TITLE
AuthUI V2 - Implement OTP Field

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3562]
![Image](https://github.com/authgear/authgear-server/assets/34942210/4350a853-ac5b-494a-ba92-ec54a68ae0cc)

- Implement as a stimulus controller attached to input element
- Auto submit the form after the 6th digit was entered.
- Error state should be supported.

**Comment by IniZio** [comment]
@tung2744 What's the recommended way for adding variant to components? Currently `.label-btn` only has fixed font size `1rem` and padding 🙏 .

**Comment by tung2744** [comment]
@IniZio It seems the resend button is not same as the label button. I think we might want another class for the resend button.

**Comment by louischan-oursky** [comment]
> It seems the resend button is not same as the label button. I think we might want another class for the resend button.

It seems like we need to confirm with the designer on this. @IniZio Please leave a comment in the Figma file for Arvin.

**Comment by IniZio** [comment]
Tracking in https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE?node-id=769:49233&mode=dev#665880997
