### ISSUE TITLE
AuthUI V2 - Countdown Controller

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3565]
![Image](https://github.com/authgear/authgear-server/assets/34942210/4b9eb237-5247-4bd3-a7ea-3b43d68b37ad)

![Image](https://github.com/authgear/authgear-server/assets/34942210/4943b820-019a-45c0-9530-496d3f2e044d)

- Basically same as `ResendButtonController`, but not only for resend.
- Support disabling a button before count down finish, and reenable it after finish.

**Comment by IniZio** [comment]
@tung2744 What is different beside renaming, want to make it extendable as well? 🙏

**Comment by tung2744** [comment]
@IniZio Basically the same, but the original implementation is only for resend button. I think we might want a more generic implementation which:
- Do not assume the host element is a button element, use target to specify the button to disable instead.
- Except `cooldown` which is the original relative time, also accept using a timestamp as a absolute time. <- Can be used in account lockout
