### ISSUE TITLE
AuthUI V2 - Signup: Setup 2FA OOB OTP

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3573]
- Phone
  - https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=1151-29110&mode=design&t=t2ocn0LIQuJP59g8-4

- Email
  - https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=953-7404&mode=design&t=t2ocn0LIQuJP59g8-4

**Comment by IniZio** [comment]
@tung2744 Will we need to update setting page with v2 style as well?
