### ISSUE TITLE
AuthUI V2 - Signup: View Recovery Code

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3575]
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=747-33713&mode=design&t=t2ocn0LIQuJP59g8-4

- In android / ios, show "Copy"
- Else, show "Copy" and "Download" 

@fungc-io Sorry I forgot our conclusion on the copy / download button in this screen, please see if my description is correct?

**Comment by fungc-io** [comment]
@tung2744 yes u r correct
