### ISSUE TITLE
AuthUI V2 - Login: Enter Recovery Code

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3580]
~Design pending https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE?node-id=747:33782&mode=design#664217479~

Design: https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=805-63247&mode=design&t=3ZEbz4t2gQfotR9a-4

**Comment by tung2744** [comment]
@fungc-io Found we missed this screen, asked in figma too.

**Comment by arvinhoux** [comment]
Design has been updated here
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=805-63247&mode=design&t=3ZEbz4t2gQfotR9a-4
