### ISSUE TITLE
AuthUI V2 - Login: Using Passkey

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3581]
![Image](https://github.com/authgear/authgear-server/assets/34942210/42043252-8351-43e8-92ea-e736f1c972bf)

- Use passkey at login screen
- Use passkey as alternatives in other screens
- Use passkey screen @fungc-io The design of use passkey screen is still missing

**Comment by fungc-io** [comment]
@arvinhoux 
The use passkey screen is missing
Please refer to this comment: https://github.com/authgear/authgear-server/issues/3553#issuecomment-1877279865

**Comment by fungc-io** [comment]
@arvinhoux similar screen on android


![Image](https://github.com/authgear/authgear-server/assets/15207470/f7cad33c-27b4-45f3-88cd-2df756a1d3ba)
Reference: https://developer.android.com/design/ui/mobile/guides/patterns/passkeys

**Comment by fungc-io** [comment]
@arvinhoux pointed out that the "Use Passkey" is a bit weird UX-wise, 
Let's talk and decide if an alternative UX can be implemented

**Comment by arvinhoux** [comment]
Design has been updated
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=805-63257&mode=design&t=3ZEbz4t2gQfotR9a-4

**Comment by tung2744** [comment]
@fungc-io @arvinhoux It seems the use passkey screen doesn't exist.
It is basically just a screen required by the server to display to the user, and the native passkey dialog will pop-up automatically. What is the conern in ux?

**Comment by fungc-io** [comment]
@tung2744 When they dismiss the Passkey dialog, showing the alternative method seems a better UX.

<img width="609" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/b086f1b3-450d-4654-a3d8-980850dde9d9">

Can we avoid the Use passkey screen?

**Comment by tung2744** [comment]
@fungc-io It is difficult.
The problem is if the project configured passkey as the first authenticator, and when a user login in the login page (Not pressing "login with passkey", but type username and press enter), the server returns with a response which redirects the user to the use passkey screen.
And in this case, we cannot show the passkey dialog in the login screen directly, because we don't know the selected authenticator is passkey until server returned the redirect response.
It is possible to refactor the flow and eliminate the screen, but I suggest we simply add a screen for it. If your concern is user should be able to select other alternatives, user passkey screen can also show alternatives.

**Comment by fungc-io** [comment]
My concern was a UX problem, when the user dismiss the passkey dialog, they are more likely to use other methods instead of pressing the "Use passkey" again.

@arvinhoux Please help add a "Use Passkey" screen design.
We will eliminate this in a future issue as it requires API change. Let's keep it as-is for this scope

**Comment by tung2744** [comment]
> My concern was a UX problem, when the user dismiss the passkey dialog, they are more likely to use other methods instead of pressing the "Use passkey" again.

Can this be solved by a auto back on passkey dialog dismissed?

**Comment by fungc-io** [comment]
Probably, but I think  it would be the best if the background UI don't change and don't flash,

**Comment by tung2744** [comment]
Sorry, after rethink, the screen is still necessary.
Consider the following config:

```yaml
primary_authenticators:
  - passkey 
  - oob_otp_sms
```

In case the use passkey screen doesn't exist:

1. The user enter the login id in login screen, and press continue.
2. Now, he see a passkey dialog because the passkey is the first authenticator.
3. He want to use sms otp instead, but after closing the passkey dialog, he cannot switch to oob otp.

**Comment by fungc-io** [comment]
In this case my original thought is showing OOBOTP in the background, with a "use passkey" button below the OTP input

So after they dismiss the passkey dialog, they can enter OOBOTP immediately 

But rethink not sure at which step should the OTP be sent🤔

**Comment by tung2744** [comment]
I suggest we simply display an error message in the passkey screen when the user closed the dialog:
```
Failed to authenticate with passkey. Please [Retry] or select another authentication method below. 
```

**Comment by fungc-io** [comment]
@arvinhoux let's have a use passkey screen, i agree with @tung2744 that this is needed

A similar screen in GitHub:

![SCR-20240131-da1](https://github.com/authgear/authgear-server/assets/15207470/c03f24d8-671e-44c8-b8aa-8f211f9a1e90)

**Comment by fungc-io** [comment]
@tung2744,
Arvin is busy on another project,
Maybe you can create the page first, and let's adjust the copywriting later

**Comment by tung2744** [comment]
Current implemented ui:

![Image](https://github.com/authgear/authgear-server/assets/34942210/8740f715-77bb-40dd-af6e-54f2ddc518f9)

**Comment by fungc-io** [comment]
@tung2744 

let's change "Continue to login with passkey" to "Log in using the button below."
Less repetitive and more helpful instruction
