### ISSUE TITLE
AuthUI V2 - Login: Update Password

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3585]
- Update Password
  -  https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=739-31059&mode=design&t=t2ocn0LIQuJP59g8-4
- Update Password Sucess
  - https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=217-10197&mode=design&t=t2ocn0LIQuJP59g8-4

**Comment by Ngkaokis** [comment]
@tung2744 Is this duplicated to #3590 #3591 ?

**Comment by tung2744** [comment]
@Ngkaokis No, but they are similar.
Update password occurs when the existing password doesn't meet the current password policy. A screen will appear to force the user to set a new password.

**Comment by Ngkaokis** [comment]
@tung2744 In that case, do we really have this Change password success screen? I don't see we have one in current implementation (only forgot_password / reset_password has success screen). And seems figma don't have this flow.

**Comment by tung2744** [comment]
@Ngkaokis I think you can make it without the success screen first. Lets confirm with designer later.

**Comment by fungc-io** [comment]
@arvinhoux please help add the design in Figma for force update password
The copywriting should be different from the reset password flow

**Comment by Ngkaokis** [comment]
Per offline discussion, adding a force update password success screen requires updates on authflow controller which we want to avoid doing it in a UI task. 

Created another task #3695

**Comment by arvinhoux** [comment]
Updated
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=1474%3A14711&mode=design&t=9kh4JP3zNwuJ7zdf-1

**Comment by louischan-oursky** [comment]
That's trivial to change. Just swap https://github.com/authgear/authgear-server/blob/main/pkg/lib/authenticationflow/declarative/generate_config_login_flow.go#L193 with https://github.com/authgear/authgear-server/blob/main/pkg/lib/authenticationflow/declarative/generate_config_login_flow.go#L200
