### ISSUE TITLE
AuthUI V2 - Reauth

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3586]
Reference pkg/auth/handler/webapp/authflow_reauth.go

@fungc-io Do we need different copywritings in reauth flow in the screens?

For example, the otp screen will show `This action you are trying to perform requires you to enter one-time password.` if it is used in reauth flow in the current authui.

**Comment by fungc-io** [comment]
Hi @arvinhoux ,
When the user performs re-auth, we will show the password screen with a copy explaining why they need to do that. Can you help design this scene in the figma?

Please check out this discussion: https://github.com/authgear/authgear-server/issues/3146

The screen looks like:
![IMG_508810B2BE75-1](https://github.com/authgear/authgear-server/assets/15207470/c405a593-f914-4281-8b7e-16b10df10752)


btw, @tung2744 @louischan-oursky , do we support using OOB-OTP in reauth too? See if the design is needed

**Comment by louischan-oursky** [comment]
Yes, we support OOB-OTP in reauth when the implementation is Auth flow.

**Comment by arvinhoux** [comment]
The new design update is here
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=805-63421&mode=design&t=3ZEbz4t2gQfotR9a-4

**Comment by tung2744** [comment]
All descriptions used during reauth of differenent authentication methods:

- primary password: For your security, we need to verify it's you.
- secondary password: For your security, we need your additional password to continue.

- oob otp (sms / email): For your security, we need to verify it's you. We''ve just sent a {CodeLength}-digit verification code to {MaskedClaimValue}.
- oob otp (whatsapp): For your security, we need to verify it's you. We''ve just sent a {CodeLength}-digit verification code to your WhatsApp number at {MaskedClaimValue}.

- oob otp (email link): For your security, we need to verify it's you. We’ve just sent a login link to {MaskedClaimValue}. If not received, please resend.

- totp: For your security, we need to verify it's you. Enter the 6-digit code you see in the authenticator device/app.

- recovery code: For your security, we need to verify it's you. Enter an unused 10-character recovery code.

- passkey: For your security, we need to verify it''s you. Log in using the button below.

**Comment by fungc-io** [comment]
@tung2744 
Thank, the copywriting are mostly great.

I've a question tho, specifically in email link, there is "If not received, please resend.", why not in others too? do we show a resend button in other cases?

**Comment by tung2744** [comment]
> I've a question tho, specifically in email link, there is "If not received, please resend.", why not in others too? 

I basically follow the original copywritings in figma. 

> do we show a resend button in other cases?

oob otp authenticators (email link, sms otp, email otp, whatsapp otp) always have resend. Others don't have resend button.

**Comment by fungc-io** [comment]
> I basically follow the original copywritings in figma.

oh alright, lets review them all later
See if we can have all tentative copywriting ready tomorrow.
