### ISSUE TITLE
AuthUI V2 - Wechat Signup / Login

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3592]

**Comment by IniZio** [comment]
@fungc-io Wechat is different from other apps and need extra screens to use:

 

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/b911115a-1d39-43bd-80cb-1f8cd2ce7c64/06685588-3175-429e-a0cd-35d2f273440f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9iOTExMTE1YS0xZDM5LTQzYmQtODBjYi0xZjhjZDJjZTdjNjQvMDY2ODU1ODgtMzE3NS00MjllLWEwY2QtMzVkMmYyNzM0NDBmIiwiaWF0IjoxNzEwODQ2NzMxLCJleHAiOjMzMjgxNDA2NzMxfQ.4iKbaicwgaMnwT1xPb-QGzSwJxvam12rESfCQ3i3jWo " alt="IMG_2BD263FEC8EF-1.jpeg" width="828" height="1792" />

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/1272df82-546f-47f5-b4e3-140ff12b084d/660d878f-2be3-471c-b7e3-29263b369d7d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8xMjcyZGY4Mi01NDZmLTQ3ZjUtYjRlMy0xNDBmZjEyYjA4NGQvNjYwZDg3OGYtMmJlMy00NzFjLWI3ZTMtMjkyNjNiMzY5ZDdkIiwiaWF0IjoxNzEwODQ2NzMxLCJleHAiOjMzMjgxNDA2NzMxfQ.y8SDcpIL2OsVqeu3MzrTk2nDMO9_Nigrg_v4M_ORGJg " alt="IMG_CEAC6236DB4F-1.jpeg" width="828" height="1792" />

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/7b5b68c6-d1ed-4599-8a6f-c7684809237c/79bc5d52-6d6b-4824-a3fa-ccca44d13841?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi83YjViNjhjNi1kMWVkLTQ1OTktOGE2Zi1jNzY4NDgwOTIzN2MvNzliYzVkNTItNmQ2Yi00ODI0LWEzZmEtY2NjYTQ0ZDEzODQxIiwiaWF0IjoxNzEwODQ2NzMxLCJleHAiOjMzMjgxNDA2NzMxfQ.SGIMCBT_9eyosTLV06AI_gEJDXmlgr9ia2kCBh59h1w " alt="IMG_EA0F0106838E-1.jpeg" width="828" height="1792" />

Will need @arvinho's help to add these screens? 🙏
