### ISSUE TITLE
AuthUI V2 - Error Screen

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3595]
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=738-25095&mode=design&t=t2ocn0LIQuJP59g8-4

See resources/authgear/templates/en/web/fatal_error.html

- Session expired error
- Unknown error (panics)

**Comment by IniZio** [comment]
Noticed that new UI never shows return button, as opposed to old UI. Should we have that in new UI as well?
