### ISSUE TITLE
AuthUI V2 - Signup: Signup Disallowed

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3596]

**Comment by tung2744** [comment]
@fungc-io @arvinhoux 

There is a feature to disable public signup. We may want a ui to display when someone access the signup page when public signup is disabled.

Or I guess we can simply reuse the generic error screen? https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=738-25095&mode=design&t=t2ocn0LIQuJP59g8-4


![Image](https://github.com/authgear/authgear-server/assets/34942210/b26da48f-a67f-496a-ac03-a38fa4e00783)

**Comment by fungc-io** [comment]
Use the generic error page with the following copy:

"Unexpected Issues"
"Signup is disabled. Please contact system admin."
No button, the user can only cancel or close this page.

**Comment by louischan-oursky** [comment]
@IniZio I believe this flag is not currently honored in authflow. We need to block public signup at API level.

**Comment by IniZio** [comment]
Yes am trying to add, thanks 🙏

**Comment by louischan-oursky** [comment]
Note that we have `signup` and `signup_login` flow. If public signup is disabled, then the creation of `signup` and `signup_login` flow should be disallowed.
