### ISSUE TITLE
AuthUI V2 - Signup: Alternative Signup methods

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3597]
Handle branches of signup flow.

References: resources/authgear/templates/en/web/__authflow_branch.html

Create a template to Handle branches:
- Setup Password
- Setup Additional Password
- Set up authenticator app (TOTP)
- Setup SMS OOB OTP
- Setup Whatstapp OOB OTP
- Setup SMS Link
- Setup Email OOB OTP
- Setup Email Link
- Verify by SMS OTP
- Verify by Whatsapp OTP

Apply to signup related screens.

**Comment by IniZio** [comment]
@tung2744 Do we have task to handle email link?

**Comment by tung2744** [comment]
@IniZio Yes, https://github.com/authgear/authgear-server/issues/3572 https://github.com/authgear/authgear-server/issues/3594
