### ISSUE TITLE
AuthUI V2 - Login: Alternative authenticate methods

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3598]
Handle branches of login flow.

References: resources/authgear/templates/en/web/__authflow_branch.html

Create a template to Handle branches:
- Enter Password
- Enter Additional Password
- Use Passkey
- TOTP
- SMS OOB OTP
- Whatstapp OOB OTP
- SMS Login Link
- Email OOB OTP
- Email Login Link

Apply to login related screens.

**Comment by tung2744** [comment]
Handle in #3597

**Comment by IniZio** [comment]
Think this is already handled in #3654

**Comment by tung2744** [comment]
Yes, let me close it
