### ISSUE TITLE
Minimal Admin API

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#36]
- Separate 3 binding (ip/ports) (public, admin, proxy_auth)? Consideration:
   - Proxy_auth is intended for k8s gateway only, which should be internal network, and control access by network policies / firewall; While admin endpoint could be internal, or external system and auth by say client_credentials (replacing Master Key), and it will be easier if users can configure firewall by ip/ports
- web portal
  - Edit config
  - UI to Admin API
   - outsource to other team?
   - Use MS fluent UI

**Comment by chpapa** [comment]
@louischan-oursky updated with the reason why I think admin and proxy_auth should be two endpoint. BTW I think the configuration should not be "two ports", but "two binding" aka both ip address and port.

**Comment by kiootic** [comment]
Some notes:
- we would like to use GraphQL for the admin API
- admin API develops in a separate repo
- use Go?
    - need investigation on data loader in Go
    - may have some messy code due to Go's type system
- may try to prototype in Go, then decide whether go ahead/use JS instead.

**Comment by kiootic** [comment]
- Admin API
    - Auth: None/JWT
        - Portal: handle authorization, proxy request to Admin API
- Self-host portal
       - Host in same domain? e.g. `accounts.admin.example.com` & `accounts.example.com`
           - Need cookie prefix
       - Backend auth: can use same instance for multi-tenant mode/two instances for single-tenant mode
       - Settings edit: export config for downloading edited config/edit config in-place in mounted fs with live-reload
- Cloud-host
       - Settings edit: edit k8s configmap directly, mounted to authgear instance with live-reload
