### ISSUE TITLE
AuthUI V2 - Select Account

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3600]
Pending Design

See https://github.com/authgear/authgear-server/issues/3553#issuecomment-1884305284

@fungc-io @arvinhoux

**Comment by arvinhoux** [comment]
The new design update is here
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=730-21918&mode=design&t=3ZEbz4t2gQfotR9a-4
