### ISSUE TITLE
Update password policy design into separate bullet points

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3615]

**Comment by arvinhoux** [comment]
Set up password
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=953-77320&mode=design&t=nC31eMpOZBC8UQ5J-4

Password strength/ Extreme
https://www.figma.com/file/LRE8EfCaTfYxC0lk5AeMmE/New-Auth-UI?type=design&node-id=953-77934&mode=design&t=nC31eMpOZBC8UQ5J-4

**Comment by fungc-io** [comment]
@Ngkaokis please help update to the latest error state design :adore:
