### ISSUE TITLE
Auth ui behave weirdly under certain configs

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3617]
Under some configs, the auth ui is buggy.

Config:

1. Set phone verification to required
2. Enabled password, sms oob otp authenticators. Password must be the first authenticator.

Signup a user by phone:
1. See otp verification. This step is normal. 
2. Enter the code to pass the verification.
3. See Setup password screen. We see "Send one-time password via SMS instead" as alternative, but we already verified the phone number in previous step.
4. If click on "Send one-time password via SMS instead", it will be an error. This is a auth ui bug.

@fungc-io @louischan-oursky I am not sure how to fix this, or what should be the expected behavior. So opened this issue first.

**Comment by louischan-oursky** [comment]
Per our offline discussion, we will make these changes.

1. Add `"target": { "masked_display_name": "", "verification_required": false }` if target is not required.
2. For `primary_oob_otp_email` and `primary_oob_otp_sms`, verification can be skipped if the claim has been verified in a previous step. For `secondary_oob_otp_email` and secondary_oob_otp_sms`, verification is always required even the target has been verified in a previous step.
