### ISSUE TITLE
[Portal, Login Methods] Empty error message when change login methods to Social with Passkey turned on

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3629]
## Environment
- Environment: Staging
- App: qa-app
- Browser: Chrome on Macbook Pro

## Description
If the project is setup with Passkey enabled, when admin tries to switch the login method to "Social / Enterprise only", it will be unable to save, and show an error state with empty message.

It is due to the conflict with passkey setting according to the console log. If this is disallowed, should either confirm user to turn off passkey first or help user to turn it off when switching the login method to social.

## Steps to reproduce
1. Login to admin portal
2. Go to "Login Methods"
3. Configure any email / mobile methods, and enable Passkey
4. Sign up some users
5. Try to change the login method to "Social / Enterprise only"
6. See empty red bar on top when click "Save"

## Expected behavior
Suggest helping user to disable passkey automatically when changing the login method, or show a confirmation dialog to ask if user wants to proceed, if it will affect some existing users.

The error meesage returns should also not be empty.

## Screenshots
<img width="1177" alt="Screenshot 2024-01-16 at 7 28 51 PM" src="https://github.com/authgear/authgear-server/assets/12539486/11f54c82-8dc9-4af3-9f71-d1f4e0e10a9b">

**Comment by fungc-io** [comment]
Thanks for the report
Fixed in another issue:
https://github.com/authgear/authgear-server/issues/3720
