### ISSUE TITLE
Improve error page for CSRF Error page

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3633]
When the user experience CSRF error, the message is not useful.

![image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/f48114d7-a74d-4926-80a8-ac5e4334126c/bb301d6f-57ec-4fae-9bd8-f466eee8a0b9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9mNDgxMTRkNy1hNzRkLTQ5MjYtODBhOC1hYzVlNDMzNDEyNmMvYmIzMDFkNmYtNTdlYy00ZmFlLTliZDgtZjQ2NmVlZThhMGI5IiwiaWF0IjoxNzIyOTU4NjA4LCJleHAiOjMzMjkzNTE4NjA4fQ.6vOe_UN7pMISe2_ppYLkvM3S-E2hajeKhcTbpNMl_Ug "=320x")

Change design to:

> ## Oops!
>
> An error occured. Make sure cookies are enabled and try again. See instructions.

**Comment by louischan-oursky** [comment]
Let's include a line to tell the user to check if they have disabled cookies in their browser settings.

**Comment by chpapa** [comment]
I think instead of just "showing a line", we shall display different user friendly information to ask them to check the setting, depends on:

* browser
* desktop / mobile

By default?

**Comment by fungc-io** [comment]
> ## Oops!
> We experienced a problem accessing this page. Please close this page and retry login from the website or app.
> If the problem persists, check if cookies are enabled in your browser settings.
> 
> --- SHOW INSTRUCTIONS BASED ON OS/BROWSER, INCLUDE SCREENSHOTS---
> ### iOS
> 1. Go to the "Settings" app
> 2. Go to "Safari" -> "Advanced" 
> 3. "Block All Cookies" is turned **Off**
> 
> ### Chrome Desktop
> 1. At the top right, click More "..." > Settings. OR Visit `chrome://settings/content/siteData`
> 2. Click **Privacy and security** > **Site settings**.
> 3. Click **Additional content settings** > **On-device site data**. 
> 4. Select "Allow sites to save data on your device"
> 
> <img width="657" alt="image" src="https://github.com/authgear/authgear-server/assets/15207470/d8a35b48-bfa0-4bc7-80ef-bd89649f4a68">
>
> ### Android
> 1. On your Android device, open Chrome.
> 2. To the right of the address bar, tap More "..." and then **Settings**.
> 3. Under “**Advanced**,” tap **Site settings** > **On-device site data**.
> 4. Turn **On-device site data** on.
