### ISSUE TITLE
Audit Log is not rendering properly on the 1st load

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3641]
**Describe the bug**

- Only part of the audit log is rendered in a page, only the upper part is visible
- It will show the rest when a resize the window

**Authgear Version**

- All versions

**To Reproduce**

1. Go to audit log page with a full page of events
2. See the lower part is missing
3. Resize the window
4. The lower part appears

**Comment by tung2744** [comment]
I think related to https://github.com/authgear/authgear-server/issues/3508

**Comment by fungc-io** [comment]
tested
