### ISSUE TITLE
Introduce flow testing for authflow/authflowv2

### ISSUE THREAD

**Issue by IniZio** [authgear/authgear-server#3653]
### Problem

Currently it's difficult to visualize and test different flow's behaviour in authflow.

Also the change of defaulting all auth implementation to authflow has been reverted since several key features were broken on staging after the switch.

#### Examples

* It was found that OOB OTP does not have lockout mechanism during authflow migration `[79d3a36](https://github.com/authgear/authgear-server/pull/3660/commits/79d3a36cb349e01916ddc466fd4f93fe9528eadd)`[ (#3660)](https://github.com/authgear/authgear-server/pull/3660/commits/79d3a36cb349e01916ddc466fd4f93fe9528eadd)
* "Login by username" failed in authflow [https://github.com/authgear/authgear-server/issues/3631](https://github.com/authgear/authgear-server/issues/3631)
* Forgot password email always 200 [https://github.com/authgear/authgear-server/issues/3708](https://github.com/authgear/authgear-server/issues/3708)
* ~#3737~ Actually is new feature
* [https://github.com/authgear/authgear-server/pull/3756](https://github.com/authgear/authgear-server/pull/3756)
* [https://github.com/authgear/authgear-server/pull/3756/files](https://github.com/authgear/authgear-server/pull/3756/files)

### Possible ways

* e2e test through authflow HTTP API
* statemachine-like testing through unit testing

> We have basic client testing at `pkg/auth/handler/webapp/authflow_controller_test.go`

### Breakdown

- [ ] #3773
- [X] Add mock redis + test postgres db
- [X] Code-level project fixture + user
- [X] Add goconvey test for e2e authflow
- [X] Add CI for e2e test
- [X] [DEV-1162](https://linear.app/authgear/issue/DEV-1162/add-readable-config-for-e2e-tests)
- [X] [DEV-1163](https://linear.app/authgear/issue/DEV-1163/add-e2e-fixtures-user-project)
- [X] Add yaml(?) for test step + assertions
- [X] [DEV-1164](https://linear.app/authgear/issue/DEV-1164/cover-tomato-test-cases)
- [ ] ~Add test coverage for e2e test~

**Comment by IniZio** [comment]
@louischan-oursky @tung2744 Understand the tight schedule for authui v2, but I have been thinking if we can add simple authflow tests along the way of revamp e.g. #3580?

The reason I raise this is because we seem to find a number of bugs where some logic in interaction is missing in authflow during last sprint.

**Comment by tung2744** [comment]
I believe e2e testing requires some setup.
Maybe we can start from unit tests?
Do you have any thought on it?

**Comment by IniZio** [comment]
I think unit test is already good enough at current stage , since we will need to mock quite some interfaces if we want to use e2e?

The part I am not sure is how to make it easier to compare with interaction behaviour.

**Comment by tung2744** [comment]
The e2e test I mentioned before is to setup a test db, test redis, and a server connected with them and run the testes at http level with a list of defined use cases. So nothing is mocked.

For unit test, I am not sure what is the "unit" we can test. We actually have unit tests for some intents / nodes already. But if we want to test a flow (Therefore able to test something like lockout, or forcing user change password), it seems we need to mock the redis and database?

> The part I am not sure is how to make it easier to compare with interaction behaviour.

I think we don't need to stick with interaction, as there are indeed some behavior difference. Maybe we should define a list of implemented features and test them.

**Comment by IniZio** [comment]
As per offline discussion:

- At current phase, e2e testing against Authflow HTTP api is most worthy
    - Potentially able to pick up https://github.com/authgear/authgear-server/pull/3482 again
- Interaction intended behaviour is significantly different from Authflow. Will solely test against Authflow instead of trying to test parity


Setup e2e:
- Setup mock redis + test-specific postgres.
- Add tasks to setup/teardown fixtures
    - Use yaml format so easier to understand
- Spawn multiple projects per scenerio
- Prefer declarative input/output, can be read like snapshot test diff

**Comment by IniZio** [comment]
Currently attempting the setup in https://github.com/authgear/authgear-server/issues/3773

**Comment by IniZio** [comment]
@fungc-io See if can work on adding functional testing for authflow next sprint as well?
