### ISSUE TITLE
Review All error message and copywriting in the AuthUI v2

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3656]
For all EN, zh-Hant, and zh-Hans
- Fill in all TBC copywriting
- Review all copywriting and make sure they are clear

**Comment by fungc-io** [comment]
@tung2744 ,
please help compile the list of copywriting by the end of tmr for review

**Comment by tung2744** [comment]
@fungc-io Please find the list of copywritings of v2 ui below.
The zh translations are basically translated from en version.

[zh.json](https://github.com/authgear/authgear-server/files/14178831/zh.json)
[en.json](https://github.com/authgear/authgear-server/files/14178832/en.json)

**Comment by Ngkaokis** [comment]
Need to review the copy writing of 
1. verify login link as it's shared by both signup and login
2. Sign up page's `sign up with email` button  

ref #3787

**Comment by louischan-oursky** [comment]
We also want to tidy up the translation.json files a bit.

- Ensure all v2-* keys are placed at the end of the file.
- Some v2 keys are using `.` We do not use `.`. Correct them to use `-`.
- (Optional) Sort the v2 keys alphabetically. Add linter to ensure this ordering.

**Comment by fungc-io** [comment]
@tung2744 @louischan-oursky 
I've reviewed the copywriting
https://docs.google.com/spreadsheets/d/1qZLiazkEJbLZ44NwbZZO7luL7CKLzEi_hsqF__x8j60/edit#gid=137567725

I've left comments on row 6,12,14

Maybe we can document the following translation for future reference too:

| En | Hong Kong | Taiwan | Notes |
| --- | --- | --- | --- |
| Account | 帳戶 | 帳號 | |
| Username | 用戶名稱 | 用戶名稱 | instead of "用戶名"/"使用者名稱"... |
| Email / Email address | 電郵 / 電郵地址 | 電郵 / 電郵地址 | instead of 電子郵件/電子郵件地址
| Passkeys | 通行密匙 | 通行密鑰 | |
| Login with ... | 以...登入 | 使用...登入 | e.g. 以 Apple 帳戶登入, 使用 Apple 帳號登入 |
| a verification code | 一組驗證碼 | 一組驗證碼| instead of 一"段"驗證碼 | 
| a message | 一則訊息 | 一則訊息 | instead of 一條 | 
| link | 連結 | 連結 | instead of "鏈接" |
| QR Code | QR Code | QR Code | instead of 二維碼 |
| 2-Step Verification | 雙重驗證 | 雙重驗證 | instead of 多重驗證 |
| authenticator | 驗證器 | 驗證器 | |

**Comment by louischan-oursky** [comment]
Thank you for making the table. It is very useful for us to write future copywriting.

> I've left comments on row 6,12,14

Currently we write something like the following in our HTML template

```
        {{ if $.ClientName }}
        {{ template "v2-login.title" (dict "AppOrClientName" $.ClientName) }}
        {{ else }}
        {{ $appName := (include "app.name" nil) }}
        {{ template "v2-login.title" (dict "AppOrClientName" $appName) }}
        {{ end }}
```

If we want the developer to use either AppName or ClientName, then we need to write something like

```
{{/* $hasClientName is a boolean now, but we actually need to make it a string */}}
{{ $hasClientName := (ne $.ClientName "") }}
{{ template "v2-login.title" (dict "AppName" $appName "ClientName" $.ClientName "HasClientName" $hasClientName) }}
```

And the translation message can become

```
{HasClientName, select, true{Login to {AppName} to continue {ClientName}} otherwise{Login to {AppName}}}
```

**Comment by fungc-io** [comment]
I see,
@tung2744 can you help update the spreadsheet as above :adore:

**Comment by tung2744** [comment]
I think I will update to always use project name first, because currently client name must exist. Therefore as a result client name always being used instead of project name.

**Comment by tung2744** [comment]
@fungc-io ClientName doesn't always exist. (If the login have no client context, it doesn't exist). Therefore I modified "v2-login.subtitle". to `Login to {AppName}` when no client name.

**Comment by tung2744** [comment]
I exported the latest translation to a new sheet `v2-translations_29-02-2024`

**Comment by fungc-io** [comment]
ok thanks
