### ISSUE TITLE
Password Expiry

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3659]
## Problem

Some companies have a strict password policy that the password expires after certain days, the user must change the password after it's expired.

## Appetite

2 weeks

### Part 1

* Password Expiration Renew: default=never expire; days
  * If an expired password is used, after the authentication success, the user needs to change the password to proceed.
  * UI:
    * Heading: Password expired
    * Paragraph: Time to change your password
    * \[Input box for new pw\]
    * \[Input box for reenter new pw\]
    * Save button

### Part 2

* Password Expiration Warning: default=90; days
  * If the warning days are pasted, after using a password to login, show a password expiration warning message
  * In the UI warning page:
    * Heading: Password expired
    * Paragraph: Time to change your password
    * Buttons:
      * "Change password" to go to the change password flow, or 
      * Text button "Not Now" to continue login
* Password Expiration Reject: default=never; days
  * Block user login if the password expired
  * Heading: Password expired
  * Paragraph: You cannot login because the password is expired. Please contact customer support.
  * Button: \[Back to login\]

~(Copied from an old issue: #129 )~

### Breakdown

* [DEV-1106](https://linear.app/authgear/issue/DEV-1106/add-and-parse-password-expiry-config)
* [DEV-1105](https://linear.app/authgear/issue/DEV-1105/add-password-expiration-checker)
* [DEV-1109](https://linear.app/authgear/issue/DEV-1109/add-password-expiry-warning-screen)
* [DEV-1107](https://linear.app/authgear/issue/DEV-1107/add-password-expiry-config-in-portal-advanced-password-requirements)
* [DEV-1110](https://linear.app/authgear/issue/DEV-1110/support-password-expiry-reject)

**Comment by fungc-io** [comment]
@newman please help plan and draft a spec for this feature

**Comment by IniZio** [comment]
Have some questions to confirm:

* Does admin change password reset the period?
* How to present warning in authui and authflow?
* Same as other UI, customize message in Localization?
* Do we need to enforce not allow to be unchanged?

**Comment by fungc-io** [comment]
@newman per our offline discussion,

We will add "reject", "renew", "warning" mode to the design, and in the config, all 3 can be set simultaneously. With priority Reject > Renew > Warning

I've updated the usage details in the pitch above. Please help design the plan, and we will complete the 1st part, i.e. "Renew", in the next sprint first.
