### ISSUE TITLE
AuthUI V2 - Force Update Password Success Screen

### ISSUE THREAD

**Issue by Ngkaokis** [authgear/authgear-server#3695]
ref #3585

It requires changes on authflow controller

https://oursky.slack.com/archives/C03AH1ACM/p1706098152824109?thread_ts=1706097103.235049&cid=C03AH1ACM

**Comment by Ngkaokis** [comment]
- Tried Approach:
Persist the `Result` in `AuthflowScreen` and hijack the redirect URI of `Result.RedirectURL`. Then redirect it to ResetPasswordSuccessScreen and then restore the previous persisted `Result` in order to continue the original flow.

- Problem Found:
As the session is deleted after the flow is finished, it's not possible to restore the session to get the persisted `Result`.

- Next Approach:
Every flows is required to be redirected to `/authflow/finsh` to manually finish the flow instead of bind it with `AdvanceInput`. And hence we can inject intermediate screen before the screen is finished.

**Comment by fungc-io** [comment]
tested ok
