### ISSUE TITLE
Consider applying alert message to every screen for any possible unknown error

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3698]
see https://github.com/authgear/authgear-server/pull/3693#discussion_r1465920261

Ensure error alert is displayed for any unhandled error in screens with this layout

**Comment by Ngkaokis** [comment]
@tung2744 
I think this issue is still worth doing? Let me pick up it and add a screen__header component? I guess only screen with `form` element need it? Or you expect to use this component for all screens

**Comment by tung2744** [comment]
Renamed the issue to clarify the goal of the issue.

**Comment by fungc-io** [comment]
1. OAuth conflict
2. OTP error: Verification code sending failed. Please try again.
3. Network error

**Comment by fungc-io** [comment]
@Ngkaokis 
For Network errors:
"There was a problem performing this action. Please try again"
"發生錯誤，請重試"
"发生错误，请重试"

**Comment by fungc-io** [comment]
tested ok
