### ISSUE TITLE
Safari 14.4 crashes in auth ui v2

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3705]
It crash with the following log
```
SyntaxError: Invalid character: '#'
```

While v1 can successfully run.
<img width="888" alt="Screenshot 2024-01-25 at 8 18 35 PM" src="https://github.com/authgear/authgear-server/assets/34942210/01125e3b-20f8-4b30-8d5e-19f87ee2c8ae">

**Comment by chpapa** [comment]
Can we gracefully downgrade for iOS14 support? (Eg if certain new features is not available on iOS14, show a relatively bad looking Ui but not crash)

IOS14 quick search in google seems have 0.2% in 2023. Seems not that we don't test but also not worth to spend too much efforts on it

**Comment by IniZio** [comment]
This error is due to static property in stimulus controllers

```js
class $2bd1e05d0769289b$export$afee231278c28f2c extends (0, $72ydB.Controller) {
    static #_ = this.targets = [
    "input",
    "submit",
    "digitsContainer"
    ];
```

Tested if I update browserlist to include iOS 14 with `last 4 iOS major versions`, it can run normally on iOS 14
