### ISSUE TITLE
Portal - Error occurs if I untick all identities and authentication methods, but only enabled passkey

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3720]
1. Select "Custom"
2. Untick all Authenticator and Login ID
3. Tick Enable Passkey
4. Save
5. See error without error message

![Image](https://github.com/authgear/authgear-server/assets/34942210/830fc1fa-4319-4cd1-9607-e7555bd18dbc)

**Comment by fungc-io** [comment]
Let's show an error message: "To use passkey, at least one Login ID must be activated"

**Comment by fungc-io** [comment]
@tung2744 @louischan-oursky or we can just let them save. But the signup/login page will show only social login (if any) and the passkey will be unsable under such config.

**Comment by louischan-oursky** [comment]
I suggest we keep the original behavior. Let's fix the error message instead.

**Comment by fungc-io** [comment]
tested
