### ISSUE TITLE
Remove whitespace-pre-wrap and replace \n with <br> in translation

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#3722]
The conclusion is to remove `whitespace-pre-wrap` and replace `\n` with `<br>` in translation.

---
Original description

> Currently in authflowv2, we are using `whitespace-pre-wrap` and a `\n` in the translation string to force breaking a newline. While the HTML-way to do that is to use `<br>` element.
> Thoughts? @tung2744 @Ngkaokis @IniZio

**Comment by tung2744** [comment]
I think it depends on context:
If it is used as a text, then it should be `\n`. If it is used as html, then it should be `<br>`.

**Comment by louischan-oursky** [comment]
I mean we only add `whitespace-pre-wrap` if the translation string has a line break originally. If we were to allow all translation strings to have line break, then we have to add `whitespace-pre-wrap` to every element that show translation strings.
