### ISSUE TITLE
Phone input UI issues

### ISSUE THREAD

**Issue by Ngkaokis** [authgear/authgear-server#3728]
Seems the phone input still not working fine in safari
- Desktop (macos 14.1.1 )
  - Can't see flag 
- mobile (simulator ios 15)
  - The search bar extends beyond the viewport
  - The menu can't not be collapsed after picking an option

UX improvements:
- If not searching, selected option is the original option. Else, should by default select first row.
- Should not blur the input when pressing arrows.

https://github.com/authgear/authgear-server/assets/63200569/1914cd5d-c9b1-473f-9514-df295da7b354

**Comment by IniZio** [comment]
For emoji display issue, there were 2 reasons:
- The font used https://github.com/mozilla/twemoji-colr cannot render properly on Safari. Using https://github.com/13rac1/twemoji-color-font can render well on Safari and other platforms fine.
- Previously there is post-processing done that subsets only flag emojis from the font to file size. https://fonttools.readthedocs.io/en/latest/subset/index.html was used but also makes font not render on Safari `pyftsubset $TTF \
  --no-subset-tables+=FFTM \
  --unicodes=U+1F1E6-1F1FF,U+1F3F4,U+E0061-E007A,U+E007F \
  --output-file=./twemoji-countries.woff2 \
  --flavor=woff2`
