### ISSUE TITLE
Setup OOB OTP 2FA via Phone should not have alternative

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3732]
When 2FA is OOB OTP and verification is whatsapp or SMS, this screen is shown when setting up.

Phone number input in upper part and a "Set up Phone" button below

User should not be allowed to select alternative when entering the phone number.

![Image](https://github.com/authgear/authgear-server/assets/15207470/8746578f-9739-43d7-a276-5f498e7d47d4)

**Comment by tung2744** [comment]
I think the expected behavior should be hide all phone otp related alternatives in this screen, but keep other alternatives such as totp.
