### ISSUE TITLE
Cannot see the OTP entered

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3735]
I think we should not mask the OTP input at all or at least when editing that specific digit field
I cannot see the OTP i've entered at all

https://github.com/authgear/authgear-server/assets/15207470/f042f4b7-d453-41e3-b36c-a0d9ed8f9527

**Comment by fungc-io** [comment]
@arvinhoux Ok to not masking the OTP input?

**Comment by arvinhoux** [comment]
Yes, the user should see the number they are currently entering. Once they move to the next input box after entering, the previous number should be hidden.

Additionally, when the user re-enters, the previous error state should be reset (meaning no error state should be displayed while entering, covering all input boxes).

**Comment by louischan-oursky** [comment]
Implementation note: Should TextFieldController be applicable to OTP Input?

**Comment by fungc-io** [comment]
When focus, unmask the last input digit.
When loss focus, mask all digits
