### ISSUE TITLE
Spinner not load correctly on first load

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3736]
In the primary button, the spinner is not loaded correctly when 1st accessing the site. (e.g. after clearing the cache)

![Image](https://github.com/authgear/authgear-server/assets/15207470/fa60a45b-5b2e-4413-abd2-62f0be59e896)

**Comment by tung2744** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

Try if it can be fixed by this

**Comment by IniZio** [comment]
`font-display: block` has a 3s threshold, and it will still show fallback font. A even "safer" way is to do font check in js, not sure if we will need it for material icon's case.

material icon's file size is 3MB

**Comment by tung2744** [comment]
If we found the font is too large to load, I think we need to create a smaller font file containing only the used icons in ui.
Maybe we can follow up later.

**Comment by IniZio** [comment]
Agree, let me add some tools found when trying to reduce file size.
