### ISSUE TITLE
Should block login if no 2FA set up but 2FA is mandatory

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3737]
# Step to reproduce 

1. Create a user without 2FA
2. Make 2FA mandatory in the project
3. Login with that user
4. Instead of asking me to setup 2FA, i'm asked to enter the "recovery code".

# Expected

Show fatal error if the user don't have recovery code. (No available authenticator)

**Comment by tung2744** [comment]
It seems a new feature we haven't supported yet.

**Comment by tung2744** [comment]
**Proposed modification to authflow**

- In login flow, all authenticators will only show if the user has it. Exceptions are:
    - Primary OOB OTP: Always show in options, and create the authenticator if it doesn't exist.

**Proposed modification to authui**

- If there are not usable authentication options, display a blocked screen, and ask user to contact admin.

**Comment by fungc-io** [comment]
@tung2744 @louischan-oursky 
Btw, this leads me thinking is there anything the admin can help recover if this happened?
Once the project became 2FA-mandatary and some users didn't set it up in the grace period. What can the admin do to help?

**Comment by tung2744** [comment]
Seems no at the moment. Maybe we should consider allowing admin to use portal to add totp / secondary password / secondary oob otp email or phone?

**Comment by fungc-io** [comment]
tested ok
