### ISSUE TITLE
[AuthUI V2, Performance] Take long time to load first contentful paint

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3742]
## Background
- Env: Staging
- Project: qa-ui-vtwo (V2), projectqa (V1)
- Browser: Chrome on Mac

## Description
When runnning lighthouse performance test, V2 takes much longer time than V1 to load the first contentful paint (FCP) and largest contentful paint (LCP).

## Lighthouse Result (AuthUI V2)

![Image](https://github.com/authgear/authgear-server/assets/12539486/2eec61fd-9305-4dd2-8c4d-c405c908622a)

## Lighthouse Result (AuthUI V1)

![Image](https://github.com/authgear/authgear-server/assets/12539486/dda15e96-569c-4fd2-92e6-8956d1027e59)

**Comment by fungc-io** [comment]
@IniZio :
- Need to improve the loading time for icon fonts and emoji flags used in phone input

**Comment by IniZio** [comment]
Current bundle size: 
<img width="1501" alt="image" src="https://github.com/authgear/authgear-server/assets/3119725/601b7b21-49ed-4900-96e7-32ef0db3c8c0">

**Comment by IniZio** [comment]
@louischan-oursky @tung2744 For the country list, is it ok is we only include the official locales (en,zh-TW,zh-HK)? Seems the 3MB from cldr library is already minimal if want to include all locales.

Otherwise will try lazy import / pass from backend instead.

**Comment by louischan-oursky** [comment]
We only use country names. So let's build a custom JSON that contains country names in all supported locales in cldr.

**Comment by IniZio** [comment]
Noticed that currently static assets do not have brotoli / gzip, would it worth adding compression to reduce download time?

**Comment by louischan-oursky** [comment]
We have util/httputil/file_server.go. Right now, FileServer has no constructor. Let's introduce a constructor for it. The constructor should return a FileServer wrapped by https://github.com/nytimes/gziphandler Then we should have gzip enabled.

**Comment by louischan-oursky** [comment]
Opened https://github.com/authgear/authgear-server/issues/3790

**Comment by fungc-io** [comment]
After optimization the FCP is similar to AuthUI v1,
will close this issue

![Image](https://github.com/authgear/authgear-server/assets/15207470/a6ba1535-fe2f-4f35-ae2b-007b37fafac1)
