### ISSUE TITLE
Support Custom Webview as replacement for ASWebAuthentication

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3745]
In mobile SDKs, support the use of custom webview

**Comment by louischan-oursky** [comment]
- Rename WebView to UIImplementation
- Rename DefaultWebView To DeviceBrowserUIImplementation
- Rename PlatformWebView to WebKitWebViewUIImplementation
- Research WKWebKitWebView support for safe area.

**Comment by louischan-oursky** [comment]
- https://github.com/authgear/authgear-sdk-js/issues/260
- https://github.com/authgear/authgear-sdk-ios/issues/159
- https://github.com/authgear/authgear-sdk-android/issues/179
