### ISSUE TITLE
Error message for conflict identity for social login and email in AuthUI v2

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3771]
## Problem

We do not support merging identities on login/signup yet. The error message should suggest the user that the identity is already created but the login method is not available for this account.

### User is signed up with Google or other oauth providers

* User tries to login with email

> Looks like you used Google for login before. You can try login with Google or use another email below.

* User tries to sign up with email

> This email is already registered. You can try login with Google or use another email below.

### User is signed up with email

* User tries to login with Google or other oauth providers

> Looks like you haven't linked up with that Google account yet. You can try another Google account or use your email below.

## Design

The error message should be shown as a message bar on the top of the signup/login page

![image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/92cad885-4720-4794-9a02-8a963584e3ad/f8283878-5367-48bb-bb41-5704be9d8a70?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi85MmNhZDg4NS00NzIwLTQ3OTQtOWEwMi04YTk2MzU4NGUzYWQvZjgyODM4NzgtNTM2Ny00OGJiLWJiNDEtNTcwNGJlOWQ4YTcwIiwiaWF0IjoxNzA5MTgzNzEwLCJleHAiOjMzMjc5NzQzNzEwfQ.c781cxLNssbtPWToKun9JqhbKbp3rvgMHyH-RMDbU9w)

**Comment by fungc-io** [comment]
@louischan-oursky @tung2744 
See if these error messages are feasible without much backend changes?

**Comment by louischan-oursky** [comment]
It is feasible. But we need to introduce translation key for oauth provider. (for replacing the word "Google" in your example)

**Comment by fungc-io** [comment]
That's great, let's do this

**Comment by IniZio** [comment]
@fungc-io How about copywriting for following cases?

- Login with azure when same email already logged in with google
- Signup with email already registered

**Comment by fungc-io** [comment]
@IniZio 

- Login with azure when same email already logged in with google

> Looks like you haven't linked up with that Google account yet. You can try another Google account or use another method below

- Signup with email already registered

> This email is already registered. Do you want to login?

**Comment by fungc-io** [comment]
The position of the error message is wrong

Implemented:
![Image](https://github.com/authgear/authgear-server/assets/15207470/d3a2b9e0-ad43-4986-86b4-3af58fb29089)

Design:
![Image](https://github.com/authgear/authgear-server/assets/15207470/8f7d151b-d07d-474f-ba3c-7b9ba6f8e665)
