### ISSUE TITLE
Claim customization in JWT payload/UserInfo and preview in portal

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3782]
## Problem

- In the portal we allow the developers to modify the JWT payload and UserInfo, like the visibility of attributes.
  - However it's limited because the user cannot change the claim names to fit their system.
  - e.g. They may want to put the `role` info into `x-hasura-allowed-roles`. 
- The developer must test it in their integration to check if the configuration is successful
  - It would be great if they can see the result immediately in the portal

## Appetite

2 weeks

## Solution

- Introduce a template markup language to customize the claim
  - Reference: https://stytch.com/docs/guides/sessions/custom-claim-templates
- In the portal user detail page, add a tab for "User JSON"
- Show the JWT payload and UserInfo in JSON format below. The JWT payload should be already processed by the hook.

**Comment by tung2744** [comment]
> The JWT payload should be already processed by the hook.

It means we must call the hook when you visit the page in portal. However, some hooks could have side effects such as writing data to their own db, so I am not sure if it is suitable.

**Comment by fungc-io** [comment]
🤔 right,
Perhaps we should first allow adding attributes to the JWT natively without the hook.

**Comment by fungc-io** [comment]
Updated issue to include the customizing the claims with template markup language
