### ISSUE TITLE
Auth ui v2 should display login screen if page is unspecified and was signed up in same device

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3785]
Should behave same as v1

**Comment by Ngkaokis** [comment]
@tung2744 What do you mean by `was signed up in same device` here?

**Comment by tung2744** [comment]
@Ngkaokis If I remember correctly, when you signed up in a device, and logout later. Next time when you open the authui, it should go to login by default.
I am not sure if this is correct, please check the login in interaction.
