### ISSUE TITLE
Auth ui v2 - Some alternatives are missing icon

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3787]
![Image](https://github.com/authgear/authgear-server/assets/34942210/4ee9c407-f06f-43fe-a07c-e9b668ed1905)

And the copywriting seems incorrect too

**Comment by Ngkaokis** [comment]
Copy writing for signing up without password should be correct. Instead, as login link and sign up link share the same route `verify_login_link`. We should update the copywriting of verify login link

![Image](https://github.com/authgear/authgear-server/assets/63200569/1c7df51e-4cf3-44d9-be4c-db1ca1dc1413)
