### ISSUE TITLE
Password Strength Meter Broken

### ISSUE THREAD

**Issue by Ngkaokis** [authgear/authgear-server#3796]
![Image](https://github.com/authgear/authgear-server/assets/63200569/d10ea266-1674-43c3-824b-3ce626df86b9)

**Comment by IniZio** [comment]
Some notes before reverting lazy loading zxcvbn:

- Lazy load works for some lib but fails for others (tested stimulus and `axios` works, `zxcvbn` and `@floating-ui/dom` always fails).
- `parcel@2.8.3` is the last version that lazy load works for zxcvbn. `2.9.0` introduced new transform and default to swc optimizer. Suspect it changed behaviour of lazy loading cjs, thus causing bundle not found error.

**Comment by louischan-oursky** [comment]
parcel seems very unstable. Switching to vite is also a choice worth exploring.
