### ISSUE TITLE
Doc link to GTM integration leads to 404 on portal

### ISSUE THREAD

**Issue by buildbro** [authgear/authgear-server#3800]
**Describe the bug**
The link to the Google Tag Manager integration guide in the Authgear Portal leads to an invalid page (404).

This issue is based on another issue raised [here](https://github.com/authgear/docs/issues/151).

**Authgear Version**
 - Version: till today 16/02/2024

**To Reproduce**
1. Login to Authgear Portal,
2. Select your project,
3. Navigate to **Integrations** > **Google Tag Manager**
<img width="1470" alt="authgear-gtm-guide-link" src="https://github.com/authgear/authgear-server/assets/16970059/d607f5b4-851f-41d5-aac9-4e20630c256b">
 
4. Click on the "integration guide" link to see the 404.

**Expected behavior**
In intent is for this link to point to the GTM Integration guide. The guide is actually here: `https://docs.authgear.com/how-to-guide/integration/user-analytics-by-google-tag-manager`

**Screenshots**
<img width="1232" alt="authgear-doc-404" src="https://github.com/authgear/authgear-server/assets/16970059/3c4cb443-d0a5-4be7-87d1-49556b6718b1">

**Comment by fungc-io** [comment]
@Ngkaokis please also help edit this link since you are working on the portal
