### ISSUE TITLE
Open and close “Change Password” page from SDK

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3813]
## Problem

Some users wish to use our pre-built "Change Password" page but not the full "Settings" page.

## Solution

- Provide `authgear.open(Page.ChangePassword)` in the SDKs
- When the change password page is opened by this approach, the user cannot navigate to the `/settings` page or other pages from the UI. After changing the password, in the success screen, the primary button will close the webview.

**Comment by IniZio** [comment]
Currently we use interaction to change password, with redirectURI hard-coded to `/settings`, can we pass custom redirectURI as follow?

```swift
authgear.open(.changePassword, escOnSuccess: true)
```

It concats `?redirect_uri=%2F%3Ferror%3Dsuccess` which replaces server side's redirectURI https://github.com/authgear/authgear-server/blob/c536713e7fc73b5dc585501090ccd6cc52ea7693/pkg/auth/handler/webapp/settings_change_password.go#L78

**Comment by fungc-io** [comment]
Need to discuss how should web be handled

**Comment by IniZio** [comment]
After discussion:

- If page is opened in new tab, will close on success similar to other SDK's behaviours
- If page is opened in same tab, will try to pop history til original page

**Comment by fungc-io** [comment]
If pop history is not feasible, we may need to provide a field in the portal for "Post-change-password URL"..

**Comment by IniZio** [comment]
After testing implementing with web sdk, found original double redirect_uri approach hard to accommodate it.

Will do following changes:
- Separate web SDK from prs since it will need special handling on history after success 
- Pick up https://github.com/authgear/authgear-server/pull/2886 again, treating settings action as an intermediate before redirect URI
- Update SDK to have explicit `changePassword()` method that resolves on redirectURI and fails on cancel

**Comment by IniZio** [comment]
@tung2744 @louischan-oursky Since we have settings action behave like authenticate now, don't think we will have `openInSameTab` option now? Will need to try blocking user going back to change password page after complete instead.

**Comment by louischan-oursky** [comment]
Let's remove the `openInSameTab` option in our new methods.

**Comment by fungc-io** [comment]
@newman @louischan,

I found that the change password function is not on API reference yet.

[https://authgear.github.io/authgear-sdk-js/docs/capacitor/classes/CapacitorContainer/](https://authgear.github.io/authgear-sdk-js/docs/capacitor/classes/CapacitorContainer/)

Is it available in the v2.7.0? If so, should we update the references?

**Comment by louischan-oursky** [comment]
Updated the API reference.

**Comment by fungc-io** [comment]
@newman @louischan For other SDK: iOS, Android, Flutter, do we need to update the version?
asking coz i saw that the last-update date for ios doc is 2023-01-12 [https://authgear.github.io/authgear-sdk-ios/](https://authgear.github.io/authgear-sdk-ios/)
and the publish date for flutter sdk on pub.dev is 4 months ago [https://pub.dev/packages/flutter_authgear](https://pub.dev/packages/flutter_authgear)

**Comment by louischan-oursky** [comment]
iOS: Fixed a bug that docs was not deployed https://github.com/authgear/authgear-sdk-ios/commit/458d4bab1e11452c86500838dab6323b93cf1315
Android: Added a job to deploy docs https://github.com/authgear/authgear-sdk-android/commit/8463fbf67fad7de6e3aee2ae68d9239075b14238
Flutter: Published 1.2.0 https://pub.dev/packages/flutter_authgear/versions/1.2.0

**Comment by fungc-io** [comment]
Thanks @louischan-oursky
