### ISSUE TITLE
Consider adding identifier for each data type in authflow

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3823]
Currently, same action could have different data returned in different steps.
For example, when `action.type` is `create_authenticator`, and `authentication` is `secondary_oob_otp_sms`, there are two possible data types can be returned: `NodeVerifyClaimData` and `IntentSignupFlowStepCreateAuthenticatorData`.
If `NodeVerifyClaimData` is returned, user should input a otp. If `IntentSignupFlowStepCreateAuthenticatorData` is returned, user should provide a `target`.

Currently, in our webapp, we check the internal type of the data and do corresponding logic. However, it will be impossible to do so for external integrations which call the http api.

Should we consider to add a `type` to each data type we returned?

**Comment by IniZio** [comment]
Had same thought when exploring authflow testing as well. Thinking if we could provide identifier for next steps and corresponding schemas?
