### ISSUE TITLE
Review restrictions Portal API on modifying html templates or css

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3824]
Currently, projects can have their own css and html templates overridden by app specific resources. However, it seems we should have some restrictions on it, or else any project can modify the template / css to remove watermark or even host a unrelated static site.

Maybe we should only allow apps with paid plan to do so?

**Comment by fungc-io** [comment]
- Use allowlist to allow which resources can be override by the users

**Comment by tung2744** [comment]
Tested and it will be blocked by csp.
