### ISSUE TITLE
[AuthUI v2] Passkey is not supported in WKWebView/ WebKitWebView

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3844]
## Problem

In WebKit WebView,
Passkey is not available on iOS and Android.
Which is similar to the problem described here: https://github.com/authgear/authgear-server/issues/3420

However now we support WKWebView in the SDKs by default, the user will see passkey option easily in the signup login flow.

## Solution

Hide Passkey options in the AuthUIv2 if the user agent cannot support it.

**Comment by tung2744** [comment]
As discussed in product meeting, we will throw error instead.

**Comment by fungc-io** [comment]
It may conflict with the Scenario 5 marked here: https://github.com/authgear/authgear-server/issues/2320

A possible solution may be find a error message that works for both situations

**Comment by tung2744** [comment]
I think we cannot distinguish the two situations.
What if we display the following message?
"Invalid passkey, or passkey is not supported in this device."

**Comment by louischan-oursky** [comment]
Actually Scenario 5 seems like a bug in iOS 16. Can Tung try to reproduce it on iOS 17?

**Comment by tung2744** [comment]
Let me test it out later.
But I guess we need to handle that error too as safari 16 is common.

**Comment by fungc-io** [comment]
@tung in the Taiwan translation, a 匙 is missed `無效通行密匙或您的瀏覽器不支援通行密鑰。請選擇其他驗證方法。` Btw let's change to 

`Passkey is not supported in this device, or invalid passkey. Please select another authentication method.`

`您的裝置不支援通行密匙或通行密匙無效。請選擇其他驗證方法。`
`您的裝置不支援通行密鑰或通行密鑰無效。請選擇其他驗證方法。`

? seems "browser unsupported" is more common than the scenario 5 above?
