### ISSUE TITLE
Disable text selection in WKWebView mode

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3846]
- [x] iOS https://github.com/authgear/authgear-sdk-ios/pull/163
- [x] Android
- [x] React Native
- [x] Capacitor
- [x] Flutter

---

When the developers use WKWebView UI mode, they expect an experience as close to native as possible
which the text on the interface should not be selectable

See if we can disable text selection in this mode?

![Image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/6d2b73fe-636e-440f-9d02-f11f095f5b90/fb0af159-690a-4eab-87dd-2719d62f0fc3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi82ZDJiNzNmZS02MzZlLTQ0MGYtOWQwMi1mMTFmMDk1ZjViOTAvZmIwYWYxNTktNjkwYS00ZWFiLTg3ZGQtMjcxOWQ2MmYwZmMzIiwiaWF0IjoxNzA5MTgxOTY4LCJleHAiOjMzMjc5NzQxOTY4fQ.5xhNf6duvaovJBgTh9JqEaqjivam7biQ_z-BXOIgcL8)

**Comment by tung2744** [comment]
@fungc-io What do you think if we always disable text selection in auth ui?

**Comment by louischan-oursky** [comment]
I think we should keep text selection. It feels more natural on the web.

**Comment by tung2744** [comment]
🤔 Then we need to use something such as query parameter to determine if it is inside webview.

**Comment by louischan-oursky** [comment]
I think we can fix this in the WKWebView. For example, inject a small JavaScript to run `document.body.style.userSelect = 'none';` 

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
The doc says that the default value of `auto` behaves much like inherited. So we only need to set `user-select: none` on `<body>`

**Comment by louischan-oursky** [comment]
Some SDKs are still missing this fix.
