### ISSUE TITLE
Country list may be broken if the search box is scrolled away

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3848]
## Steps to reproduce 

- Use WebKit Webview on iOS
- open the country list in phone input
- Drag the area around the search box and scroll up.
- The country list will be broken and cannot see the searchbox again.

The problem is not severe because 1) the user can select any country and re-open the list,  it will reset automatically & 2) it's a very specific action that is not easy to trigger,
It's more a aesthetic problem.

![Image](https://github.com/authgear/authgear-server/assets/15207470/758cfc8e-f2c7-4050-8a31-ff01e0ec51ac)

https://github.com/authgear/authgear-server/assets/15207470/167bc9a3-90f5-4b85-b024-eff8a5b26e2e

**Comment by fungc-io** [comment]
Possible fix: Dismiss keyboard (unfocus) when tapping outside the text box

**Comment by IniZio** [comment]
Still got edge cases with this fix, moving back.
