### ISSUE TITLE
Should automatically remove leading 0 from local phone number in phone input

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3850]
In many countries such as UK and Taiwan,
The local phone number is preceded by a leading `0` when used locally. It's normal for user to type the `0` into the phone number field when using a local service.

e.g. a number `+44 7712 123456` is usually entered as `07712 123456`

It's treated as invalid in the new AuthUI.

However in the old implementation `+44 07712 123456` would be recognized as `+44 7712 123456` correctly

![Image](https://github.com/authgear/authgear-server/assets/15207470/dddcc695-f7ac-4fd8-84e0-a0f2d08f5997)

**Comment by tung2744** [comment]
It seems instead of handling in authui, we should handle it in server.

The phone number should be normalized in server side.

**Comment by tung2744** [comment]
I wanted to fix it in server side, however, I found that it is related to the PhoneChecker https://github.com/authgear/authgear-server/blob/main/pkg/lib/authn/identity/loginid/type_checkers.go#L281 which calls the format checker https://github.com/authgear/authgear-server/blob/main/pkg/util/validation/formats.go#L64.
And this checker is used in many places to validate phone inputs.
So to prevent changing behavior of many places, I think I will fix it in ui.
