### ISSUE TITLE
WebKit Webview iPad support

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3851]
In the capacitor demo app, the webkitwebview is should as a small window 

![Image](https://github.com/authgear/authgear-server/assets/15207470/49fdeba1-b8a5-4f43-8b8e-c003ebd550e8)

Is the feature supported in iPad or it's just our demo app?

**Comment by louischan-oursky** [comment]
I have set [UIModalPresentationStyle.fullScreen](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/fullscreen) but it did not work as I expected. Need further investigation why that happened.
