### ISSUE TITLE
The type-ahead country code should be hidden upon input

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3852]
Old implementation, the country code is hidden after certain digits are entered

https://github.com/authgear/authgear-server/assets/15207470/0e764b11-b223-4788-8f33-8701ed555b3e

New implementation, the country code will not go away

https://github.com/authgear/authgear-server/assets/15207470/d8ac2ab4-8c94-4a7f-91ce-66b68537b696

**Comment by louischan-oursky** [comment]
I doubt whether changing the text when the user is still editing is a good UX. Maybe we can remove the country calling code when the input is blur?

**Comment by tung2744** [comment]
Agree. And actually the old auth ui also won't remove the country code immediately.

**Comment by fungc-io** [comment]
@tung2744 oh right, i've just tested that again.
Why the behavior is different in Portal and old AuthUI?

**Comment by tung2744** [comment]
It seems we did some special handling on portal.

**Comment by fungc-io** [comment]
🤔 , ok
Let's trim the country code only on blur
