### ISSUE TITLE
Alternative SMS/WhatsApp button in Active state

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3861]
![Image](https://github.com/authgear/authgear-server/assets/15207470/e9ef132c-b04c-4ea8-b875-edc42bd62d9a)

When verifying phone number, the SMS/WhatsApp button is in grey state color scheme in the default state.

**Comment by tung2744** [comment]
@fungc-io I am unable to reproduce it, where do you see this bug?

**Comment by fungc-io** [comment]
I tried that on the iOS capacitor app

**Comment by fungc-io** [comment]
Screenshots containing personal info were sent privately.
On further testing, this would happen when switched multiple times. e.g. SMS->WhatsApp->SMS

**Comment by tung2744** [comment]
@fungc-io It seems that is because ios safari put your cursor on that position after you pressed the button, therefore the button at that position becomes "hover" state. Not sure if this can be fixed..
