### ISSUE TITLE
Cannot open external link in webkit webview

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3864]
When using webkit webview,
Clicking "Terms of Service" and "Privacy Policy" will have no response.

1. Set up the links in UI Settings
   * I put `https://google.com`
2. Open the login page with webkit webview
3. Click the links and no response

The links works on desktop. I guess thats because of `target=_blank`?

---

Fix sdks

- [X] ios [https://github.com/authgear/authgear-sdk-ios/pull/164](https://github.com/authgear/authgear-sdk-ios/pull/164)
- [X] android [https://github.com/authgear/authgear-sdk-android/pull/185](https://github.com/authgear/authgear-sdk-android/pull/185)
- [X] Capacitor [https://github.com/authgear/authgear-sdk-js/pull/268](https://github.com/authgear/authgear-sdk-js/pull/268)
- [X] React Native [https://github.com/authgear/authgear-sdk-js/pull/268](https://github.com/authgear/authgear-sdk-js/pull/268)
- [X] Flutter [https://github.com/authgear/authgear-sdk-flutter/pull/34](https://github.com/authgear/authgear-sdk-flutter/pull/34)

**Comment by tung2744** [comment]
It seems we need to listen to all click event of anchor elements, and use native code to open the url in sdk when the ui is running in webview.

@louischan-oursky @IniZio @Ngkaokis See if any other thoughts?

**Comment by louischan-oursky** [comment]
In WKWebView, we should extend our navigationDelegate to handle external link. See https://stackoverflow.com/a/25713070
In android.webkit.WebView, we need to investigate whether our ChromeClient can detect external link.

For both platform, I think the behavior is to open the link with the device browser.

**Comment by IniZio** [comment]
Should we only whitelist authgear and links configured by client or allow all links?

**Comment by louischan-oursky** [comment]
The link can be set to anything by the developer. So all links are allowed.

**Comment by tung2744** [comment]
I found this thread for android:
https://stackoverflow.com/questions/18187714/android-open-target-blank-links-in-webview-with-external-browser

But it seems the solution isn't perfect.
