### ISSUE TITLE
Link to Docs and Discuss your needs in the Portal

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3872]
In the portal header, add links to "Docs" and "Discuss your needs"

* Docs should link to: [https://docs.authgear.com/](https://docs.authgear.com/)
* Discuss your needs should link to [https://www.authgear.com/schedule-demo](https://www.authgear.com/schedule-demo) with the Email and name prefilled

**Comment by fungc-io** [comment]
Figma: [https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=102-24418&mode=design&t=MRp0DpKCNDAHEiO3-4](https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=102-24418&mode=design&t=MRp0DpKCNDAHEiO3-4)

On wider screens:

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/5d5e20a0-f5eb-4b63-b4f0-2f4b7da5bfd4/4d9a4ab3-8ca1-41f8-b9a1-ecfb341a370f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi81ZDVlMjBhMC1mNWViLTRiNjMtYjRmMC0yZjRiN2RhNWJmZDQvNGQ5YTRhYjMtOGNhMS00MWY4LWI5YTEtZWNmYjM0MWEzNzBmIiwiaWF0IjoxNzA5MzEyMzA5LCJleHAiOjMzMjc5ODcyMzA5fQ.fLN7QJ6J-cH6SruES-DsSeONxVI7aazLU4UVTSuLsB4 " alt="image.png" width="3024" height="1680" />

In narrower screens:

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/4bd32bb7-144e-45fb-a031-89cd921cf705/2c9273ff-1253-4c7a-abb8-109446560451?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi80YmQzMmJiNy0xNDRlLTQ1ZmItYTAzMS04OWNkOTIxY2Y3MDUvMmM5MjczZmYtMTI1My00YzdhLWFiYjgtMTA5NDQ2NTYwNDUxIiwiaWF0IjoxNzA5MzEyMzA5LCJleHAiOjMzMjc5ODcyMzA5fQ.SgjOFaU2eG7ge9kcyPVBMruZCIphuCmLF6AxDOp2Ep4 " alt="image.png" width="786" height="1704" />

When the screen is narrow:

* Move the user name, account setting, sign out into the navigation bar
* 

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/1c679d4d-5b65-4fa8-8f9e-8aaaad991a6c/68884056-da09-4241-8de0-6a05650f7db4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8xYzY3OWQ0ZC01YjY1LTRmYTgtOGY5ZS04YWFhYWQ5OTFhNmMvNjg4ODQwNTYtZGEwOS00MjQxLThkZTAtNmEwNTY1MGY3ZGI0IiwiaWF0IjoxNzA5MzEyMzA5LCJleHAiOjMzMjc5ODcyMzA5fQ.IZlWen1V6xN0tsFpfegUNj2w25MNUsuihnMu6l1FvFg " alt="image.png" width="544" height="1750" />

Measurement

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/b9e4dc86-32a9-4fbb-aa54-cdc2509f65aa/f8290592-10c2-4f0a-9688-a7ba0ec67e3e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9iOWU0ZGM4Ni0zMmE5LTRmYmItYWE1NC1jZGMyNTA5ZjY1YWEvZjgyOTA1OTItMTBjMi00ZjBhLTk2ODgtYTdiYTBlYzY3ZTNlIiwiaWF0IjoxNzA5MzEyMzA5LCJleHAiOjMzMjc5ODcyMzA5fQ.mOnTAnwi9zPwSnm0ECo11RloBVuoteaWWwW4RfnvsxQ " alt="image.png" width="544" height="1750" />

**Comment by IniZio** [comment]
@fungc-io Not sure whats the query param to prefill schedule demo form?

**Comment by fungc-io** [comment]
It's not set yet. I think we can just put `?email=xxx&name=xxx` first. And I will ask the marketing team to update to accept the params

**Comment by IniZio** [comment]
Seems works

Example generated url: https://www.authgear.com/schedule-demo?email=newman_phone%40ourskyadfs.com&name=Sum+Ting+Wong

![image](https://github.com/authgear/authgear-server/assets/3119725/7bb7387b-b9f6-4df8-8e07-20cf19eacc5c)
