### ISSUE TITLE
Add phone number to onboarding wizard

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3873]
## Problem

We would love to contact the signed up user to discuss their use cases.

## Solution

* In "Create your first project wizard", add an additional field for an optional phone number.

![SCR-20240228-jbj.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/29b84116-e1b2-4ff1-88cd-580a63fa257d/6dba3f14-8be2-499e-a8b1-fcfadf974df7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8yOWI4NDExNi1lMWIyLTRmZjEtODhjZC01ODBhNjNmYTI1N2QvNmRiYTNmMTQtOGJlMi00OTllLWE4YjEtZmNmYWRmOTc0ZGY3IiwiaWF0IjoxNzA5MjA0MjE0LCJleHAiOjMzMjc5NzY0MjE0fQ.jOWn8AgKHi4UzHlU7_eAJYPEBTGsUyeXPf6BZqWp12w "=1272x")

* Copywriting:

> **Would you mind to share us your phone number?**
>
> \\\[phone input\\\]

* There will be no validation on the phone number
* The country code is auto-selected based on IP.
* Add the phone number as a custom attribute in the `accounts` app, so it will be shown in the `user.updated` webhook for further integration

**Comment by chpapa** [comment]
A few thoughts:

1. Maybe a shorter copywriting: "Would you like to discuss your needs over phone?"
2. As phone no is optional, let's not do validation? (So we don't block users who don't care)

**Comment by fungc-io** [comment]
Ok, the description is edited

**Comment by fungc-io** [comment]
@newman Seems the country code selection is not based on my IP address.

It's showing Afghanistan for in when i test it

**Comment by fungc-io** [comment]
The location fix should be included in the next release, @louischan can you help review and merge in on Tuesday morning?

**Comment by fungc-io** [comment]
@newman 

There is some problem with the phone input. I should be able to put in random number without validation.

Problems:

1. It's blocked by the custom attribute validation in the first attempt?
2. In the second attempt, it will say the project ID is already created. However, when i refresh the page, i will see the user does not own any project.

[Screen Recording 2024-04-02 at 09.49.06.mov](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/980eb4e1-c1d1-4896-ba19-04e7886086a7/83481170-4d49-4e44-92cf-08da75f40c69?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi85ODBlYjRlMS1jMWQxLTQ4OTYtYmExOS0wNGU3ODg2MDg2YTcvODM0ODExNzAtNGQ0OS00ZTQ0LTkyY2YtMDhkYTc1ZjQwYzY5IiwiaWF0IjoxNzEyMDQ3OTEyLCJleHAiOjMzMjgyNjA3OTEyfQ.B2FSAjTTGENh7yl046_AgWVexrXL4ToMksXHsGe21-Y)
