### ISSUE TITLE
Staging Portal takes long time to update resources

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3888]
1. Trying to update some translations
2. Save
3. Waited 44 seconds

![Screenshot 2024-02-29 at 7.35.12 PM.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/3b0cce04-8ebf-4b1c-9541-57dba090cb83/f46d3b41-4aa2-484d-a6d1-cbd4fd7f1c5c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8zYjBjY2UwNC04ZWJmLTRiMWMtOTU0MS01N2RiYTA5MGNiODMvZjQ2ZDNiNDEtNGFhMi00ODRkLWE2ZDEtY2JkNGZkN2YxYzVjIiwiaWF0IjoxNzA5MjA2NTcyLCJleHAiOjMzMjc5NzY2NTcyfQ.HwAf49Kqu0cBDowj5t8llKUrhaUMKED7wDpE069g3jA "=748x")

**Comment by louischan-oursky** [comment]
Affected by the checksum?

**Comment by IniZio** [comment]
Seems only localization has this issue, other pages are fine.
