### ISSUE TITLE
Implement loginID phone number widget

### ISSUE THREAD

**Issue by axolotl0212** [authgear/authgear-server#390]
Design for phone number widget is updated

- [x] Country name translation -> i18n-iso-countries
- [x] Phone number country code to region code mapping
  - [x] script for generate hard coded map => google libphonenumber (getRegionCodesForCountryCode)
  - [x] use hard coded map for getting country code with calling code
- [x] Create list with selection and ordering in only selected item
- [x] selected all -> checked, partially selected -> indeterminate, none selected -> unchecked
- [x] Implement search box (local filtering, only filter unselected)
- [x] Implement search logic and filtering
- [x] Study mapping between config and UI state
- [x] Handle change config mutation

**Comment by kiootic** [comment]
- Update config
    - Replace `values` with `allowlist`: List of country codes in the list (excluding in `pinned`)
    - Replace `default` with `pinned_list`: List of country codes pinned to the top of the list

**Comment by axolotl0212** [comment]
@kiootic config / backend is not yet updated? only pinned item can be ordered according to design? Does pinned item has any special meaning? If not, splitting selected items into two list in config seems weird to me

**Comment by kiootic** [comment]
Yes config is not updated yet, I'll open an issue for that.

Pinned items would be shown at the top of the country code list in UI (e.g. when logging in), and the rest of the active countries would be sort in default order. Only active items can be pinned; pinning inactive items would make them active, and inactivate pinned item would make them unpinned.
