### ISSUE TITLE
Role - Create Role Form

### ISSUE THREAD

**Issue by Ngkaokis** [authgear/authgear-server#3902]
![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/d8bd91b3-9b1c-45c6-9105-7e96b0d5ff61/80582493-1dbc-4883-8406-2d235ec2ad9e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9kOGJkOTFiMy05YjFjLTQ1YzYtOTEwNS03ZTk2YjBkNWZmNjEvODA1ODI0OTMtMWRiYy00ODgzLTg0MDYtMmQyMzVlYzJhZDllIiwiaWF0IjoxNzA5NTM1NjE4LCJleHAiOjMzMjgwMDk1NjE4fQ.KdnowEcP39D5TEmaFC8GYYp0ZaqoKBTvlYUOiLx7Eng "=1253x")

**Comment by tung2744** [comment]
@fung Sorry, I forgot what is our decision about the generated value on the role name field? Do we still generate it from the key?

**Comment by fungc-io** [comment]
No, only in Group. No need to setup key-name relation in Roles
