### ISSUE TITLE
Further improvement on copywriting

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3918]
Now the AuthUI v2 is available on production for testing, this issue is used for collecting feedback on the copywriting:

1. `Login to [Project] to continue to [Application]` is too convoluted
   1. suggested to change to : `Login to [Application]`

**Comment by fungc-io** [comment]
@fungc-io to check the copywriting in Sign up too

**Comment by fungc-io** [comment]
@newman,

checked and no need to change the message for sign up, keep:

| Sign up for {AppName} | 建立您的 {AppName} 帳戶 | 建立您的 {AppName} 帳號 |

For login:

* en: Login to {ClientName} || Login to {AppName}
* zh-hant: 登入至 {ClientName} || 登入至 {AppName}}

**Comment by louischan-oursky** [comment]
I wonder why AppName is used in Sign up, while ApplicationName is used in Log in.

**Comment by tung2744** [comment]
@fungc-io Does it means we always use project name instead of client name in all cases? (signup, login, signup login)

**Comment by fungc-io** [comment]
No, i meant to use project name in signup and signup/login; and client name in login.

imo the user is login to the app and signup to the project… 🤔 

do you guys think it's simpler to just "signup/login to the project"?

**Comment by louischan-oursky** [comment]
It is easier to explain if we stick with project name by default.

**Comment by fungc-io** [comment]
all right, let's do that 🙌 @louischan @tung2744 @newman 

Signup, login and signup/login to project name
