### ISSUE TITLE
Support custom domain

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#392]
## Imagined Scenario

Authgear is deployed on `authgearapps.com`. John is a developer working for `company.com`. John wants to use Authgear for his company, deployed at `accounts.company.com`.

Things to be resolved:

- How to provide the TLS certificate of `accounts.company.com`?
- How should `www.company.com` authenticate the request?

**Comment by kiootic** [comment]
> How to provide the TLS certificate of accounts.company.com?

I suppose Let's Encrypt with HTTP01 challenge should work when using CNAME record.

> How should www.company.com authenticate the request?

I suppose you mean how would the application backend validate the credentials (e.g. OAuth access token, cookies) in the request. I suppose we may expose the resolver endpoint at a random sub-path of the domain, in case we don't want public access to it? (e.g. `https://example-app.authgear.com/_resolve/4A102642-C16A-493C-A15C-6D239D40CC4F`)

**Comment by kiootic** [comment]
- Remove `hosts.json`, replace with per-app ingresses
    - Use wildcard cert for SaaS deployment
    - Use per-app ingress? or wildcard ingress. (investigate cert-only Let's Encrypt cert-manager)
- verified domain state
    - add database to portal backend
    - two tables, one for pending (no unique), for verified domain (with unique constraint on eTLD + 1 & app)
    - need careful safety check for data consistency
    - provide TXT record & CNAME record
    - only one custom domain per app; only one authgear per eTLD + 1
- TLS cert
    - wildcard cert: cert-manager with Let's Encrypt DNS validation (cert-only, no ingress)
    - per-app custom cert: cert-manager with Let's Encrypt HTTP validation (automatic with ingress)
- Resolver endpoint (TBD)
