### ISSUE TITLE
Create default translation for Email, SMS in zh-Hant-HK/TW

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3935]
- [X] Add script for 2-stage mjml to generate html per language

Seems latte's a bit different, it's gotemplate is the 2nd stage whereas authgear's need to be gotemplate -> mjml -> html instead?

- [X] Apply translations for text templates and html templates

**Comment by IniZio** [comment]
All templates in https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages lack zh translation.

Text versions:
- [authenticate_primary_login_link.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/authenticate_primary_login_link.txt)
- [setup_primary_login_link.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/setup_primary_login_link.txt)
- [authenticate_primary_oob_email.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/authenticate_primary_oob_email.txt)
- [setup_primary_oob_email.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/setup_primary_oob_email.txt)
- [authenticate_secondary_login_link.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/authenticate_secondary_login_link.txt)
- [setup_secondary_login_link.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/setup_secondary_login_link.txt)
- [authenticate_secondary_oob_email.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/authenticate_secondary_oob_email.txt)
- [setup_secondary_oob_email.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/setup_secondary_oob_email.txt)
- [forgot_password_email.txt](https://github.com/authgear/authgear-server/tree/main/resources/authgear/templates/en/messages/forgot_password_email.txt)

Should can copy back to mjml template after updated these. 

---

As suggested in meeting, can probably use 2-stage mjml to generate final html per language

**Comment by fungc-io** [comment]
@newman please find the updated translation in this spreadsheet:
[https://docs.google.com/spreadsheets/d/1wzbft4HH4jE5UmpSuMxbRs6MTjrVyAfLEXGQkJT0q80/edit#gid=0](https://docs.google.com/spreadsheets/d/1wzbft4HH4jE5UmpSuMxbRs6MTjrVyAfLEXGQkJT0q80/edit#gid=0)

**Comment by fungc-io** [comment]
@newman I found the reset pw sms contain duplicated sentences 

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/ee60546f-a6ca-4a56-807e-0ae9de1baa59/f6efba24-efaf-4f87-9b7c-fca362572a26?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9lZTYwNTQ2Zi1hNmNhLTRhNTYtODA3ZS0wYWU5ZGUxYmFhNTkvZjZlZmJhMjQtZWZhZi00Zjg3LTliN2MtZmNhMzYyNTcyYTI2IiwiaWF0IjoxNzEwNDE5MTIzLCJleHAiOjMzMjgwOTc5MTIzfQ.8f7Exu_GIThQtbhCm6txIOU-1zjlHGVdsoJeRTEUBt0 " alt="image.png" width="798" height="281" />

**Comment by louischan-oursky** [comment]
Fixed in 1b75dc700f869629acca96f1a181f720a8d4dee4

**Comment by fungc-io** [comment]
tested, thanks!
