### ISSUE TITLE
[Portal] Make component body shorter

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#396]
Try make component body shorter

## Break the component into smaller, local components within the file

```typescript
// ScreenA.tsx

function SectionA() {

}

function SectionB() {

}

function ScreenA() {
  return (
    <div>
      <SectionA propA={propA} propB={propB} />
      <SectionB propC={propC} propB={propB} />
    </div>
  );
}
```

The goal here is to make each component easy to understand and reason about.

**Comment by roxk** [comment]
I will add: it improves readability too :D since nested component's indentation hurts readability.
