### ISSUE TITLE
Role and groups - Tag picker styles follow up

### ISSUE THREAD

**Issue by Ngkaokis** [authgear/authgear-server#3969]
[https://github.com/authgear/authgear-server/pull/3963#pullrequestreview-1933181055](https://github.com/authgear/authgear-server/pull/3963#pullrequestreview-1933181055)

**Comment by Ngkaokis** [comment]
Tried to look into the callout props. Seems nothing to help adjusting the width. 

Any concern I go ahead to implement ResizeObserver? @tung2744

**Comment by tung2744** [comment]
@Ngkaokis What about `onLayerMounted`?
If that doesn't work please use `ResizeObserver`.

**Comment by Ngkaokis** [comment]
> What about onLayerMounted?

Seems work! Originally thought it's something only triggered on the very first place :derpthink:
