### ISSUE TITLE
Searching users with roles and groups

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3975]
## User Story

* As a user, i want to search the users based on roles and groups and a free text search.
* **Use case:** given 100 users; 20 IT Manager (5 of them are from `@acme.com`); 80 others (10 of them are from `@acme.com`)
  * The user wants to search the 5 IT managers that are working in Acme.
* **Use case:** e.g. there are over 100 user groups, I can type "IT" to reduce the list to only IT-related groups, so it's easier for me to find the "IT Manager".

## Design

Figma:

[https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=418-5938&mode=design&t=Qec3sNbP5bJRVWVL-4](https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=418-5938&mode=design&t=Qec3sNbP5bJRVWVL-4)

* Add 2 boxes next to the search box, 1 for "Roles", 1 for "Groups"
  * When there were no roles defined in the project, hide this element. Same as Groups.
* When open the dropdown, it will show all the roles defined, use the search box to filter the list with by searching the role name and role key.
  * 6 items max will be shown at the same time without scrolling
  * when nothing match the search criteria, show empty state
  * After click, Show the selected role in the box, the box length is variable to show the full role key value
  * Press "X" to empty the role selection and open the dropdown list.
* Same as group, but in group, show the group name instead of group keys.
* Selected roles and groups are "AND" relation. i.e. I can search users who are both in "IT Manager" group and with "app_a_admin" role at the same time.

## Rabbit holes

1. filter by roles is not supported by API yet
2. Current redis cannot support combining filter by roles/groups and free text search at the same time.

**Comment by Ngkaokis** [comment]
\>When open the dropdown, it will show all the roles defined

I think we shouldn't show all the roles defined by default. There should be a max like 100 or something

cc @tung

**Comment by fungc-io** [comment]
ok to have a max 100, but we better show a text saying there are more than 100(need design)
