### ISSUE TITLE
Show roles and groups in the User List

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3976]
## User story

As an authgear user, I can have a glimpse at the user roles and groups in the user table.

## Design

[https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=430-11662&mode=design&t=Qec3sNbP5bJRVWVL-4](https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW/Q1-%2F-2024?type=design&node-id=430-11662&mode=design&t=Qec3sNbP5bJRVWVL-4)

* Add "Roles" and "Groups" column after "Phone"
  * Only show the roles column if there are roles in this project.
  * Only show the groups column if there are groups in this project.
* The role column shows the first assigned role name with "+N" if there are than 1, derived roles also count
* The group column shows the first assigned group name with "+N" if there are than 1
* Nothing happen on hover, user muse click into the user details to see the full list of roles/groups
* Pin the left most cell on horizontal scroll

**Comment by fungc-io** [comment]
@tung @ngkaokis,

Regarding our discussion in the meeting today,

Please keep the Name and UserID in the same cell for this issue, and do not change the filter buttons, the "Signed up" label, and do not change the dates format.

I'll create them as separate issues for other cycles.

**Comment by Ngkaokis** [comment]
<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/0e4980c5-244a-4eb1-b35e-8d067f5ec4b8/d8e99f9c-1ce3-45cd-b53b-2abc23a542a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8wZTQ5ODBjNS0yNDRhLTRlYjEtYjM1ZS04ZDA2N2Y1ZWM0YjgvZDhlOTlmOWMtMWNlMy00NWNkLWI1M2ItMmFiYzIzYTU0MmE5IiwiaWF0IjoxNzEwMzk3Nzc2LCJleHAiOjMzMjgwOTU3Nzc2fQ.CytJI9I5fdCYMQYMmPKLLLkROkX4YVi5yvfnhMDLrAo " alt="image.png" width="341" height="195" />

So for the first column, I expect to keep what it is now except updating the icon color?

**Comment by fungc-io** [comment]
Thanks for pointing out @ngkaokis 
we can keep the icon color
