### ISSUE TITLE
User Search - Support filters users by role key

### ISSUE THREAD

**Issue by Ngkaokis** [authgear/authgear-server#3984]
ref `pkg/admin/graphql/query.go`

- [ ] evaluate if the indices are used properly

**Comment by tung2744** [comment]
Suspected query:

```
EXPLAIN ANALYZE SELECT * FROM _auth_user au
LEFT JOIN _auth_user_group aug ON (aug.user_id = au.id)
LEFT JOIN _auth_group user_group ON (user_group.id = aug.group_id)
LEFT JOIN _auth_group_role agr ON (agr.group_id = user_group.id)
LEFt JOIN _auth_user_role aur ON (aur.user_id = au.id)
LEFT JOIN _auth_role user_role ON (user_role.id = aug.group_id)
LEFT JOIN _auth_role group_role ON (group_role.id = agr.group_id)
WHERE au.app_id = 'my-app' AND (
  user_group.key ILIKE '%test%' OR user_group.name ILIKE '%test%' OR
  user_role.key ILIKE '%test%' OR user_role.name ILIKE '%test%' OR
  group_role.key ILIKE '%test' OR group_role.name ILIKE '%test%'
)
ORDER BY au.created_at DESC LIMIT 100;
```

Some findings:

* `_auth_user` is missing index on `app_id`, filtering with app_id result in sequential scan.
* `_auth_user` is missing index on `_created_at` and `_last_login_at`, which are the two columns used to sort users in the list user api.

**Comment by tung2744** [comment]
* Tried to add ts_vector index in `_auth_group` and `_auth_role`, and filter with `@@` operator with `ts_query`. However, the index is not used.
* Tried to add gin index in `_auth_group.key` and `_auth_role.key` by converting them to arrays, but the index not used as well.
