### ISSUE TITLE
User Search - Dropdown with search bar

### ISSUE THREAD

**Issue by Ngkaokis** [authgear/authgear-server#3985]
![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/04c75898-6713-46f4-9401-03c3bdeb7dad/9ac8c57f-bf79-4a1e-9152-6447ca184409?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8wNGM3NTg5OC02NzEzLTQ2ZjQtOTQwMS0wM2MzYmRlYjdkYWQvOWFjOGM1N2YtYmY3OS00YTFlLTkxNTItNjQ0N2NhMTg0NDA5IiwiaWF0IjoxNzEwMzk4NzE4LCJleHAiOjMzMjgwOTU4NzE4fQ.L_eSWk3NYlQ3T6-mAqOXx1o1t6umCtVgf71xQTZ1ijo "=475x")

![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/e62b2859-37b9-4561-999a-87837f755b26/0e25662e-d819-43fa-8a6f-deb74812300d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9lNjJiMjg1OS0zN2I5LTQ1NjEtOTk5YS04NzgzN2Y3NTViMjYvMGUyNTY2MmUtZDgxOS00M2ZhLThhNmYtZGViNzQ4MTIzMDBkIiwiaWF0IjoxNzEwMzk4ODUxLCJleHAiOjMzMjgwOTU4ODUxfQ.hQJBxRZeBPivfVgzWiUfg0KYk7q6MPKPB1ZxjRXpl04 "=179x")

- [ ] show 6 items
- [ ] add cross button to clear result after selected one
- [ ] variable length to show full text
- [ ] empty state

**Comment by Ngkaokis** [comment]
Not sure if this dropdown is achievable with fluent UI. Don't see a way to customize it as this

@tung Any idea?

**Comment by tung2744** [comment]
I guess we need to implement it by using the CallOut component.
