### ISSUE TITLE
[Portal] Invent a better abstraction for showing errors

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#400]
We can borrow some ideas from the prior art by Terry. The main goals are

1. Avoid conversions. They do not add any value.
2. Be declarative. Imperative errors classification is long and error-prone.
3. Support classified errors and unclassified errors. Classified errors should typically be shown near the control. Unclassified errors should be presented globally, like at the top of the screen and as a dialog.

**Comment by axolotl0212** [comment]
Plan: 

- Remove Violation, use error from backend directly
- Two layer, one ErrorContext and FormContext per screen
- split error handling into two part, validation error and other generic error

## Validation error

- create a custom Form component, takes error, and `fields error list`, only handle error with reason `ValidationFailed`
  ```typescript
      interface FieldErrorHandler {
         jsonPointer: RegExp | string;
         violationType: ValidationErrorCause["kind"];  // violation type in JSON schema
         errorMessageID: string;
       }
    ```
- value extracted from violation (eg. minimum from `minimum` rule violation) will be passed to `renderToString`
- one handler for each kind of violation (in JSON schema)
- special handle required violation (missing field, field name = last segment in json pointer), other just match location with jsonPointer
- RegExp => regExp.source.replace(/\\/g, "").split("/").pop() to get field name

## Generic error
- For unhandled error, throw custom error 
- Error boundary to catch not field specific custom error
  ```typescript
    interface GenericErrorHandler {
       errorReason: APIError["reason"]  // all handled error reason which is string
       errorMessageID: string
    }
    ```
- value extracted from error (eg. errorName, info) will be passed to `renderToString`
- provide handler for common error handler by default (network error)
- if not recognized, use fallback error message (eg. Unknown error)

- error message(s) are injected to components / screen by context as mentioned above, allow customized display of error message
- form context provides error map `Record<FieldNames, string>`, used in each input field
- error context provides error message, displayed in dialog / message bar
