### ISSUE TITLE
Copy writing updates for Groups

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4007]
## No Groups state

More explanation:

> Create groups to represent the types of users that access your applications. Users in a group share the same roles.
>
> For example, all users in "Marketing Manager" group will automatically possess the admin right of a marketing app

![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/87de207a-1668-447d-875e-da37141fbf67/c49861e6-3022-4d66-97dc-a69d98594241?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi84N2RlMjA3YS0xNjY4LTQ0N2QtODc1ZS1kYTM3MTQxZmJmNjcvYzQ5ODYxZTYtMzAyMi00ZDY2LTk3ZGMtYTY5ZDk4NTk0MjQxIiwiaWF0IjoxNzEwNzczNjY3LCJleHAiOjMzMjgxMzMzNjY3fQ.Nizbb2eJXR6bsF920W66UPrDa5BUaKFdqA_615HyNIA "=1322x")

## Group Key

Mention when group keys are used

> The Group Key is a unique identifier for this group when referenced from Admin API and Hooks

![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/32e8c567-ff44-4e96-8463-f156f147d838/3661c541-3c1f-4781-a5d1-dc6c01459e22?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8zMmU4YzU2Ny1mZjQ0LTRlOTYtODQ2My1mMTU2ZjE0N2Q4MzgvMzY2MWM1NDEtM2MxZi00NzgxLWE1ZDEtZGM2YzAxNDU5ZTIyIiwiaWF0IjoxNzEwNzczNjY3LCJleHAiOjMzMjgxMzMzNjY3fQ.7PLyTeCMGZ5n9gY8RkvUlSQtGk-KAVOSqOyJILBWGtI "=418x")

## Add role to group button

The mental hirerachy is that the roles are inside a group. Instead of "Adding group to role" it should be "Adding role to group"

Change button text: "Add to Role" into

> Add Role

![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/eed86833-a467-4352-a868-c8403898d2f3/76e53326-239d-41ff-b3dc-1c71f01b3f35?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9lZWQ4NjgzMy1hNDY3LTQzNTItYTg2OC1jODQwMzg5OGQyZjMvNzZlNTMzMjYtMjM5ZC00MWZmLWIzZGMtMWM3MWYwMWIzZjM1IiwiaWF0IjoxNzEwNzczNzc2LCJleHAiOjMzMjgxMzMzNzc2fQ.-zoynZtxPov3KUozuSYftdWiZ1BGCHc2HK67ruCjfBA "=1248x")

**Comment by tung2744** [comment]
<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/59f9e13f-38bf-4736-9980-c18e487ce5e5/9a7f4300-0eb9-4a0b-96f4-31a6641fd332?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi81OWY5ZTEzZi0zOGJmLTQ3MzYtOTk4MC1jMThlNDg3Y2U1ZTUvOWE3ZjQzMDAtMGViOS00YTBiLTk2ZjQtMzFhNjY0MWZkMzMyIiwiaWF0IjoxNzEwODIzOTA5LCJleHAiOjMzMjgxMzgzOTA5fQ.ldU0Opq_29_-eotq2FAfg8XVzPh59CxAj03TbjsqojY " alt="Screenshot 2024-03-19 at 12.51.30 PM.png" width="380" height="208" />

Like this?

**Comment by fungc-io** [comment]
Sorry @tung2744 can you help change the whole description to this

> Create groups to represent the types of users that access your applications. Users in a group inherit the same set of roles.

Improved wordings and take out the confusing example
