### ISSUE TITLE
[Portal] Refresh authenticator list after removing authenticator

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#403]
Authenticator list is not refreshed after authenticator is successfully removed, will add refetchQueries for now

**Comment by axolotl0212** [comment]
Way to reproduce: 
- user with:
  - 1 password primary authenticator
  - 1 totp secondary authenticator

When calling mutation to delete authenticator (secondary), the following unhandled error is thrown by backend

```
get following error from backend

{
	"data": null,
	"errors": [
		{
			"message": "reflect: call of reflect.Value.Type on zero Value",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			],
			"path": [
				"deleteAuthenticator"
			]
		}
	]
}
```

**Comment by kiootic** [comment]
Cannot reproduce. I've pushed a fix while merging the PR last Friday, can you check if you're working with version `git-58a80c33daff`? You can see what version you're running by observing the log message on startup:
```
INFO[0000] authgear (version git-58a80c33daff)           logger=server
```

**Comment by axolotl0212** [comment]
> Cannot reproduce. I've pushed a fix while merging the PR last Friday, can you check if you're working with version `git-58a80c33daff`? You can see what version you're running by observing the log message on startup:
> 
> ```
> INFO[0000] authgear (version git-58a80c33daff)           logger=server
> ```

Didn't observe this error after pulling the latest code, seems like this is fixed @kiootic
