### ISSUE TITLE
[Portal] Improve dialog UX

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#405]
- [x] Sometimes the dialog flashed while dismissing (after removing a username)
- [x] Sometimes the dialog can be interact with while dismissing.

**Comment by nicolaslee2775** [comment]
For first issue, the confirm and cancel button become enable during dismissing.

![issue-405-1](https://user-images.githubusercontent.com/25860896/95850397-5c93d080-0d83-11eb-9462-38c02eb65eca.gif)
