### ISSUE TITLE
Delete non-existing user will crash

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#4083]

**Comment by fungc-io** [comment]
@louischan how to check this problem? I can close it if this admin api mutation is ok?

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/8ab008d1-a523-4015-829a-2d54b8baa34c/3e0ce255-b6f3-48a5-85e7-34fd22ecdb91?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi84YWIwMDhkMS1hNTIzLTQwMTUtODI5YS0yZDU0YjhiYWEzNGMvM2UwY2UyNTUtYjZmMy00OGE1LTg1ZTctMzRmZDIyZWNkYjkxIiwiaWF0IjoxNzExNjI3MDE2LCJleHAiOjMzMjgyMTg3MDE2fQ.j3ZiIWvhaXrIYmxVlyNJklWZFYaj3w-8X_UZu-isWfc " alt="image.png" width="1082" height="630" />

**Comment by louischan-oursky** [comment]
You need to input a valid but non-existent ID. For example, `echo -n 'User:invalid' | basenc --base64url`

**Comment by fungc-io** [comment]
ok thanks, tested ok 👏
