### ISSUE TITLE
Distinguish first-party & third-party clients

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#410]
For some clients, the access token may have access to more privileged operations, such as logging out of the session from authgear (IdP provider). We need to allow developer to configure the trust of clients.

**Comment by chpapa** [comment]
Is that the only "privileged operations" is to logout the IdP session? If yes, I think most of Authgear's use case should be considered the Client ID as "trusted" / 1st party. Hence maybe in our configuration file and management portal, we can default for trusted, and add a checkbox like "This Client ID is for external applications"

**Comment by kiootic** [comment]
I suppose a trusted client can do everything possible in settings page, so logging out, add/remove identity/authenticator, etc.

For most scenario with untrusted client, they are dynamically registered at runtime (e.g. creating an OAuth client at Google), so I agree that the default status of a client defined in configuration is trusted.
