### ISSUE TITLE
Logout API

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#411]
This API logs user out of authgear. It should be invoked using access token of first-party client only.

Dependency on #410

**Comment by kiootic** [comment]
Scenario: Suppose a vendor develops a website and a mobile app, the vendor wants to have this behaviors:
- When a user logged in in website, the user can log in mobile app without logging in again
- When a user logs out from the mobile app, the user is also logged out from the website.

Potential solution:
- Open a browser to perform logout
- Set a short session expiry time, so the IdP session is expired while the app have a long-lasting refresh token.

**Comment by fungc-io** [comment]
Fixed in https://github.com/authgear/authgear-server/issues/1860
