### ISSUE TITLE
Translation for major East/South-East Asian and European languages

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4131]
## Goal

To provide basic support in the AuthUI for major languages in East/South-East Asian and European languages. So the languages can be used out-of-the-box instead of users' need to translate the file manually.

## Approach

Use Claude to Translate the transtion.json file.

The model I used was `claude-3-haiku-20240307`

Prompt I tried:

```plaintext
- translate the values in the JSON from English into {the language}.
- Don't translate the phrase "Passkey", keep it as is. 
- Return only the JSON and nothing else
```

Due to token limits, the file should be translated 60 lines at a time.

## Appetite

2 days

## East/South-East Asian

* Chinese (Hong Kong)
* Chinese (Taiwan)
* Chinese (China)
* Korean
* Japanese
* Vietnamese
* Thai
* Malay
* Filipino (Tagalog)
* Indonesian

## European

* English
* French
* Spanish (Spain)
  * Variant: Spanish (Latin America)
* Italian
* Portuguese (Portugual)
  * Variant: Portuguese (Brazil)
* German
* Polish
* Dutch
* Greek

**Comment by fungc-io** [comment]
@louischan <br>There are 2 empty entry in the language list, probably from "ES" and "PT"

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/560daa73-3579-47c6-852b-3123016ba1b7/2892f373-3f80-409c-9ea3-98198e50e55b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi81NjBkYWE3My0zNTc5LTQ3YzYtODUyYi0zMTIzMDE2YmExYjcvMjg5MmYzNzMtM2Y4MC00MDljLTllYTMtOTgxOThlNTBlNTViIiwiaWF0IjoxNzE0MTE4NzM0LCJleHAiOjMzMjg0Njc4NzM0fQ.dbSH0toN__0v1BIO1afINDSGafg_PWpKtbPu6-R4q_g " alt="image.png" width="1110" height="1450" />

---

There are some problem with the language resolver. It does not respect the "Accept-Language" and is always using the "Default" language.

**Accept-Language: ko (Korean) in Request Header:**

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/03b68d63-7691-4dea-98d8-7b7024608a87/595c0d54-0eb8-4c16-91e7-5fb4ea36e8f8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8wM2I2OGQ2My03NjkxLTRkZWEtOThkOC03YjcwMjQ2MDhhODcvNTk1YzBkNTQtMGViOC00YzE2LTkxZTctNWZiNGVhMzZlOGY4IiwiaWF0IjoxNzE0MTE4NzM0LCJleHAiOjMzMjg0Njc4NzM0fQ.O6A3nqwOpPeuaS_w_myBJNNV7aiyhxDn2iYegFYY6Yw " alt="image.png" width="3266" height="1808" />

**My Language settings in Chrome:**

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/478a8b46-83c6-4bcb-88ba-6214c3bb6757/c787fb69-654c-427e-9df9-6a6065869b87?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi80NzhhOGI0Ni04M2M2LTRiY2ItODhiYS02MjE0YzNiYjY3NTcvYzc4N2ZiNjktNjU0Yy00MjdlLTlkZjktNmE2MDY1ODY5Yjg3IiwiaWF0IjoxNzE0MTE4NzM0LCJleHAiOjMzMjg0Njc4NzM0fQ.JrTh7NBntc4GmRH6iGMf-m-1ZZZEIi5U_iBDQibb_nY " alt="image.png" width="1516" height="630" />

**Config in Authgear:**

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/ccb32efe-813d-4626-98b8-1bc62b5fcb26/468c0970-6bf0-45b5-9026-bf8142b673ca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9jY2IzMmVmZS04MTNkLTQ2MjYtOThiOC0xYmM2MmI1ZmNiMjYvNDY4YzA5NzAtNmJmMC00NWI1LTkwMjYtYmY4MTQyYjY3M2NhIiwiaWF0IjoxNzE0MTE4NzM0LCJleHAiOjMzMjg0Njc4NzM0fQ.LT_UQxLekiFH5YiS6YaBsJSZ6-5j40A9kkqXZOyqNiA " alt="image.png" width="1050" height="936" />

**Comment by louischan-oursky** [comment]
If you hard-refresh, the first problem should be solved.

**Comment by fungc-io** [comment]
ok 🆗 it's gone
