### ISSUE TITLE
Expose UserProfile in continue screen (Select Account) template

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4136]
So user can choose what text to show to identify the user in the continue screen (Select Account Screen)

![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/764ae63a-5974-4c7a-a3d5-9aa4b5ad7a91/9cfc19ca-2499-4daa-9cda-f112dd8a6c4b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi83NjRhZTYzYS01OTc0LTRjN2EtYTNkNS05YWE0YjVhZDdhOTEvOWNmYzE5Y2EtMjQ5OS00ZGFhLTljZGEtZjExMmRkOGE2YzRiIiwiaWF0IjoxNzEzMzQ1NzE5LCJleHAiOjMzMjgzOTA1NzE5fQ.\_S08nvS1ReBu7N_kMZLJa5rjaaFdyU0WGQoR_ksrOGY "=399x")

**Comment by IniZio** [comment]
Two limitations of ICU messageformat were found:

* It cannot check against empty string in `select`
* It cannot access nested variable

Changes to be made accordingly:

* UserProfile will be merged with original dict as extra attributes
* UserProfile will only support standard attributes of bool or string
* For each attribute, will add `${attr}__is_present` flag to show whether the field exists
