### ISSUE TITLE
Show "Devices" for OIDC apps in sessions in Admin Portal

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4139]
## Problem

If the user is not using the SDK but rather a standard OIDC integration, the device name is unknown in the session listing, which is hard to identify and looks broken in the UI.

![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/2a38d562-4bf6-4c9e-b2c5-641000f130b2/4f8cc822-7fad-422b-ab16-5321aa424cea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8yYTM4ZDU2Mi00YmY2LTRjOWUtYjJjNS02NDEwMDBmMTMwYjIvNGY4Y2M4MjItN2ZhZC00MjJiLWFiMTYtNTMyMWFhNDI0Y2VhIiwiaWF0IjoxNzEzMzcwNzM4LCJleHAiOjMzMjgzOTMwNzM4fQ.X6iyGW_VmgFvXrdnv07SrzqaJHBmUuMcs58OaSMY_kk "=471x")

## Todo

Two things to change:

1. Try to collect the device name and show it
   1. Use header forward passthrough
2. If the user did not pass the device info in the header and it's still unknown: Show "*Unknown"* (in italics) clearly in the list
   1. So it does not look broken in the UI.

**Comment by IniZio** [comment]
For header forward, believe preferred way would be using `X-Forwarded-User-Agent` ? However after testing with next-auth and python's authlib, there is not really a builtin way to pass custom headers.

Another way would be to use a custom query param `x_user_agent` like `x_device_info` . Tried it can be done with both next-auth and authlib, but will need custom token handler during config e.g. [https://next-auth.js.org/configuration/providers/oauth#token-option](https://next-auth.js.org/configuration/providers/oauth#token-option).

**Comment by louischan-oursky** [comment]
Per offline discussion

1. Change UserAgent.Format to output raw is a formatted output is empty.
2. Add new tests for the user agent observed in python's authlib

**Comment by IniZio** [comment]
To avoid exposing server info, will show unknown in user settings page
