### ISSUE TITLE
Declarative management of config

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#4187]
## Problem

> What’s the use case? What have we seen that motivates us to work on this?

As an app devloper, I'd like to allow non-technical teammates (e.g. customer support) to access Portal, however prevent they from changing configurations unexpectedly. We'd also like to ensure the deployed environment is using same configuration as local development, preferably synchronized from repo to production environment in CI/CD pipeline.

## Appetite

> How much time do we want to spend and how does that constrain the solution? (Usually 2 weeks or 6 weeks)

I don't know.

## Solution

> The solution, if involved UI changes, include Fat Marker Sketches

Have command line tool/API that would apply a config file (YAML) to a project using API key. Current workaround is to have a script ran manually, using session token extracted from portal.

Also it would be a nice to have to have a toggle to prevent all changes to config in UI (only allow programmatical update to avoid desync).

## Success definition

> Based on the “Problem” statement, define how we know if the feature is successful using event tracking.
>
> Event definition: Event name, Action that triggered the event, Which page the user will perform this action, Event properties

I don't know.

## Rabbit holes

> Details about the solution worth calling out to avoid problems

I don't know.

## No-goes

> Functionality or use cases we intentionally aren’t covering to fit the appetite

I don't know.

**Comment by fungc-io** [comment]
Good idea, it can improve the UX for developers managing multiple environments. Accepting this issue as a low priority feature

**Comment by fungc-io** [comment]
Proposal included in project: [Project configs management for different environments​](https://linear.app/authgear/project/project-configs-management-for-different-environments-65d933ee0554)
