### ISSUE TITLE
Elasticsearch reindex command cannot be run on HK cluster

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#4190]
2024/05/01 15:38:26 App): reindexing

Failed to update last_indexed_at of user <redacted>. pq: unexpected Parse response 'C'

Error: sql: transaction has already been committed or rolled back

**Comment by tung2744** [comment]
I suspect there is some race condition in this line:

[https://github.com/authgear/authgear-server/blob/main/cmd/authgear/elasticsearch/reindex.go#L229-L231](https://github.com/authgear/authgear-server/blob/main/cmd/authgear/elasticsearch/reindex.go#L229-L231)

The problem maybe `UpdateLastIndexedAt` is using the same db handle used by `QueryPage`, which internally assigning a same variable in HookHandle `tx`. I guess maybe they are running at the same time causing the problem.<br>Maybe we should `UpdateLastIndexedAt` in a queue.

**Comment by fungc-io** [comment]
@tung2744 do we still observe this problem in staging?
