### ISSUE TITLE
Disallow multiple login ids of same type in portal

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#4230]
- [X] Disallow in portal
- [X] Disallow in admin api (Check if any project is having multiple email first)

**Comment by tung2744** [comment]
Checked for existing users that are having more than one login id of same type, the results are in:<br>[https://oursky.slack.com/archives/C03AH1ACM/p1716287303165609](https://oursky.slack.com/archives/C03AH1ACM/p1716287303165609)

**Comment by tung2744** [comment]
As discussed, will not implement this. Modify the settings page to support multiple login ids instead.

**Comment by fungc-io** [comment]
Replaced by #4254 #4255
