### ISSUE TITLE
Track "CSRF Errors" in sentry

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4248]
Some user reported seeing CSRF Error during signup/login randomly but we cannot find the root cause of it yet.

Todo: Set up sentry event for CSRF Error in the Auth Flow, so we can collect more info on the condition of the error and determine its severity

Track all the HTTP headers and the URL

**Comment by louischan-oursky** [comment]
All Sentry SDKs support [SendDefaultPII](https://pkg.go.dev/github.com/getsentry/sentry-go#section-readme:~:text=data%20is%20sent.-,SendDefaultPII,-bool%0A%09//%20BeforeSend%20is). We DO NOT want to turn it on. Instead, we want to diagnose why the user agent does not send CSRF cookie.

We have to first write some testing cookies. We can do this by mounting a new middleware that write these testing cookies.

The testing cookies should be:
1. Omit the SameSite attribute **AT PROTOCOL LEVEL**
2. SameSite=None
3. SameSite=Lax
4. SameSite=Strict

When we encounter the CSRF cookie missing error, we inspect the request, and gather the testing cookies we actually receive.

Case 1: No testing cookies are received
The user agent probably has cookie disabled. No testing cookies were stored in the user agent, so nothing was sent back.

Case 2: Only some cookies are received
The user agent maybe buggy, and failed to store some cookies. With the information we collect, we may be able to come up with a fix for the user agent.

We also need to configure our sentry integration to include the testing cookies as extra data in each error report. On sentry there is "Tags", "Contexts", and "Additional Data". Please research which place is most suitable to store the received testing cookies.
