### ISSUE TITLE
[Portal] Add OAuth client screen

### ISSUE THREAD

**Issue by axolotl0212** [authgear/authgear-server#426]
- [x] create modify oauth client form (reuse in edit screen)
     - application type => 3 button selection with icon and description => Choice group 
        - customize option => onRenderField
     - name => text field
     - access token lifetime, refresh token lifetime => number field => spin button, no decimal
     - redirect URIs => picker
- [x] handle state and onSave
- [x] validation
       - redirect uris necessary field, at least 1 item
- [x] client ID generated
- [x] dialog on create success, with button for copying new client ID
- [x] block navigation if form dirty

**Comment by kiootic** [comment]
Difference between different application types:
- different grant_types/response_types: Actually can be set as the widest common types
- post_logout_redirect_uris: Recommended only for first-party clients (traditional web-app in same eTLD + 1), otherwise optional. Let's make it optional.

Conclusion: no need to differentiate between application types.

**Comment by axolotl0212** [comment]
> Conclusion: no need to differentiate between application types.

So the user don't need to choose between application types?

> different grant_types/response_types: Actually can be set as the widest common types

What is the widest common types? In the examples on https://github.com/authgear/authgear-server/blob/9ffbfe6f08a6d8ecf01a3295c1810e7e451398d5/docs/specs/oidc.md, single page app has different grant types and response types?

**Comment by kiootic** [comment]
For name of client: it is not the name displayed on OAuth screen, but only a display name in portal (`name` in OAuth client config)

**Comment by kiootic** [comment]
> So the user don't need to choose between application types?

Yes.

> What is the widest common types?

- grant_types: `authorization_code` and `refresh_token`
- response_types: `code` and `none`

**Comment by axolotl0212** [comment]
Will remove the choose application type section then.

> For name of client: it is not the name displayed on OAuth screen, but only a display name in portal (name in OAuth client config)

How is this stored? Adding a field called name in config? 

Also how portal get new client ID when creating new client? I guess there is a will be a new mutation?

**Comment by kiootic** [comment]
> How is this stored? Adding a field called name in config?

Yes, I'll open an issue to add this in config later.

> Also how portal get new client ID when creating new client? I guess there is a will be a new mutation?

Client ID can be randomly generated, just set it as `client_id` in the OAuth client configuration.

**Comment by kiootic** [comment]
> understood, use UUID?

I would prefer avoiding special characters (dash) in URL. I think a short string (16 characters) is enough.
