### ISSUE TITLE
Set "Use JWT as access token" by default for Native Application & SPA

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#4269]
A design question since it seems the most popular way for people to integrate the backend with Authgear.

* Native App
* SPA

**Comment by fungc-io** [comment]
I agree, it's a reasonable default

**Comment by fungc-io** [comment]
@bencheng @louischan @tung2744 do you think we should default enable it for SPA too? As it's also very common for our client to do so.

**Comment by chpapa** [comment]
Sure.
