### ISSUE TITLE
UI stuck when network connectivity lost

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#43]
When user tap next in UI while the server is unreachable (e.g. server down):
- UI is stuck at current screen with no feedback
- tapping next has no reaction
- click back button (browser/in-page) would show 'no connection' browser error page propertly.

**Comment by louischan-oursky** [comment]
- Somehow a component template renders network error message initially hidden.
- The XHR submission should detect network and use javascript to show/hide that message.

**Comment by kiootic** [comment]
Handled as part of using Turbolinks.
