### ISSUE TITLE
[Captcha] Implement the new captcha configuration

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#4325]
* \[ \] Keep the old configuration intact
* \[ \] Introduce the new configuration
  * The Go structs
  * The JSON schema
  * Write tests to test for valid and invalid configurations

**Comment by pkong-ds** [comment]
> Keep the old configuration intact

old config use key `captcha`, which conflicts with new config key
Maybe mark old one as `captcha_legacy`?

**Comment by louischan-oursky** [comment]
No. You add new fields to it directly. Just leave the legacy `provider` unchanged.
