### ISSUE TITLE
Add UI to update the project config as a file directly in portal

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#4336]
Now there are many hidden features which are not configurable in portal. When we need to configure those, we will directly modify data in the database. As there is no validation, the app could break if we write something wrong in the data. Suggest to:

- [ ] Add a UI with config validation in portal

---

## Goal

* Add a page with path: `/edit-config`
  * This page is only entered by directly entering this URL, it's not shown on the nav bar
* Design:
  * Heading:Edit Project Configurations
  * Code editor
  * \[Save\]
* Upon \[Save\], the config is validated and saved
* Show confirmation dialog to warn unsaved change when leaving the page

![image.png](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/1aa72162-7c79-4863-b34b-066857b8af18/bb729338-fe86-4688-b860-74e38e27cb19?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8xYWE3MjE2Mi03Yzc5LTQ4NjMtYjM0Yi0wNjY4NTdiOGFmMTgvYmI3MjkzMzgtZmU4Ni00Njg4LWI4NjAtNzRlMzhlMjdjYjE5IiwiaWF0IjoxNzE4MzcxNTMwLCJleHAiOjMzMjg4OTMxNTMwfQ.2GsMWEB8L4hRxWnUffPMCjnRj5BZt43N0Qg8QqgAA2A "=3024x")

**Comment by fungc-io** [comment]
@tung2744, this issue sounds like this one:<br>[DEV-1259](https://linear.app/authgear/issue/DEV-1259/declarative-management-of-config)<br>Are they related?

**Comment by tung2744** [comment]
@fungc-io Not really related. This issue is about having a raw editor to edit the config in portal. And [DEV-1259](https://linear.app/authgear/issue/DEV-1259/declarative-management-of-config) is about easier to management all things of authgear with a config file with api / commands to apply that config to a project.
So this issue does not solve the problem in DEV-1259

**Comment by fungc-io** [comment]
Let's do this in the next sprint. Thanks, @pkong-ds for helping.<br>The design is specified in the issue content. 🙏
