### ISSUE TITLE
Wrong redirection when navigate to https://portal.authgear.com/project/:projectID/configuration

### ISSUE THREAD

**Issue by cychiuae** [authgear/authgear-server#4339]
**Describe the bug**
When navigate to `https://portal.authgear.com/project/:projectID/configuration`, users will be redirected to `https://portal.authgear.com/project/:projectID/configuration/authentication/login-id`, which is a blank page

**Authgear Version**
 - Version: SaaS

**To Reproduce**
1. Go to `https://portal.authgear.com/project/:projectID/configuration` via url

**Expected behavior**
It should redirect users to a meaningful page.

**Comment by fungc-io** [comment]
checked ok
