### ISSUE TITLE
Wrong background color in footer in login with url verification success page in auth ui v2

### ISSUE THREAD

**Issue by cychiuae** [authgear/authgear-server#4373]
**Describe the bug**
Wrong background color in footer in login with url verification success page in auth ui v2

**Authgear Version**

* Version: SaaS

**To Reproduce**

1. Login with login link
2. After clicked the login link, verification success page footer become white color

**Expected behavior**
Background color should be consistent

**Screenshots**

![Screenshot 2024-06-19 at 5 00 08 PM](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/c6511364-9c1c-4191-bcb0-bc424397c02a/1f6ffec9-cfdf-4e50-a4cc-fd8a8f154d5f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9jNjUxMTM2NC05YzFjLTQxOTEtYmNiMC1iYzQyNDM5N2MwMmEvMWY2ZmZlYzktY2ZkZi00ZTUwLWE0Y2MtZmQ4YThmMTU0ZDVmIiwiaWF0IjoxNzE4Nzg4NDAxLCJleHAiOjMzMjg5MzQ4NDAxfQ.pzRaYOrAq8IHVTrjM3IlYOwFQwIeTwNwocqecdwZTs8 "=1650x")

**Comment by fungc-io** [comment]
Checked ok
