### ISSUE TITLE
e2e tests fails on second run

### ISSUE THREAD

**Issue by cychiuae** [authgear/authgear-server#4553]
**Describe the bug**
e2e tests fails on second run

**Authgear Version**
63da7665c15def8e0e447553fbbb60a98a1e484f

**To Reproduce**
1. Navigate to `e2e/`
1. Run `make setup`
1. Run `make tests`
1. Run `make tests`

**Expected behavior**
e2e tests should pass

**Comment by IniZio** [comment]
Should also fix `custom_sql` step with unique constraint error not failing the test case.

**Comment by louischan-oursky** [comment]
https://github.com/authgear/authgear-server/pull/4561
https://github.com/authgear/authgear-server/pull/4562
