### ISSUE TITLE
Fix template queries on multi-tenant mode

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#510]
- Add a new query to get default template files
- Update front-end template logic:
    - get template
      1. get `authgear.yaml`
      2. parse it and find the corresponding item in `templates` items
      3. if found: load the file using `rawConfigFile` query
      4. if not found: load the default template using the new query
    - set template
      1. if the new template is same default template: delete corresponding item in `templates` items
      2. otherwise, update `authgear.yaml`: upsert corresponding item in `templates` items
      3. update the file at the path with the new query
- Update `rawConfigFile` query
    - Rename to `template`?
    - Accept `null` for path: always return `null` if path is `null`

**Comment by axolotl0212** [comment]
## Error message (Passwordless authenticator screen)
```
Error: open /templates/setup_primary_oob_email.html: file does not exist
```

## Notes
In first app, the `templates_2f_translation.json` is missing from the secret
In app created afterwards, `templates_2f_translation.json` exist, 

## k8s secrets
```bash
kubectl --kubeconfig=hack/kube-apiserver/.kubeconfig get secrets              
NAME           TYPE     DATA   AGE
app-accounts   Opaque   2      132m
app-test1      Opaque   3      38m
```

data corresponds to

```
authgear.secrets.yaml:          4012 bytes
authgear.yaml:                  152 bytes
templates_2f_translation.json:  99 bytes
```

**Comment by axolotl0212** [comment]
> In first app, the `templates_2f_translation.json` is missing from the secret

Consider adding `templates_2f_translation.json` to k8s-manifest.yaml ?

**Comment by kiootic** [comment]
Replaced by #511
