### ISSUE TITLE
Revamp resource resolution

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#511]
To provide more robust customization of resources, we should revamp the existing system:
- Use virtual FS for every resources:
    - authgear.yaml
    - authgear.secrets.yaml
    - templates (templates that goes through the template engine)
        - authgear
          - web
            - login.html
            - logout.html
            - etc.
          - messages
            - forgot_password_email.html
            - verification_sms.txt
            - etc.
          - translation.json
        - portal
          - messages
            - invitation_email.html
            - etc.
    - static (static assets that mounted at the authgear server)
        - img
            - logo.png
            - etc.
        - authgear.css
        - authgear.js
    - data (additional data needed by logic)
        - reserved_name.txt
- 2 layer of FS:
    - global FS: bundled in image, can be mounted by cluster admin to customize branding
    - app FS: app-specific resources, customized by developer
- custom layer merge function for each file type
    - config: for authgear.yaml, same as static for now
    - secrets: for authgear.secrets.yaml, merge from each layer using custom logic
    - templates: for templates that goes through the template engine, the file from top-most layer is used
    - static: for static assets that is used as-is, the file from top-most layer is used
- remove new app environment variables from portal: customize the global FS in main authgear server instead
- R/W resources:
    - reading resources:
      - portal GraphQL API to read effective (i.e. merged from both FS) & raw (i.e. in app FS) resources
      - for secret file type: only raw can be read
    - writing resources:
      - portal GraphQL API to update resources in app FS
      - validate FS after merge
    - assumption: portal server & authgear server must share the same mounted resource FS

**Comment by louischan-oursky** [comment]
I would like add more details on the structure of the templates

```
/templates/authgear/__default__/web/login.html
/templates/authgear/en/web/login.html
/templates/authgear/zh-Hant/web/login.html
/templates/authgear/zh-Hant/web/translation.json

/templates/authgear/__default__/messages/forgot_password_email.html
/templates/authgear/__default__/translation.json
```

So if the resource type is template, then its definition may look like

```
HTMLTemplateResource{
  Type: "/templates/authgear/web/login.html",
  PathTemplate: "/templates/authgear/{{ .LanguageTag }}/web/login.html",
}

TextTemplateResource{
  Type: "/templates/authgear/messages/forgot_password_email.txt",
  PathTemplate: "/templates/authgear/{{ .LanguageTag }}/messages/forgot_password_email.txt",
}

TranslationJSONResource{
  Type: "/templates/authgear/translation.json",
  PathTemplate: "/templates/authgear/{{ .LanguageTag }}/translation.json",
}
```

Some questions

1. Do we need to keep Type?
2. Maybe the value of Type should be the same of PathTemplate?
3. Maybe we should make the top level directory the component name. That is, `/authgear/templates/...` and `/portal/templates/...`

**Comment by kiootic** [comment]
> Maybe we should make the top level directory the component name. That is, /authgear/templates/... and /portal/templates/...

That sounds good to me. In repo the resources would be put in `/resources/authgear/templates/...` and `/resources/portal/templates/...`, and the root directory for each component would be specified in environment variable as global FS base path.

> Do we need to keep Type?
> Maybe the value of Type should be the same of PathTemplate?

I would like the individual resource kinds to derive resource path set by itself, so for example:
```
// would lookup from /templates/__default__/translation.json, /templates/en-US/translation.json, etc.
HTMLTemplateResource{
  Name: "translation.json"
}
// would lookup from /static/authgear.css only.
StaticResource{
  Name: "authgear.css"
}
```
