### ISSUE TITLE
Simplify validation schema setup

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#513]
Currently we use multipart validation schema everywhere. To simplify setup complexity, we should use simple schema for common ad-hoc validation scenarios (e.g. POST forms, simple API validation), while leaving multi-part schema to be used only for complex user-facing schemas (i.e. app config, secret config).

**Comment by keithtkl** [comment]
@kiootic is this done and can close?

**Comment by kiootic** [comment]
No, this is a technical refactoring with rather low priority.
