### ISSUE TITLE
Single Sign On Portal Page UX

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#537]
1. Can update the link of "Need help?" to this URL https://docs.authgear.com/how-tos/how-to-setup-sso-integrations
2. Need to fix the name. I don't think it's appropriate to call it "Sign in with Microsoft" while it is for general Azure AD?

**Comment by louischan-oursky** [comment]
[Their branding guide](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-branding-in-azure-ad-apps) does use the term "Sign in with Microsoft"
