### ISSUE TITLE
Visit DNS page will fire unwanted mutation

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#538]

**Comment by louischan-oursky** [comment]
This is quite critical. Can we have a look on this first? @keithtkl @axolotl0212

**Comment by axolotl0212** [comment]
@louischan-oursky  could be related to https://github.com/authgear/authgear-server/blob/master/portal/src/graphql/portal/DNSConfigurationScreen.tsx#L235-L265

This is used for updating the public origin if the selected one is deleted, will investigate what is causing the mutation
