### ISSUE TITLE
Disable User

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#54]
(Describe the issue here)

- Authgear Server Date/Version:
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Steps to reproduce

1.
2.
3.

**Comment by keithtkl** [comment]
Goal:
1. not allow user to login
2. revoke all user login session

**Comment by louischan-oursky** [comment]
Implemented in https://github.com/authgear/authgear-server/pull/738
