### ISSUE TITLE
User verification

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#55]
- Definition of verified Login ID
  - Satisfy one of the following condition
     - The login ID has an associated authenticator
     - The user has SSO user info with `email` claim equal to the login ID

**Comment by keithtkl** [comment]
Add verification status to the setting page

**Comment by kiootic** [comment]
Discussed with @louischan-oursky :
- we'll having separate templates for user verification and OTP message
- verification will be using the same OOB authenticators to share its semantics, but
   code handling would be done differently.
- for email verification:
    - the code (a long code) will be stored separately
    - message will have link (contains code & interaction id) to the web UI
    - user can verify with just the code, no need to log in
    - if interaction can be restored, the interaction will continue
- for phone verification:
    - the code (a short code) will be stored in interaction
    - message will have just the code
    - user must enter the code in same page
