### ISSUE TITLE
Make default sign in page and sign up page more distinglishable

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#556]
Current design's sign in and sign up page is almost indistinguishable. Which is sort of a usability nightmare.

**Comment by keithtkl** [comment]
also need to have designer to provide either:
1. spec for the banner image
2. handling on various banner / icon sizes

**Comment by chpapa** [comment]
@keithtkl and also ask the designer to give some samples of what it might looks like when people put different banners / logos on it, so they're aware of the looks & feel too.

**Comment by keithtkl** [comment]
cc @koskosm
