### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#56]
- [x] Review web app state machine and draw a state digram
- [x] In login, available authenticators are unaffected by config
- [x] Remove identity should remove its bound OOB authenticator
- [x] Populate AMR
- [x] Populate ACR
- [x] Support setup 2nd authenticator in signup
- [x] Support setup 2nd authenticator in login
- [x] Support setup 2nd authenticator in promote
- [x] Support password as 2nd factor
- [x] Add `setup_totp.html`
  - [x] Show a QR code image
  - [x] Show a text input field with digits only
  - [x] Submit button
- [x] Add `enter_totp.html`
  - [x] Show a text input field with digits only
  - [x] Submit button
- [x] Add `setup_recovery_code.html`
  - [x] Show a list of recovery code
  - [x] Offer a button to download the codes
- [x] Allow switching to use recovery code / another 2nd authenticator
- [x] Respect preferred 2nd authenticator and maximum
- [x] Support default tag
- [x] Add `enter_recovery_code.html`
  - [x] Show a text input field
  - [x] Submit button
- [x] Add remember this device checkbox conditionally to
  - [x] `enter_password.html`
  - [x] `enter_totp.html`
  - [x] `enter_oob_otp.html`
- [x] Automatically bypass 2nd authentication when device token is available

**Comment by louischan-oursky** [comment]
@koskosm
