### ISSUE TITLE
Add time for username is always at 1/1/1, 7:36 AM

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#568]
When try to add a username under "Add Identity" dropdown, will see the add time is 1/1/1 7:36AM. But the date time will change to a correct one after page reload

![Screenshot 2020-10-23 at 14 17 20](https://user-images.githubusercontent.com/10443251/96963073-93fc3d00-153a-11eb-8e40-ec76f0c2a986.png)

**Comment by kiootic** [comment]
@keithtkl This is a backend bug, let me take over this issue.
