### ISSUE TITLE
Not able to add user on portal after enabled anonymous users

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#575]
Add user page will show "Please enable at least one of username, email or phone in authentication screen" when anonymous users enabled

**Comment by axolotl0212** [comment]
Criteria for user identities to be added 
=> `login_id` included in `/authentication/identities`
=> the identity type (such as `username`) is included in `identity/login_id/keys`

Changing anonymous user enabled / disabled will affect `/authentication/identities` array. 

By default, if the field `/authentication/identities` does not exist in raw config, the effective config will contain `login_id` and `oauth`, hence user identities can be add user by default.

If anonymous user state toggled, the field is added to raw config, overriding the default effective config, hence `/authentication/identities` array becomes ["anonymous"], without `login_id`, hence identities can no longer be created
