### ISSUE TITLE
Proper CSP (Content Security Policy) settings for the portal

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#601]
Is it possible?

**Comment by kiootic** [comment]
Checking for `Content-Type: application/json` and having a proper CORS policy should be sufficient for modern browser to prevent CSRF. I don't think we need to add CSRF header for GraphQL API endpoints.

**Comment by chpapa** [comment]
@kiootic Sorry I was too busy and write things too fast, so I wrote a typo...

I meant setting CSP for the portal, so we can reduce the risk of having XSS there.

**Comment by kiootic** [comment]
Understood. As mentioned by @louischan-oursky , we had proper CSP set in main authgear servers. However we didn't apply them in portal server. It should not be difficult to add them.

**Comment by chpapa** [comment]
Sure, maybe lets put this issue as nice to have and next thing to add after we meet the deadline.

**Comment by kiootic** [comment]
ref #752
