### ISSUE TITLE
[Demo App, iOS] App crash when click "Configure" button with empty endpoint

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#622]
## Environment:
- Platform: iOS
- Device: iPhone XS - MAX (13.6.1)
- Demo app build: iOS 1.0 (1602057811)

## Description:
On iOS devices, the app crashes upon clicking the "Configure" button with an empty endpoint.

## Steps to reproduce:
1. Open the app on iOS
2. Click the 'Configure' button without filling in any value on the endpoint field
3. See the app crashed

## Expected result:
Should have no response/disable the button when the endpoint is empty

## Screenshot:
![IMG_18E520F5D931-1](https://user-images.githubusercontent.com/12539486/97413761-2424f280-193e-11eb-8f86-ebe4cfac59bd.jpeg)

**Comment by keithtkl** [comment]
@joyzoursky won't fix as this should only happen on demo app. other application should have the cliend ID and endpoint hard-coded when integrate authgear so should not have this problem
