### ISSUE TITLE
[Demo App] App crash upon clicking 'Open settings' button with invalid endpoint configured

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#634]
## Environment:
- Platform: Web / Android / iOS
- Demo app build: Android 1.0 (1602057818), iOS 1.0 (1602057811)

## Description:
The app will crash upon clicking the 'open settings' button without a valid endpoint.

## Steps to reproduce:
1. Fill in an invalid endpoint (i.e. aaa) or leave empty on the endpoint field
2. Click 'Configure'
3. Click the 'Open Settings' button
4. App crash

## Expected result:
Should display an error message instead of crashing the app

## Screenshot:
https://drive.google.com/file/d/1F3BglT_GQGAiswSZECbIawddwrFYG3m-/view?usp=sharing

**Comment by keithtkl** [comment]
@joyzoursky won't fix as this should only happen on demo app. other application should have the cliend ID and endpoint hard-coded when integrate authgear so should not have this problem
