### ISSUE TITLE
Expose resolver and Admin API

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#656]
Resolver:

- Mounted at APPID.authgearapps.com/_resolver
- No authentication is required
- Only simple information is included in the response headers (same as now)

Admin API:

- Mounted at APPID.authgearapps.com/_api/admin
- Same authentication as what we have now

**Comment by louischan-oursky** [comment]
Nginx ingress always route by host first. So we cannot have exact host and wildcard host ingress defined at the same time. I am going to study whether we can switch our ingress controller to traefik.
