### ISSUE TITLE
Insufficient File Path Checking

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#657]
- UpdateAppTemplateMutation, AppTemplatesQuery, UpdateAppRawTemplatesMutation are used to update template messages/ css
- The file path in the GraphQL is not checked against a whitelist
- Arbitrary file might be retrieved and updated by leveraging this vulnerability

**Comment by kiootic** [comment]
This seems not a problem. The example requests given are all intentional and valid.

**Comment by louischan-oursky** [comment]
Did we forbid arbitrary path like `/foo/bar`?

**Comment by kiootic** [comment]
It's a whitelist against registered resource types in resource FS.
