### ISSUE TITLE
Press back button on Connected Identities page cannot back to main setting page

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#668]
Step to reproduce:
1. Signup an account with the application have SSO configured
2. Go to Connected Identities
3. Try connecting to a SSO that will result login failed
4. Press back button on the Connected Identities page will back to the SSO page instead of back to the previous Authgear setting page

**Comment by louischan-oursky** [comment]
Can we remove the back button from all pages? It is hard to make back button work perfectly on a web app.
