### ISSUE TITLE
Investigate why some times portal.[authgear.com] would loop into "state" error"

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#710]
Today I want to login portal.[authgear.com], but I keep getting an error as follows:

1. Visit https://portal.[authgear.com]
2. Browser redirects me to https://accounts.portal.[authgear.com]/login?x_sid=[???], with the following error:
> The state associated with this URL is invalid. Maybe you have idled too long or switched your browser?
3. There is a back button, but it go back to 1.

There are 6 cookies:
* `__cfduid`
* `amplitude_id_.....`
* 2 x `csrf_token` (portal and accounts.portal each)
* 2 x `ua_token` (portal and accounts.portal each)

- Authgear Server Date/Version:
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results
Show me the login screen

#### Actual Results
Show me error message and loop as above, no way I can get rid of it.

#### Steps to reproduce
Not sure how to reproduce yet. Works again after I removed all cookies.

**Comment by louischan-oursky** [comment]
It should be a side effect when we deployed a change to explicitly set the cookie domain to `portal.secaas.hk`
