### ISSUE TITLE
Multilingual messages configuration on portal

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#718]
Wireframe: [Multilingual templates.pdf](https://github.com/authgear/authgear-server/files/5521367/Multilingual.templates.pdf)

**Comment by kiootic** [comment]
- Backend provides an exhaustive list of possible locales: 
    - https://support.google.com/googleplay/android-developer/answer/9844778?hl=en
- Backend validate resource path using the locale list.
- Frontend derive supported languages from configured resource paths.
- On remove supported language: frontend remove all resources of the removed locales.
