### ISSUE TITLE
[Portal] Provide configured locales of app in API

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#728]
Localized resources may have locale ID in path (e.g. `templates/{lang}/web/login.html`, `static/{lang}/app_logo.png`). Portal frontend would like to obtain a list of configured locales for display. It would be more accurate to provide the computed list of locales from backend.

However, resource path format is determined by individual resource kind descriptor. Currently we don't have interface to extract configured locales from a resource FS. Can we expose this in API with minimal changes?

**Comment by louischan-oursky** [comment]
The current convention is return `[]byte` for AppFileView and EffectiveFileView, ready-for-use value for EffectiveResourceView. Instead of returning a byte slice, we could return a struct instead.

```
type Resource {
  Path string
  LanguageTag string
  Content []byte
}
```

**Comment by kiootic** [comment]
@louischan-oursky It turns out your approach is a bit tricky:
- Returning `Resource` for `AppFileView`: default templates will fails with `ErrResourceNotFound`, thus not returning correct language tag.
- Returning `Resource` for `EffectiveFileView`: secret config would be forbidden to access, causing erroneous error.

Instead I changed `MatchResource` of `resource.Descriptor` to return `(*Match, bool)`, the match would contains  a language tag.
