### ISSUE TITLE
Review first party app use case

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#737]
And make the integration easier

**Comment by kiootic** [comment]
I assume 'first-party app' as described refers to the physically first-party apps (i.e. web apps within same eTLD+1 as the authorization server), not logically first-party apps (e.g. 'this mobile app is developed by us so it's a first-party app').

## Use cases

- **server-side rendering (SSR)**: The backend of a first-party SSR app would like to know the authentication status of the HTTP page request. A normal HTTP page request would not include Authorization header, so the backend can only derive the authentication status from HTTP cookies.
- **internal single sign-on/sign-out (SSO)**: It is often desirable that the authentication status of all first-party apps are shared. For example, once user logs in at `www.example.com` through authorization server at `accounts.example.com`, user would also be logged in at `forum.example.com`, `support.example.com`, etc. Again, this is usually achieved by using a shared cookie across the eTLD+1.
- **privileged user operations**: OAuth protocols allow user to *delegate* some permissions to OAuth clients. However, usually first-party apps have full authority acting as the user (effectively *impersonating* the user), which can perform privileged operations not exposed through OAuth protocol (e.g. we cannot change Google's user password using their OAuth APIs), and user consent is not required.

## Current support

Authgear supports these use cases currently:
- Authgear provides a 'resolver' endpoint, which would validate the session cookie in the incoming HTTP request, and expose the authentication status of the request in response headers. It is intended that developers would setup an authentication proxy (e.g. nginx `auth_request`) using this endpoint.
    - would authentication status headers include sensitive information? does the resolver endpoint need authz?
    - reverse proxy supports chained auth request? e.g. first authgear resolve authn, then resolve authz.
    - deployment complexity?
    - resolver performance? (cross region request, caching, etc.)
- Developers can configure the domain attribute of session cookie to enable cookie sharing across domains of the system.
- Developers can trigger authentication flow by redirecting to auth UI.
    - FIXME: fix auth UI redirect URI validation to check eTLD+1 instead of exact host match.
- Developers can perform privileged operations through admin API.
    - developers setup their own authz to admin API.

## Alternative approaches

- Self-managed session:
  Developer can choose to use authgear for authentication only, and manage sessions in their own applications. This allow full control on session mechanism and solves SSR and SSO use cases.
  This approach is recommended by [Auth0](https://auth0.com/docs/sessions-and-cookies) when the applications have backends.

- OIDC session management:
  Developer can use OIDC session management mechanisms (session management, back/front-channel logout) to ensure authentication status is synchronized across different OAuth clients. This solves the SSO use case.

- OAuth tokens as authentication cookie:
  Using [backend-for-frontend pattern](https://www.scottbrady91.com/OAuth/Cheat-Sheet-OAuth-for-Browser-Based-Applications#bff), the backend can store the access/refresh tokens in cookie instead, and proxy API accesses/perform SSR using the the authentication cookie. This solves both SSR and SSO use case.

**Comment by chpapa** [comment]
👍 Let's present and discuss it in next product meeting?

**Comment by keithtkl** [comment]
@kiootic let's also review on okta and see what is their approach

**Comment by kiootic** [comment]
Okta supports manipulating session cookie directly through their [Sessions API](https://developer.okta.com/docs/reference/api/sessions/).

Okta published [a blog post on how to use nginx `auth_request` for authentication](https://developer.okta.com/blog/2018/08/28/nginx-auth-request). They recommend using a authentication proxy ([Vouch](https://github.com/vouch/vouch-proxy)) as a OAuth/OIDC adaptor. The proxy uses a self-issued JWT in cookie to store session information (including access tokens), which is similar to the third approach mentioned above (backend-for-frontend).

**Comment by chpapa** [comment]
@kiootic thx a lot! noted on the 2nd approach.

For the sessions API, may you help walk us through the functions and how it works? Now I think we understood there are no simple way for users to do it in Web SSR first-party case, but I think it would still be good to let the team get some impressions on what are the functions about.

**Comment by kiootic** [comment]
There are two set of Okta APIs that is of our concern here: Authentication API and Session API.

Authentication API is like the backend of our web UI: it allows developer to programatically perform authentication using the API. After successful authentication, the API will return a *session token* and user information for further processing.

Developers may opted to create and manage their own session using the user information directly. Otherwise, developers may use *session token* to exchange for a *session cookie* to let Okta manage user sessions.

The *session token* is a one-time-use token used to exchange for *session cookie*, the exchange can be performed in three way:
1. Use Session API to exchange *session token* with the value of *session cookie*. Useful when developer want to set the *session cookie* directly without additional redirect.
2. (recommended) Use OAuth authorization flow with the *session token*. User will redirect to `redirect_uri` directly with the *session cookie* set.
3. (not encouraged) Use a proprietary endpoint that is mostly equivalent to (2).
