### ISSUE TITLE
App name + App icon + Banner configuration on portal

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#742]
We should allow user to edit app name, icon and banner through portal

Let's put this configuration to "Templates" tab for now as user may want to have different name & banner for different language

**Comment by louischan-oursky** [comment]
1. Generalize ForgotPasswordTemplateSettings and PasswordlessAuthenticatorTemplatesSettings into a single component
2. Use the generalized component to support all remaining templates (thus the developer can edit app name)
3. Rename "Templates" to "Templates and Resources"
4. Invent a file picker. Fluent UI does not have one https://github.com/microsoft/fluentui/issues/11516
5. Support saving app_banner and app_logo
