### ISSUE TITLE
Put reset and save button to command bar

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#748]

**Comment by kiootic** [comment]
Some pages have pivots (i.e. tab pages). The current behavior is treating each tab page as separate form context, requiring user to save/discard changes before saving tab. After switching to use command bar for save & reset, it would become strange that a lower component (pivot tabs) controls the behavior of upper component (command bar).

Also, the current placement of command bar in 'Portal Admin' tab of 'Settings' page is strange.

Instead, we should use [hierarchical navigation](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#hierarchical-navigation) pattern of Fluent UI design. I suppose the equivalent component on web platform would be nested `Nav` links.
