### ISSUE TITLE
Allow some interaction steps to be performed by another user agent

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#763]
## Motivation

When the user is signing up in a mobile application with email address and password, they will receive a verification email. In the verification email, there is a link. It is expected that most of the users will click on the link. At the moment, clicking the link will result in error.

## Approach 1 - Allow some specific steps to be performed by another user agent

We would like to allow some specific steps to be performed by another user agent. Example of the steps are verification, in which the verification code is associated with the interaction. Therefore, by the verification code only, it is possible to perform this interaction step. Since the another user agent does not have the interaction cookie, after performing the step, we will display a page telling the user that they should return to the original application to resume the interaction.

Since some of the interaction steps can now be performed by another user agent, we need to have a persistence websocket connection per interaction to keep the interaction in sync. There is new websocket endpoint which accepts connection by interaction cookie. If the request has a valid interaction cookie, connection is established. The client will then listen for the event of interaction step being performed by another user agent. The client will also ping the server periodically to see if the interaction is stale. If the interaction is stale, the server will return a new URL, in which the client will redirect to it.

## Implementation of Approach 1

- Ensure interaction cookie is only written once when the interaction starts.
- Add a static page to tell the user to return to the original application.
- Make verification special case. Allow it to be performed without interaction cookie.
- Redirect to the static page after interaction step is performed.
- Figure out how to handle the external interaction step is the last step of the interaction.
- Introduce the websocket endpoint at server side.
- Implement the webcocket protocol between the server and the client.

## The reason why approach 1 cannot solve our problem

In an edge case where the interaction step to be performed by another user agent is the last step of the interaction, the interaction is destroyed and the original user agent cannot resume the interaction.

## Approach 2 - Allow another user agent to contribute to input to the original agent

The interaction mechanism is a finite state machine, where it constantly renders a page that collects user input and steps forward. If a specific step is opened by another user agent, we want to model this as an alternative way to collect user input. Specifically, the another user agent will show page to tell the user to click the continue button. Clicking the button will submit the form to the server. The server will store the form data in the web session. The page will try to use the form data in the web session as pre-filled form values. There also exists a persistent websocket connection for listening the change in the form data in the web session.

Let's explain this by considering verification as example. When `/verify_identity` is visited without web session cookie, the verification code is inspected to see how was the verification triggered. If the verification was triggered by authentication intent, then the page in the original user agent is pre-filled. If the verification was triggered by verification intent, then a new intent is created to resume the verification flow.

## Implementation of Approach 2

- Add a flag in NodeVerifyIdentity to differentiate between authentication and verification intent.
- Store web session ID in verification code.
- Add pre-filled form data in web session. Clear it after every POST.
- Update `/verify_identity` view model to use pre-filled form data in web session.
- When `/verify_identity` is visited without web session cookie, verification is triggered by authentication, render a form with a button to continue. When the button is clicked, fill in the pre-filled form data in web session. After the button is clicked, render a static page telling the user to return to where they were.
- Introduce a redis-based websocket protocol to support auto pre-fill without refreshing.

**Comment by chpapa** [comment]
However it is a very common feature for most apps, I think we should figure out how to support it?

**Comment by louischan-oursky** [comment]
- The user opens the ASWebAuthenticationSession.
- The user continues to interact until they reach the verification page.
- The user receives the verification code from email
- The user chooses to click the link in the email message, leaving the original ASWebAuthenticationSession remaining opened in the app.
- The user will see an error now because for security reason, interaction is bound to the user agent who started the interaction (via cookie).

We have to remove the binding and allow some of the interaction steps to be performed by another user agent. This is non-trivial. If we think of verification is kind of like one-time password, it is acceptable not to provide a link. In passwordless login, we just send the user the code. They have to enter it manually. Simply removing the link is the simplest solution to the problem.

**Comment by chpapa** [comment]
@louischan-oursky I think from a UX point of view, OTP is okay to be manually input the code.

But it is not okay for the verification email and email passwordless login (vs SMS); Any idea how we could implement that? (I know it is non-trivial)

**Comment by kiootic** [comment]
I think it's more helpful to consider each cases separately:
1. Email verification at sign-up
2. Email verification at setting page
3. Email password-less login
4. SMS password-less login

I think we agree that we don't need a link in case 4. For case 2, I think it's okay to keep the link in email.

However for case 1, we need to note 2 points in current design:
- we do not commit anything to database until the end of sign-up process.
- we perform email verification before setting up authenticators (e.g. password, MFA).

Therefore, to provide the link in email in case 1, we potentially need to transfer & resume the interaction across user-agents & devices. Currently we allow resuming the interaction within a user-agent (i.e. opening the email link in same browser as sign-up flow), however it's not designed for that case.

For case 3, the main problem is again the transfer of interaction across device/user agents. I suppose to keep the link in email, using WebSocket or similar technologies is unavoidable.

**Comment by louischan-oursky** [comment]
I just discussed with Ben. The ideal behavior is that the link in the verification email is a deep link, which can bring the user back to the app, and resume the interaction. As part of the deep link redirection, the verification code should be filled in. Autofill is impossible with ASWebAuthenticationSession. Therefore

When the SDK is using ASWebAuthenticationSession, the verification email should not have the link.
When the SDK is using WKWebView, the SDK should handle the deep link, fill in the code and let the user to resume the interaction. This is possible because WKWebView supports including custom JavaScript.

The actionable items are

1. Ask the developer if they really want verification to be required. If not, tell them to make verification optional so the user will not see the verification page in the signup interaction.
2. However, the developer may want to send a verification email after the interaction. Should we make this an option? Or should we add a mutation in Admin API to trigger a verification interaction?

**Comment by chpapa** [comment]
> Ask the developer if they really want verification to be required. If not, tell them to make verification optional so the user will not see the verification page in the signup interaction.

We could just make the email verification default to optional?

> However, the developer may want to send a verification email after the interaction. Should we make this an option? Or should we add a mutation in Admin API to trigger a verification interaction?

ummmm I think at the beginning an admin API to trigger verification email if the verification email is set to optional is good enough.

A shortcut could be in setting portal, have an option for developer to choose trigger this email automatically first time after sign up, and every time after login.

**Comment by kiootic** [comment]
> When the SDK is using WKWebView, the SDK should handle the deep link, fill in the code and let the user to resume the interaction. This is possible because WKWebView supports including custom JavaScript.

I'm not sure if we'd really want to support using webview, it's against OAuth best practice.

> When the SDK is using ASWebAuthenticationSession, the verification email should not have the link.

We may want to see if we can use `localStorage` for this? (since it seems `BroadcastChannel` doesn't work on Safari yet)
ref: https://dev.to/naismith/cross-tab-communication-with-javascript-1hc9

**Comment by louischan-oursky** [comment]
Findings

- ASWebAuthenticationSession does not share localStorage with Safari :(
