### ISSUE TITLE
WeChat login

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#773]
[Integration Documentation](https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html)

---

Implementation Notes

- Authorization endpoint: `https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE#wechat_redirect`
- Token endpoint: `https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code`
- UserInfo endpoint: `https://api.weixin.qq.com/sns/userinfo`, needs scope `snsapi_userinfo`

---

[Apply for sandbox account](https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login)

---

[Useful article](https://blog.51cto.com/zero01/2117892)

---

The flow is very different from normal OAuth 2.0 providers (e.g. Facebook). The authorization URL we generate cannot be opened by a normal browser. We must generate a QR code image of it and display it to the user. Then we tell the user to scan the QR code with their Wechat app. By scanning the QR code, the authorization URL is visited by the embedded Wechat browser. If the authorization URL is visited by other browser, an error will be shown saying that the URL must be opened by the embedded Wechat browser. The user consent the authorization in the Wechat app and then being redirected to redirect URI. Since there are now two user agents, we have to think of a way to instruct the user to come back to the original user agent to continue the flow. The original user agent is showing the QR code while the redirect URI is visited by the embedded Wechat browser. We need to be able to support interaction in more than one user agent.

---

Known Caveats

- We must use publicly accessible domain name for the redirect URI.
- ngrok.com is blocked by Wechat.
- The wechat authorization URL is not a deep link of the Wechat app. So on mobile device, we cannot show the authorization URL as link and expect the user to click on it to redirect to the Wechat app.

---

Mobile Flow

1. The user clicks the Login with Wechat button.
1. We show a page with the authorization URL encoded as QR code image. Tell the user to scan the QR code with their Wechat app.
1. The user scans the QR code and authorize in the Wechat app.
1. Wechat redirects the user to the redirect URI we gave them.
1. The handler of the redirect URI steps forward the graph.

---

Web Flow

---

iOS SDK setup

1. In Build Phases, Link Binary with Libraries, add libc++.tbd
1. In Build Phases, Link Binary with Libraries, add WebKit.framework
1. In Info.plist

```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>weixin</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>PUT_APP_ID_HERE</string>
			</array>
		</dict>
	</array>
```
1. In Info.plist

```
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>weixin</string>
        <string>weixinULAPI</string>
    </array>
```

1. In Build Settings, Add "-ObjC -all_load" to Other Linker Flags.

---

iOS SDK experiments

```objc
OpenWebviewReq *req = [OpenWebviewReq new];
    req.url = @"https://open.weixin.qq.com/connect/oauth2/authorize?appid=redacted&redirect_uri=https%3A%2F%2Frproxy-louischan.pandawork.com%2Fsso%2Foauth2%2Fcallback%2Fwechat&response_type=code&scope=snsapi_userinfo";
    [WXApi sendReq:req completion:^(BOOL success) {
        NSLog(@"completion %d", success);
    }];
```

The above code can open wechat browser but will fail with "Bad param".
https://developers.weixin.qq.com/community/develop/doc/0006ce26604430306b8955edd5bc00

**Comment by louischan-oursky** [comment]
I created a mobile app and it is pending verification.

**Comment by keithtkl** [comment]
Let's also check how Azure Active Directory B2C and Authing achieve the WeChat login flow
https://azure.microsoft.com/en-us/services/active-directory/external-identities/b2c/
https://authing.cn/
