### ISSUE TITLE
[App, Create account] Disallow copy and paste when re-type new password

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#776]
## Background:
- Device / Browser (OS version): Chrome on Win 10

## Description:
When the user creates an account, after he inputs the new password, he can copy the decrypted new password and paste it to the re-type new password field.

## Steps to reproduce:
1. Go to https://ourskyqa.authgear-staging.com
2. Click "Create One!"
3. Create an account by any method then click "Next" (e.g. create by username)
4. Input a new password and click the show password icon on the right to see the decrypted password
5. Copy the decrypted new password and paste it to the re-type new password field
6. Click the show password icon on the right, see the decrypted re-type password is the same as the new password

## Expected result:
Should not be able to copy and paste the new password, including when the field is in a decrypted state, otherwise re-typing the password is meaningless.

## Video:
https://gitlab.com/skytester/authgear-server/uploads/b4c7a8a9c81768db4ceaf93c6cd0d5ef/bandicam_2020-11-20_18-17-45-857.mp4

**Comment by louischan-oursky** [comment]
Personally I am an user of 1Password. I use very long password. If I have to type it manually, I would be very annoyed.

**Comment by louischan-oursky** [comment]
Some findings

- On modern browsers, if it is `<input type=password>`, then the text cannot be copied.
- We do not offer a toggle button to show password in enter password screen, therefore it is impossible to steal a saved password.
- We only offer a toggle button to show password in create password screen.
- Given that we have a toggle button in create password screen, it is possible to see the actual plaintext password.
- Given that it is possible to see the actual plaintext password, disallowing copying does not make it more secure. It would just make the UX worse.
- For a user of password manager, the password is usually generated, complex and long. If the user is required to type it, it would be more likely to make typo mistakes.

So I guess we should just leave the current behavior unchanged.
