### ISSUE TITLE
[App, Forgot password] Cannot reset password for account created by username

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#777]
## Background:
- Device / Browser (OS version): Chrome on Win 10

## Description:
For an account that is created by username, if the account owner forgot password, he cannot reset password by email.

## Steps to reproduce:
1. Go to https://ourskyqa.authgear-staging.com
2. Login by username and click "Next"
3. Click "Forgot Password?"
4. Input a valid email and click "Next"
5. See an error message "specified user not found"

## Expected result:
Should be able to reset password by email for account created by username.

## Screenshot:
![image](https://gitlab.com/skytester/authgear-server/uploads/d78d41ae0b987c276de3e6aebd09aaa1/image.png)

**Comment by louischan-oursky** [comment]
Due to this pitfall, username is by default disabled :(

**Comment by keithtkl** [comment]
known issue, as we cannot send reset pwd link to the user if s/he only got username. won't fix for now
