### ISSUE TITLE
Prevent enumeration of Login ID (username/phone/email)

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#779]
## Background:
- Device / Browser (OS version): Safari on Mac OS Catalina
- Build: staging 23-11-2020
- Remark: Reported by tester

## Description:
If the login ID (username, phone, email) not exist, it will show invalid credentials BEFORE user inputs the password, which means it will be possible to retrieve the list of login ID, or check if a particular Login ID exists in the system.

It might not be acceptable in some security context.

We shall have an option to hide such information from the users both on UI and API level.

## Steps to reproduce:
1. Login to the app https://ourskyqa.authgear-staging.com/login
2. Type any words that is not a username and not a email 
3. And then press enter 
4. In Error message field show "Invalid credentials"

## Expected result:
Should not show "Invalid credential" in the step of input username. 
Suggestion, should check the username after (user inputed the password). For more security and privacy.

**Comment by louischan-oursky** [comment]
This attack is prevented by rate limiting.

**Comment by chpapa** [comment]
Re-open this issue since it is actually not prevented by rate limiting.

**Comment by stanleylhs** [comment]
Issue validation check: Reproducible, but behaviour changed

## Description: 
Error message is now `This identity cannot be found. Please ensure it is correct.` when it's within limit.
After the rate limit 15 tries, error message will become `Please wait for a moment before retrying.` 
After 1 mins another 15 tries is allowed, no max limit found yet.

## Background:
Device / Browser (OS version): Chrome 114.0.5735.198 on Mac 13.4.1
Build: staging 2023-07-05.0
Retested on: 10 July 2023

**Comment by chpapa** [comment]
Just to clarify, I meant rate-limiting is not the right way to solve the issues -- the problem is not just enumeration, but on some system, it is actually non-favorable to even allow checking if certain login ID exists in the system. So there should be a switch to disable such behaviour at all.

**Comment by fungc-io** [comment]
replaced by [DEV-1220 : Prevent user enumeration in Login flow​](https://linear.app/authgear/issue/DEV-1220/prevent-user-enumeration-in-login-flow)
