### ISSUE TITLE
[Demo App, Authorize] Error shown with stack trace when click Authorize button

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#784]
## Background:
- Device / Browser (OS version): on One Plus 
- Build: Staging 24-11-2020 / app Authgear demo Android version 1.0 (on the build 18-Nov-2020) 
- Remark: Reported by tester

## Description:
Return an error message contain debug message or stack trace log when clicking the "Authorize" button. 

Not sure if this is fixed on new version already or not, please close if not reproducible, thanks.

## Steps to reproduce:
1. Open the demo app
2. Input the information, click "Configure" 
3. Show "Success".
4. And then click "Authorize" 
5. Immediately prompt an error "Error message."

## Expected result:
Should not contain debug message or stack trace log in an Error message box.  

## Screenshot:
![Screenshot_20201124-180355](https://gitlab.com/skytester/authgear-server/uploads/419a891002743ccc73a937194dc7bc57/Screenshot_20201124-180355.png)
![Screenshot_20201124-180404](https://gitlab.com/skytester/authgear-server/uploads/fd0ee3d38a00b8c073401ad740f9dda6/Screenshot_20201124-180404.png)

**Comment by louischan-oursky** [comment]
Maybe the android version is too old?

**Comment by joyzoursky** [comment]
@louischan-oursky No stack trace error now, but cannot redirect to the login page, any idea how to resolve this error?

![Screenshot_20201208-201012](https://user-images.githubusercontent.com/12539486/101482533-d2867380-3991-11eb-939c-558050fb3797.png)

**Comment by louischan-oursky** [comment]
I guess the configured redirect URIs do not contain the one the demo app is using. Can you check if the redirect URIs include `com.authgear.example://host/path`?

![Screen Shot 2020-12-09 at 11 19 01 AM](https://user-images.githubusercontent.com/15082564/101570052-921a0a80-3a10-11eb-824d-920d58b34d9e.png)

**Comment by joyzoursky** [comment]
@louischan-oursky It works now, thanks
