### ISSUE TITLE
Show offline grant session info

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#837]
- Make the token endpoint accept `x_device_info` (base64URL)
  - Populate DeviceInfo when offline grant is created.
  - Update DeviceInfo when refresh token is used.
- Use DeviceInfo if available, fallback to existing user agent string otherwise.

---

List of information we should include

- Platform (`android` or `ios`)
- OS version (e.g. iOS 14.x.x)
- Bundle ID or Application ID (i.e. the reverse domain name of the app)
- User-specified device name (e.g. Louis' iPhone)

**Comment by chpapa** [comment]
For Sesseion Description, now it is User Agent. From customers feedback they want at least the OS version and Device type too.

**Comment by royuen** [comment]
@chpapa @louischan-oursky is that we can also store the additional information such as IDFV (for iOS) to the device? Is that we implement this ourselves and send to authgear?

**Comment by chpapa** [comment]
@royuen This is basically just the user agent string and we wanna make it configurable.

@louischan-oursky but I don't see the configuration in the iOS SDK yet, is that something we should include in this issue?

**Comment by louischan-oursky** [comment]
Let's list out the information we want to include before we act on this issue. I am going to add the list of information we want to include in the issue description.

**Comment by chpapa** [comment]
To avoid the list become too long and reasonablely understandable for most users, I think by default we include the following is good enough.

* Bundle ID or Application ID (i.e. the reverse domain name of the app)
* Platform, OS version

Others are nice to have as optional, or users can supply on their own.

**Comment by royuen** [comment]
if the user provided their own, is that can see in portal individually (i.e. in the individual column)?

**Comment by chpapa** [comment]
Users supplied one will override (or extend?) On the same column
