### ISSUE TITLE
Switch the position of MFA and Connected Identities in settings screen

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#848]

**Comment by chpapa** [comment]
Some simple redesign is needed I think, but agree basically the idea is to make it:

Main Section:
[List of Identities]
[Password]

Multi-Factors Authentications: Details
Signed in Sessions: Details

**Comment by keithtkl** [comment]
Conclusion:

Main section:
[List of identities]
[Security]
[Multi-factor Verifications] <- need press detail to access `Authenticator Apps / Devices` & `Verification code via SMS / Email`

**Comment by louischan-oursky** [comment]
![Screen Shot 2021-01-06 at 12 16 05 PM](https://user-images.githubusercontent.com/15082564/103728459-05676a00-5019-11eb-938e-b5df2e3a04ff.png)
![Screen Shot 2021-01-06 at 12 16 07 PM](https://user-images.githubusercontent.com/15082564/103728463-09938780-5019-11eb-8639-dc2df5b0df98.png)
![Screen Shot 2021-01-06 at 12 16 13 PM](https://user-images.githubusercontent.com/15082564/103728464-0a2c1e00-5019-11eb-84c1-b463723119b9.png)

@chpapa There are the screenshots of the updated layout. See if it looks better now?

**Comment by chpapa** [comment]
Looks great! Thanks @louischan-oursky 

Some comments:

* For layman: "Connected Identities" => "Login Info"
* Maybe a new issue: For MFA, if it is inactive, the "Details" change to "Setup"

**Comment by louischan-oursky** [comment]
Opened this issue for the 2nd comment https://github.com/authgear/authgear-server/issues/860
