### ISSUE TITLE
Add a "Try the Auth" button at Portal

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#849]
Right now, if users want to look at the login page or setting page to test, they need to go to DNS > Custom Domains, and copy the testing domains.

For starter, it would be easier if they can see a button on the portal, and go to the domain directly. Suggestions are welcomed, and it seems one possibility is put it on bottom left as a button, or top right as a text link?

If it is not subtle (say on bottom left), it could be automatically hide if users have setup a DNS already which meant it is on production / advanced users.

- Authgear Server Date/Version:
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Steps to reproduce

1.
2.
3.

**Comment by keithtkl** [comment]
Breadcrumb change to : Authger > app name - url
and `app name - url` can be clickable to open the app
