### ISSUE TITLE
Cannot add new language in appearance & localization screen

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#863]

**Comment by axolotl0212** [comment]
When translation.json contains Chinese (traditional character), clicking save button no response, no console log / error, no network request sent

Browser: Chrome(87.0.4280.88)
OS: MacOS(BigSur 11.1)

<img width="1076" alt="Screenshot 2021-01-06 at 4 17 06 PM" src="https://user-images.githubusercontent.com/54486231/103745733-f7c2dc00-503a-11eb-919c-7e2d2b67d3b4.png">

minimal case to reproduce error

```json
{
  "settings-page-security-section-title": "安全"
}
```

**Comment by axolotl0212** [comment]
This is caused by base64 encoding function btoa only works for ASCII character up to char code 255

ref: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa
