### ISSUE TITLE
Study the UX of verification email on battery-saving mode enabled mobile devices

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#871]
- On iPhone with Low Power Mode turned on, WebSocket works as normal.
- On Nokia 8.1 with Android 10 and Power Saver turned on, WebSocket works as normal though some delay was observed.
- On Samsung A70 with Android 10 and Medium Power mode turned on, WebSocket works as normal.
- On Samsung A70 with Android 10 and Maximum Power mode turned on, WebSocket works as normal though some delay was observed.

**Comment by mr9dollars** [comment]
No issues found on websocket on mobile browsers when android is in battery-saving mode.
