### ISSUE TITLE
[Authentication, Authenticators] Unable to save when only 'Passwordless via SMS / Email' chosen as Primary Authenticator in some applications

### ISSUE THREAD

**Issue by haretorii** [authgear/authgear-server#879]
## Background:
- Reported date: 2021.01.11
- Portal login: joyz@oursky.com / 123456Aa

## Description:
When only 'passwordless via SMS/Email' is selected as Primary Authenticator, portal admin is unable to save authenticator settings and will see 'No usable primary authenticator is enabled' error in some applications

With error: ourskyqa, qaalex, joyjoy, hello

Without error: ffsks, jojomenodohuman

## Steps to reproduce:
1. Go to Authentication > Authenticator
2. Check 'Passwordless via SMS/Email' as the only choice in Primary Authenticator
3. Check nothing or any checkbox as Secondary Authenticator
4. Click Save button
5. See 'No usable primary authenticator is enabled' error

## Expected result:
Should allow user to save if only 'Passwordless via SMS/Email' is checked in Primary Authnticator

## Screenshot:

![Screenshot_2021-01-11_at_3.36.28_PM](/uploads/3547f2c6bfaf12a0e20c2dbd74e2379a/Screenshot_2021-01-11_at_3.36.28_PM.png)

**Comment by mr9dollars** [comment]
@haretorii We cannot reproduce this issue. Could you try again with more details?

**Comment by mr9dollars** [comment]
@louischan-oursky @haretorii can reproduce within ourskyqa application.

**Comment by louischan-oursky** [comment]
This is actually not a bug. The issue is that the error message did not explain clear enough what is happening. I am going to revise the error message such that it is:

![Screen Shot 2021-01-15 at 3 59 04 PM](https://user-images.githubusercontent.com/15082564/104697407-ac9b7e00-574a-11eb-9900-d2fc9738041d.png)
