### ISSUE TITLE
Auth ui style refinement

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#887]
1. ~From the design, the input field should have small left right padding.~
1. The social login button left right padding should be smaller
1. Maybe we can apply color to social login button icon in dark mode, except the google one we cannot make multiple color.
1. The secondary btn should not have left right padding? We can check the enter password page.
1. Wrong padding in enter_login_id page

**Comment by chpapa** [comment]
For 1, if it is talking about the input field of email, I think the design is wrong... can we consult Frank for that?

**Comment by louischan-oursky** [comment]
Actually the current one is following Ben's and Elliot's suggestion. That is, there is horizontal padding.

**Comment by carmenlau** [comment]
Ok, I removed point 1.

**Comment by carmenlau** [comment]
@mr9dollars We discussed about the input field padding, if it is not too trouble can we ask Tsung min to reflect it in the design? Input field should not have small left padding. Thanks 🙏🏻

**Comment by mr9dollars** [comment]
@carmenlau sure
