### ISSUE TITLE
Re-org of Portal Navigation (Obsoleted)

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#901]
This issue is about re-arrangement of portal's navigation, without major re-design, and intend to simplify the IA.

There are 2 parts of update:
1. Update of navigations
2. Update of respective UI

## Update of Navigation
Simplify to a one level navigation; 

Development note: Hope we can have similar interfaces as below, to categorize different options into: `Management`, `Configuration` and `Advanced`, if too complicated for now, flatten all into ONE level except Advanced.
<img width="478" alt="categorized" src="https://user-images.githubusercontent.com/387241/105048127-29f62400-5aa6-11eb-9870-caaa8332e10f.png">

* Management
  * Users Management
  * Audit Log
  * Portal Admins = `Settings > Portal Admins` (put it to bottom for single level)
* Configuration
  * Login IDs = `Authentication > Login ID` + `Anonymous Users`
  * Authenticators = `Authentication > Authenticators`
  * Verifications = `Authentication > User Verifications`
  * Single Sign-on = `Single-Sign on`
  * Password Policy = `Passwords > Password Policy`
  * Custom Domains = `DNS > Public Origin` + `DNS > Custom Domains`
  * UI Settings
  * Localization (this tab is no good, but leave it for now...)
  * Subscription
* Advanced
  * Timeouts = `Passwords > Forgot Password` + `Settings > Sessions`
  * Web-Hooks = `Settings > Web-hooks`

As shown above, there are some merging and rearranging for each section, will further explain below.

## Update of respective UI

This section describe the change on each page above.

First of all, let's define some terminology, it's expected each page are updated with the IA style as follows:

![section-samples](https://user-images.githubusercontent.com/387241/105049735-eb616900-5aa7-11eb-8d85-d43cf3d1511d.png)

* Each page starts with a h1 **Title** (`Controls` in the example)
* Followed by a **Description** with a depth pane (`Fluent UI's robust, up-to-date.... availabe using Fluent UI React.` in the example`)
* Followed by multiple **Section** with a depth pane and a h2 subtitle (`Basic Inputs` in the example)
* For `Advanced` Section, it could be collaspable.

Now let's discuss the change on each page

### Login IDs
Combine existing `Authentication > Login ID` + `Anonymous Users`

**Description**: `Configure the type of unique identifiers (email, phone, username) your users can login to your applications, and enable/disable anonymous users login support, which is usually useful for gaming or social apps that want to lower the friction of user sign up yet keep tracking the users after they provided a login ID to signup.`

**Section**: Login ID (same as current design, but might need to experiment and see if the depth of pane works fine within another pane, please let Ben take a look)

**Section**: Anonymous Users

### Authenticators
Equal to existing `Authentication > Authenticators`

Change `Policy` to `Multiple Authenticators Policy`

### Verifications
Equal to existing `Authentication > User Verifications`

**Section**: Verification Policy
* Change copywriting to: `Verified user criteria`: `User is verified if one of the email/phone was verified`, `User is verified only if all emails/phones were verified`

(email/phone number same as current design)

**Section**: Advanced: `Verification code valid duration (seconds)`

### Applications
**Description**: `Configure multiple web or mobile applications to integrate with Authgear`

**Section**: `Applications`:
```
Endpoint: https://test.authgear-staging.com

You can change this endpoint at the [Custom Domains] with your domain names.
```

### Advanced
**Section**: `Settings > Sessions`, add these description: `These sessions settings applies to the session cookies at your domains or [app id].authgearapps.com. `

**Comment by chpapa** [comment]
(updated the issues to contain only remaining items that need to be updated)

**Comment by fungc-io** [comment]
To be merged with issue #1392

**Comment by samchan0221** [comment]
time estimation: 5 hrs

**Comment by fungc-io** [comment]
Move the simpler changes into #1392  for the first stage.
@samchan0221 can you work on that issue in this sprint first instead?

**Comment by samchan0221** [comment]
> Move the simpler changes into #1392 for the first stage.
> @samchan0221 can you work on that issue in this sprint first instead?

Ok, I will work on that first.

**Comment by chpapa** [comment]
Too oudated
