### ISSUE TITLE
Domain blacklist and whitelist for Email Login ID signup

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#906]
Allow users to configure, either:

- a blacklist of domains that is disallowed to signup
- a whitelist of domains that is only allowed for signup

This issue should consist of both:

- server daemon, config file
- portal

Some notes for implementation:

- the blacklist/whitelist should affect only signup, so users created from portal or via admin API are not affected
- it would be nice, on portal end, we have a default free email provider list, that users could have a checkbox to include those in the blacklist. (It should be possible to google for such a list)

**Comment by mr9dollars** [comment]
1. Do we want support regex for black/whitelist?
2. If regex, what should be the behaviour if the domain falls in both blacklist and whitelist?

**Comment by chpapa** [comment]
1. I think no need regex? (Or we can add it if we do have a use cases)
2. I think the blacklist and whitelist should be mutually exclusive (so you either configure to use the whitelist, or use the blacklist), that's why "either".

**Comment by carmenlau** [comment]
Added a simple spec for the feature https://github.com/authgear/authgear-server/pull/1055

1. We will not support regex, only exact match the domain
2. blacklist and whitelist is mutually exclusive
