### ISSUE TITLE
[Portal] Allow developer to download admin api jwk from portal

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#912]
- [x] https://github.com/authgear/authgear-server/issues/1394
- [x] https://github.com/authgear/authgear-server/issues/1395
- [x] https://github.com/authgear/authgear-server/issues/1401
- [x] https://github.com/authgear/authgear-server/issues/1400 
- [x] https://github.com/authgear/authgear-server/issues/1406

**Comment by carmenlau** [comment]
@mr9dollars The webhook documentation reminds me again, we need to work on this to allow user download webhook secret  from the portal 🙈 I still mentioned webhook signature in the doc, but we still need to update portal to complete the feature.

**Comment by fungc-io** [comment]
**Proposed UI Design - Webhook secret**
In Portal > **Settings** > **Webhooks**, add a section called **Signature**
Under it show the secret key string with a copy button
Link to doc in the description.
![Webhook Signature](https://user-images.githubusercontent.com/15207470/124245988-15d54900-db53-11eb-9dc6-3013646b43d7.png)

**Comment by fungc-io** [comment]
**Proposed UI Design - Admin API Key**
In the first version, there will be only one key. Developer will be able to rotate and revoke keys in the future.
Show a link to doc about how to use the keys and admin API on the top.
Require re-auth to download the key if auth time was longer than 1 hour.
The key will be download as a .pem file

![Admin API Key](https://user-images.githubusercontent.com/15207470/124908976-803b2d00-e01c-11eb-8945-78f31179f46c.png)

**Comment by louischan-oursky** [comment]
## Migrate octet key to use alphanumeric character only

We store all key materials in JWK format. When the key is an octet key, JWK spec requires the key to be stored in base64URL encoded form. When we initially wrote the key generation, we did not realize that the key should be in alphanumeric character set. Instead, the key contains solely random bytes, thus not copy-paste friendly.

For new octet key generation, we should use the `[a-zA-Z0-9_]` character set only. When we accept developer-proposed octet key, we must verify the key in the character set. We must also ensure the entropy of the proposed key is high enough. [GitHub provides an example of how to generate an octet key](https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks). We should follow that.

## Hide authgear.secrets.yaml from the GraphQL endpoint

Currently, authgear.secrets.yaml can be retrieved just like other resources via the GraphQL endpoint.
This flexibility leads to the introduction of secret key allowlist.
Not exposing authgear.secrets.yaml can remove secret key allowlist, and hide implementation details.

Instead, we are going to add specific GraphQL fields to expose different types of secret in their most suitable way.
Here is the pseudo code of the GraphQL schema.

```graphql
type Query {
  # There is only one webhook secret because
  # webhook secret is developer-provided
  # If the developer wants to rotate it, they should
  # 1. Generate a new octet key
  # 2. Make their server to support both the old one and the new one
  # 3. Tell us the new one so that webhooks are signed with the new key.
  # 4. Make their server to support the new one only. This effectively revoke the old key.
  webhookSecret: WebhookSecret

  oauthClientSecrets: OAuthClientSecret[]
  
}

type WebhookSecret {
  # This secret is an octet key.
  # If it is null, then the UI should show it as masked.
  secret: String
}

type OAuthClientSecret {
  alias: String!
  // client secret is never masked so it is non-null.
  clientSecret: String!
}
```
