### ISSUE TITLE
UX issues of Authgear Portal Collaborator invitation

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#915]
## 1. The email could be improved:
  * Subject: "Collaborator invitation" => "[Name] has invited you to work on Authgear - [tenant name]"
  * Content: (something like the one below)

****

invitation email content:

[Authgear Logo]

**Join your team on Authgear**

[Ben Cheng] ([bencheng@oursky.com]) has invited you to use Authgear with an tenant called [**tenant name**].

Please click the link below to view the invitation:

[Button]

****

## 2. Behaviour after click accept button should be improved

![photo_2021-01-25 17 11 35](https://user-images.githubusercontent.com/387241/105684814-64d9db00-5f30-11eb-9468-ecfddf2a8df9.jpeg)

After clicking the button on Email, depends on situation, do the following:

1. if users already logged in && if user account match, show the following page 
(Portal)
> Heading: Confirm your invitation to join the tenant [**tenant name**]
> You will join the tenant with **admin** access by clicking the Accept button below.
> **[Accept]**
 
2. if users already logged in && if the user account doesn't match, display the error below immediately, not after users click the "Accept" button:
(Portal)
> Heading: The invitee email does not match your logged-in email
> Try login with a different user?
> **[Login with another user]**

3. if users is not logged in, DO NOT redirect to sign up immediately, instead:
    > Heading: You're invited to join Authgear with an tenant called [**tenant name**]
    > You will need to create a new Authgear account or login to your existing account
    > **[Sign up]** or **[Login]** with Authgear
* Notes: The button should go to signup tab after redirect #1244 
* After sign up / login, go back to situation 1, instead of show the setting page.

4. Invalid invitation code

> Heading: Invite Invalid
> Paragraph: This invite link is invalid or expired. Please contact the admin to resend an invite.
> **[Continue to Authgear]** (Link to Portal `/projects`)

**Comment by samchan0221** [comment]
time estimation: 3 hrs

**Comment by fungc-io** [comment]
Design:
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ/Authgear-UI?node-id=4253%3A23577

**Comment by fungc-io** [comment]
@samchan0221 Design of the third case has been updated.

**Comment by fungc-io** [comment]
@samchan0221 Added the forth case: invalid code

**Comment by fungc-io** [comment]
@samchan0221 the copy for case 2 has been updated
