### ISSUE TITLE
[WebUI] Resend verification email button is hard to read in light mode

### ISSUE THREAD

**Issue by axolotl0212** [authgear/authgear-server#918]
(Describe the issue here)

- Authgear Staging
- Application Platform: MacOS Chrome

# Screenshot

<img width="1176" alt="Screenshot 2021-01-27 at 11 18 35 AM" src="https://user-images.githubusercontent.com/54486231/105938169-fe6cce00-6091-11eb-8590-1a2765ee6f55.png">

#### Expected Results

- Resend verification email button disabled state more readable

#### Actual Results

- hard to read

#### Steps to reproduce

1. Sign up with email
2. Cannot read resend button text / timer

**Comment by carmenlau** [comment]
fixed in #923
