### ISSUE TITLE
Allow users to set SMTP configuration on portal

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#919]
User can configure external SMTP provider thru the Portal, so the transactional emails will be sent with addresses of their domains.
After setting the provider and the default "from" address, user can send a test email from the Portal

- [x] Design a SMTP provider setting page in the Portal #1353 
---
Users can choose from common providers or a custom one:
- [x] Sendgrid #1354
- [ ] Mailgun
- [ ] Maildrill
- [x] Custom
---
Documentations
- [ ] Docs: Guides for configuring the provider authgear/docs#51

**Comment by fungc-io** [comment]
@louischan-oursky 

**Summary of our offline discussion:**
- After pressing "Send Test Email", there will be an input dialog for the testing "To" address. The default value is the logged-in user's address. The dialog will dismiss after confirmation.
- The "Send Test Email" should be disabled while loading.
- No need for a rate limit for testing.

**Test email content**
Subject: [Test] Authgear email
From: {{default from address from the config}}
Body: This email was successfully sent from {{tenent name}}

**Comment by fungc-io** [comment]
regarding to https://github.com/authgear/authgear-server/pull/1452
- From address should use default sender
- typo "SMPT" -> "SMTP" in the test email dialog box
- the help text below the provider selections switched place

**Comment by louischan-oursky** [comment]
Point 1, 3, 4 have been fixed and deployed. Point 2 turned out to be a configuration problem.

**Comment by fungc-io** [comment]
Replaced by https://github.com/authgear/authgear-server/issues/4217
