### ISSUE TITLE
Use different subject for different OTP message

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#92]

**Comment by louischan-oursky** [comment]
We now have separate templates for different OTP message

- Verification SMS
- Verification email (txt/html)
- Setup primary OOB SMS
  - Also known as **Setup Passwordless login with SMS**
- Setup primary OOB email (txt/html)
  - Also known as **Setup Passwordless login with email**
- Setup secondary OOB SMS
  - Also known as **Setup 2-step verification with SMS**
- Setup secondary OOB email (txt/html)
  - Also known as **Setup 2-step verification with email**
- Authenticate primary OOB SMS
  - Also known as **Passwordless login with SMS**
- Authenticate primary OOB email (txt/html)
  - Also known as **Passwordless login with email**
- Authenticate secondary OOB SMS
  - Also known as **2-step verification with SMS**
- Authenticate secondary OOB email (txt/html)
  - Also known as **2-step verification with email**

**Comment by kiootic** [comment]
This issue is referring to the subject (and maybe sender address) of the message, so it is still valid.
