### ISSUE TITLE
[Color Theming] Hyperlink color should be using themePrimary

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#925]
Design:
![image](https://user-images.githubusercontent.com/16920209/105955184-d771c480-60b0-11eb-8a2a-26d6f37c27c0.png)

Now:
See T&C links are in blue instead of using themePrimary set by user
![image](https://user-images.githubusercontent.com/16920209/105955230-e789a400-60b0-11eb-876c-bfb94d989317.png)
![image](https://user-images.githubusercontent.com/16920209/105955419-39cac500-60b1-11eb-899d-c3f871f6e372.png)

**Comment by chpapa** [comment]
@mr9dollars maybe all links should use primary color too? Not sure how fluent UI generate.

**Comment by carmenlau** [comment]
<img width="618" alt="Screenshot 2021-01-27 at 7 08 01 PM" src="https://user-images.githubusercontent.com/388892/105961754-0ac54b00-60d3-11eb-8a74-cafb8c9b2df0.png">

In the updated version, the links are using the primary color already. I think during support theming, we changed some class name. Maybe the app did the translation before we support theming, so some css class is missing? 

Here is the updated copywriting, `link` class is need for anchor.
```
{  "toc-pp-footer": "By registering, you agree to our <a class=\"link\" target=\"_blank\" href=\"{termsOfService}\">Terms of Service</a> and <a class=\"link\" target=\"_blank\" href=\"{privacyPolicy}\">Privacy Policy</a>" }
````

**Comment by carmenlau** [comment]
Maybe better we could apply colors to the basic anchor too, so it will change the color even the class is missing.
