### ISSUE TITLE
Unable to go back to app homepage through back button and app logo

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#926]
## Description:
After going to the login page, can't go back to the main page by pressing "back" button or by clicking the application logo.

## Steps to reproduce:
1. Go to Sign up / Sign in Page
2. Try to press the Project House icon or Back button
3. See will stay on Sign up / Sign in page

## TODO
- [ ] Allow configuration on Portal UI for adding home/back to app button
- [ ] Allow redirection link for the home and back to app button

## Screenshot:

https://user-images.githubusercontent.com/69806274/105948974-e5bae300-60a6-11eb-9466-70b90248c33b.mov

**Comment by mr9dollars** [comment]
1. Cannot go back to the website with back button.
2. Cannot click logo to back to home page

@carmenlau 

Not sure about whether the first issue is a bug from us.
The second issue should be an enhancement that we allow a redirect URL for clicking the logo?

**Comment by chpapa** [comment]
@mr9dollars I think you should update this issues, maybe have a parameter options to add a "back" / "home" button in the login / signup page, and setting page.

I think it requires some design update as well.

**Comment by louischan-oursky** [comment]
In https://github.com/authgear/authgear-server/pull/957 I make the logo an anchor if home URI is specified. Is that good enough for this issue? Adding a back button in login/signup/settings page seems too weird to me.

**Comment by mr9dollars** [comment]
![image](https://user-images.githubusercontent.com/16920209/106733531-f6da9580-664c-11eb-95d4-e2eee23a8b42.png)

Do you think we can make a back to app/home button here when user finds a way to quit the login/signup flow? Logo as button might be too subtle.

**Comment by louischan-oursky** [comment]
Let's come up with a design first and then discuss it in the product meeting.
