### ISSUE TITLE
Unknown rate limit setup

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#934]
Project house encounters "Please wait for a moment before trying" error in login page even after 10mins of idle. They would like to know rate limit setup for the default applications and see if we can grant them a more reasonable rate limit.

![image](https://user-images.githubusercontent.com/16920209/106109413-79161600-6184-11eb-892c-62dbfe54bcea.png)

**Comment by carmenlau** [comment]
The rate limit for general request is 60 per mins per ip address. The problem that user hits the limit easily is due to the deployment problem, opened issue and will be handled there https://github.com/authgear/helm-charts/issues/1

**Comment by mr9dollars** [comment]
Demoed by Jim on staging, he still sees rate limit error after several attempt in forget password.

**Comment by louischan-oursky** [comment]
- Increase `email-message` size to 10, remove message type
- Increase `sms-message` size to 10, remove message type
- Rename `AuthIP` to `AccountEnumeration`
- Increase `Request` size to 200

**Comment by louischan-oursky** [comment]
Fixed in https://github.com/authgear/authgear-server/pull/976
