### ISSUE TITLE
Enhancement for login and register

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#938]
- [ ] The first time I click "login / register" on top right goes to the login page, 
  - [ ] If users go to the page the first time (no cookies), show sign up page first
  - [ ] If users go to the page with cookies, show login page

----
Question:
(How the API is designed now? I think it would be suitable if there is an API about "login_or_signup")

**Comment by carmenlau** [comment]
> How the API is designed now? I think it would be suitable if there is an API about "login_or_signup"

Currently we start a login / signup flow (interaction) based on visiting path, that means `/login` start login interaction and `/signup` start signup interaction.

If we introduce login_or_signup, we will need to support it for all the login methods. For the current login methods that we have, I think it is possible. For login id case, maybe a new endpoint that will try signup interaction first, if there is `DuplicatedIdentity` error, start new login interaction. For sso, it is "login_or_signup" already. But maybe we need to think about the new login methods that we are going to support.

For this issue, I updated /login and /signup behaviour first. Go to /signup when user first visit, go to /login after user signed up or logged in.
