### ISSUE TITLE
Update error display UI

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#939]
From https://github.com/authgear/authgear-server/issues/920,

We had a discussion on how to display error message properly. 

1. Putting generic error message in AuthUI as snack bar error. Allow putting URL in error msg

![image](https://user-images.githubusercontent.com/16920209/106229352-60f7d280-6228-11eb-9a60-f276aaab0505.png)

2. Put input related error back into textfield error
![image](https://user-images.githubusercontent.com/16920209/106229392-70771b80-6228-11eb-9d90-d4c81acc69ca.png)

**Comment by mr9dollars** [comment]
Go for 1. first. Separate 2. out as another issue

**Comment by carmenlau** [comment]
Point 2 will be handled in #947
