### ISSUE TITLE
User Verification Email template

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#965]
### Background
In the issue https://github.com/authgear/authgear-server/issues/852, user suggests to add a config for users to take away the verification link. A better solution would be to allow the user to edit the HTML template.

### TODO
- Under Appearance tab, add an "Verification" sub-tab.
- Prefill our current HTML template for all email
- Provide string interpolation guide
- Allow to config under different translation

**Comment by chpapa** [comment]
@mr9dollars I think design for this might not needed -- because we already have forgot password and password less authenticator emails already.

**Comment by louischan-oursky** [comment]
Should we simply just remove the button?

**Comment by chpapa** [comment]
@louischan-oursky let's remove the button first.

But I think this issue is still relevant, for editing the verification email template.

**Comment by mr9dollars** [comment]
Removed the button for Project House's urgency.
