### ISSUE TITLE
Got x-authgear-session-valid=false in resolver endpoint before refresh token expiry

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#970]
User browses the website and the api get x-authgear-session-valid=false from the resolver endpoint before the refresh token expiry. But when user refresh the page, the session will become valid again.

It looks like the sdk failed to refresh the access token in the middle, only reconfigure the SDK (refresh page) can refresh the token. Need further check.

- Application Platform: Web

**Comment by louischan-oursky** [comment]
@carmenlau Does our fix in the JS SDK work? Can we close this?

**Comment by carmenlau** [comment]
The problem is fixed in https://github.com/authgear/authgear-sdk-js/pull/58 and no new issue is reported. Close it for now.
