### ISSUE TITLE
Allow to change the password reset page content using html

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#972]
Allow to change the password reset page content using html 

Put below forget password under translation tab

![image](https://user-images.githubusercontent.com/16920209/107013075-dccbbf00-67d4-11eb-8d38-4c35aca6de4f.png)

**Comment by louischan-oursky** [comment]
This is not trivial though.

If the application is a mobile app, the reset password page will be opened by Safari / Chrome, adding a link there will not work unless the URI of the link is an universal link. This implies the mobile app MUST support universal link for the link to work as expected.

I tested with google. It took me a few clicks to get to the forgot password success page. On that page, pressing login will redirect me to somewhere else. So effectively I could not get back to the app.

**Comment by chpapa** [comment]
Maybe go back to the auth login first, and let users to write their own logic to handle after web login what to do? (We have default redirect uri now right?)

**Comment by chpapa** [comment]
Duplicated with #812
