### ISSUE TITLE
Write a new Getting Started guide to integrate via JS SDK for Web SPA with the current experience

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#974]
Let's write a new Getting Started guide for integration via JS SDK for Web SPA based on the current questions Jim / Yin have, a few things that seems we must write:

## Basic
- How to integrate the backend properly
- How to integrate the frontend (i.e. when to call `fetchUserInfo()`)

## Advanced
- What is our "sensible default" for session timeout and what the developer should knows
- Set default redirect URL for the login/signup page

**Comment by chpapa** [comment]
@mr9dollars let's put it in next product meeting agenda too, thanks

**Comment by louischan-oursky** [comment]
I interviewed Allen and here some points he made:

1. [Do not know where the resolve endpoint is](https://github.com/authgear/docs/issues/16)
2. [Do not know how to edit template](https://github.com/authgear/docs/issues/22)
3. [Do not know which translation key to edit.](https://github.com/authgear/docs/issues/23) Personally I have a thought to let the developer to browse (i.e. read-only) the web page templates. So they will know exactly which translation keys are referenced by which page. [Additionally, there is no validation on the value of the translation.](https://github.com/authgear/authgear-server/issues/985)
4. [Not sure how to setup custom domain without breaking existing testing apps](https://github.com/authgear/authgear-server/issues/945). Initially they did not setup custom domain so their app was referencing the default domain. Once they setup custom domain, the default domain breaks instantly, leaving the user seeing a broken login page if the user is still using an older app. I think we should support any domain as long as the HTTP request is routed successfully. [We should teach the developer how to setup custom domain properly](https://github.com/authgear/docs/issues/24)
5. No documentation on the Admin API. The initial thought was the developer can use something like GraphiQL to explore the Admin API. But GraphiQL is disabled in our deployment.
6. Insufficient information returned in the user info endpoint. For example, Allen said that he want to know the verified claims. This is related to [Custom attributes and Claims](https://github.com/authgear/authgear-server/pull/341). Maybe we can expose useful claims in the ID token / user info first?
7. Their app has a link to the settings page. The user can change their email login ID there. But unfortunately they did not expect that to happen. One solution for them is to implement the `before_identity_update` hook, so they can block ALL changes to email. [Or we have options in to toggle on/off which sections can be seen in the settings page.](https://github.com/authgear/authgear-server/issues/986)

**Comment by louischan-oursky** [comment]
I interviewed ChunYin and Kuen Kuen and here are some points they made:

1. In the backend integration guide, we should mention how to setup reverse proxy and how to cache auth response for better performance.
2. Resend button should replace history.
3. Document the detailed behavior of `configure()`. What it does, its effect, callable or not. What kind of IO does it perform? If the app supports offline mode, how should they manage the lifecycle of authgear.
4. Mention the portal endpoint in the docs
5. Mention the Admin API endpoint in the docs
6. Document how to configure MFA.

**Comment by fungc-io** [comment]
the doc for using JS SDK in Web SPA is done
To get the user info, the developer will need to use the admin API
See progress in the following issues:
**Document how to call admin API**  https://github.com/authgear/docs/issues/31
**[Portal] Allow developer to download admin api jwk from portal**  https://github.com/authgear/authgear-server/issues/912
