### ISSUE TITLE
Auth page blocked by anti virus

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#994]
A project house production user reported that the federated login page is being blocked by bitdefender (antivirus the user installed on an Android phone, apparently)

Louis: possibly because of the URL containing password and keyboard auto focus to password field. Need further testing
![image](https://user-images.githubusercontent.com/16920209/107609621-746c5a00-6c7a-11eb-95c8-26f0a35d5113.png)

**Comment by louischan-oursky** [comment]
Seems irrelevant anymore. Closing for now.
